#!/usr/bin/env python3
"""Generate the user-facing GitHub Wiki for Lurek2D.

All pages are generated. There are no manual scaffolds and no contributor/CAG
pages. The generator writes flat GitHub Wiki-style Markdown files to docs/wiki
by default, or to a local wiki clone with --output DIR.
"""

from __future__ import annotations

import argparse
import difflib
import json
import os
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parent.parent.parent
DEFAULT_OUTPUT = ROOT / "docs" / "wiki"
API_DATA = ROOT / "logs" / "data" / "lua_api_data.json"
SPEC_DIR = ROOT / "docs" / "specs"
SPEC_INDEX = SPEC_DIR / "README.md"
EXAMPLES_DIR = ROOT / "content" / "examples"
EXAMPLES_INDEX = EXAMPLES_DIR / "README.md"
GAMES_DIR = ROOT / "content" / "games"
GAMES_INDEX = GAMES_DIR / "README.md"
LIBRARY_DOC = ROOT / "docs" / "api" / "library.md"
API_MARKDOWN = ROOT / "docs" / "api" / "lurek.md"
API_STUB = ROOT / "docs" / "api" / "lurek.lua"
ENGINE_ARCH = ROOT / "docs" / "architecture" / "engine-architecture.md"

BANNER = "<!-- Auto-generated by tools/docs/gen_wiki.py; do not edit by hand. -->\n\n"
GROUPS = ["Foundations", "Core Runtime", "Platform Services", "Feature Systems", "Edge / Integration"]
STATIC_ORDER = [
    "Home", "Getting-Started", "First-Game", "Project-Structure", "Callbacks",
    "Runtime-Model", "Modules", "API", "API-Reference", "Examples",
    "Reference-Games", "Lunasome", "Glossary", "_Sidebar", "_Footer",
]
CALLBACK_ORDER = [
    "lurek.init", "lurek.ready", "lurek.process", "lurek.process_physics",
    "lurek.process_late", "lurek.draw", "lurek.draw_ui", "lurek.keypressed",
    "lurek.keyreleased", "lurek.mousepressed", "lurek.mousereleased",
    "lurek.mousemoved", "lurek.wheelmoved", "lurek.textinput", "lurek.resize",
    "lurek.focus", "lurek.quit",
]


def u(text: str) -> str:
    return text.encode("ascii").decode("unicode_escape")


@dataclass(frozen=True)
class Page:
    filename: str
    content: str

    @property
    def slug(self) -> str:
        return self.filename.removesuffix(".md")


@dataclass
class SpecInfo:
    module: str
    group: str = ""
    purpose: str = ""
    summary: str = ""
    namespace: str = ""


@dataclass
class ExampleInfo:
    file_name: str
    namespace: str
    description: str
    module: str
    path: Path


@dataclass
class GameInfo:
    name: str
    category: str
    description: str
    folder: Path
    modules: list[str]


@dataclass(frozen=True)
class ExampleSnippet:
    snippet: str
    source_name: str
    source_path: Path
    match_kind: str


@dataclass
class Context:
    output: Path
    api_data: dict[str, Any]
    api_modules: dict[str, dict[str, Any]]
    specs: dict[str, SpecInfo]
    examples: list[ExampleInfo]
    callable_examples: dict[str, ExampleSnippet]
    module_examples: dict[str, ExampleSnippet]
    global_example: ExampleSnippet | None
    games: list[GameInfo]
    library_summary: str
    library_entries: list[tuple[str, str, str]]
    callbacks: list[dict[str, str]]
    modules: list[str]
    api_markdown_lines: int
    api_stub_lines: int


def read(path: Path) -> str:
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8-sig").replace("\r\n", "\n")


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def md_row(line: str) -> list[str]:
    return [re.sub(r"\s+", " ", cell.strip()) for cell in line.strip().strip("|").split("|")]


def section(text: str, heading: str) -> str:
    match = re.search(rf"(?ms)^##\s+{re.escape(heading)}\s*\n(.*?)(?=^##\s+|\Z)", text)
    return match.group(1).strip() if match else ""


def strip_links(text: str) -> str:
    text = re.sub(r"\[([^\]]+)\]\([^\)]+\)", r"\1", text)
    return text.replace("`", "").strip()


def clean_text(text: str) -> str:
    cleaned = text.strip()
    cleaned = re.sub(r"`(?:src|tests|\.github|work|tools)/[^`]+`", "", cleaned)
    cleaned = re.sub(r"(?im)^.*(?:Rust test path|Lua test path|Source path|Lua API path).*\n?", "", cleaned)
    cleaned = re.sub(r"\s+", " ", cleaned)
    return cleaned.strip(" -")


def table_cell(text: str) -> str:
    return clean_text(text).replace("|", "\\|").replace("\n", "<br>")


def first_paragraphs(text: str, limit: int = 2) -> str:
    text = re.sub(r"```.*?```", "", text, flags=re.DOTALL)
    paragraphs = [clean_text(part) for part in text.split("\n\n")]
    return "\n\n".join(part for part in paragraphs if part)[:limit * 1200]


def first_sentence(text: str) -> str:
    compact = re.sub(r"\s+", " ", strip_links(text)).strip()
    if not compact:
        return ""
    match = re.search(r"(.+?[.!?])(?:\s|$)", compact)
    return match.group(1).strip() if match else compact[:220].strip()


def heading_anchor(text: str) -> str:
    plain = strip_links(re.sub(r"[`*_]", "", text)).lower()
    plain = re.sub(r"[^a-z0-9\s-]", "", plain)
    plain = re.sub(r"[\s-]+", "-", plain).strip("-")
    return plain or "section"


def wiki(slug: str, label: str | None = None) -> str:
    return f"[[{label}|{slug}]]" if label and label != slug else f"[[{slug}]]"


def page_link(slug: str, label: str | None = None) -> str:
    if label and label != slug:
        return f"{label} ({wiki(slug)})"
    return wiki(slug)


def navigation_block(extra_links: list[tuple[str, str]] | None = None) -> list[str]:
    links = [
        wiki("Home"),
        wiki("Modules"),
        wiki("API"),
        wiki("Examples"),
        wiki("Reference-Games", "Reference Games"),
        wiki("Lunasome"),
    ]
    for slug, label in extra_links or []:
        rendered = wiki(slug, label)
        if rendered not in links:
            links.append(rendered)
    return ["## Navigation", "", " | ".join(links)]


def table_of_contents(body: list[str]) -> list[str]:
    entries: list[str] = []
    for line in body:
        match = re.match(r"^(#{2,4})\s+(.+?)\s*$", line)
        if not match:
            continue
        title = re.sub(r"<[^>]+>", "", match.group(2)).strip()
        if not title or title.lower() in {"table of contents", "navigation", "example"}:
            continue
        indent = "  " * (len(match.group(1)) - 2)
        entries.append(f"{indent}- [{strip_links(title)}](#{heading_anchor(title)})")
    return ["## Table of Contents", "", *(entries or ["- [Overview](#overview)"])]


def file_link(context: Context, target: Path, label: str | None = None) -> str:
    try:
        repo_path = target.resolve(strict=False).relative_to(ROOT).as_posix()
        kind = "tree" if target.is_dir() else "blob"
        href = f"../{kind}/main/{repo_path}"
    except ValueError:
        try:
            href = Path(os.path.relpath(target, context.output)).as_posix()
        except ValueError:
            href = target.as_posix()
    return f"[{label or target.name}]({href.replace(' ', '%20')})"


def source_file_link(context: Context, rel_path: str, label: str | None = None) -> str:
    return file_link(context, ROOT / rel_path, label or rel_path)


def example_module_from_file(example_path: Path) -> str:
    match = re.search(r"lurek\.([A-Za-z_][A-Za-z0-9_]*)", read(example_path))
    return match.group(1) if match else example_path.stem


def game_category_from_folder(folder: Path) -> str:
    try:
        parts = folder.relative_to(GAMES_DIR).parts
    except ValueError:
        parts = ()
    return parts[0] if len(parts) > 1 else "uncategorized"


def page(title: str, body: list[str], extra_links: list[tuple[str, str]] | None = None) -> str:
    parts = navigation_block(extra_links) + [""] + table_of_contents(body) + [""] + body
    return (BANNER + f"# {title}\n\n" + "\n".join(parts).rstrip() + "\n")


def parse_specs() -> dict[str, SpecInfo]:
    specs: dict[str, SpecInfo] = {}
    current_group = ""
    for line in read(SPEC_INDEX).splitlines():
        heading = re.match(r"^###\s+(.+?)\s*$", line)
        if heading:
            current_group = heading.group(1).strip() if heading.group(1).strip() in GROUPS else ""
            continue
        if not current_group or not line.startswith("| `"):
            continue
        cells = md_row(line)
        if len(cells) < 3:
            continue
        module_match = re.search(r"`([^`]+)`", cells[0])
        if module_match:
            specs[module_match.group(1)] = SpecInfo(
                module=module_match.group(1),
                group=current_group,
                purpose=strip_links(cells[2]),
            )
    for spec_path in sorted(SPEC_DIR.glob("*.md")):
        if spec_path.name in {"README.md", "SPEC_TEMPLATE.md"}:
            continue
        module = spec_path.stem
        text = read(spec_path)
        info = specs.get(module, SpecInfo(module=module))
        info.summary = first_paragraphs(section(text, "Summary"), 2)
        general = section(text, "General Info")
        group_match = re.search(r"^- Module group:\s*`?([^`\n]+)`?", general, re.MULTILINE)
        namespace_match = re.search(r"^- Primary Lua namespace:\s*`?([^`\n]+)`?", general, re.MULTILINE)
        info.group = info.group or (group_match.group(1).strip() if group_match else "")
        info.namespace = namespace_match.group(1).strip() if namespace_match else f"lurek.{module}"
        specs[module] = info
    return specs


def parse_examples() -> list[ExampleInfo]:
    metadata: dict[str, tuple[str, str, str]] = {}
    for line in read(EXAMPLES_INDEX).splitlines():
        if not line.startswith("| `"):
            continue
        cells = md_row(line)
        if len(cells) < 3 or cells[0].lower() == "file":
            continue
        file_name = cells[0].strip("`")
        namespace = cells[1].strip("`")
        module = namespace.removeprefix("lurek.").split(".")[0]
        metadata[file_name] = (namespace, strip_links(cells[2]), module)

    examples: list[ExampleInfo] = []
    for example_path in sorted(EXAMPLES_DIR.glob("*.lua")):
        if example_path.name in metadata:
            namespace, description, module = metadata[example_path.name]
        else:
            module = example_module_from_file(example_path)
            namespace = f"lurek.{module}"
            description = "API example"
        examples.append(ExampleInfo(example_path.name, namespace, description, module, example_path))
    return sorted(examples, key=lambda item: (item.module, item.file_name))


def parse_games(api_names: set[str]) -> list[GameInfo]:
    metadata: dict[Path, GameInfo] = {}
    category = ""
    for line in read(GAMES_INDEX).splitlines():
        heading = re.match(r"^##\s+(.+?)\s*$", line)
        if heading:
            category = heading.group(1).strip()
            continue
        if not category or ("[Otworz folder]" not in line and "[Open folder]" not in line):
            continue
        cells = md_row(line)
        if len(cells) < 4:
            continue
        folder_match = re.search(r"\]\(\.\/([^\)]+)\)", cells[-2])
        if not folder_match:
            continue
        folder = GAMES_DIR / folder_match.group(1)
        metadata[folder] = GameInfo(strip_links(cells[0]), category, strip_links(" | ".join(cells[1:-2])), folder, [])

    games: list[GameInfo] = []
    for main_path in sorted(GAMES_DIR.glob("**/main.lua")):
        folder = main_path.parent
        game = metadata.get(folder, GameInfo(folder.name, game_category_from_folder(folder), "", folder, []))
        found = sorted(set(re.findall(r"\blurek\.([A-Za-z_][A-Za-z0-9_]*)", read(main_path))))
        game.modules = [module for module in found if module in api_names]
        games.append(game)
    return sorted(games, key=lambda item: (item.category.lower(), item.name.lower()))


def parse_library() -> tuple[str, list[tuple[str, str, str]]]:
    text = read(LIBRARY_DOC)
    summary_match = re.search(r"\*(\d+\s+libraries,\s+\d+\s+functions)\*", text)
    entries: list[tuple[str, str, str]] = []
    for line in text.splitlines():
        match = re.match(r"^- \[`library\.([^`]+)`\]\(#([^\)]+)\)\s+(.+)$", line.strip())
        if match:
            entries.append((match.group(1), match.group(2), match.group(3).strip(" -")))
    return (summary_match.group(1) if summary_match else "", entries)


def parse_callbacks() -> list[dict[str, str]]:
    callback_section = section(read(ENGINE_ARCH), "Callback Contract")
    callbacks: list[dict[str, str]] = []
    for line in callback_section.splitlines():
        if not line.startswith("|") or "`lurek." not in line:
            continue
        cells = md_row(line)
        if len(cells) >= 4:
            callbacks.append({"name": cells[0].strip("`"), "sig": cells[1].strip("`"), "when": cells[2], "purpose": cells[3]})
    order = {name: index for index, name in enumerate(CALLBACK_ORDER)}
    return sorted(callbacks, key=lambda item: order.get(item["name"], len(order)))


def lua_block_delta(line: str) -> int:
    code = line.split("--", 1)[0]
    opens = len(re.findall(r"\b(?:do|function|then|repeat)\b", code))
    closes = len(re.findall(r"\b(?:end|until)\b", code))
    return opens - closes


def extract_lua_block(lines: list[str], start: int, max_lines: int = 48) -> str:
    selected: list[str] = []
    depth = 0
    for index in range(start, min(len(lines), start + max_lines)):
        line = lines[index]
        if any(marker in line for marker in (".github/", "CAG", "SCAFFOLD", "flesh-out-example", "Generated by tools/", "COVERAGE:")):
            continue
        selected.append(line)
        depth += lua_block_delta(line)
        if index > start and depth <= 0:
            break
    while selected and not selected[0].strip():
        selected.pop(0)
    while selected and not selected[-1].strip():
        selected.pop()
    return "\n".join(selected)


def snippet_around(lines: list[str], index: int, max_lines: int = 18) -> str:
    start = max(0, index - 4)
    while start > 0 and lines[start].strip() and not lines[start].strip().startswith("--@api-stub"):
        if index - start >= 6:
            break
        start -= 1
    selected = lines[start:min(len(lines), start + max_lines)]
    while selected and selected[0].strip().startswith("--@api-stub"):
        selected.pop(0)
    while selected and not selected[0].strip():
        selected.pop(0)
    while selected and not selected[-1].strip():
        selected.pop()
    return "\n".join(selected)


def example_key(value: str) -> str:
    return re.sub(r"\s+", "", value.strip().strip("`")).lower()


def example_key_variants(value: str) -> set[str]:
    clean_value = value.strip().strip("` ")
    variants = {clean_value}
    if ":" in clean_value:
        owner, method_name = clean_value.split(":", 1)
        if owner.startswith("L") and len(owner) > 1 and not owner.startswith("LL"):
            variants.add(owner[1:] + ":" + method_name)
        else:
            variants.add("L" + owner + ":" + method_name)
    return {example_key(item) for item in variants if item}


def callable_example_keys(module: str, function_data: dict[str, Any], class_name: str | None = None) -> list[str]:
    name = str(function_data.get("name", "") or "")
    lua_name = str(function_data.get("lua_name", "") or "")
    owner = class_name or str(function_data.get("owner_type", "") or "")
    raw_keys: list[str] = []
    if lua_name:
        raw_keys.append(lua_name)
    if class_name or owner:
        raw_keys.append(f"{owner}:{name}")
        if owner.startswith("L") and len(owner) > 1:
            raw_keys.append(f"{owner[1:]}:{name}")
    elif name:
        raw_keys.append(f"lurek.{module}.{name}")
    result: list[str] = []
    for raw_key in raw_keys:
        for variant in example_key_variants(raw_key):
            if variant not in result:
                result.append(variant)
    return result


def example_snippet_from_lines(lines: list[str], max_lines: int = 48) -> str:
    for index, line in enumerate(lines):
        if re.match(r"\s*do\s+--\s+", line):
            return extract_lua_block(lines, index, max_lines)
    for index, line in enumerate(lines):
        if "function lurek." in line and not line.strip().startswith("--"):
            return snippet_around(lines, index, max_lines)
    for index, line in enumerate(lines):
        if line.strip() and not line.strip().startswith("--"):
            return snippet_around(lines, index, max_lines)
    return ""


def build_example_indexes(examples: list[ExampleInfo]) -> tuple[dict[str, ExampleSnippet], dict[str, ExampleSnippet], ExampleSnippet | None]:
    callable_examples: dict[str, ExampleSnippet] = {}
    module_examples: dict[str, ExampleSnippet] = {}
    global_example: ExampleSnippet | None = None
    for example in examples:
        lines = read(example.path).splitlines()
        module_snippet = example_snippet_from_lines(lines)
        if module_snippet:
            snippet = ExampleSnippet(module_snippet, example.file_name, example.path, "module-level")
            module_examples.setdefault(example.module, snippet)
            if global_example is None:
                global_example = ExampleSnippet(module_snippet, example.file_name, example.path, "general")

        pending_targets: list[str] = []
        for index, line in enumerate(lines):
            stub_match = re.search(r"--@api-stub:\s*([^\s]+)", line)
            if stub_match:
                pending_targets = [stub_match.group(1)]
                continue
            # Support both old format (do -- lurek.x.y) and new format (plain do after --@api-stub:)
            block_match = re.match(r"\s*do\s+--\s*(.+?)\s*$", line)
            plain_do = re.match(r"\s*do\s*$", line) and bool(pending_targets)
            if block_match or plain_do:
                block = extract_lua_block(lines, index)
                if block_match:
                    targets = pending_targets + [block_match.group(1)]
                else:
                    targets = pending_targets
                pending_targets = []
                for target in targets:
                    for key in example_key_variants(target):
                        callable_examples[key] = ExampleSnippet(block, example.file_name, example.path, "exact")
                continue
            if pending_targets and line.strip() and not line.strip().startswith("--"):
                block = snippet_around(lines, index)
                targets = pending_targets
                pending_targets = []
                for target in targets:
                    for key in example_key_variants(target):
                        callable_examples.setdefault(key, ExampleSnippet(block, example.file_name, example.path, "exact"))

        text = "\n".join(lines)
        for direct_match in re.finditer(r"\blurek\.[A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)+", text):
            target = direct_match.group(0)
            line_index = text[:direct_match.start()].count("\n")
            if lines[line_index].lstrip().startswith("--"):
                continue
            callable_examples.setdefault(example_key(target), ExampleSnippet(snippet_around(lines, line_index), example.file_name, example.path, "exact"))
    return callable_examples, module_examples, global_example


def build_context(output: Path) -> Context:
    api_data = json.loads(read(API_DATA))
    api_modules = api_data.get("lua_api", {}).get("modules", {})
    specs = parse_specs()
    examples = parse_examples()
    callable_examples, module_examples, global_example = build_example_indexes(examples)
    games = parse_games(set(api_modules))
    library_summary, library_entries = parse_library()
    modules = sorted(set(api_modules) | set(specs))
    api_markdown_text = read(API_MARKDOWN)
    api_stub_text = read(API_STUB)
    return Context(
        output,
        api_data,
        api_modules,
        specs,
        examples,
        callable_examples,
        module_examples,
        global_example,
        games,
        library_summary,
        library_entries,
        parse_callbacks(),
        modules,
        len(api_markdown_text.splitlines()) if api_markdown_text else 0,
        len(api_stub_text.splitlines()) if api_stub_text else 0,
    )


def examples_by_module(context: Context) -> dict[str, list[ExampleInfo]]:
    grouped: dict[str, list[ExampleInfo]] = {}
    for example in context.examples:
        grouped.setdefault(example.module, []).append(example)
    return grouped


def games_by_module(context: Context) -> dict[str, list[GameInfo]]:
    grouped: dict[str, list[GameInfo]] = {}
    for game in context.games:
        for module in game.modules:
            grouped.setdefault(module, []).append(game)
    return grouped


def module_group(context: Context, module: str) -> str:
    info = context.specs.get(module)
    return info.group if info and info.group else "Other"


def namespace(context: Context, module: str) -> str:
    info = context.specs.get(module)
    if info and info.namespace:
        return info.namespace
    return f"lurek.{module}" if module in context.api_modules else ""


def module_description(context: Context, module: str) -> str:
    info = context.specs.get(module)
    api_module = context.api_modules.get(module, {})
    candidates = [info.purpose if info else "", first_sentence(info.summary) if info else "", first_sentence(api_module.get("description", ""))]
    for candidate in candidates:
        cleaned = clean_text(candidate)
        if cleaned:
            return cleaned
    return "Lurek2D runtime module."


def key_text(value: Any) -> str:
    return re.sub(r"\s+", "", str(value or "").strip()).lower()


def callable_param_key(function_data: dict[str, Any]) -> tuple[Any, ...]:
    optional = optional_names(function_data)
    parts: list[tuple[str, bool]] = []
    for raw_param in function_data.get("typed_params", []) or []:
        if isinstance(raw_param, dict):
            name = str(raw_param.get("name", ""))
            raw_type = str(raw_param.get("type", raw_param.get("lua_type", "any")))
            is_optional = bool(raw_param.get("optional", False)) or name in optional or raw_type.endswith("?")
            parts.append((raw_type.rstrip("?").lower() or "any", is_optional))
        elif isinstance(raw_param, (list, tuple)) and len(raw_param) >= 2:
            name = str(raw_param[0])
            raw_type = str(raw_param[1])
            is_optional = name in optional or raw_type.endswith("?") or any(isinstance(extra, bool) and extra for extra in raw_param[2:])
            parts.append((raw_type.rstrip("?").lower() or "any", is_optional))
    if parts:
        return tuple(parts)

    inferred = str(function_data.get("inferred_sig", "") or "").strip()
    inferred = re.sub(r"\[[A-Za-z_][A-Za-z0-9_]*\]", "[]", inferred)
    inferred = re.sub(r"\b[A-Za-z_][A-Za-z0-9_]*\s*:", ":", inferred)
    return (key_text(inferred),) if inferred else ()


def callable_key(function_data: dict[str, Any]) -> tuple[Any, ...]:
    call_name = function_data.get("lua_name", "") or function_data.get("name", "")
    return (key_text(call_name), callable_param_key(function_data))


def callable_sort_key(function_data: dict[str, Any]) -> tuple[str, str, str]:
    return (
        str(function_data.get("name", "") or "").lower(),
        str(function_data.get("lua_name", "") or "").lower(),
        key_text(function_data.get("inferred_sig", "")),
    )


def dedupe_callables(items: list[dict[str, Any]]) -> list[dict[str, Any]]:
    result: list[dict[str, Any]] = []
    seen: set[tuple[Any, ...]] = set()
    for item in items:
        if not isinstance(item, dict):
            continue
        item_key = callable_key(item)
        if item_key in seen:
            continue
        seen.add(item_key)
        result.append(item)
    return result


def functions(api_module: dict[str, Any]) -> list[dict[str, Any]]:
    return sorted(dedupe_callables(api_module.get("functions", []) or []), key=callable_sort_key)


def classes(api_module: dict[str, Any]) -> list[tuple[str, dict[str, Any]]]:
    return sorted((api_module.get("classes", {}) or {}).items(), key=lambda item: item[0].lower())


def methods(class_data: dict[str, Any]) -> list[dict[str, Any]]:
    return sorted(dedupe_callables(class_data.get("methods", []) or []), key=callable_sort_key)


def api_callable_total(context: Context) -> int:
    total = 0
    for api_module in context.api_modules.values():
        total += len(functions(api_module))
        for _class_name, class_data in classes(api_module):
            total += len(methods(class_data))
    return total


def param_docs(function_data: dict[str, Any]) -> dict[str, str]:
    docs: dict[str, str] = {}
    for line in str(function_data.get("params_doc", "") or "").splitlines():
        clean_line = line.strip().lstrip("- ").strip()
        match = re.match(r"`?([A-Za-z_][A-Za-z0-9_]*)`?\s*(?:[:\-\u2013\u2014]|--)?\s*(.*)$", clean_line)
        if match:
            docs[match.group(1)] = match.group(2).strip()
    return docs


def optional_names(function_data: dict[str, Any]) -> set[str]:
    sig = str(function_data.get("inferred_sig", "") or "")
    return {match.group(1) for match in re.finditer(r"\[([A-Za-z_][A-Za-z0-9_]*)\]", sig)}


def params(function_data: dict[str, Any]) -> list[tuple[str, str, str, bool]]:
    docs = param_docs(function_data)
    optional = optional_names(function_data)
    result: list[tuple[str, str, str, bool]] = []
    for raw_param in function_data.get("typed_params", []) or []:
        if isinstance(raw_param, dict):
            name = str(raw_param.get("name", ""))
            type_name = str(raw_param.get("type", raw_param.get("lua_type", "any"))).rstrip("?") or "any"
            description = str(raw_param.get("description", docs.get(name, "")))
            is_optional = bool(raw_param.get("optional", False)) or name in optional
        elif isinstance(raw_param, (list, tuple)) and len(raw_param) >= 2:
            name = str(raw_param[0])
            type_name = str(raw_param[1]).rstrip("?") or "any"
            description = docs.get(name, "")
            is_optional = name in optional or str(raw_param[1]).endswith("?")
            for extra in raw_param[2:]:
                if isinstance(extra, bool):
                    is_optional = is_optional or extra
                elif isinstance(extra, str) and extra:
                    description = extra
        else:
            continue
        result.append((name, type_name, description, is_optional))
    return result


def return_type(function_data: dict[str, Any]) -> str:
    inferred = str(function_data.get("inferred_return", "") or "").strip()
    if inferred and inferred.lower() not in {"nil", "none", "()"}:
        return inferred
    returns_doc = str(function_data.get("returns_doc", "") or "").strip()
    if returns_doc and returns_doc.lower() not in {"nil", "none"}:
        match = re.match(r"`?([A-Za-z_][A-Za-z0-9_?\|]*)`?", returns_doc.splitlines()[0].strip())
        if match and match.group(1).lower() not in {"nil", "none", "the", "a", "an"}:
            return match.group(1).rstrip("?")
    return ""


def return_desc(function_data: dict[str, Any]) -> str:
    desc = str(function_data.get("return_description", "") or "").strip()
    if desc:
        return desc
    returns_doc = str(function_data.get("returns_doc", "") or "")
    return returns_doc.split(" - ", 1)[1].strip() if " - " in returns_doc else ""


def signature(function_data: dict[str, Any], module: str, class_name: str | None = None) -> str:
    param_parts = []
    for name, type_name, _description, is_optional in params(function_data):
        param_parts.append(f"{'[' + name + ']' if is_optional else name}: {type_name}")
    if not param_parts:
        inferred = str(function_data.get("inferred_sig", "") or "")
        if inferred.startswith("(") and inferred.endswith(")"):
            inferred_inner = inferred[1:-1].strip()
            if inferred_inner:
                param_parts.append(inferred_inner)
    name = str(function_data.get("name", ""))
    call = f"{class_name}:{name}" if class_name else str(function_data.get("lua_name", "") or f"lurek.{module}.{name}")
    result = f"{call}({', '.join(param_parts)})"
    returns = return_type(function_data)
    return f"{result} -> {returns}" if returns else result


def compact_line(function_data: dict[str, Any], module: str, class_name: str | None = None) -> str:
    desc = clean_text(str(function_data.get("description", "") or ""))
    if len(desc) > 110:
        desc = desc[:107].rstrip() + "..."
    return f"{signature(function_data, module, class_name)} -- {desc}" if desc else signature(function_data, module, class_name)


def callable_example(context: Context, module: str, function_data: dict[str, Any], class_name: str | None = None) -> ExampleSnippet | None:
    for key in callable_example_keys(module, function_data, class_name):
        if key in context.callable_examples:
            return context.callable_examples[key]
    if module in context.module_examples:
        return context.module_examples[module]
    return context.global_example


def rendered_example_section(context: Context, example: ExampleSnippet | None) -> list[str]:
    lines = ["#### Example", ""]
    if example is None or not example.snippet:
        lines += ["No generated example snippet was found in `content/examples/`.", "", "```lua", "-- No example snippet available.", "```", ""]
        return lines
    if example.match_kind == "exact":
        lead = "Exact example from"
    elif example.match_kind == "module-level":
        lead = "Module-level example from"
    else:
        lead = "General example from"
    lines += [f"{lead} {file_link(context, example.source_path, example.source_name)}:", "", "```lua", example.snippet, "```", ""]
    return lines


def example_section(context: Context, module: str, function_data: dict[str, Any], class_name: str | None = None) -> list[str]:
    return rendered_example_section(context, callable_example(context, module, function_data, class_name))


def returns_type(function_data: dict[str, Any], class_name: str) -> bool:
    return class_name in {part.strip().rstrip("?") for part in return_type(function_data).split("|")}


def type_example(
    context: Context,
    module: str,
    class_name: str,
    function_list: list[dict[str, Any]],
    class_list: list[tuple[str, dict[str, Any]]],
) -> ExampleSnippet | None:
    for key in example_key_variants(class_name):
        if key in context.callable_examples:
            return context.callable_examples[key]
    for function_data in function_list:
        if returns_type(function_data, class_name):
            example = callable_example(context, module, function_data)
            if example and example.match_kind == "exact":
                return example
    for owner_name, owner_data in class_list:
        for method_data in methods(owner_data):
            if returns_type(method_data, class_name):
                example = callable_example(context, module, method_data, owner_name)
                if example and example.match_kind == "exact":
                    return example
    if module in context.module_examples:
        return context.module_examples[module]
    return context.global_example


def type_example_section(
    context: Context,
    module: str,
    class_name: str,
    function_list: list[dict[str, Any]],
    class_list: list[tuple[str, dict[str, Any]]],
) -> list[str]:
    return rendered_example_section(context, type_example(context, module, class_name, function_list, class_list))


def detail(context: Context, function_data: dict[str, Any], module: str, class_name: str | None = None) -> list[str]:
    lines = [f"### `{signature(function_data, module, class_name)}`", ""]
    desc = clean_text(str(function_data.get("description", "") or ""))
    if desc:
        lines += [desc, ""]
    function_params = params(function_data)
    if function_params:
        lines += ["**Parameters**", ""]
        for name, type_name, description, is_optional in function_params:
            marker = "optional" if is_optional else "required"
            suffix = f" - {clean_text(description)}" if clean_text(description) else ""
            lines.append(f"- `{name}` (`{type_name}`, {marker}){suffix}")
        lines.append("")
    returns = return_type(function_data)
    if returns:
        suffix = f" - {clean_text(return_desc(function_data))}" if clean_text(return_desc(function_data)) else ""
        lines += [f"**Returns**: `{returns}`{suffix}", ""]
    lines += example_section(context, module, function_data, class_name)
    return lines


def example_snippet(example: ExampleInfo, max_lines: int = 70) -> str:
    return example_snippet_from_lines(read(example.path).splitlines(), max_lines)


def related(context: Context, module: str, limit: int = 6) -> list[str]:
    group = module_group(context, module)
    return [candidate for candidate in context.modules if candidate != module and module_group(context, candidate) == group][:limit]


def module_neighbors(context: Context, module: str) -> tuple[str | None, str | None]:
    if module not in context.modules:
        return None, None
    index = context.modules.index(module)
    previous_module = context.modules[index - 1] if index > 0 else None
    next_module = context.modules[index + 1] if index + 1 < len(context.modules) else None
    return previous_module, next_module


def module_page(context: Context, module: str) -> Page:
    info = context.specs.get(module)
    examples = examples_by_module(context).get(module, [])
    games = games_by_module(context).get(module, [])
    api_module = context.api_modules.get(module, {})
    purpose = clean_text(info.purpose if info else "") or module_description(context, module)
    summary = info.summary if info and info.summary else module_description(context, module)
    body = [
        "This page is generated from the current module specs, examples, and Lua API data.",
        "",
        f"**Module group:** {module_group(context, module)}",
    ]
    if namespace(context, module):
        body.append(f"**Namespace:** `{namespace(context, module)}`")
    body += ["", "## Purpose", "", purpose, "", "## Summary", "", summary]

    module_example = context.module_examples.get(module) or context.global_example
    body += ["", "## Minimal Module Example", ""]
    if module_example and module_example.snippet:
        lead = "Module example" if module_example.match_kind == "module-level" else "General example"
        body += [f"{lead} from {file_link(context, module_example.source_path, module_example.source_name)}:", "", "```lua", module_example.snippet, "```"]
    else:
        body += ["No example snippet was found in `content/examples/`.", "", "```lua", "-- No example snippet available.", "```"]

    class_list = classes(api_module)
    body += ["", "## Key Types", ""]
    if class_list:
        for class_name, class_data in class_list[:16]:
            desc = clean_text(str(class_data.get("description", "") or ""))
            body.append(f"- `{class_name}` ({len(methods(class_data))} methods){' - ' + desc if desc else ''}")
    else:
        body.append("This module has no separate Lua-visible classes in the generated API data.")

    function_list = functions(api_module)
    body += ["", "## API Overview", ""]
    if module in context.specs:
        body.append(f"- Source spec: {file_link(context, SPEC_DIR / (module + '.md'), 'docs/specs/' + module + '.md')}")
    body.append("")
    if function_list:
        body.append("```lua")
        body += [compact_line(function_data, module) for function_data in function_list[:18]]
        if len(function_list) > 18:
            body.append(f"-- ... {len(function_list) - 18} more module functions")
        body.append("```")
    else:
        body.append("No module functions appear in the generated Lua API data.")

    if function_list:
        body += ["", "## Module Functions", ""]
        for function_data in function_list:
            body += detail(context, function_data, module)
    if class_list:
        body += ["", "## Types and Methods", ""]
        for class_name, class_data in class_list:
            body += [f"### `{class_name}`", ""]
            if class_data.get("description"):
                body += [clean_text(str(class_data.get("description", ""))), ""]
            body += type_example_section(context, module, class_name, function_list, class_list)
            for method_data in methods(class_data):
                body += detail(context, method_data, module, class_name)

    body += ["", "## Examples", ""]
    body += [f"- {file_link(context, example.path, example.file_name)} - {example.description}" for example in examples] or ["No module-specific example file was found."]
    body += ["", "## Reference Games", ""]
    body += [f"- {file_link(context, game.folder, game.name)} ({game.category})" for game in games[:20]] or ["No direct references were found in `content/games/**/main.lua`."]

    body += ["", "## Related Modules", ""]
    previous_module, next_module = module_neighbors(context, module)
    if previous_module:
        body.append(f"- Previous: {wiki('Module-' + previous_module, previous_module)}")
    if next_module:
        body.append(f"- Next: {wiki('Module-' + next_module, next_module)}")
    related_modules = related(context, module)
    body += [f"- {wiki('Module-' + item, item)} - {module_description(context, item)}" for item in related_modules] or ["No related modules were detected in the same group."]
    return Page(f"Module-{module}.md", page(f"Module {module}", body))


def home_page(context: Context) -> Page:
    summary = context.api_data.get("lua_api", {}).get("summary", {})
    body = [
        "Lurek2D is a single-binary 2D runtime for games written in Lua. This wiki is generated from the current specs, examples, reference games, and Lua API artifacts.",
        "",
        "## Project Snapshot",
        "",
        f"- {summary.get('modules', len(context.api_modules))} Lua API modules",
        f"- {summary.get('total_functions', 0)} Lua API functions",
        f"- {len(context.specs)} module specs",
        f"- {len(context.examples)} API examples",
        f"- {len(context.games)} reference games",
        f"- {context.library_summary or str(len(context.library_entries)) + ' libraries'}",
        "",
        "## Short Path",
        "",
        f"1. {wiki('Getting-Started', 'Getting Started')} - orientation and first commands.",
        f"2. {wiki('First-Game', 'First Game')} - minimal game script.",
        f"3. {wiki('Modules')} - choose the right `lurek.*` namespace.",
        f"4. {wiki('API')} - detailed functions, methods, types, and examples.",
        "",
        "## Wiki Map",
        "",
        f"- {wiki('Callbacks')} - functions the engine calls in a game script.",
        f"- {wiki('Runtime-Model', 'Runtime Model')} - startup and frame order.",
        f"- {wiki('Examples')} - files from `content/examples/`.",
        f"- {wiki('Reference-Games', 'Reference Games')} - games from `content/games/`.",
        f"- {wiki('Lunasome')} - reusable Lua libraries over the runtime.",
        f"- {wiki('Glossary')} - common runtime and API terms.",
    ]
    return Page("Home.md", page("Lurek2D Wiki", body))


def start_page(context: Context) -> Page:
    body = [
        "This page leads from an empty game folder to the rest of the wiki.",
        "",
        "## Game Folder",
        "",
        "- `main.lua` - main game script and optional `lurek.*` callbacks.",
        "- `conf.lua` - optional window and runtime configuration.",
        "- `assets/` - images, sounds, fonts, and game data.",
        "",
        "## First Pages",
        "",
        f"- {wiki('First-Game', 'First Game')}",
        f"- {wiki('Callbacks')}",
        f"- {wiki('Modules')}",
        f"- {wiki('Examples')}",
        "",
        "## Run An Example",
        "",
        "```bash",
        "cargo run -- content/examples/render.lua",
        "cargo run -- content/games/showcase/hello_world",
        "```",
    ]
    return Page("Getting-Started.md", page("Getting Started", body))


def first_game_page(context: Context) -> Page:
    body = [
        "A minimal game needs state, update logic, and drawing. Callbacks are optional, but this set is a useful starting point.",
        "",
        "```lua",
        "local player = { x = 100, y = 220, speed = 180 }",
        "",
        "function lurek.init()",
        '    lurek.window.setTitle("First game")',
        "    lurek.render.setBackgroundColor(0.05, 0.07, 0.10)",
        "end",
        "",
        "function lurek.process(dt)",
        '    if lurek.input.keyboard.isDown("right") then',
        "        player.x = player.x + player.speed * dt",
        "    end",
        '    if lurek.input.keyboard.isDown("left") then',
        "        player.x = player.x - player.speed * dt",
        "    end",
        "end",
        "",
        "function lurek.draw()",
        "    lurek.render.setColor(1, 1, 1, 1)",
        '    lurek.render.rectangle("fill", player.x, player.y, 48, 48)',
        "end",
        "```",
        "",
        "## Next Steps",
        "",
        f"- {wiki('Project-Structure', 'Project Structure')}",
        f"- {wiki('Module-input', 'input')}, {wiki('Module-render', 'render')}, {wiki('Module-audio', 'audio')}",
    ]
    return Page("First-Game.md", page("First Game", body))


def project_page(context: Context) -> Page:
    body = [
        "A typical game folder is small. The runtime looks for `main.lua`; the rest of the files depend on the game.",
        "",
        "```text",
        "my_game/",
        "  conf.lua",
        "  main.lua",
        "  assets/",
        "    player.png",
        "    click.ogg",
        "  data/",
        "    level1.toml",
        "```",
        "",
        "## Files",
        "",
        "- `main.lua` - defines callbacks and connects game modules.",
        "- `conf.lua` - optionally sets window and runtime options before the game starts.",
        "- `assets/` - media used by render, audio, image, and game code.",
        "- `data/` - TOML or other game data read through the sandbox filesystem.",
    ]
    return Page("Project-Structure.md", page("Project Structure", body))


def callbacks_page(context: Context) -> Page:
    body = ["A callback is a function on the `lurek` table that the runtime calls at a specific point. Every callback is optional.", "", "## Callback Table", "", "| Callback | Signature | When | Purpose |", "|---|---|---|---|"]
    for callback in context.callbacks:
        body.append(f"| `{callback['name']}` | `{callback['sig']}` | {table_cell(callback['when'])} | {table_cell(callback['purpose'])} |")
    body += ["", "## Frame Order", "", "```text", "input callbacks -> process(dt) -> process_physics(dt) -> process_late(dt) -> draw() -> draw_ui()", "```"]
    return Page("Callbacks.md", page("Callbacks", body))


def runtime_page(context: Context) -> Page:
    body = [
        "The runtime loads configuration, creates the Lua VM, registers `lurek.*`, then runs a fixed frame loop.",
        "",
        "## Startup",
        "",
        "1. The runtime locates the game folder and configuration.",
        "2. It creates the isolated Lua environment.",
        "3. It registers the `lurek.*` modules.",
        "4. It calls `lurek.init`, then `lurek.ready` if they are defined.",
        "",
        "## Frame",
        "",
        "- `lurek.process(dt)` updates game logic.",
        "- `lurek.process_physics(dt)` runs fixed-step physics logic.",
        "- `lurek.draw()` queues world draw commands.",
        "- `lurek.draw_ui()` queues HUD and UI draw commands above the world.",
    ]
    return Page("Runtime-Model.md", page("Runtime Model", body))


def modules_page(context: Context) -> Page:
    body = ["Modules are grouped by runtime layer. Each module page includes its spec Purpose, spec Summary, examples, API overview, and related modules.", ""]
    for group in GROUPS + ["Other"]:
        group_modules = [module for module in context.modules if module_group(context, module) == group]
        if not group_modules:
            continue
        body += [f"## {group}", "", "| Module | Namespace | Purpose |", "|---|---|---|"]
        for module in group_modules:
            body.append(f"| {page_link('Module-' + module, module)} | `{namespace(context, module) or '-'}` | {table_cell(module_description(context, module))} |")
        body.append("")
    return Page("Modules.md", page("Modules", body))


def api_page(context: Context) -> Page:
    summary = context.api_data.get("lua_api", {}).get("summary", {})
    body = [
        "The API index is generated from machine-readable Lua API data and links back to the generated source artifacts.",
        "",
        "## Source Artifacts",
        "",
        f"- Lua API data: {file_link(context, API_DATA, 'logs/data/lua_api_data.json')}",
        f"- Markdown reference: {file_link(context, API_MARKDOWN, 'docs/api/lurek.md')} ({context.api_markdown_lines} lines)",
        f"- LuaCATS stub: {file_link(context, API_STUB, 'docs/api/lurek.lua')} ({context.api_stub_lines} lines)",
        "",
        "## Coverage",
        "",
        f"- {summary.get('modules', len(context.api_modules))} modules",
        f"- {api_callable_total(context)} functions and methods",
        f"- {summary.get('coverage_pct', 0)}% documented",
        "",
        "## API Module Index",
        "",
        "| API | Functions | Types | Purpose |",
        "|---|---:|---:|---|",
    ]
    for module in sorted(context.api_modules):
        api_module = context.api_modules[module]
        body.append(f"| {page_link('Module-' + module, 'lurek.' + module)} | {len(functions(api_module))} | {len(classes(api_module))} | {table_cell(module_description(context, module))} |")
    body += ["", f"One-page callable index: {wiki('API-Reference', 'API Reference')}."]
    return Page("API.md", page("API", body))


def api_reference_page(context: Context) -> Page:
    body = ["Compact index of all functions and methods. Parameter details and examples live on the per-module `Module-<module>` pages.", ""]
    separator = " " + chr(183) + " "
    for module in sorted(context.api_modules):
        api_module = context.api_modules[module]
        body += [f"## lurek.{module}", "", wiki('Module-' + module, 'Module page'), ""]
        function_list = functions(api_module)
        if function_list:
            body.append("```lua")
            body += [compact_line(function_data, module) for function_data in function_list]
            body += ["```", ""]
        for class_name, class_data in classes(api_module):
            method_list = methods(class_data)
            if method_list:
                body += [f"### {class_name}", "", "```lua"]
                body += [compact_line(method_data, module, class_name) for method_data in method_list]
                body += ["```", ""]
    return Page("API-Reference.md", page("API Reference", body))


def examples_page(context: Context) -> Page:
    body = ["Examples come from `content/examples/` and show isolated `lurek.*` namespaces. API pages reuse these snippets for callable examples.", "", "| File | Namespace | Description |", "|---|---|---|"]
    body += [f"| {file_link(context, example.path, example.file_name)} | `{example.namespace}` | {table_cell(example.description)} |" for example in context.examples]
    return Page("Examples.md", page("Examples", body))


def games_page(context: Context) -> Page:
    body = ["Reference games come from `content/games/`. Module usage is detected by scanning each `main.lua`.", ""]
    for category in sorted(set(game.category for game in context.games), key=str.lower):
        body += [f"## {category}", "", "| Game | Description | Modules |", "|---|---|---|"]
        for game in [item for item in context.games if item.category == category]:
            module_links = ", ".join(page_link("Module-" + module, module) for module in game.modules[:8])
            if len(game.modules) > 8:
                module_links += f", +{len(game.modules) - 8}"
            body.append(f"| {file_link(context, game.folder, game.name)} | {table_cell(game.description or 'No description in the game index.')} | {table_cell(module_links or '-')} |")
        body.append("")
    return Page("Reference-Games.md", page("Reference Games", body))


def lunasome_page(context: Context) -> Page:
    body = ["Lunasome is the set of reusable Lua libraries built on top of the runtime. This page summarizes the generated `docs/api/library.md` reference.", ""]
    if context.library_summary:
        body += [f"**{context.library_summary}**", ""]
    body += [f"Full source file: {file_link(context, LIBRARY_DOC, 'docs/api/library.md')}", "", "| Library | Scope |", "|---|---|"]
    for name, _anchor, detail_text in context.library_entries:
        body.append(f"| {file_link(context, LIBRARY_DOC, 'library.' + name)} | {table_cell(detail_text)} |")
    return Page("Lunasome.md", page("Lunasome", body))


def glossary_page(context: Context) -> Page:
    body = ["The glossary collects terms that appear across module and API pages.", "", "## Core Terms", "", "- `lurek.*` - the only public API namespace for game scripts.", "- `callback` - a function called by the runtime, such as `lurek.process(dt)`.", "- `dt` - elapsed time since the previous frame, in seconds.", "- `main.lua` - the main game script.", "- `conf.lua` - optional startup configuration for a game.", "- `Lunasome` - reusable Lua libraries layered over the base runtime API.", "", "## Lua API Types", ""]
    class_rows: list[tuple[str, str, str]] = []
    for module, api_module in context.api_modules.items():
        for class_name, class_data in classes(api_module):
            class_rows.append((class_name, module, clean_text(str(class_data.get("description", "") or ""))))
    for class_name, module, description in sorted(class_rows, key=lambda item: item[0].lower())[:120]:
        body.append(f"- `{class_name}` ({wiki('Module-' + module, 'lurek.' + module)}){' - ' + description if description else ''}")
    return Page("Glossary.md", page("Glossary", body))


def sidebar_page(context: Context) -> Page:
    lines = ["* " + wiki("Home"), "* " + wiki("Getting-Started", "Getting Started"), "* " + wiki("First-Game", "First Game"), "* " + wiki("Project-Structure", "Project Structure"), "", "**User Guide**", "", "* " + wiki("Callbacks"), "* " + wiki("Runtime-Model", "Runtime Model"), "* " + wiki("Glossary"), "", "**Module Groups**", "", "* " + wiki("Modules", "All Modules")]
    lines += ["* " + wiki("Modules#" + heading_anchor(group), group) for group in GROUPS if any(module_group(context, module) == group for module in context.modules)]
    lines += ["", "**API Indexes**", "", "* " + wiki("API"), "* " + wiki("API-Reference", "API Reference"), "", "**Examples And Games**", "", "* " + wiki("Examples"), "* " + wiki("Reference-Games", "Reference Games"), "", "**Libraries**", "", "* " + wiki("Lunasome")]
    return Page("_Sidebar.md", BANNER + "\n".join(lines).rstrip() + "\n")


def footer_page(context: Context) -> Page:
    separator = " " + chr(183) + " "
    lines = ["Generated by `tools/docs/gen_wiki.py`. Do not edit generated wiki pages by hand.", "", separator.join([wiki("Home"), wiki("Modules"), wiki("API"), wiki("Examples"), wiki("Reference-Games", "Reference Games"), wiki("Lunasome")])]
    return Page("_Footer.md", BANNER + "\n".join(lines).rstrip() + "\n")


def build_pages(context: Context) -> list[Page]:
    pages = [home_page(context), start_page(context), first_game_page(context), project_page(context), callbacks_page(context), runtime_page(context), modules_page(context), api_page(context), api_reference_page(context), examples_page(context), games_page(context), lunasome_page(context), glossary_page(context)]
    pages += [module_page(context, module) for module in context.modules]
    pages += [sidebar_page(context), footer_page(context)]
    order = {slug + ".md": index for index, slug in enumerate(STATIC_ORDER)}
    return sorted(pages, key=lambda item: (order.get(item.filename, 1000), item.filename.lower()))


def select_pages(pages: list[Page], slug: str | None) -> list[Page]:
    if not slug:
        return pages
    filename = slug if slug.endswith(".md") else slug + ".md"
    selected = [page_item for page_item in pages if page_item.filename == filename]
    if not selected:
        raise SystemExit(f"Unknown page '{slug}'.")
    return selected


def check_pages(pages: list[Page], output: Path, page_filter: str | None) -> int:
    expected = {page_item.filename: page_item.content for page_item in pages}
    existing = {path.name for path in output.glob("*.md")} if output.exists() else set()
    failures: list[str] = []
    if page_filter is None:
        failures += ["missing " + name for name in sorted(set(expected) - existing)]
        failures += ["extra " + name for name in sorted(existing - set(expected))]
    for filename, expected_content in expected.items():
        path = output / filename
        if not path.exists():
            if page_filter is not None:
                failures.append("missing " + filename)
            continue
        actual = read(path)
        if actual != expected_content:
            failures.append("changed " + filename)
            diff = difflib.unified_diff(actual.splitlines(), expected_content.splitlines(), fromfile="existing/" + filename, tofile="generated/" + filename, lineterm="")
            for diff_line in list(diff)[:40]:
                print(diff_line)
    if failures:
        print("Wiki check failed:")
        for failure in failures:
            print("  " + failure)
        return 1
    print("Wiki check passed.")
    return 0


def remove_stale_generated_pages(pages: list[Page], output: Path, page_filter: str | None) -> None:
    if page_filter is not None or not output.exists():
        return
    expected = {page_item.filename for page_item in pages}
    for path in sorted(output.glob("*.md")):
        if path.name in expected:
            continue
        if read(path).startswith(BANNER.strip()):
            path.unlink()
            try:
                display = path.relative_to(ROOT).as_posix()
            except ValueError:
                display = path.as_posix()
            print(f"removed stale generated page {display}")


def validate_examples(context: Context) -> int:
    """Check that every callable in lua_api_data.json has a real example in the generated pages."""
    total = 0
    covered = 0
    failures: list[tuple[str, str]] = []
    for module, api_module in sorted(context.api_modules.items()):
        function_list = functions(api_module)
        class_list = classes(api_module)
        for function_data in function_list:
            total += 1
            example = callable_example(context, module, function_data)
            if example and example.snippet and _has_real_code(example.snippet):
                covered += 1
            else:
                name = str(function_data.get("lua_name", "") or function_data.get("name", ""))
                failures.append((module, name))
        for class_name, class_data in class_list:
            for method_data in methods(class_data):
                total += 1
                example = callable_example(context, module, method_data, class_name)
                if example and example.snippet and _has_real_code(example.snippet):
                    covered += 1
                else:
                    name = f"{class_name}:{method_data.get('name', '')}"
                    failures.append((module, name))
    pct = (covered * 100 // total) if total else 100
    print(f"Example coverage: {covered}/{total} callables ({pct}%)")
    if failures:
        print(f"\nMissing real examples ({len(failures)}):")
        for module, name in failures[:80]:
            print(f"  {module}: {name}")
        if len(failures) > 80:
            print(f"  ... and {len(failures) - 80} more")
    if pct < 100:
        print(f"\nValidation failed: coverage {pct}% < 100%")
        return 1
    print("Validation passed.")
    return 0


def _has_real_code(snippet: str) -> bool:
    """Return True if at least one line in the snippet is not a comment or blank."""
    for line in snippet.splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("--"):
            return True
    return False


def run(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description="Generate Lurek2D GitHub Wiki pages.")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--list", action="store_true")
    parser.add_argument("--page")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--validate", action="store_true")
    args = parser.parse_args(argv)
    output = args.output if args.output.is_absolute() else ROOT / args.output
    context = build_context(output.resolve())
    if args.validate:
        return validate_examples(context)
    pages = select_pages(build_pages(context), args.page)
    if args.list:
        for page_item in pages:
            print(page_item.slug)
        return 0
    if args.dry_run:
        for page_item in pages:
            print(f"{page_item.filename}\t{page_item.content.count(chr(10))} lines\t{len(page_item.content)} bytes")
        return 0
    if args.check:
        return check_pages(pages, output, args.page)
    output.mkdir(parents=True, exist_ok=True)
    remove_stale_generated_pages(pages, output, args.page)
    for page_item in pages:
        write(output / page_item.filename, page_item.content)
        try:
            display = output.relative_to(ROOT).as_posix()
        except ValueError:
            display = output.as_posix()
        print(f"wrote {display}/{page_item.filename}")
    return 0


if __name__ == "__main__":
    raise SystemExit(run(sys.argv[1:]))
