#!/usr/bin/env python3
"""
gen_docs_rust.py — Generate compact inline Rust API reference from logs/rust_api_data.json.

Each public item is rendered in a Rust code block:
    pub fn name(param: Type) -> ReturnType  // description
    pub struct Name  // description
    pub enum Name  // description

Includes per-module and overall docstring coverage statistics.

Usage:
    python tools/gen_docs_rust.py                   # -> docs/reports/rust-api.md
    python tools/gen_docs_rust.py --output FILE     # custom output path
    python tools/gen_docs_rust.py --input FILE      # custom input path

Exit codes:
    0 — success
    1 — fatal error
"""

import argparse
import json
import sys
from pathlib import Path

WORKSPACE_ROOT = Path(__file__).resolve().parent.parent.parent
INPUT_FILE = WORKSPACE_ROOT / "logs" / "rust_api_data.json"
OUTPUT_FILE = WORKSPACE_ROOT / "docs" / "reports" / "rust-api.md"

# Modules to skip (test utilities, build scripts, etc.)
_SKIP_MODS = {"main", "root", "lib"}

# Kind → pub keyword for inline Rust code
_KIND_KW = {
    "struct": "pub struct",
    "enum": "pub enum",
    "fn": "pub fn",
    "trait": "pub trait",
    "type": "pub type",
    "const": "pub const",
    "static": "pub static",
    "mod": "pub mod",
}

# Sort order for kinds (structs first, fns last)
_KIND_ORDER = ["struct", "enum", "trait", "type", "const", "static", "fn", "mod"]


def _top_group(mod_path: str) -> str:
    """Return the top-level module group name (first path segment)."""
    if "::" in mod_path:
        return mod_path.split("::")[0]
    return mod_path


def _format_item_line(item: dict) -> str:
    """Format one public item as a single inline Rust code line with trailing comment."""
    kind = item.get("kind", "fn")
    name = item["name"]
    kw = _KIND_KW.get(kind, f"pub {kind}")
    desc = (item.get("description", "") or "").strip()

    if kind == "fn":
        params = item.get("params", "") or ""
        ret = item.get("return_type", "") or ""
        sig = f"({params})"
        if ret:
            sig += f" -> {ret}"
        code = f"{kw} {name}{sig}"
    else:
        code = f"{kw} {name}"

    if desc:
        short = desc.split("\n")[0]
        if len(short) > 90:
            short = short[:87] + "..."
        return f"{code}  // {short}"
    return f"{code}  // (undocumented)"


def generate_rust_docs(data: dict) -> str:
    rust_api = data["rust_api"]
    modules = rust_api["modules"]
    s = rust_api["summary"]
    generated = data["meta"]["generated"][:10]
    version = data["meta"]["version"]

    # Group modules by top-level folder
    groups: dict[str, list] = {}
    for mod_path, mod_data in sorted(modules.items()):
        if mod_path in _SKIP_MODS:
            continue
        if not mod_data.get("items"):
            continue
        groups.setdefault(_top_group(mod_path), []).append((mod_path, mod_data))

    # Compute per-group coverage
    group_cov: dict[str, tuple[int, int]] = {}
    for group, mods_list in groups.items():
        total = documented = 0
        for _, md in mods_list:
            for it in md.get("items", []):
                total += 1
                if (it.get("description", "") or "").strip():
                    documented += 1
        group_cov[group] = (documented, total)

    overall_pct = round(s["documented"] / s["total_items"] * 100, 1) if s["total_items"] else 0

    out = []
    out.append("# Lurek2D Rust API Reference")
    out.append("")
    out.append(f"*Auto-generated by `tools/gen_docs_rust.py`. Version: `{version}` | Generated: {generated}*")
    out.append(f"*Coverage: {s['documented']}/{s['total_items']} public items documented ({overall_pct}%)*")
    out.append("")
    out.append("> For Lua scripting API see [lua-api.md](lua-api.md).")
    out.append("> This reference is for **engine contributors** and extension authors only.")
    out.append("")
    out.append("---")
    out.append("")

    # Table of contents
    out.append("## Contents")
    out.append("")
    for group in sorted(groups.keys()):
        anchor = group.replace("_", "-")
        documented, total = group_cov[group]
        pct = round(documented / total * 100) if total else 0
        out.append(f"- [`{group}`](#{anchor}) — {total} items ({pct}% documented)")
    out.append("")
    out.append("---")
    out.append("")

    # Per-group sections
    for group in sorted(groups.keys()):
        anchor = group.replace("_", "-")
        documented, total = group_cov[group]
        pct = round(documented / total * 100) if total else 0
        out.append(f"## `{group}` {{#{anchor}}}")
        out.append("")
        out.append(f"*Coverage: {documented}/{total} items ({pct}%)*")
        out.append("")

        for mod_path, mod_data in sorted(groups[group]):
            items = mod_data.get("items", [])
            if not items:
                continue

            module_doc = (mod_data.get("module_doc", "") or "").strip()
            src = mod_data.get("source_file", "")

            # Module coverage
            mod_documented = sum(1 for it in items if (it.get("description", "") or "").strip())
            mod_pct = round(mod_documented / len(items) * 100) if items else 0

            out.append(f"### `{mod_path}`")
            out.append("")
            if module_doc:
                first_para = module_doc.split("\n\n")[0].strip()
                first_line = first_para.split("\n")[0].strip()
                if first_line:
                    out.append(f"> {first_line}")
                    out.append("")
            if src:
                out.append(f"*[{src}]({src}) — {mod_documented}/{len(items)} documented ({mod_pct}%)*")
                out.append("")

            # Sort by kind order, then name
            sorted_items = sorted(
                items,
                key=lambda x: (
                    _KIND_ORDER.index(x.get("kind", "fn")) if x.get("kind", "fn") in _KIND_ORDER else 99,
                    x["name"]
                )
            )

            out.append("```rust")
            for item in sorted_items:
                out.append(_format_item_line(item))
            out.append("```")
            out.append("")

    out.append("---")
    out.append("*Generated by `tools/gen_docs_rust.py`. Do not edit by hand.*")

    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate Lurek2D compact inline Rust API docs.")
    parser.add_argument("--input", default=str(INPUT_FILE))
    parser.add_argument("--output", default=str(OUTPUT_FILE))
    args = parser.parse_args()

    input_path = Path(args.input)
    if not input_path.exists():
        print(f"[ERROR] Input not found: {input_path}", file=sys.stderr)
        print("Run 'python tools/gen_rust_api_data.py' first.", file=sys.stderr)
        return 1

    data = json.loads(input_path.read_text(encoding="utf-8"))
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    content = generate_rust_docs(data)
    output_path.write_text(content, encoding="utf-8")

    lines = content.count("\n")
    print(f"[OK] Generated {output_path.relative_to(WORKSPACE_ROOT)} ({lines} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
