#!/usr/bin/env python3
"""
gen_wiki.py — Regenerate ALL Lurek2D wiki pages from source content.

Two page types:
  SCRIPTED  — fully auto-generated; overwritten on every run.
  MANUAL    — created once with a scaffold; never overwritten if the file exists.

Reads:  docs/specs/*.md, content/examples/*.lua, content/library/, content/demos/, tools/, docs/architecture/,
        .github/agents/, .github/skills/, extensions/vscode/README.md,
        CONTRIBUTING.md
Writes: docs/wiki/*.md  (61 pages total)

Usage:
    python tools/docs/gen_wiki.py                # regenerate all pages
    python tools/docs/gen_wiki.py --page Home    # single page by slug
    python tools/docs/gen_wiki.py --list         # list available page slugs
    python tools/docs/gen_wiki.py --dry-run      # preview without writing
    python tools/docs/gen_wiki.py --force        # overwrite even manual pages

Exit codes:
    0 — success
    1 — fatal error
"""

import argparse
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from textwrap import dedent

# ── Paths ─────────────────────────────────────────────────────────────────────

ROOT     = Path(__file__).resolve().parent.parent.parent
SPECS    = ROOT / "docs" / "specs"
EXAMPLES = ROOT / "content" / "examples"
LIBRARY  = ROOT / "content" / "library"
DEMOS    = ROOT / "content" / "demos"
TOOLS    = ROOT / "tools"
DOCS     = ROOT / "docs"
GITHUB   = ROOT / ".github"
VSEXT    = ROOT / "extensions" / "vscode"
WIKI     = ROOT / "docs" / "wiki"

GITHUB_URL = "https://github.com/LurekDude/luna_2d"
GEN_DATE   = datetime.now(timezone.utc).strftime("%Y-%m-%d")
GEN_BANNER = (
    f"<!-- Auto-generated by gen_wiki.py on {GEN_DATE} — "
    "do not edit by hand. Regenerate: python tools/docs/gen_wiki.py -->\n\n"
)
MANUAL_BANNER = (
    "<!-- This page is maintained by hand. gen_wiki.py will NOT overwrite it. -->\n\n"
)

# ── Utility ───────────────────────────────────────────────────────────────────

def _read(path: Path) -> str:
    """Read a file; return empty string if missing."""
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8")


def _section(text: str, name: str) -> str:
    """Extract content under '## name' heading up to the next '##' or EOF."""
    pat = rf"(?m)^## {re.escape(name)}\n(.*?)(?=^##|\Z)"
    m = re.search(pat, text, re.DOTALL)
    return m.group(1).strip() if m else ""


def _prop(text: str, key: str) -> str:
    """Extract value from '| **key** | value |' metadata table row."""
    pat = rf"\*\*{re.escape(key)}\*\*\s*\|\s*(.+?)\s*(?:\||\n)"
    m = re.search(pat, text)
    return m.group(1).strip() if m else ""


def _strip_source_refs(text: str) -> str:
    """Remove references to source file paths (src/, tests/, content/library/ paths)."""
    # Replace `src/module/` references with descriptive text
    text = re.sub(r'`src/([a-z_]+)/`', r'the \1 module', text)
    text = re.sub(r'`src/([a-z_]+)/([a-z_]+\.rs)`', r'the \1 module', text)
    text = re.sub(r'`tests/[^`]+`', 'the test suite', text)
    # Remove "Source: `src/...`" lines
    text = re.sub(r'\s*·\s*Source:\s*`[^`]+`', '', text)
    return text


def read_spec(module: str) -> dict:
    """Read a spec file and return parsed metadata dict."""
    text = _read(SPECS / f"{module}.md")
    if not text:
        return {}
    return {
        "raw":     text,
        "tier":    _prop(text, "Tier"),
        "status":  _prop(text, "Status"),
        "api":     _prop(text, "Lua API"),
        "source":  _prop(text, "Source"),
        "summary": _section(text, "Summary"),
        "arch":    _section(text, "Architecture"),
        "lua_api": _section(text, "Lua API"),
        "types":   _section(text, "Types"),
        "cross":   _section(text, "Cross-Module References"),
    }


def _spec_summary(module: str, n_paragraphs: int = 3) -> str:
    """Return first n_paragraphs of spec Summary."""
    spec = read_spec(module)
    text = spec.get("summary", "")
    text = re.sub(r"```.*?```", "", text, flags=re.DOTALL)
    paras = [p.strip() for p in text.split("\n\n") if p.strip()]
    return "\n\n".join(paras[:n_paragraphs])


def _spec_lua_api(module: str) -> str:
    """Return the Lua API section from the spec, cleaned of source refs."""
    spec = read_spec(module)
    text = spec.get("lua_api", "")
    return _strip_source_refs(text)


def read_example(module: str, max_lines: int = 120) -> str:
    """Read an example file, stripping the boilerplate header comment."""
    text = _read(EXAMPLES / f"{module}.lua")
    if not text:
        return ""
    lines = text.split("\n")
    cut = 0
    for i, ln in enumerate(lines[:8]):
        if re.match(r"^-- (content/examples/|Lurek2D\b)", ln):
            cut = i + 1
    return "\n".join(lines[cut:max_lines]).strip()


def write_page(filename: str, content: str, dry_run: bool = False,
               is_manual: bool = False, force: bool = False) -> str:
    """Write a wiki page. Returns status string."""
    path = WIKI / filename
    if dry_run:
        print(f"\n{'='*60}\n{filename} ({'MANUAL' if is_manual else 'SCRIPTED'})\n{'='*60}")
        print(content[:800])
        print("  [... truncated ...]")
        return "dry-run"
    if is_manual and path.exists() and not force:
        print(f"  skip   docs/wiki/{filename} (manual page exists)")
        return "skipped"
    path.write_text(content, encoding="utf-8")
    tag = "wrote " if not is_manual else "scaffolded"
    print(f"  {tag} docs/wiki/{filename}")
    return "wrote"


# ── Per-module see-also map ────────────────────────────────────────────────────

_SEE_ALSO: dict[str, list[str]] = {
    "graphics":    ["Shader-Patterns", "Camera-API", "Particle-API",
                    "FX-API", "Animation-API"],
    "audio":       ["Event-API"],
    "physics":     ["Math-API", "Entity-API"],
    "input":       ["Event-API", "Window-API"],
    "math":        ["Physics-API", "Animation-API"],
    "timer":       ["Callbacks"],
    "window":      ["Configuration", "Input-API"],
    "filesystem":  ["Savegame-API", "Modding-API"],
    "entity":      ["Scene-API", "Physics-API"],
    "scene":       ["Entity-API", "Tilemap-API", "Camera-API"],
    "tilemap":     ["Pathfinding-API", "Scene-API", "Procgen-API"],
    "pathfinding": ["AI-API", "Tilemap-API"],
    "ai":          ["Pathfinding-API", "Entity-API"],
    "thread":      ["Event-API", "Network-API"],
    "particle":    ["Graphics-API", "FX-API"],
    "animation":   ["Graphics-API", "Tilemap-API"],
    "camera":      ["Graphics-API", "Scene-API"],
    "gui":         ["Terminal-API", "Event-API"],
    "terminal":    ["GUI-API"],
    "fx":          ["Graphics-API", "Shader-Patterns"],
    "pipeline":    ["Graphics-API", "FX-API"],
    "event":       ["Threading", "Automation-API"],
    "automation":  ["Event-API"],
    "data":        ["Data-APIs", "Filesystem-API"],
    "dataframe":   ["Data-APIs"],
    "compute":     ["Data-APIs"],
    "graph":       ["Data-APIs", "Pathfinding-API"],
    "serial":      ["Data-APIs", "Filesystem-API"],
    "image":       ["Graphics-API"],
    "network":     ["Threading", "Filesystem-API"],
    "savegame":    ["Filesystem-API", "Data-APIs"],
    "modding":     ["Filesystem-API", "Lunasome"],
    "minimap":     ["Tilemap-API", "Camera-API"],
    "light":       ["Graphics-API", "Shader-Patterns"],
    "procgen":     ["Tilemap-API", "Math-API"],
    "raycaster":   ["Physics-API", "Tilemap-API"],
    "spine":       ["Animation-API", "Graphics-API"],
}


# ── Generic module API page ────────────────────────────────────────────────────

def gen_module_page(
    module: str,
    wiki_title: str,
    n_summary_paras: int = 3,
    example_max_lines: int = 120,
    extra_sections: str = "",
    see_also_override: list | None = None,
) -> str:
    spec = read_spec(module)
    if not spec:
        return (
            GEN_BANNER
            + f"# {wiki_title}\n\n"
            + f"> Specification not yet available for `{module}`.\n"
        )

    tier     = spec.get("tier", "")
    status   = spec.get("status", "")
    api_ns   = spec.get("api", f"lurek.{module}")
    tier_short = re.sub(r" — .*", "", tier)

    overview = _spec_summary(module, n_summary_paras)
    lua_api  = _spec_lua_api(module)
    example  = read_example(module, example_max_lines)

    see_pages = see_also_override or _SEE_ALSO.get(module, [])
    see_links = " · ".join(f"[[{p}]]" for p in see_pages)
    if see_links:
        see_links += " · "
    see_links += "[[API-Reference]]"

    parts = [
        GEN_BANNER,
        f"# {wiki_title}",
        "",
        f"> *{tier_short} · Lua namespace: `{api_ns}` · {status}*",
        "",
        "---",
        "",
        "## Overview",
        "",
        _strip_source_refs(overview),
        "",
    ]

    # Include Lua API function reference if available
    if lua_api:
        parts += [
            "---",
            "",
            "## API Reference",
            "",
            _strip_source_refs(lua_api),
            "",
        ]

    if example:
        parts += [
            "---",
            "",
            "## Example",
            "",
            "```lua",
            example,
            "```",
            "",
        ]

    if extra_sections:
        parts += [
            "---",
            "",
            extra_sections.strip(),
            "",
        ]

    parts += [
        "---",
        "",
        "## See Also",
        "",
        see_links,
    ]

    return "\n".join(parts)


# ═══════════════════════════════════════════════════════════════════════════════
# Section 1: Welcome & Getting Started (SCRIPTED + MANUAL)
# ═══════════════════════════════════════════════════════════════════════════════

def gen_home() -> str:
    return GEN_BANNER + dedent(f"""\
    # Lurek2D — Wiki

    > **Lurek2D** is a 2D game engine written in Rust that loads and executes Lua game scripts.
    > Single binary · Desktop-first · LuaJIT · wgpu 22 · rapier2d 0.32 · rodio 0.17

    ---

    ## Quick Start

    ```powershell
    git clone {GITHUB_URL}
    cd luna_2d
    cargo build --release
    cargo run -- content/demos/showcase/hello_world
    ```

    Minimal `main.lua`:

    ```lua
    function lurek.load()
        lurek.window.setTitle("My Game")
        lurek.renders.setBackgroundColor(0.1, 0.1, 0.2)
    end

    function lurek.update(dt)
        -- game logic: move objects, run physics, etc.
    end

    function lurek.draw()
        lurek.renders.setColor(1, 1, 1)
        lurek.renders.print("Hello, Lurek2D!", 300, 280, 3)
    end
    ```

    ---

    ## Navigation

    ### Getting Started
    | Page | What it covers |
    |------|----------------|
    | [[Getting-Started]] | Installation, first game, project layout |
    | [[Your-First-Game]] | Step-by-step tutorial: from nothing to a moving sprite |
    | [[Project-Structure]] | `main.lua`, `conf.lua`, folder layout, assets |
    | [[Configuration]] | `conf.lua` / `conf.toml` — window and module settings |
    | [[Callbacks]] | All engine callbacks (`lurek.load`, `lurek.update`, `lurek.draw`, …) |
    | [[Examples]] | 38 single-file API usage scripts |
    | [[Demos]] | 111+ playable demos organised by genre |

    ### Engine Architecture
    | Page | What it covers |
    |------|----------------|
    | [[Architecture]] | Module tiers, boot sequence, shared state, dependency graph |
    | [[Design-Principles]] | The Zen of Luna — binding constraints and first principles |
    | [[Module-Tiers]] | Tier system, dependency rules, module catalogue |
    | [[Testing-Framework]] | Two-layer test system, how to run tests, how to add tests |

    ### Core API Reference
    | Page | What it covers |
    |------|----------------|
    | [[API-Reference]] | Full Lurek2D cheatsheet — every `lurek.*` function on one page |
    | [[Graphics-API]] | `lurek.renders` — drawing, images, fonts, shaders, canvas |
    | [[Audio-API]] | `lurek.audio` — sources, playback, mixer, buses, MIDI |
    | [[Physics-API]] | `lurek.physics` — worlds, bodies, shapes, joints, raycasting |
    | [[Input-API]] | `lurek.input` / keyboard / mouse / gamepad / touch |
    | [[Math-API]] | `lurek.math` — vectors, random, noise, transforms |
    | [[Timer-API]] | `lurek.timer` — delta time, FPS, sleep, scheduler |
    | [[Filesystem-API]] | `lurek.filesystem` — sandboxed I/O, virtual FS |
    | [[Window-API]] | `lurek.window` — fullscreen, DPI, clipboard |

    ### Graphics & Rendering
    | Page | What it covers |
    |------|----------------|
    | [[Camera-API]] | `lurek.camera` — viewport transforms, zoom, shake |
    | [[Animation-API]] | `lurek.animation` — sprite-sheet frame animation |
    | [[Particle-API]] | `lurek.particle` — emitters, modifiers, keyframe |
    | [[FX-API]] | `lurek.fx` / `lurek.pipeline` — post-processing, render pipeline |
    | [[Shader-Patterns]] | Custom WGSL shaders with `lurek.renders.newShader` |

    ### Game Systems
    | Page | What it covers |
    |------|----------------|
    | [[Tilemap-API]] | `lurek.tilemap` — tiles, layers, auto-tile, isometric/hex |
    | [[Scene-API]] | `lurek.scene` — scene stack, transitions, depth sorting |
    | [[Entity-API]] | `lurek.ecs` — ECS, components, tags, systems |
    | [[Pathfinding-API]] | `lurek.pathfind` — NavGrid, A\\*, flow fields |
    | [[AI-API]] | `lurek.ai` — FSM, behaviour trees, steering, GOAP, Q-learning |
    | [[Savegame-API]] | `lurek.save` — save/load slots, versioned tables |

    ### UI & Terminal
    | Page | What it covers |
    |------|----------------|
    | [[GUI-API]] | `lurek.gui` — retained-mode widget system, 32 widget types |
    | [[Terminal-API]] | `lurek.terminal` — grid-based character terminal emulator |

    ### Data & Scripting
    | Page | What it covers |
    |------|----------------|
    | [[Data-APIs]] | `lurek.data` / compute / dataframe / graph / serial / image |
    | [[Event-API]] | `lurek.event` — event queue and pub/sub |
    | [[Threading]] | `lurek.thread` — worker threads, channels |
    | [[Automation-API]] | `lurek.automation` — scripted sequences and macros |
    | [[Network-API]] | `lurek.network` — TCP/UDP client-server, HTTP client |

    ### Effects & Extras
    | Page | What it covers |
    |------|----------------|
    | [[Modding-API]] | `lurek.mods` — mod loading, hot-reload |
    | [[Procgen-API]] | `lurek.procgen` — map generators, noise, cellular automata |
    | [[Advanced-APIs]] | Raycaster, Spine, Light, Minimap |

    ### Standard Library (Lunasome)
    | Page | What it covers |
    |------|----------------|
    | [[Lunasome]] | Pure-Lua game systems overview |
    | [[Lunasome-Modules]] | Per-module detail: dialog, inventory, crafting, quest, battle … |

    ### Contributing
    | Page | What it covers |
    |------|----------------|
    | [[Contributing]] | How to contribute — overview for all audiences |
    | [[Contributing-Engine]] | Rust engine contribution guide |
    | [[Contributing-Demos]] | Adding new demos |
    | [[Contributing-Libraries]] | Writing Lunasome modules |
    | [[Contributing-Extension]] | VS Code extension development |
    | [[Contributing-CAG]] | CAG/AI system contributions |
    | [[Coding-Conventions]] | Rust + Lua style guide |

    ### Tooling
    | Page | What it covers |
    |------|----------------|
    | [[VS-Code-Extension]] | IntelliSense, MCP server, debugger, completions |
    | [[Extension-MCP-Server]] | All 6 MCP tools documented |
    | [[Extension-Development]] | How to develop/extend the VS Code extension |
    | [[Tools]] | CLI scripts — docs, audit, validate, dist, github |
    | [[Build-System]] | Cargo profiles, features, distribution, installer |
    | [[CAG-System]] | Copilot Agent system — agents, skills, prompts |
    | [[CAG-Workflow]] | How to use CAG for development |

    ---

    ## Engine at a Glance

    | Layer | Modules |
    |-------|---------|
    | **Baseline** | `math` |
    | **Tier 1** | `graphics` · `audio` · `physics` · `input` · `timer` · `window` · `filesystem` · `entity` · `event` · `image` · `data` · `thread` · `camera` · `animation` · `automation` · `compute` · `sound` |
    | **Tier 2** | `gui` · `scene` · `tilemap` · `particle` · `pathfinding` · `ai` · `fx` · `pipeline` · `terminal` · `minimap` · `modding` · `network` · `savegame` · `dataframe` · `graph` · `serial` · `spine` · `light` · `raycaster` · `procgen` |
    | **Bridge** | `lua_api` — registers every `lurek.*` binding |
    | **Tier 3** | Lunasome — pure-Lua game libraries |
    | **Games** | `content/demos/` · user `main.lua` |

    ---

    *[Lurek2D on GitHub]({GITHUB_URL}) · MIT License · Rust 1.78+ · LuaJIT via mlua 0.9 · wgpu 22 · winit 0.30 · rapier2d 0.32 · rodio 0.17*
    """)


def gen_getting_started() -> str:
    return GEN_BANNER + dedent(f"""\
    # Getting Started

    ## Prerequisites

    - **Rust** stable ≥ 1.78 — install via [rustup](https://rustup.rs)
    - A **C compiler** for the LuaJIT vendored build: MSVC on Windows, GCC/Clang on Linux/macOS
    - **Git** for cloning the repository

    ## Clone and Build

    ```powershell
    git clone {GITHUB_URL}
    cd luna_2d
    cargo build --release
    ```

    The binary is at `build/release/lurek2d` (or `lurek2d.exe` on Windows).

    > Lurek2D overrides Cargo's default output directory — binaries go to `build/` instead of `target/`.

    ## Install Locally (optional)

    ```powershell
    # Windows
    powershell tools/dist/install.ps1

    # Linux / macOS
    bash tools/dist/install.sh
    ```

    After installation, you can use `luna` from anywhere:

    ```bash
    luna content/demos/showcase/hello_world
    luna path/to/my_game
    ```

    ---

    ## Your First Game

    Create a folder with a `main.lua` file:

    ```
    my_game/
    └── main.lua
    ```

    ```lua
    function lurek.load()
        lurek.window.setTitle("My First Game")
        lurek.renders.setBackgroundColor(0.1, 0.1, 0.2)
    end

    function lurek.update(dt)
        -- game logic here
    end

    function lurek.draw()
        lurek.renders.setColor(1, 1, 1)
        lurek.renders.print("Hello, Lurek2D!", 300, 280, 3)
    end
    ```

    Run it:

    ```bash
    cargo run -- path/to/my_game
    # or if installed:
    luna path/to/my_game
    ```

    ---

    ## Adding a Config File (optional)

    Create `conf.lua` in your game folder to configure the window before it opens:

    ```lua
    function lurek.conf(t)
        t.window.title  = "My Game"
        t.window.width  = 1280
        t.window.height = 720
        t.window.vsync  = true
        t.identity      = "my_game"   -- save directory name
    end
    ```

    See [[Configuration]] for the full list of options.

    ---

    ## Running the Demos

    Lurek2D ships with 111+ playable demos:

    ```bash
    cargo run -- content/demos/arcade/pong
    cargo run -- content/demos/showcase/hello_world
    cargo run -- content/demos/simulation/physics_demo
    ```

    See [[Demos]] for the full index.

    ---

    ## Running Examples

    Single-file API usage scripts:

    ```bash
    cargo run -- content/examples/physics.lua
    cargo run -- content/examples/tilemap.lua
    ```

    See [[Examples]] for all 38 examples.

    ---

    ## VS Code Integration

    Lurek2D has a first-party VS Code extension with:
    - Lua API autocomplete
    - MCP server for AI-assisted development
    - Example runner
    - Lua debugger

    See [[VS-Code-Extension]] for installation and features.

    ---

    ## Next Steps

    | Topic | Page |
    |-------|------|
    | Step-by-step tutorial | [[Your-First-Game]] |
    | Callbacks reference | [[Callbacks]] |
    | Full API cheatsheet | [[API-Reference]] |
    | Graphics API | [[Graphics-API]] |
    | Physics API | [[Physics-API]] |
    | Standard library | [[Lunasome]] |
    | Contributing | [[Contributing]] |
    """)


def gen_your_first_game() -> str:
    """MANUAL page — step-by-step tutorial."""
    return MANUAL_BANNER + dedent("""\
    # Your First Game

    This tutorial walks you through building a simple game from scratch using Lurek2D.
    By the end, you'll have a moving sprite that you can control with the keyboard.

    ---

    ## Step 1: Create a Project Folder

    ```
    my_platformer/
    └── main.lua
    ```

    ## Step 2: Set Up the Game Window

    ```lua
    function lurek.load()
        lurek.window.setTitle("My Platformer")
        lurek.window.setMode(800, 600)
        lurek.renders.setBackgroundColor(0.2, 0.3, 0.4)

        -- Player state
        player = { x = 400, y = 300, speed = 200 }
    end
    ```

    ## Step 3: Add Player Movement

    ```lua
    function lurek.update(dt)
        if lurek.input.keyboard.isDown("left", "a") then
            player.x = player.x - player.speed * dt
        end
        if lurek.input.keyboard.isDown("right", "d") then
            player.x = player.x + player.speed * dt
        end
        if lurek.input.keyboard.isDown("up", "w") then
            player.y = player.y - player.speed * dt
        end
        if lurek.input.keyboard.isDown("down", "s") then
            player.y = player.y + player.speed * dt
        end
    end
    ```

    ## Step 4: Draw the Player

    ```lua
    function lurek.draw()
        -- Draw a white rectangle as the player
        lurek.renders.setColor(1, 1, 1)
        lurek.renders.rectangle("fill", player.x - 16, player.y - 16, 32, 32)

        -- Draw position text
        lurek.renders.setColor(0.8, 0.8, 0.8)
        lurek.renders.print(string.format("x: %.0f  y: %.0f", player.x, player.y), 10, 10)
    end
    ```

    ## Step 5: Run It

    ```bash
    cargo run -- my_platformer
    ```

    Use WASD or arrow keys to move the white square around the screen.

    ---

    ## Step 6: Add a Sprite (optional)

    Place an image file in your game folder and load it:

    ```lua
    function lurek.load()
        lurek.window.setTitle("Sprite Demo")
        sprite = lurek.renders.newImage("player.png")
        player = { x = 400, y = 300, speed = 200 }
    end

    function lurek.draw()
        lurek.renders.setColor(1, 1, 1)
        lurek.renders.draw(sprite, player.x, player.y)
    end
    ```

    ---

    ## Step 7: Add Physics (optional)

    ```lua
    function lurek.load()
        world = lurek.physics.newWorld(0, 500)  -- gravity pulling down

        -- Ground
        ground = world:newBody("static", 400, 580, "rectangle", 800, 40)

        -- Player ball
        ball = world:newBody("dynamic", 400, 100, "circle", 20)
        ball:setRestitution(0.6)  -- bouncy
    end

    function lurek.update(dt)
        world:step(dt)
    end

    function lurek.draw()
        -- Draw ground
        lurek.renders.setColor(0.3, 0.7, 0.3)
        local gx, gy = ground:getPosition()
        lurek.renders.rectangle("fill", gx - 400, gy - 20, 800, 40)

        -- Draw ball
        lurek.renders.setColor(1, 0.5, 0.2)
        local bx, by = ball:getPosition()
        lurek.renders.circle("fill", bx, by, 20)
    end
    ```

    ---

    ## Next Steps

    | Topic | Page |
    |-------|------|
    | Project file layout | [[Project-Structure]] |
    | Window and module config | [[Configuration]] |
    | All engine callbacks | [[Callbacks]] |
    | Full graphics API | [[Graphics-API]] |
    | Physics system | [[Physics-API]] |
    | Browse 111+ demos | [[Demos]] |
    """)


def gen_project_structure() -> str:
    """MANUAL page — game project layout."""
    return MANUAL_BANNER + dedent("""\
    # Project Structure

    A Lurek2D game is a folder containing Lua scripts and assets.

    ---

    ## Minimal Project

    ```
    my_game/
    └── main.lua           -- entry point (required)
    ```

    The engine looks for `main.lua` as the entry point. Everything else is optional.

    ---

    ## Full Project Layout

    ```
    my_game/
    ├── main.lua           -- entry point
    ├── conf.lua           -- window/module configuration (optional)
    ├── assets/            -- images, sounds, fonts (optional)
    │   ├── player.png
    │   ├── enemy.png
    │   └── music.ogg
    ├── lib/               -- your own Lua modules (optional)
    │   ├── player.lua
    │   └── level.lua
    └── save/              -- save files (created at runtime)
    ```

    ---

    ## Entry Point: main.lua

    The engine executes `main.lua` after booting. Define callbacks here:

    ```lua
    function lurek.load()       end  -- called once after init
    function lurek.update(dt)   end  -- called every frame
    function lurek.draw()       end  -- called every frame after update
    function lurek.quit()       end  -- called before exit
    ```

    See [[Callbacks]] for the full callback reference.

    ---

    ## Configuration: conf.lua

    If `conf.lua` exists, the engine calls `lurek.conf(t)` before opening the window:

    ```lua
    function lurek.conf(t)
        t.window.title  = "My Game"
        t.window.width  = 1280
        t.window.height = 720
        t.identity      = "my_game"
    end
    ```

    See [[Configuration]] for all available fields.

    ---

    ## Asset Loading

    The engine sandboxes file access to your game folder. Load assets by relative path:

    ```lua
    local img   = lurek.renders.newImage("assets/player.png")
    local font  = lurek.renders.newFont("assets/font.ttf", 16)
    local sound = lurek.audio.newSource("assets/jump.ogg", "static")
    ```

    ---

    ## Save Directory

    The `save/` folder (relative to the game directory) is writable at runtime.
    Use the `t.identity` setting in `conf.lua` or the filesystem API:

    ```lua
    lurek.filesystem.write("save/progress.json", data)
    local data = lurek.filesystem.read("save/progress.json")
    ```

    See [[Filesystem-API]] for the full I/O API.

    ---

    ## Using Lunasome Libraries

    Lurek2D ships with pure-Lua game libraries that you can `require`:

    ```lua
    local dialog    = require("library.dialog")
    local inventory = require("library.inventory")
    local quest     = require("library.quest")
    ```

    See [[Lunasome]] for the full library catalogue.

    ---

    ## Running Your Game

    ```bash
    cargo run -- path/to/my_game
    # or if installed:
    luna path/to/my_game
    ```

    ---

    See also: [[Getting-Started]] · [[Configuration]] · [[Callbacks]] · [[Filesystem-API]]
    """)


def gen_configuration() -> str:
    return GEN_BANNER + dedent("""\
    # Configuration

    Lurek2D reads configuration from two optional files before any game code runs.

    ---

    ## conf.lua

    Place `conf.lua` in your game folder alongside `main.lua`.
    The `lurek.conf(t)` callback is called during engine boot — before the window opens.

    ```lua
    function lurek.conf(t)
        -- Window
        t.window.title      = "My Game"
        t.window.width      = 1280
        t.window.height     = 720
        t.window.fullscreen = false
        t.window.resizable  = true
        t.window.vsync      = true
        t.window.fps_cap    = 0      -- 0 = no cap

        -- Identity (used for save directory)
        t.identity = "my_game"

        -- Modules (set false to disable)
        t.modules.physics   = true
        t.modules.audio     = true
        t.modules.gui       = true
        t.modules.terminal  = true
        t.modules.network   = false
        t.modules.modding   = false

        -- Debug
        t.debug.show_fps    = false
    end
    ```

    ---

    ## conf.toml

    Alternatively, use a `conf.toml` file (TOML format) for the same settings:

    ```toml
    [window]
    title      = "My Game"
    width      = 1280
    height     = 720
    fullscreen = false
    vsync      = true

    [modules]
    physics = true
    audio   = true
    ```

    Both formats are equivalent. `conf.lua` takes precedence if both exist.

    ---

    ## Config Fields Reference

    | Field | Type | Default | Description |
    |-------|------|---------|-------------|
    | `window.title` | string | `"Lurek2D"` | Window title bar text |
    | `window.width` | int | `1280` | Initial window width in pixels |
    | `window.height` | int | `720` | Initial window height in pixels |
    | `window.fullscreen` | bool | `false` | Start in fullscreen |
    | `window.resizable` | bool | `true` | Allow window resize |
    | `window.vsync` | bool | `true` | Enable vertical sync |
    | `window.fps_cap` | int | `0` | Max FPS (0 = unlimited) |
    | `identity` | string | `""` | App identity for save directory |
    | `modules.physics` | bool | `true` | Enable physics module |
    | `modules.audio` | bool | `true` | Enable audio module |
    | `modules.gui` | bool | `true` | Enable GUI module |
    | `modules.terminal` | bool | `true` | Enable terminal module |
    | `modules.network` | bool | `false` | Enable network module |
    | `modules.modding` | bool | `false` | Enable modding module |
    | `debug.show_fps` | bool | `false` | Show FPS counter overlay |

    ---

    See also: [[Getting-Started]] · [[Callbacks]] · [[Window-API]] · [[Project-Structure]]
    """)


def gen_callbacks() -> str:
    return GEN_BANNER + dedent("""\
    # Callbacks

    All engine callbacks are defined as global functions in `main.lua`. Every callback is optional — a blank `main.lua` is valid.

    ---

    ## Core Loop

    ```lua
    function lurek.conf(t)       end  -- called before window opens; configure in conf.lua
    function lurek.load()        end  -- called once after script and assets are loaded
    function lurek.update(dt)    end  -- dt: seconds; called every frame before draw
    function lurek.draw()        end  -- called every frame; push draw commands here
    function lurek.quit()        end  -- called before the engine exits; return true to cancel
    ```

    ---

    ## Keyboard

    ```lua
    function lurek.keypressed(key, scancode, isrepeat)  end  -- key: string; isrepeat: bool
    function lurek.keyreleased(key, scancode)           end
    function lurek.textinput(text)                      end  -- Unicode character input
    ```

    ---

    ## Mouse

    ```lua
    function lurek.mousepressed(x, y, button)           end  -- button: 1=left 2=right 3=middle
    function lurek.mousereleased(x, y, button)          end
    function lurek.mousemoved(x, y, dx, dy)             end
    function lurek.wheelmoved(x, y)                     end  -- scroll delta
    ```

    ---

    ## Gamepad

    ```lua
    function lurek.input.gamepadpressed(id, button)           end  -- id: number; button: string
    function lurek.input.gamepadreleased(id, button)          end
    function lurek.input.gamepadaxis(id, axis, value)         end  -- value: -1.0..1.0
    function lurek.joystickadded(id)                    end  -- device connected
    function lurek.joystickremoved(id)                  end  -- device disconnected
    ```

    ---

    ## Touch

    ```lua
    function lurek.touchpressed(id, x, y, dx, dy, pressure)   end
    function lurek.touchmoved(id, x, y, dx, dy, pressure)     end
    function lurek.touchreleased(id, x, y, dx, dy, pressure)  end
    ```

    ---

    ## Window

    ```lua
    function lurek.focus(focused)    end  -- focused: bool; window focus changed
    function lurek.visible(visible)  end  -- visible: bool; window hidden or shown
    function lurek.resize(w, h)      end  -- new window dimensions
    ```

    ---

    ## Callback Execution Order

    ```
    lurek.conf(t)          ← before window opens (from conf.lua)
    window opens
    lurek.load()           ← once, after full init
    ┌─ frame loop ──────────────────────────────
    │  poll events → fire lurek.key*/mouse*/etc.
    │  lurek.update(dt)
    │  lurek.draw()        ← push DrawCommands
    │  GPU renderer processes the command queue
    └────────────────────────────────────────────
    lurek.quit()           ← on window close
    ```

    ---

    See also: [[Getting-Started]] · [[Timer-API]] · [[Input-API]]
    """)


# ═══════════════════════════════════════════════════════════════════════════════
# Section 2: Architecture & Design (SCRIPTED)
# ═══════════════════════════════════════════════════════════════════════════════

def gen_architecture() -> str:
    arch_text = _read(DOCS / "architecture" / "engine-architecture.md")
    if not arch_text:
        return GEN_BANNER + "# Lurek2D Architecture\n\n> Architecture document not found.\n"

    # Strip source file references for self-contained wiki
    arch_text = _strip_source_refs(arch_text)

    # Replace .md cross-references with wiki links
    arch_text = re.sub(
        r'\[([^\]]+)\]\(philosophy\.md\)',
        r'[[\1|Design-Principles]]',
        arch_text,
    )
    arch_text = re.sub(
        r'\[([^\]]+)\]\(test-framework\.md\)',
        r'[[\1|Testing-Framework]]',
        arch_text,
    )

    return GEN_BANNER + f"# Lurek2D Architecture\n\n{arch_text.strip()}\n"


def gen_design_principles() -> str:
    phil_text = _read(DOCS / "architecture" / "philosophy.md")
    if not phil_text:
        return GEN_BANNER + "# Design Principles\n\n> Philosophy document not found.\n"

    phil_text = _strip_source_refs(phil_text)
    return GEN_BANNER + f"# Design Principles\n\n{phil_text.strip()}\n"


def gen_module_tiers() -> str:
    """Generate Module-Tiers.md from spec metadata."""
    # Collect all modules by tier
    tiers: dict[str, list[tuple[str, str, str]]] = {}
    spec_files = sorted(SPECS.glob("*.md"))
    for sf in spec_files:
        module = sf.stem
        if module in ("README", "lua_api", "bin", "engine"):
            continue
        text = _read(sf)
        tier = _prop(text, "Tier")
        status = _prop(text, "Status")
        api = _prop(text, "Lua API")
        tier_key = re.sub(r" — .*", "", tier) if tier else "Unknown"
        if tier_key not in tiers:
            tiers[tier_key] = []
        tiers[tier_key].append((module, api, status))

    sections = []
    tier_order = ["Baseline", "Tier 1", "Tier 2"]
    for tk in tier_order:
        modules = tiers.get(tk, [])
        if not modules:
            continue
        rows = "\n".join(
            f"| `{m}` | `{api}` | {st} |"
            for m, api, st in sorted(modules)
        )
        sections.append(f"### {tk}\n\n| Module | Lua API | Status |\n|--------|---------|--------|\n{rows}\n")

    body = "\n---\n\n".join(sections)

    return GEN_BANNER + dedent(f"""\
    # Module Tiers

    Lurek2D uses a strictly layered architecture. Each module belongs to a tier that determines
    what it can depend on. No lower tier may import a higher tier.

    ---

    ## Dependency Rules

    ```
    Games / Demos
        ↓ uses
    Tier 3 — Lunasome (pure-Lua libraries)
        ↓ uses (lurek.* API only)
    Bridge — lua_api (registers all lurek.* bindings)
        ↓ imports
    Tier 2 — Engine Extensions (may import Baseline + Tier 1)
        ↓ imports
    Tier 1 — Core Subsystems (may import Baseline only)
        ↓ imports
    Baseline — math (leaf module, no internal deps)
    ```

    **Rules**:
    - No Tier 1 ↔ Tier 1 cross-imports
    - No Tier 2 ↔ Tier 2 cross-imports
    - Domain modules must **never** import the Lua API bridge
    - All cross-tier data flows go through the Baseline shared state

    ---

    ## Module Catalogue

    {body}

    ---

    ## Tier 3 — Lunasome (Pure-Lua Libraries)

    These are pure-Lua modules that consume only the `lurek.*` API. They are not compiled into
    the engine binary.

    | Module | Description |
    |--------|-------------|
    | `battle` | Turn-based battle engine |
    | `cardgame` | Card definitions, stacks, pools, analysis |
    | `combat` | Action-combat: vehicles, turrets, weapons, projectiles |
    | `crafting` | Recipes, timed queues, upgrade trees, knowledge |
    | `dialog` | Typewriter dialogue sequencer with branching |
    | `doll` | Socket-based visual character composition |
    | `economy` | Resource management with flow, decay, conversion |
    | `inventory` | Slot-based containers, equip, stacking, sets |
    | `item` | Type registry, instances, stacks, pools |
    | `province_map` | Grand-strategy province maps with routing |
    | `quest` | Quest tracking with staged objectives |
    | `stats` | Character stats, buffs, traits, XP |

    See [[Lunasome]] and [[Lunasome-Modules]] for detailed documentation.

    ---

    See also: [[Architecture]] · [[Design-Principles]] · [[API-Reference]]
    """)


def gen_testing_framework() -> str:
    """Generate Testing-Framework.md from docs/architecture/test-framework.md."""
    test_text = _read(DOCS / "architecture" / "test-framework.md")
    if not test_text:
        return GEN_BANNER + "# Testing Framework\n\n> Test framework document not found.\n"

    test_text = _strip_source_refs(test_text)

    # Replace the title
    test_text = re.sub(r"^# .+\n", "", test_text, count=1)

    return GEN_BANNER + f"# Testing Framework\n\n{test_text.strip()}\n"


# ═══════════════════════════════════════════════════════════════════════════════
# Section 3: API Reference (handled by gen_wiki_api.py, skip here)
# ═══════════════════════════════════════════════════════════════════════════════


# ═══════════════════════════════════════════════════════════════════════════════
# Section 5: Graphics & Rendering (Shader-Patterns is MANUAL)
# ═══════════════════════════════════════════════════════════════════════════════

def gen_shader_patterns() -> str:
    """MANUAL page — custom WGSL shaders."""
    return MANUAL_BANNER + dedent("""\
    # Shader Patterns

    Lurek2D supports custom WGSL shaders via `lurek.renders.newShader`.

    ---

    ## Creating a Shader

    ```lua
    local shader = lurek.renders.newShader([[
        @group(0) @binding(0) var tex: texture_2d<f32>;
        @group(0) @binding(1) var samp: sampler;

        struct VertexOut {
            @builtin(position) pos : vec4<f32>,
            @location(0) uv : vec2<f32>,
        };

        @fragment
        fn fs_main(in: VertexOut) -> @location(0) vec4<f32> {
            let col = textureSample(tex, samp, in.uv);
            return vec4(1.0 - col.r, 1.0 - col.g, 1.0 - col.b, col.a);  // invert
        }
    ]])
    ```

    ---

    ## Applying a Shader

    ```lua
    function lurek.draw()
        lurek.renders.setShader(shader)
        lurek.renders.draw(image, 0, 0)
        lurek.renders.setShader()  -- reset to default
    end
    ```

    ---

    ## Shader Uniforms

    ```lua
    shader:send("time", lurek.timer.getTime())
    shader:send("resolution", {1280, 720})
    ```

    ---

    ## Post-Processing Shaders

    For screen-space effects, use `lurek.fx` with a canvas:

    ```lua
    local canvas = lurek.renders.newCanvas(1280, 720)
    local blur   = lurek.fx.newEffect("blur", { radius = 4 })

    function lurek.draw()
        lurek.renders.setCanvas(canvas)
        -- draw scene ...
        lurek.renders.setCanvas()

        lurek.fx.apply(blur, canvas)
        lurek.renders.draw(canvas, 0, 0)
    end
    ```

    ---

    See also: [[Graphics-API]] · [[FX-API]] · [[Camera-API]]
    """)


# ═══════════════════════════════════════════════════════════════════════════════
# Section 8: Data & Networking (combined pages)
# ═══════════════════════════════════════════════════════════════════════════════

def gen_data_apis() -> str:
    """Combined page for data, dataframe, compute, graph, serial, image."""
    sections = []
    for module, title in [
        ("data",      "lurek.data — Data Utilities"),
        ("dataframe", "lurek.dataframe — DataFrame"),
        ("compute",   "lurek.compute — NdArray Compute"),
        ("graph",     "lurek.graph — Graph"),
        ("serial",    "lurek.serial — Serialization"),
        ("image",     "lurek.image — CPU Image"),
    ]:
        spec = read_spec(module)
        summary = _spec_summary(module, 2)
        example = read_example(module, 60)
        tier_short = re.sub(r" — .*", "", spec.get("tier", "")) if spec else ""
        api_ns = spec.get("api", f"lurek.{module}") if spec else f"lurek.{module}"

        section = [f"## {title}", ""]
        if tier_short:
            section.append(f"> *{tier_short} · `{api_ns}`*")
            section.append("")
        if summary:
            section.append(_strip_source_refs(summary))
            section.append("")
        if example:
            section += ["```lua", example, "```", ""]
        sections.append("\n".join(section))

    body = "\n---\n\n".join(sections)

    return GEN_BANNER + dedent(f"""\
    # Data APIs

    Lurek2D provides a comprehensive suite of data processing modules for games that need
    structured data, numerical computation, graph algorithms, and serialisation.

    ---

    {body}

    ---

    See also: [[Filesystem-API]] · [[Savegame-API]] · [[Network-API]] · [[API-Reference]]
    """)


def gen_fx_api() -> str:
    """Combined page for fx and pipeline."""
    fx_overview  = _strip_source_refs(_spec_summary("fx", 3))
    fx_example   = read_example("fx", 80)
    pip_overview = _strip_source_refs(_spec_summary("pipeline", 3))
    pip_example  = read_example("pipeline", 80)

    return GEN_BANNER + dedent(f"""\
    # FX & Pipeline API

    Post-processing effects and multi-pass render pipeline.

    ---

    ## lurek.fx — Post-Processing Effects

    {fx_overview}

    ```lua
    {fx_example}
    ```

    ---

    ## lurek.pipeline — Render Pipeline Control

    {pip_overview}

    ```lua
    {pip_example}
    ```

    ---

    See also: [[Graphics-API]] · [[Shader-Patterns]] · [[Camera-API]] · [[API-Reference]]
    """)


def gen_advanced_apis() -> str:
    """Page for raycaster, spine, light, minimap."""
    sections = []
    for module, title in [
        ("raycaster", "lurek.raycaster — 3D-style Raycasting"),
        ("light",     "lurek.light — Dynamic 2D Lighting"),
        ("minimap",   "lurek.minimap — Minimap Renderer"),
        ("spine",     "lurek.spine — Spine Skeletal Animation"),
    ]:
        summary = _strip_source_refs(_spec_summary(module, 2))
        example = read_example(module, 60)
        spec = read_spec(module)
        api_ns = spec.get("api", f"lurek.{module}") if spec else f"lurek.{module}"
        section = [f"## {title}", "", f"> *`{api_ns}`*", ""]
        if summary:
            section += [summary, ""]
        if example:
            section += ["```lua", example, "```", ""]
        sections.append("\n".join(section))

    body = "\n---\n\n".join(sections)

    return GEN_BANNER + dedent(f"""\
    # Advanced APIs

    Specialised modules for visual effects, procedural generation, and advanced rendering.

    ---

    {body}

    ---

    See also: [[Graphics-API]] · [[Tilemap-API]] · [[Shader-Patterns]] · [[Procgen-API]] · [[API-Reference]]
    """)


# ═══════════════════════════════════════════════════════════════════════════════
# Section 10: Standard Library — Lunasome
# ═══════════════════════════════════════════════════════════════════════════════

def gen_lunasome() -> str:
    """Overview + module index."""
    module_rows = []
    for subdir in sorted(LIBRARY.iterdir()):
        if not subdir.is_dir():
            continue
        agent_md = _read(subdir / "AGENT.md")
        summary = ""
        if agent_md:
            for ln in agent_md.split("\n")[1:]:
                ln = ln.strip()
                if ln and not ln.startswith("#") and not ln.startswith("|") and not ln.startswith("---"):
                    summary = ln[:120]
                    break
        if not summary:
            summary = f"`library.{subdir.name}`"
        module_rows.append(f"| `{subdir.name}` | {summary} |")

    rows_str = "\n".join(module_rows)

    return GEN_BANNER + dedent(f"""\
    # Lunasome — Standard Library

    Tier 3 pure-Lua gameplay libraries that ship alongside Lurek2D but are not embedded in the binary.
    They consume only the public `lurek.*` API — no engine internals.

    ## Using Lunasome

    ```lua
    local dialog    = require("library.dialog")
    local inventory = require("library.inventory")
    local quest     = require("library.quest")
    local battle    = require("library.battle")
    ```

    The engine automatically adds the `content/library/` search path when a game is loaded.

    ---

    ## Module Index

    | Module | Description |
    |--------|-------------|
    {rows_str}

    ---

    ## Layer Contract

    - Lunasome modules **only** import from `lurek.*` and other `library.*` modules
    - The Rust engine never depends on Lunasome
    - Lunasome is versioned alongside the engine

    ---

    ## Testing

    Every Lunasome module has a corresponding Lua BDD test file:

    ```bash
    cargo test lua_test_library_dialog
    cargo test lua_test_library_inventory
    cargo test lua_test_library_quest
    cargo test lua_test_library_battle
    ```

    ---

    For detailed per-module documentation, see [[Lunasome-Modules]].

    See also: [[Demos]] · [[Examples]] · [[API-Reference]] · [[Contributing-Libraries]]
    """)


def gen_lunasome_modules() -> str:
    """Per-module detail page generated from content/library/*/AGENT.md."""
    sections = []
    for subdir in sorted(LIBRARY.iterdir()):
        if not subdir.is_dir():
            continue
        agent_md = _read(subdir / "AGENT.md")
        if not agent_md:
            continue

        name = subdir.name
        # Strip the first heading to avoid duplication
        body = re.sub(r"^#[^\n]+\n+", "", agent_md, count=1).strip()
        body = _strip_source_refs(body)

        sections.append(f"## {name}\n\n{body}\n")

    body_str = "\n---\n\n".join(sections)

    return GEN_BANNER + dedent(f"""\
    # Lunasome — Module Reference

    Detailed documentation for each Lunasome (Tier 3) pure-Lua library module.

    ---

    {body_str}

    ---

    See also: [[Lunasome]] · [[Contributing-Libraries]] · [[API-Reference]]
    """)


# ═══════════════════════════════════════════════════════════════════════════════
# Section 11: Demos & Examples
# ═══════════════════════════════════════════════════════════════════════════════

def gen_examples() -> str:
    """List all examples with descriptions."""
    ex_dir = EXAMPLES
    files = sorted(ex_dir.glob("*.lua"))

    rows = []
    for f in files:
        name = f.stem
        text = _read(f)
        lines = text.split("\n")
        desc = ""
        for ln in lines[:6]:
            ln = ln.strip()
            if ln.startswith("-- ") and not ln.startswith("-- content/examples/") and not ln.startswith("-- Lurek2D "):
                desc = ln[3:].strip()
                break
        if not desc:
            desc = f"Usage examples for `lurek.{name}`"
        rows.append(f"| `{name}.lua` | {desc} |")

    table = "\n".join(rows)
    return GEN_BANNER + dedent(f"""\
    # Examples

    Single-file API usage scripts — each demonstrates one `lurek.*` namespace.

    ## Running an Example

    ```bash
    cargo run -- content/examples/timer.lua
    cargo run -- content/examples/physics.lua
    ```

    Or with the installed binary:
    ```bash
    luna content/examples/timer.lua
    ```

    ---

    ## Example Index

    | File | Description |
    |------|-------------|
    {table}

    ---

    For complete runnable games, see [[Demos]].
    For the full API reference, see [[API-Reference]].
    """)


def gen_demos() -> str:
    """Generate Demos.md from content/demos/README.md."""
    demos_readme = _read(DEMOS / "README.md")
    if demos_readme:
        # Strip source references
        demos_readme = _strip_source_refs(demos_readme)
        return GEN_BANNER + f"# Demos\n\n{demos_readme.strip()}\n\n---\n\nSee also: [[Examples]] · [[Getting-Started]]\n"

    # Fallback: generate from directory structure
    categories = []
    for subdir in sorted(DEMOS.iterdir()):
        if not subdir.is_dir():
            continue
        demos = sorted(d.name for d in subdir.iterdir() if d.is_dir())
        count = len(demos)
        samples = ", ".join(demos[:5])
        if count > 5:
            samples += ", …"
        categories.append(f"| `{subdir.name}/` | {count} | {samples} |")

    table = "\n".join(categories)
    return GEN_BANNER + dedent(f"""\
    # Demos

    Lurek2D ships with 111+ fully playable demo games, organised by genre.

    ## Running a Demo

    ```bash
    cargo run -- content/demos/<category>/<name>
    luna content/demos/<category>/<name>
    ```

    ---

    ## Genres

    | Category | Count | Examples |
    |----------|-------|---------|
    {table}

    ---

    See also: [[Examples]] · [[Getting-Started]] · [[Contributing-Demos]]
    """)


def gen_demo_showcase() -> str:
    """MANUAL page — highlighted demos."""
    return MANUAL_BANNER + dedent("""\
    # Demo Showcase

    Hand-picked demos that showcase Lurek2D's capabilities.

    ---

    ## Arcade Classics

    ### Pong
    Two-player paddle game with physics-based ball bouncing.
    ```bash
    cargo run -- content/demos/arcade/pong
    ```

    ### Tetris
    Classic block-stacking puzzle with rotation and line clearing.
    ```bash
    cargo run -- content/demos/arcade/tetris
    ```

    ---

    ## Action Games

    ### Platformer
    Side-scrolling platformer with physics-based movement, jumping, and collectibles.
    ```bash
    cargo run -- content/demos/action/platformer
    ```

    ### Bullet Hell
    Intense dodging game with patterned enemy fire and score tracking.
    ```bash
    cargo run -- content/demos/action/bullet_hell
    ```

    ---

    ## Simulation

    ### Physics Demo
    Interactive physics sandbox — drag and throw objects, see collisions and joints in action.
    ```bash
    cargo run -- content/demos/simulation/physics_demo
    ```

    ### Farming Sim
    Plant crops, manage resources, and build a farm using the economy and inventory systems.
    ```bash
    cargo run -- content/demos/simulation/farming_sim
    ```

    ---

    ## Strategy

    ### Tower Defense
    Place towers, upgrade them, and defend against waves of enemies using the AI pathfinding system.
    ```bash
    cargo run -- content/demos/strategy/tower_defense
    ```

    ---

    For the full demo list, see [[Demos]].
    """)


# ═══════════════════════════════════════════════════════════════════════════════
# Section 12: Contributing (all MANUAL)
# ═══════════════════════════════════════════════════════════════════════════════

def gen_contributing() -> str:
    return MANUAL_BANNER + dedent(f"""\
    # Contributing to Lurek2D

    Lurek2D welcomes contributions from many different audiences. Whether you want to fix a bug in
    the Rust engine, add a new demo, write a Lunasome library module, improve the VS Code extension,
    or enhance the AI agent system — there's a place for you.

    ---

    ## Quick Start

    ```bash
    git clone {GITHUB_URL}
    cd luna_2d
    cargo build
    cargo run -- content/demos/showcase/hello_world
    ```

    ---

    ## Quality Gates

    Run these before opening a pull request:

    ```bash
    cargo fmt --check
    cargo clippy -- -D warnings
    cargo test
    ```

    ---

    ## Contribution Areas

    | What you want to do | Guide |
    |---------------------|-------|
    | Fix a bug or add an engine feature (Rust) | [[Contributing-Engine]] |
    | Add a new playable demo | [[Contributing-Demos]] |
    | Write a Lunasome library module (Lua) | [[Contributing-Libraries]] |
    | Improve the VS Code extension | [[Contributing-Extension]] |
    | Add or improve AI agents/skills | [[Contributing-CAG]] |
    | Understand code style rules | [[Coding-Conventions]] |

    ---

    ## Pull Request Guidelines

    - Keep changes focused — avoid unrelated cleanup
    - Add a regression test for bug fixes
    - Add integration coverage for new public APIs
    - Keep Lua tests headless-safe (no window, GPU, or audio device required)
    - Describe user-visible behavior and test coverage in the PR description
    - Security issues: follow [SECURITY.md]({GITHUB_URL}/blob/main/SECURITY.md) instead of posting publicly

    ---

    ## Architecture Overview

    Before contributing, familiarise yourself with:
    - [[Architecture]] — module tiers, dependency rules, boot sequence
    - [[Design-Principles]] — The Zen of Luna and binding constraints
    - [[Module-Tiers]] — tier system and what each tier can import
    - [[Testing-Framework]] — how to write and run tests

    ---

    See also: [[Getting-Started]] · [[Coding-Conventions]] · [[Build-System]]
    """)


def gen_contributing_engine() -> str:
    return MANUAL_BANNER + dedent("""\
    # Contributing to the Engine (Rust)

    This guide covers contributing Rust code to the Lurek2D engine.

    ---

    ## Module Architecture

    Lurek2D enforces a strict tier system:

    - **Baseline** (`math`) — leaf module, no internal deps
    - **Tier 1** — core subsystems; may import Baseline only
    - **Tier 2** — engine extensions; may import Baseline + Tier 1
    - **Bridge** (`lua_api`) — Lua bindings; may import all Rust tiers
    - Domain modules must **never** import `lua_api`

    See [[Module-Tiers]] for the full catalogue and [[Architecture]] for the dependency graph.

    ---

    ## Coding Standards

    - `unsafe` requires a `// SAFETY:` comment
    - Per-frame code must not heap-allocate — grow buffers at startup
    - Use `log::info!` / `log::warn!` / `log::error!` — never `println!`
    - Convert errors to `LuaError` at the Lua boundary with `.map_err(LuaError::external)`
    - Every `pub` item needs a `///` docstring
    - See [[Coding-Conventions]] for the full style guide

    ---

    ## Adding a New Lua API Function

    1. Add the Rust implementation in the domain module
    2. Register the Lua binding in the corresponding `_api.rs` file
    3. Use the standard registration pattern:

    ```rust
    let s = state.clone();
    tbl.set("myFunction", lua.create_function(move |_, args: (f64, f64)| {
        let state = s.borrow();
        Ok(state.do_something(args.0, args.1))
    })?)?;
    ```

    4. Add a Lua BDD test
    5. Update the example file if one exists

    ---

    ## Adding a New Module

    1. Create the module directory with `mod.rs`
    2. Create an `AGENT.md` with a short overview
    3. Decide which tier the module belongs to (consult [[Module-Tiers]])
    4. Register it in `Cargo.toml` if needed
    5. If it has a Lua API, create a `_api.rs` file in the lua_api bridge
    6. Add tests in the appropriate test directory
    7. Create a spec file with full documentation

    ---

    ## Testing

    - **Rust unit tests**: named `<subject>_<scenario>_<expected>` (no `test_` prefix)
    - **Float comparisons**: use `assert!((val - expected).abs() < 1e-5)`, never `assert_eq!`
    - **Lua BDD tests**: `describe`/`it`/`expect_equal` framework
    - All tests run headless — no window, GPU, or audio required

    ```bash
    cargo test --test math_tests              # one Rust suite
    cargo test lua_test_unit_timer            # one Lua test
    cargo test                                # all tests
    ```

    See [[Testing-Framework]] for full details.

    ---

    ## Quality Gate

    ```bash
    cargo test && cargo clippy -- -D warnings
    ```

    ---

    See also: [[Architecture]] · [[Module-Tiers]] · [[Coding-Conventions]] · [[Testing-Framework]]
    """)


def gen_contributing_demos() -> str:
    return MANUAL_BANNER + dedent("""\
    # Contributing Demos

    Demos are fully playable game showcases that demonstrate Lurek2D's capabilities.

    ---

    ## Demo Folder Structure

    ```
    content/demos/<category>/<name>/
    ├── main.lua           -- entry point (required)
    ├── conf.lua           -- window config (optional)
    ├── README.md          -- description, controls, screenshot (required)
    └── assets/            -- images, sounds, fonts (optional)
    ```

    ---

    ## Categories

    | Category | For |
    |----------|-----|
    | `arcade/` | Classic arcade-style games |
    | `action/` | Action, platformer, shooter |
    | `rpg/` | Role-playing, visual novels |
    | `simulation/` | Physics, farming, factory |
    | `strategy/` | Tower defense, RTS, card games |
    | `sports/` | Sports and rhythm games |
    | `retro/` | Retro-styled games |
    | `showcase/` | Technical showcases and feature demos |

    ---

    ## Requirements

    1. **Self-contained** — demos must not depend on external files outside their folder
    2. **README.md** — must include title, description, controls, and a screenshot
    3. **Test** — every demo must have a Lua BDD test file
    4. **Headless-safe test** — the test must run without a window, GPU, or audio device

    ---

    ## Adding a Test

    Create a test file and register it in the test harness:

    ```lua
    -- tests/lua/content/demos/test_demo_my_game.lua
    describe("demo: my_game", function()
        it("loads without error", function()
            -- test game initialization
        end)
    end)
    test_summary()
    ```

    ---

    ## Running a Demo

    ```bash
    cargo run -- content/demos/<category>/<name>
    ```

    ---

    See also: [[Demos]] · [[Demo-Showcase]] · [[Contributing]] · [[Getting-Started]]
    """)


def gen_contributing_libraries() -> str:
    return MANUAL_BANNER + dedent("""\
    # Contributing Lunasome Libraries

    Lunasome is Lurek2D's standard library — pure-Lua gameplay modules.

    ---

    ## Module Structure

    ```
    content/library/<name>/
    ├── init.lua           -- module entry, returns the API table
    ├── AGENT.md           -- module documentation
    └── (additional .lua)  -- internal files if needed
    ```

    ---

    ## Layer Rules

    - **Only** import from `lurek.*` API and other `library.*` modules
    - Never access engine internals or Rust-specific features
    - Must be testable headless (no graphics, audio, or window APIs)

    ---

    ## API Pattern

    ```lua
    local M = {}

    function M.newWidget(name)
        local self = {
            name  = name or "untitled",
            value = 0,
        }
        -- methods ...
        function self:getValue() return self.value end
        function self:setValue(v) self.value = v end
        return self
    end

    return M
    ```

    ---

    ## Testing

    Every module must have a Lua BDD test:

    ```lua
    -- tests/lua/content/library/test_library_<name>.lua
    local M = require("library.<name>")

    describe("<name>", function()
        it("creates a widget", function()
            local w = M.newWidget("test")
            expect_equal(w:getValue(), 0)
        end)
    end)
    test_summary()
    ```

    Register it in the harness and run:

    ```bash
    cargo test lua_test_library_<name>
    ```

    ---

    ## Existing Modules

    See [[Lunasome-Modules]] for the full catalogue: battle, cardgame, combat, crafting,
    dialog, doll, economy, inventory, item, province_map, quest, stats.

    ---

    See also: [[Lunasome]] · [[Lunasome-Modules]] · [[Contributing]] · [[Coding-Conventions]]
    """)


def gen_contributing_extension() -> str:
    return MANUAL_BANNER + dedent("""\
    # Contributing to the VS Code Extension

    The Lurek2D VS Code extension provides Lua API completions, an MCP server for AI workflows,
    a Lua debugger, and example runner integration.

    ---

    ## Prerequisites

    - Node.js 18+
    - VS Code 1.90.0+ for testing
    - The Lurek2D engine built and accessible

    ---

    ## Setup

    ```bash
    cd vscode-extension
    npm install
    npm run compile
    ```

    Press F5 in VS Code to launch an Extension Development Host.

    ---

    ## Architecture

    The extension is organised into these areas:

    | Area | What it does |
    |------|-------------|
    | `extension.ts` | Entry point — activation, command registration |
    | `mcp/` | Model Context Protocol server with 6 tools |
    | `debug/` | Lua debug adapter and debug session handler |
    | `providers/` | LuaCATS completions and document symbol provider |
    | `services/` | API data loading, symbol indexing, status bar, process management |
    | `commands/` | Command implementations for the command palette |

    ---

    ## MCP Tools

    The extension exposes 6 MCP tools for AI-assisted development:

    | Tool | Purpose |
    |------|---------|
    | `lurek2d.runExample` | Build and run a named demo |
    | `lurek2d.getApiDoc` | Search the API reference |
    | `lurek2d.listExamples` | List all available demos |
    | `lurek2d.runLuaTest` | Run a Lua test file |
    | `lurek2d.checkBuild` | Run `cargo check` |
    | `lurek2d.getLogs` | Get recent engine log output |

    See [[Extension-MCP-Server]] for full tool documentation.

    ---

    ## Adding a New Feature

    1. Add the implementation in the appropriate directory
    2. Register commands in `package.json` and `extension.ts`
    3. Test in the Extension Development Host (F5)
    4. Update the extension's README

    ---

    See also: [[VS-Code-Extension]] · [[Extension-MCP-Server]] · [[Extension-Development]] · [[Contributing]]
    """)


def gen_contributing_cag() -> str:
    return MANUAL_BANNER + dedent("""\
    # Contributing to the CAG System

    The CAG (Copilot Agent Customization) system configures GitHub Copilot for Lurek2D development.

    ---

    ## What is CAG?

    The CAG layer consists of:
    - **Agents** — specialist AI personas with defined missions and skills
    - **Skills** — domain-specific knowledge bundles loaded on demand
    - **Prompts** — reusable prompt templates for common tasks
    - **System prompt** — the always-on backbone (`copilot-instructions.md`)

    ---

    ## File Locations

    | Type | Location | Format |
    |------|----------|--------|
    | Agents | `.github/agents/*.agent.md` | YAML frontmatter + Markdown body |
    | Skills | `.github/skills/<name>/SKILL.md` | Markdown with domain instructions |
    | Prompts | `.github/prompts/*.prompt.md` | YAML frontmatter + template body |
    | System prompt | `.github/copilot-instructions.md` | Comprehensive Markdown |

    ---

    ## Adding an Agent

    Create a new `.agent.md` file with YAML frontmatter:

    ```yaml
    ---
    name: MyAgent
    description: "**MyAgent** — One sentence mission description."
    tools:
      - read_file
      - grep_search
    ---

    # MyAgent

    ## Mission
    Describe what this agent does...

    ## Scope
    What it owns and must not do...
    ```

    ---

    ## Adding a Skill

    Create a new folder under `.github/skills/<name>/` with a `SKILL.md`:

    ```markdown
    # <Skill Name>

    One-paragraph elevator pitch.

    ## When to Load

    - Trigger conditions...

    ## Key Rules

    - Domain-specific instructions...
    ```

    ---

    ## Validation

    After every edit to `.github/`, run:

    ```bash
    python tools/validate/cag_validate.py
    ```

    The validator checks:
    - YAML frontmatter structure
    - Required sections
    - Cross-references between agents and skills
    - Naming conventions

    ---

    See also: [[CAG-System]] · [[CAG-Workflow]] · [[Contributing]]
    """)


def gen_coding_conventions() -> str:
    return MANUAL_BANNER + dedent("""\
    # Coding Conventions

    Style rules for Rust engine code and Lua game scripts.

    ---

    ## Rust Conventions

    ### Naming
    - Modules: `snake_case`
    - Types: `PascalCase`
    - Functions: `snake_case`
    - Constants: `SCREAMING_SNAKE_CASE`

    ### Safety
    - `unsafe` requires a `// SAFETY:` comment explaining the invariant
    - Never use raw pointers for state sharing
    - Per-frame code must not allocate on the heap

    ### Error Handling
    - Use `EngineError` for engine-internal errors
    - Convert to `LuaError` at the Lua API boundary: `.map_err(LuaError::external)`
    - Never panic in engine code — return `Result`

    ### Logging
    - Use `log::info!` / `log::warn!` / `log::error!` / `log::debug!`
    - Never use `println!` in engine code
    - Control output: `RUST_LOG=lurek2d=debug cargo run`

    ### Docstrings
    - Every `pub` item needs `///`
    - Every module needs `//!`
    - Format: one-sentence summary, optional detail paragraph

    ---

    ## Lua API Conventions

    ### Namespace
    - All bindings under `lurek.*` — never bare globals
    - Use inline `@param` and `@return` annotations (not `# Parameters` sections)

    ### Registration Pattern
    ```rust
    let s = state.clone();
    tbl.set("funcName", lua.create_function(move |_, arg: Type| {
        Ok(s.borrow().method(arg))
    })?)?;
    ```

    ### API Design
    - Sensible defaults — never require a parameter a beginner would always pass the same value
    - All callbacks are optional — blank `main.lua` is valid
    - Validate inputs at the Lua boundary — return descriptive `LuaError`, never panic
    - Lua API is synchronous from the script's perspective

    ---

    ## Lua Game Script Style

    ### Structure
    ```lua
    -- Module-level state
    local player = {}
    local enemies = {}

    function lurek.load()
        -- initialization
    end

    function lurek.update(dt)
        -- game logic
    end

    function lurek.draw()
        -- rendering
    end
    ```

    ### Best Practices
    - Use `local` for all variables — avoid globals
    - Use meaningful variable names
    - Group related functionality into tables
    - Use `require()` for code organisation

    ---

    ## Commit Message Format

    ```
    type(scope): description
    ```

    Types: `feat` `fix` `refactor` `test` `docs` `chore`

    ---

    See also: [[Contributing]] · [[Contributing-Engine]] · [[Architecture]] · [[Testing-Framework]]
    """)


# ═══════════════════════════════════════════════════════════════════════════════
# Section 13: VS Code Extension
# ═══════════════════════════════════════════════════════════════════════════════

def gen_vscode_ext() -> str:
    return GEN_BANNER + dedent("""\
    # VS Code Extension

    Lurek2D has a first-party VS Code extension that provides IDE integration for game development.

    ---

    ## Features

    | Feature | Description |
    |---------|-------------|
    | **MCP Server** | 6 AI-accessible tools for building, running, testing, and querying the API |
    | **Lua API Completions** | Autocomplete for all `lurek.*` functions with parameter info |
    | **LuaCATS Support** | Parses `---@class`, `---@param`, `---@return` tags for user-defined types |
    | **Lua Debugger** | Set breakpoints, step through, inspect variables in Lua scripts |
    | **Example Runner** | Browse and run Lurek2D demos directly from the command palette |
    | **API Documentation** | Search the `lurek.*` API reference without leaving the editor |
    | **Symbol Indexing** | Navigate to Lua function definitions across your project |
    | **Status Bar** | Shows Lurek2D build status and active project info |

    ---

    ## Installation

    ### From VSIX

    1. Build the extension: `cd vscode-extension && npm install && npm run compile`
    2. Package: `npx vsce package`
    3. Install: Extensions → "..." → "Install from VSIX..."

    ### From Marketplace

    *(Coming soon)*

    ---

    ## Activation

    The extension activates automatically when:
    - A folder containing `main.lua` is opened
    - A `.lua` file is opened in a Lurek2D project

    ---

    ## MCP Tools (for AI Agents)

    The extension exposes 6 tools via the Model Context Protocol:

    | Tool | Input | What it does |
    |------|-------|-------------|
    | `lurek2d.runExample` | `name: string` | Build and run a named demo |
    | `lurek2d.getApiDoc` | `query: string` | Search the API reference docs |
    | `lurek2d.listExamples` | *(none)* | List all available demos |
    | `lurek2d.runLuaTest` | `file: string` | Run a specific Lua test file |
    | `lurek2d.checkBuild` | *(none)* | Run `cargo check` and return diagnostics |
    | `lurek2d.getLogs` | `lines?: number` | Get last N lines of engine log output |

    See [[Extension-MCP-Server]] for detailed documentation.

    ---

    ## Requirements

    - VS Code 1.90.0+
    - Rust toolchain (for building Lurek2D)
    - Lurek2D source in the workspace

    ---

    ## AI-First Workflow

    The extension is designed for AI-assisted development. GitHub Copilot agents can:
    - Build the project via `lurek2d.checkBuild`
    - Run demos via `lurek2d.runExample`
    - Look up API docs via `lurek2d.getApiDoc`
    - Run tests via `lurek2d.runLuaTest`

    The CAG layer (agents, skills, prompts) ships with the extension for immediate Copilot integration.

    ---

    See also: [[Extension-MCP-Server]] · [[Extension-Development]] · [[CAG-System]] · [[Contributing-Extension]]
    """)


def gen_extension_mcp() -> str:
    """MANUAL page — detailed MCP tool reference."""
    return MANUAL_BANNER + dedent("""\
    # Extension MCP Server

    The Lurek2D VS Code extension includes a Model Context Protocol (MCP) server
    that exposes 6 tools for AI-assisted development.

    ---

    ## lurek2d.runExample

    Build and run a named demo.

    **Input**: `{ name: string }` — e.g. `"hello_world"`, `"pong"`

    **Behaviour**: Runs `cargo run -- content/demos/<name>` with a 120-second timeout.
    Returns combined stdout + stderr output.

    **Example**: `lurek2d.runExample({ name: "showcase/hello_world" })`

    ---

    ## lurek2d.getApiDoc

    Search the generated API reference for a query string.

    **Input**: `{ query: string }` — e.g. `"lurek.renders.draw"`, `"physics"`

    **Behaviour**: Searches the generated API markdown file case-insensitively.
    Returns matching sections with context.

    ---

    ## lurek2d.listExamples

    List all available demo directory names.

    **Input**: *(none)*

    **Behaviour**: Reads the `content/demos/` folder and returns a newline-separated list.

    ---

    ## lurek2d.runLuaTest

    Run a specific Lua test file.

    **Input**: `{ file: string }` — path relative to workspace root

    **Behaviour**: Runs `cargo run -- <file>` and captures output + exit code.

    ---

    ## lurek2d.checkBuild

    Run `cargo check` and return compiler diagnostics.

    **Input**: *(none)*

    **Behaviour**: Runs `cargo check` in the workspace root. Returns diagnostics output.

    ---

    ## lurek2d.getLogs

    Get recent engine log output.

    **Input**: `{ lines?: number }` — default 50

    **Behaviour**: Returns last N lines of Lurek2D engine log output (max 1MB buffer).

    ---

    ## Error Handling

    All tools return combined stdout + stderr. Non-zero exit codes are reported
    with the exit code visible in the output. Tools handle graceful timeouts.

    ---

    See also: [[VS-Code-Extension]] · [[Extension-Development]] · [[CAG-System]]
    """)


def gen_extension_dev() -> str:
    """MANUAL page — extension development guide."""
    return MANUAL_BANNER + dedent("""\
    # Extension Development

    How to develop and extend the Lurek2D VS Code extension.

    ---

    ## Prerequisites

    - Node.js 18+
    - VS Code 1.90.0+
    - Lurek2D engine built in the workspace

    ---

    ## Setup

    ```bash
    cd vscode-extension
    npm install
    npm run compile
    ```

    ---

    ## Development Workflow

    1. Open the `extensions/vscode/` folder in VS Code
    2. Press **F5** to launch an Extension Development Host
    3. Make changes to TypeScript source files
    4. Reload the Extension Development Host to test

    ---

    ## Architecture

    | Directory | Purpose |
    |-----------|---------|
    | `extension.ts` | Extension entry point and activation |
    | `commands/` | Command palette command implementations |
    | `mcp/server.ts` | MCP server setup and lifecycle |
    | `mcp/tools.ts` | MCP tool definitions and handlers |
    | `debug/luaDebugSession.ts` | Lua debug adapter protocol implementation |
    | `debug/luaDebugAdapter.ts` | Debug adapter factory |
    | `providers/luacatsProvider.ts` | LuaCATS tag completion provider |
    | `services/apiData.ts` | API data loading and search |
    | `services/symbolIndex.ts` | Lua symbol indexing |
    | `services/statusBar.ts` | Status bar integration |
    | `services/lunaProcess.ts` | Lurek2D process management |

    ---

    ## Adding a New Command

    1. Define the command in `package.json` under `contributes.commands`
    2. Implement the handler in `commands/`
    3. Register the command in `extension.ts` during activation
    4. Test via the Extension Development Host

    ---

    ## Adding a New MCP Tool

    1. Define the tool schema in `mcp/tools.ts`
    2. Implement the handler function
    3. Register it in the MCP server's tool list
    4. Test with an MCP client or via Copilot

    ---

    ## Packaging

    ```bash
    npx vsce package
    ```

    This produces a `.vsix` file that can be installed via "Install from VSIX..."
    in VS Code's Extensions view.

    ---

    See also: [[VS-Code-Extension]] · [[Extension-MCP-Server]] · [[Contributing-Extension]]
    """)


# ═══════════════════════════════════════════════════════════════════════════════
# Section 14: Tooling
# ═══════════════════════════════════════════════════════════════════════════════

def gen_tools() -> str:
    """Generate Tools.md from tools/README.md."""
    tools_readme = _read(TOOLS / "README.md")
    tools_readme = _strip_source_refs(tools_readme)

    return GEN_BANNER + dedent(f"""\
    # Tools

    Permanent CLI scripts for the Lurek2D engine pipeline.

    ---

    ## Quick Reference

    ### Documentation

    ```bash
    python tools/docs/gen_wiki.py                      # Regenerate ALL wiki pages
    python tools/docs/gen_wiki_api.py                  # Regenerate API-Reference.md cheatsheet
    python tools/docs/gen_lua_api.py                   # Lua API reference
    python tools/docs/collect_docs.py --report-missing # List missing docstrings
    python tools/gen_all_docs.py                       # Full documentation pipeline
    ```

    ### Auditing & Coverage

    ```bash
    python tools/audit/doc_coverage.py                 # Docstring coverage report
    python tools/audit/test_coverage.py                # Test coverage summary
    python tools/audit/audit_module.py <name>          # Single module audit
    python tools/audit/module_audit.py                 # Full codebase module audit
    ```

    ### Validation

    ```bash
    python tools/validate/cag_validate.py              # Validate all CAG files
    python tools/validate/validate_lua_api.py          # Check Lua API consistency
    ```

    ### Building & Distribution

    ```bash
    powershell tools/dist/dist.ps1                     # Package for Windows
    bash tools/dist/dist.sh                            # Package for Linux/macOS
    makensis tools/dist/installer.nsi                  # Build NSIS installer (Windows)
    ```

    ### Assets

    ```bash
    python tools/assets/gen_splash.py                  # Regenerate splash screen
    python tools/assets/gen_icon.py                    # Regenerate icon files
    ```

    ---

    ## Full Tool Index

    {tools_readme.strip()}

    ---

    See also: [[Build-System]] · [[CAG-System]] · [[VS-Code-Extension]]
    """)


def gen_build_system() -> str:
    """MANUAL page — build system details."""
    return MANUAL_BANNER + dedent(f"""\
    # Build System

    Lurek2D uses Cargo as its build system with a custom output directory.

    ---

    ## Building

    ```bash
    cargo build              # debug build
    cargo build --release    # release build (optimised)
    ```

    > **Output directory**: Lurek2D overrides Cargo's default `target/` and writes
    > build artifacts to `build/` instead. Debug binaries go to `build/debug/`,
    > release binaries to `build/release/`.

    ---

    ## Cargo Features

    | Feature | Purpose |
    |---------|---------|
    | `lua-jit` | **Primary** — LuaJIT runtime (default, used in production) |
    | `lua54` | Development fallback — Lua 5.4 runtime (not for shipping) |

    ```bash
    cargo build --features lua-jit           # default (LuaJIT)
    cargo build --features lua54             # fallback (Lua 5.4)
    ```

    ---

    ## Running

    ```bash
    cargo run -- content/demos/showcase/hello_world  # run a demo
    cargo run -- path/to/my_game             # run a game folder
    cargo run -- content/examples/physics.lua        # run an example
    cargo run                                # splash screen (no game)
    ```

    ---

    ## Installation

    Install the binary system-wide:

    ```bash
    # Windows
    powershell tools/dist/install.ps1

    # Linux / macOS
    bash tools/dist/install.sh
    ```

    After installation, use `luna` from anywhere:
    ```bash
    luna content/demos/showcase/hello_world
    luna path/to/my_game
    ```

    ---

    ## Distribution

    Package for distribution:

    ```bash
    # Windows — creates dist/lurek2d-windows-x86_64/
    powershell tools/dist/dist.ps1

    # Linux/macOS — creates dist/lurek2d-<os>-<arch>/
    bash tools/dist/dist.sh

    # Windows installer (requires NSIS 3.x)
    makensis tools/dist/installer.nsi
    ```

    ---

    ## Quality Gates

    ```bash
    cargo fmt --check                        # format check
    cargo clippy -- -D warnings              # lint (must pass with zero warnings)
    cargo test                               # all tests
    cargo test && cargo clippy -- -D warnings  # full quality gate
    ```

    ---

    ## Type-Check Only (Fast)

    ```bash
    cargo check                              # fast type-check, no binary output
    ```

    ---

    ## Debug Logging

    ```bash
    RUST_LOG=lurek2d=debug cargo run -- content/demos/showcase/hello_world
    ```

    | Level | Shows |
    |-------|-------|
    | `error` | Unrecoverable failures |
    | `warn` | Recoverable issues |
    | `info` | Lifecycle events (startup, shutdown) |
    | `debug` | Per-frame detail |

    ---

    See also: [[Getting-Started]] · [[Tools]] · [[Contributing-Engine]] · [[Testing-Framework]]
    """)


# ═══════════════════════════════════════════════════════════════════════════════
# Section 15: CAG System
# ═══════════════════════════════════════════════════════════════════════════════

def gen_cag_system() -> str:
    """Generate CAG-System.md from .github/ content."""
    agents_dir = GITHUB / "agents"
    skills_dir = GITHUB / "skills"

    agent_rows = []
    if agents_dir.exists():
        for f in sorted(agents_dir.glob("*.agent.md")):
            text = _read(f)
            fm_match = re.search(
                r'^description:\s*["\']?(.*?)["\']?\s*$',
                text, re.MULTILINE,
            )
            if fm_match:
                raw = fm_match.group(1).strip().strip('"\'')
                raw = re.sub(r'^\*\*[^*]+\*\*\s*—\s*', '', raw)
                mission = raw[:150]
            else:
                mm = re.search(r"## Mission\s*\n(.+?)(?:\n|$)", text)
                mission = mm.group(1).strip()[:150] if mm else "—"
            name_match = re.search(r'^name:\s*(.+)$', text, re.MULTILINE)
            display = name_match.group(1).strip() if name_match else f.stem.replace(".agent", "")
            agent_rows.append(f"| **{display}** | {mission} |")

    skill_rows = []
    if skills_dir.exists():
        for subdir in sorted(skills_dir.iterdir()):
            if not subdir.is_dir():
                continue
            skill_md = _read(subdir / "SKILL.md")
            desc = ""
            for ln in skill_md.split("\n")[:20]:
                ln = ln.strip()
                if ln and not ln.startswith("#") and not ln.startswith("<!--"):
                    desc = ln[:140]
                    break
            skill_rows.append(f"| `{subdir.name}` | {desc} |")

    agent_table = "\n".join(agent_rows) if agent_rows else "_No agents found._"
    skill_table = "\n".join(skill_rows) if skill_rows else "_No skills found._"

    return GEN_BANNER + dedent(f"""\
    # CAG System — Copilot Agent Customization

    The CAG (Copilot Agent Customization) layer configures GitHub Copilot for
    AI-first Lurek2D development. It provides specialist agents, domain skills,
    and reusable prompts.

    ---

    ## Overview

    The CAG layer follows a strict load order:

    ```
    System Prompt (copilot-instructions.md)
      └── Module AGENT.md files (overview per module)
          └── Spec files (full technical detail)
              └── Skills (loaded on demand)
                  └── Prompts / Agents (task-specific)
    ```

    ---

    ## Agents

    Specialist agents, each with a defined mission:

    | Agent | Mission |
    |-------|---------|
    {agent_table}

    ---

    ## Skills

    Domain-specific knowledge bundles loaded when a matching task is detected:

    | Skill | Description |
    |-------|-------------|
    {skill_table}

    ---

    ## Validation

    After editing any CAG file, validate:

    ```bash
    python tools/validate/cag_validate.py              # Full validation
    python tools/validate/cag_validate.py --file <path>  # Single file
    ```

    ---

    See also: [[CAG-Workflow]] · [[Contributing-CAG]] · [[VS-Code-Extension]] · [[Tools]]
    """)


def gen_cag_workflow() -> str:
    """MANUAL page — how to use CAG for development."""
    return MANUAL_BANNER + dedent("""\
    # CAG Workflow

    How the Copilot Agent Customization (CAG) system works in practice.

    ---

    ## What Happens When You Ask Copilot

    1. **System prompt** loads automatically — engine constraints, module rules, API conventions
    2. **Module AGENT.md** files provide short overviews of relevant modules
    3. **Spec files** are loaded for deep technical detail when needed
    4. **Skills** are loaded on demand based on the task domain
    5. **Agent mode** activates if you're in a specific agent (e.g., Manager, Developer, Tester)

    ---

    ## Agent Workflow

    For multi-step tasks, the Manager agent:

    1. Confirms the current Git branch
    2. Creates a work session folder with standard subfolders
    3. Decomposes the task into agent handoffs
    4. Routes each subtask to the most specific specialist
    5. Runs quality gates between phases
    6. Commits after each accepted phase

    ---

    ## Session Folders

    Every session creates:

    ```
    work/<session-name>/
    ├── scripts/         -- session-scoped scripts
    ├── handovers/       -- inter-agent context
    ├── reports/         -- analysis output
    ├── data/            -- working data
    ├── content/demos/           -- session demos
    ├── other/           -- uncategorised
    ├── temp/            -- temporary files
    └── logs/
        └── agent_log.jsonl
    ```

    ---

    ## Skills vs Agents

    | Concept | What it is | When it loads |
    |---------|------------|---------------|
    | **Skill** | Domain knowledge bundle | Automatically, when task matches skill description |
    | **Agent** | Specialist persona with defined scope | When explicitly invoked or routed to |

    ---

    ## Quality Gates

    Every phase ends with:

    ```bash
    cargo test && cargo clippy -- -D warnings
    ```

    Commit only after the gate passes.

    ---

    See also: [[CAG-System]] · [[Contributing-CAG]] · [[Architecture]]
    """)


# ═══════════════════════════════════════════════════════════════════════════════
# Section 16: Navigation
# ═══════════════════════════════════════════════════════════════════════════════

def gen_sidebar() -> str:
    return dedent("""\
    ## Lurek2D Wiki

    ### Getting Started
    * [[Home]]
    * [[Getting-Started]]
    * [[Your-First-Game]]
    * [[Project-Structure]]
    * [[Configuration]]
    * [[Callbacks]]
    * [[Examples]]
    * [[Demos]]

    ### Architecture
    * [[Architecture]]
    * [[Design-Principles]]
    * [[Module-Tiers]]
    * [[Testing-Framework]]

    ### API Reference
    * [[API-Reference]]

    ### Core Modules
    * [[Graphics-API]]
    * [[Audio-API]]
    * [[Physics-API]]
    * [[Input-API]]
    * [[Math-API]]
    * [[Timer-API]]
    * [[Filesystem-API]]
    * [[Window-API]]

    ### Graphics & Rendering
    * [[Camera-API]]
    * [[Animation-API]]
    * [[Particle-API]]
    * [[FX-API]]
    * [[Shader-Patterns]]

    ### Game Systems
    * [[Tilemap-API]]
    * [[Scene-API]]
    * [[Entity-API]]
    * [[Pathfinding-API]]
    * [[AI-API]]
    * [[Savegame-API]]

    ### UI
    * [[GUI-API]]
    * [[Terminal-API]]

    ### Data & Scripting
    * [[Data-APIs]]
    * [[Event-API]]
    * [[Automation-API]]
    * [[Threading]]
    * [[Network-API]]

    ### Effects & Extras
    * [[Modding-API]]
    * [[Procgen-API]]
    * [[Advanced-APIs]]

    ### Standard Library
    * [[Lunasome]]
    * [[Lunasome-Modules]]

    ### Contributing
    * [[Contributing]]
    * [[Contributing-Engine]]
    * [[Contributing-Demos]]
    * [[Contributing-Libraries]]
    * [[Contributing-Extension]]
    * [[Contributing-CAG]]
    * [[Coding-Conventions]]

    ### Tooling
    * [[VS-Code-Extension]]
    * [[Extension-MCP-Server]]
    * [[Extension-Development]]
    * [[Tools]]
    * [[Build-System]]
    * [[CAG-System]]
    * [[CAG-Workflow]]
    """)


def gen_footer() -> str:
    return f"---\n[Lurek2D]({GITHUB_URL}) · MIT License · Built with Rust + LuaJIT\n"


# ═══════════════════════════════════════════════════════════════════════════════
# Page registry — (slug, filename, generator, is_manual)
# ═══════════════════════════════════════════════════════════════════════════════

PAGES: dict[str, tuple[str, callable, bool]] = {
    # ── Section 1: Welcome & Getting Started ──────────────────────────
    "Home":                 ("Home.md",                gen_home,                False),
    "Getting-Started":      ("Getting-Started.md",     gen_getting_started,     False),
    "Your-First-Game":      ("Your-First-Game.md",     gen_your_first_game,     True),
    "Project-Structure":    ("Project-Structure.md",   gen_project_structure,   True),
    "Configuration":        ("Configuration.md",       gen_configuration,       False),
    "Callbacks":            ("Callbacks.md",           gen_callbacks,           False),

    # ── Section 2: Architecture & Design ──────────────────────────────
    "Architecture":         ("Architecture.md",        gen_architecture,        False),
    "Design-Principles":    ("Design-Principles.md",   gen_design_principles,   False),
    "Module-Tiers":         ("Module-Tiers.md",        gen_module_tiers,        False),
    "Testing-Framework":    ("Testing-Framework.md",   gen_testing_framework,   False),

    # ── Section 3: API Reference — handled by gen_wiki_api.py ─────────
    # API-Reference.md is NOT in this registry; it's generated by gen_wiki_api.py

    # ── Section 4: Core Module APIs ───────────────────────────────────
    "Graphics-API":         ("Graphics-API.md",
                             lambda: gen_module_page("graphics", "Graphics API"), False),
    "Audio-API":            ("Audio-API.md",
                             lambda: gen_module_page("audio", "Audio API"), False),
    "Physics-API":          ("Physics-API.md",
                             lambda: gen_module_page("physics", "Physics API"), False),
    "Input-API":            ("Input-API.md",
                             lambda: gen_module_page("input", "Input API"), False),
    "Math-API":             ("Math-API.md",
                             lambda: gen_module_page("math", "Math API"), False),
    "Timer-API":            ("Timer-API.md",
                             lambda: gen_module_page("timer", "Timer API"), False),
    "Filesystem-API":       ("Filesystem-API.md",
                             lambda: gen_module_page("filesystem", "Filesystem API"), False),
    "Window-API":           ("Window-API.md",
                             lambda: gen_module_page("window", "Window API"), False),

    # ── Section 5: Graphics & Rendering ───────────────────────────────
    "Camera-API":           ("Camera-API.md",
                             lambda: gen_module_page("camera", "Camera API"), False),
    "Animation-API":        ("Animation-API.md",
                             lambda: gen_module_page("animation", "Animation API"), False),
    "Particle-API":         ("Particle-API.md",
                             lambda: gen_module_page("particle", "Particle API"), False),
    "FX-API":               ("FX-API.md",             gen_fx_api,              False),
    "Shader-Patterns":      ("Shader-Patterns.md",    gen_shader_patterns,     True),

    # ── Section 6: Game Systems ───────────────────────────────────────
    "Tilemap-API":          ("Tilemap-API.md",
                             lambda: gen_module_page("tilemap", "Tilemap API"), False),
    "Scene-API":            ("Scene-API.md",
                             lambda: gen_module_page("scene", "Scene API"), False),
    "Entity-API":           ("Entity-API.md",
                             lambda: gen_module_page("entity", "Entity API"), False),
    "Pathfinding-API":      ("Pathfinding-API.md",
                             lambda: gen_module_page("pathfinding", "Pathfinding API"), False),
    "AI-API":               ("AI-API.md",
                             lambda: gen_module_page("ai", "AI API"), False),
    "Savegame-API":         ("Savegame-API.md",
                             lambda: gen_module_page("savegame", "Savegame API"), False),

    # ── Section 7: UI ─────────────────────────────────────────────────
    "GUI-API":              ("GUI-API.md",
                             lambda: gen_module_page("gui", "GUI API"), False),
    "Terminal-API":         ("Terminal-API.md",
                             lambda: gen_module_page("terminal", "Terminal API"), False),

    # ── Section 8: Data & Networking ──────────────────────────────────
    "Data-APIs":            ("Data-APIs.md",          gen_data_apis,           False),
    "Event-API":            ("Event-API.md",
                             lambda: gen_module_page("event", "Event API"), False),
    "Threading":            ("Threading.md",
                             lambda: gen_module_page("thread", "Threading"), False),
    "Automation-API":       ("Automation-API.md",
                             lambda: gen_module_page("automation", "Automation API"), False),
    "Network-API":          ("Network-API.md",
                             lambda: gen_module_page("network", "Network API"), False),

    # ── Section 9: Effects & Extras ───────────────────────────────────
    "Modding-API":          ("Modding-API.md",
                             lambda: gen_module_page("modding", "Modding API"), False),
    "Procgen-API":          ("Procgen-API.md",
                             lambda: gen_module_page("procgen", "Procedural Generation API"), False),
    "Advanced-APIs":        ("Advanced-APIs.md",      gen_advanced_apis,       False),

    # ── Section 10: Lunasome ──────────────────────────────────────────
    "Lunasome":             ("Lunasome.md",           gen_lunasome,            False),
    "Lunasome-Modules":     ("Lunasome-Modules.md",   gen_lunasome_modules,    False),

    # ── Section 11: Demos & Examples ──────────────────────────────────
    "Examples":             ("Examples.md",           gen_examples,            False),
    "Demos":                ("Demos.md",              gen_demos,               False),
    "Demo-Showcase":        ("Demo-Showcase.md",      gen_demo_showcase,       True),

    # ── Section 12: Contributing (all MANUAL) ─────────────────────────
    "Contributing":             ("Contributing.md",             gen_contributing,             True),
    "Contributing-Engine":      ("Contributing-Engine.md",      gen_contributing_engine,      True),
    "Contributing-Demos":       ("Contributing-Demos.md",       gen_contributing_demos,       True),
    "Contributing-Libraries":   ("Contributing-Libraries.md",   gen_contributing_libraries,   True),
    "Contributing-Extension":   ("Contributing-Extension.md",   gen_contributing_extension,   True),
    "Contributing-CAG":         ("Contributing-CAG.md",         gen_contributing_cag,         True),
    "Coding-Conventions":       ("Coding-Conventions.md",       gen_coding_conventions,       True),

    # ── Section 13: VS Code Extension ─────────────────────────────────
    "VS-Code-Extension":        ("VS-Code-Extension.md",       gen_vscode_ext,              False),
    "Extension-MCP-Server":     ("Extension-MCP-Server.md",    gen_extension_mcp,           True),
    "Extension-Development":    ("Extension-Development.md",   gen_extension_dev,           True),

    # ── Section 14: Tooling ───────────────────────────────────────────
    "Tools":                ("Tools.md",              gen_tools,               False),
    "Build-System":         ("Build-System.md",       gen_build_system,        True),

    # ── Section 15: CAG System ────────────────────────────────────────
    "CAG-System":           ("CAG-System.md",         gen_cag_system,          False),
    "CAG-Workflow":         ("CAG-Workflow.md",       gen_cag_workflow,        True),

    # ── Section 16: Navigation ────────────────────────────────────────
    "_Sidebar":             ("_Sidebar.md",           gen_sidebar,             False),
    "_Footer":              ("_Footer.md",            gen_footer,              False),
}


# ═══════════════════════════════════════════════════════════════════════════════
# CLI entry point
# ═══════════════════════════════════════════════════════════════════════════════

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Regenerate all Lurek2D wiki pages from source.",
    )
    parser.add_argument(
        "--page", metavar="SLUG",
        help="Regenerate a single page by slug (see --list)",
    )
    parser.add_argument(
        "--list", action="store_true",
        help="List all available page slugs and exit",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Print generated content without writing files",
    )
    parser.add_argument(
        "--force", action="store_true",
        help="Overwrite manual pages (normally skipped if they exist)",
    )
    args = parser.parse_args()

    if args.list:
        scripted = 0
        manual = 0
        for slug, (filename, _, is_manual) in sorted(PAGES.items()):
            tag = "MANUAL" if is_manual else "SCRIPTED"
            print(f"  {slug:30s}  →  docs/wiki/{filename:35s}  [{tag}]")
            if is_manual:
                manual += 1
            else:
                scripted += 1
        print(f"\n  Total: {scripted + manual} pages ({scripted} scripted, {manual} manual)")
        return 0

    WIKI.mkdir(parents=True, exist_ok=True)

    if args.page:
        if args.page not in PAGES:
            print(f"ERROR: unknown page slug '{args.page}'. Run --list to see options.",
                  file=sys.stderr)
            return 1
        targets = {args.page: PAGES[args.page]}
    else:
        targets = PAGES

    errors = 0
    wrote = 0
    skipped = 0
    for slug, (filename, gen_fn, is_manual) in targets.items():
        try:
            content = gen_fn()
            result = write_page(filename, content, dry_run=args.dry_run,
                                is_manual=is_manual, force=args.force)
            if result == "wrote":
                wrote += 1
            elif result == "skipped":
                skipped += 1
        except Exception as exc:  # noqa: BLE001
            print(f"  ERROR  {filename}: {exc}", file=sys.stderr)
            errors += 1

    if not args.dry_run:
        total = len(targets)
        status = "✓" if errors == 0 else "!"
        print(f"\n{status} {wrote} wrote, {skipped} skipped (manual), {errors} errors — {total} pages total")
    return 0 if errors == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
