/// Flash screen effect state.
///
/// A flash overlays an opaque colour rectangle on the screen for a short
/// duration. The alpha fades linearly from `color[3]` (at `elapsed = 0`)
/// down to zero (at `elapsed = duration`); the fade is computed on read by
/// `Overlay::get_flash_alpha`. Calling `Overlay::trigger_flash` while a
/// flash is already active restarts it from the beginning with the new
/// colour and duration.
///
/// # Fields
/// - `active` — `bool` — Whether a flash is in progress.
/// - `color` — `[f32; 4]` — Flash colour (RGBA); `color[3]` is the initial alpha.
/// - `duration` — `f32` — Total flash duration in seconds.
/// - `elapsed` — `f32` — Time elapsed since flash start.
#[derive(Debug, Clone)]
pub struct FlashState {
    /// Whether a flash is in progress.
    pub active: bool,
    /// Flash colour (RGBA).
    pub color: [f32; 4],
    /// Total flash duration in seconds.
    pub duration: f32,
    /// Time elapsed since flash start.
    pub elapsed: f32,
}

impl Default for FlashState {
    fn default() -> Self {
        Self {
            active: false,
            color: [1.0, 1.0, 1.0, 1.0],
            duration: 0.2,
            elapsed: 0.0,
        }
    }
}

/// Shake screen effect state.
///
/// The shake applies a per-frame pixel offset to the camera or draw
/// origin. Offsets are generated by a simple xorshift PRNG seeded at
/// struct creation, giving a deterministic-ish sequence every run —
/// no heap allocation is needed. The intensity decays linearly with the
/// fraction of elapsed time so the shake diminishes smoothly. Calling
/// `Overlay::trigger_shake` while a shake is already active resets
/// elapsed time to zero and applies the new parameters immediately.
///
/// # Fields
/// - `active` — `bool` — Whether a shake is in progress.
/// - `intensity` — `f32` — Peak shake magnitude in pixels.
/// - `duration` — `f32` — Total shake duration in seconds.
/// - `elapsed` — `f32` — Time elapsed since shake start.
/// - `offset_x` — `f32` — Current horizontal pixel offset (read by the renderer).
/// - `offset_y` — `f32` — Current vertical pixel offset (read by the renderer).
#[derive(Debug, Clone)]
pub struct ShakeState {
    /// Whether a shake is in progress.
    pub active: bool,
    /// Shake intensity in pixels.
    pub intensity: f32,
    /// Total shake duration in seconds.
    pub duration: f32,
    /// Time elapsed since shake start.
    pub elapsed: f32,
    /// Current horizontal offset.
    pub offset_x: f32,
    /// Current vertical offset.
    pub offset_y: f32,
    /// Simple pseudo-random seed for deterministic shake.
    seed: u32,
}

impl Default for ShakeState {
    fn default() -> Self {
        Self {
            active: false,
            intensity: 5.0,
            duration: 0.5,
            elapsed: 0.0,
            offset_x: 0.0,
            offset_y: 0.0,
            seed: 12345,
        }
    }
}

impl ShakeState {
    /// Advances a simple xorshift PRNG and returns a value in [-1, 1].
    ///
    /// # Returns
    /// `f32` in the range `[-1.0, 1.0]`.
    pub(crate) fn next_random(&mut self) -> f32 {
        self.seed ^= self.seed << 13;
        self.seed ^= self.seed >> 17;
        self.seed ^= self.seed << 5;
        // Map to [-1, 1]
        (self.seed as f32 / u32::MAX as f32) * 2.0 - 1.0
    }
}

/// Fade screen effect state.
///
/// A fade interpolates `color[3]` (the alpha channel of the fill colour)
/// from `start_alpha` to `target_alpha` over `duration` seconds.
/// `start_alpha` is captured automatically from the current `color[3]`
/// when `Overlay::trigger_fade` is called, so a fade-out can seamlessly
/// continue from wherever the previous fade-in stopped. Calling
/// `trigger_fade` while a fade is already in progress restarts it with the
/// new target and duration from the current alpha.
///
/// # Fields
/// - `active` — `bool` — Whether a fade is in progress.
/// - `color` — `[f32; 4]` — Fill colour (RGB) with the animated alpha in `[3]`.
/// - `target_alpha` — `f32` — Alpha value to reach at the end of the fade (0.0–1.0).
/// - `duration` — `f32` — Total fade duration in seconds.
/// - `elapsed` — `f32` — Time elapsed since fade start.
/// - `start_alpha` — `f32` — Alpha at the moment the fade was triggered.
#[derive(Debug, Clone)]
pub struct FadeState {
    /// Whether a fade is in progress.
    pub active: bool,
    /// Fade target colour (RGB + starting alpha in [3]).
    pub color: [f32; 4],
    /// Target alpha for the fade.
    pub target_alpha: f32,
    /// Total fade duration in seconds.
    pub duration: f32,
    /// Time elapsed since fade start.
    pub elapsed: f32,
    /// Alpha at the start of the fade.
    pub start_alpha: f32,
}

impl Default for FadeState {
    fn default() -> Self {
        Self {
            active: false,
            color: [0.0, 0.0, 0.0, 0.0],
            target_alpha: 1.0,
            duration: 1.0,
            elapsed: 0.0,
            start_alpha: 0.0,
        }
    }
}
