-- test_evidence_effect_types.lua
-- Evidence test: proves all 8 new PostFxEffectType variants can be constructed,
-- configured, and introspected via the lurek.effect Lua API.
-- Output: tests/lua/evidence/output/postfx_types_evidence.txt

local describe     = describe
local it           = it
local expect_equal = expect_equal

local NEW_TYPES = {
    "depthoffield",
    "motionblur",
    "paletteswap",
    "colorlut",
    "waterdistort",
    "sharpen",
    "dither",
    "outline",
}

-- Collect evidence lines during tests; write file at the end.
local evidence_lines = {}
local function record(line) evidence_lines[#evidence_lines + 1] = line end

describe("New PostFxEffectType construction evidence", function()
    for _, type_name in ipairs(NEW_TYPES) do
        it("newEffect('" .. type_name .. "') constructs without error", function()
            local e = lurek.effect.newEffect(type_name)
            expect_equal(e ~= nil, true)
            record(string.format("EFFECT_CREATED: %s", type_name))
        end)
    end
end)

describe("New effect types appear in getEffectTypes()", function()
    it("all 8 new types are present in the type list", function()
        local types = lurek.effect.getEffectTypes()
        local type_set = {}
        for _, t in ipairs(types) do type_set[t] = true end
        for _, expected in ipairs(NEW_TYPES) do
            expect_equal(type_set[expected] == true, true)
            record(string.format("TYPE_REGISTERED: %s", expected))
        end
        record(string.format("TOTAL_EFFECT_TYPES: %d", #types))
    end)
end)

describe("New effect types in a PostFxStack", function()
    it("all new effect types can be added to a stack", function()
        local stack = lurek.effect.newStack(320, 240)
        for _, type_name in ipairs(NEW_TYPES) do
            local e = lurek.effect.newEffect(type_name)
            stack:add(e)
            record(string.format("ADDED_TO_STACK: %s", type_name))
        end
        expect_equal(stack:count() >= #NEW_TYPES, true)
    end)
end)

describe("newPresetStack evidence", function()
    local PRESETS = { "retro_tv", "horror", "dream", "neon", "sepia_age" }
    it("all named presets can be constructed", function()
        for _, name in ipairs(PRESETS) do
            local s = lurek.effect.newPresetStack(name)
            expect_equal(s ~= nil, true)
            record(string.format("PRESET_CREATED: %s  effects=%d", name, s:count()))
        end
    end)
end)

-- Write evidence artifact.
local output_dir = "tests/lua/evidence/output"
local output_path = output_dir .. "/postfx_types_evidence.txt"
local ok = lurek.filesystem.mkdir(output_dir)
if ok then
    local f = lurek.filesystem.open(output_path, "w")
    if f then
        f:write("# PostFx Types Evidence\n")
        f:write("# Generated by test_evidence_effect_types.lua\n\n")
        for _, line in ipairs(evidence_lines) do
            f:write(line .. "\n")
        end
        f:close()
    end
end

test_summary()
