//! Rapier2d-backed physics world with backward-compatible Lurek2D API.
//!
//! Wraps the rapier2d simulation pipeline while exposing the same `Body`-based
//! interface. The `Body` struct is a sync buffer: mutations via `get_body_mut()`
//! are flushed into rapier on the next `step()` call, and rapier's computed
//! positions/velocities are read back after each step.

use std::sync::Mutex;

use rapier2d::prelude::*;
// rapier2d::prelude::* brings CollisionEvent from rapier2d::geometry into scope;
// we keep our own payload struct under a different name to avoid shadowing.

use std::collections::HashMap;

use super::body::{Body, BodyShape, BodyType};
use super::shape::Shape;

use crate::engine::log_messages::{P001_PULLEY_JOINT_FALLBACK, P002_GEAR_JOINT_FALLBACK};
#[allow(unused_imports)]
use crate::log_msg;

// ── Internal event collector ─────────────────────────────────────────────────

/// Collects rapier `CollisionEvent`s during a pipeline step.
/// Uses `Mutex` because rapier2d 0.32 requires `EventHandler: Send + Sync`.
struct LocalEventCollector {
    events: Mutex<Vec<CollisionEvent>>,
}

impl LocalEventCollector {
    fn new() -> Self {
        Self {
            events: Mutex::new(Vec::new()),
        }
    }

    fn drain(&self) -> Vec<CollisionEvent> {
        self.events.lock().expect("event mutex not poisoned").drain(..).collect()
    }
}

impl EventHandler for LocalEventCollector {
    fn handle_collision_event(
        &self,
        _bodies: &RigidBodySet,
        _colliders: &ColliderSet,
        event: CollisionEvent,
        _contact_pair: Option<&ContactPair>,
    ) {
        self.events.lock().expect("event mutex not poisoned").push(event);
    }

    fn handle_contact_force_event(
        &self,
        _dt: f32,
        _bodies: &RigidBodySet,
        _colliders: &ColliderSet,
        _contact_pair: &ContactPair,
        _total_force_magnitude: f32,
    ) {
    }
}

// ── Public types ──────────────────────────────────────────────────────────────

/// Collision event generated by `World::step` when two bodies start overlapping.
///
/// Contains stable integer body IDs for the two bodies involved.
///
/// # Fields
/// - `body_a` — Index of the first body.
/// - `body_b` — Index of the second body.
pub struct BodyContact {
    /// Index of the first body.
    pub body_a: usize,
    /// Index of the second body.
    pub body_b: usize,
}

/// Result of a `World::raycast` query.
///
/// # Fields
/// - `body_id` — Integer body ID that was hit.
/// - `point` — World-space hit point `(x, y)`.
/// - `normal` — World-space surface normal `(nx, ny)`.
/// - `toi` — Distance along the ray to the hit point.
#[derive(Debug, Clone, Copy)]
pub struct RaycastHit {
    /// Integer body ID that was hit.
    pub body_id: usize,
    /// World-space hit point `(x, y)`.
    pub point: (f32, f32),
    /// World-space surface normal `(nx, ny)`.
    pub normal: (f32, f32),
    /// Distance along the ray to the hit point.
    pub toi: f32,
}

/// Contact information between two bodies from the narrow phase.
///
/// # Fields
/// - `body_a` — Index of the first body.
/// - `body_b` — Index of the second body.
/// - `normal_x` — Contact normal X component.
/// - `normal_y` — Contact normal Y component.
/// - `is_touching` — Whether the bodies are currently touching.
#[derive(Debug, Clone)]
pub struct ContactInfo {
    /// Index of the first body.
    pub body_a: usize,
    /// Index of the second body.
    pub body_b: usize,
    /// Contact normal X component.
    pub normal_x: f32,
    /// Contact normal Y component.
    pub normal_y: f32,
    /// Whether the bodies are currently touching.
    pub is_touching: bool,
}

// ── World ─────────────────────────────────────────────────────────────────────

/// Simulates a 2D physics world using rapier2d.
///
/// Bodies are stored as a `Vec<Body>` for backward-API compatibility.
/// Each `step()` syncs mutations into rapier, runs the pipeline, then
/// reads back positions/velocities for Dynamic bodies.
///
/// # Fields
/// - `bodies` — `Vec<Body>`.
/// - `body_handles` — `Vec<RigidBodyHandle>`.
/// - `collider_handles` — `Vec<ColliderHandle>`.
/// - `extra_collider_handles` — `Vec<Vec<ColliderHandle>>`.
/// - `collider_to_body` — `HashMap<ColliderHandle`.
/// - `cached_shapes` — `Vec<BodyShape>`.
/// - `cached_restitutions` — `Vec<f32>`.
/// - `cached_layers` — `Vec<(u32`.
/// - `cached_frictions` — `Vec<f32>`.
/// - `pipeline` — `PhysicsPipeline`.
/// - `gravity` — `Vector`.
/// - `params` — `IntegrationParameters`.
/// - `islands` — `IslandManager`.
/// - `broad_phase` — `BroadPhaseBvh`.
/// - `narrow_phase` — `NarrowPhase`.
/// - `rbodies` — `RigidBodySet`.
/// - `rcolliders` — `ColliderSet`.
/// - `impulse_joints` — `ImpulseJointSet`.
/// - `multibody_joints` — `MultibodyJointSet`.
/// - `ccd_solver` — `CCDSolver`.
/// - `joint_handles` — `Vec<ImpulseJointHandle>`.
/// - `collision_events` — `Vec<BodyContact>`.
/// - `begin_contact_events` — `Vec<(usize`.
/// - `end_contact_events` — `Vec<(usize`.
/// - `joint_types` — `Vec<&'static str>`.
/// - `mouse_joint_anchors` — `HashMap<usize`.
/// - `pixels_per_meter` — `f32`.
pub struct World {
    // ── Backward-compat body buffer ──────────────────────────────────────────
    bodies: Vec<Body>,

    // ── Per-body rapier handles ───────────────────────────────────────────────
    body_handles: Vec<RigidBodyHandle>,
    collider_handles: Vec<ColliderHandle>,
    /// Extra collider handles for multi-fixture bodies.
    extra_collider_handles: Vec<Vec<ColliderHandle>>,
    /// Reverse map from collider handle to body index.
    collider_to_body: HashMap<ColliderHandle, usize>,

    // ── Change-detection caches ───────────────────────────────────────────────
    cached_shapes: Vec<BodyShape>,
    cached_restitutions: Vec<f32>,
    cached_layers: Vec<(u32, u32)>,
    cached_frictions: Vec<f32>,

    // ── Rapier pipeline fields ────────────────────────────────────────────────
    pipeline: PhysicsPipeline,
    /// Gravity vector in Y-down screen space (positive Y = downward).
    gravity: Vector,
    params: IntegrationParameters,
    islands: IslandManager,
    broad_phase: BroadPhaseBvh,
    narrow_phase: NarrowPhase,
    rbodies: RigidBodySet,
    rcolliders: ColliderSet,
    impulse_joints: ImpulseJointSet,
    multibody_joints: MultibodyJointSet,
    ccd_solver: CCDSolver,

    // ── Joint handle table ────────────────────────────────────────────────────
    joint_handles: Vec<ImpulseJointHandle>,

    // ── Collision events from last step() ────────────────────────────────────
    collision_events: Vec<BodyContact>,
    /// Contact-started events from the last step (body_a, body_b).
    begin_contact_events: Vec<(usize, usize)>,
    /// Contact-ended events from the last step (body_a, body_b).
    end_contact_events: Vec<(usize, usize)>,

    // ── Joint type tracking ───────────────────────────────────────────────────
    joint_types: Vec<&'static str>,

    // ── Mouse joint anchor tracking ───────────────────────────────────────────
    mouse_joint_anchors: HashMap<usize, usize>,

    // ── Meter scaling ─────────────────────────────────────────────────────────
    pixels_per_meter: f32,
}

impl World {
    /// Creates a new empty physics world with the given gravity vector.
    ///
    /// Positive `gy` means downward in screen-space Y-down coordinates.
    ///
    /// # Parameters
    /// - `gx` — Horizontal gravity component.
    /// - `gy` — Vertical gravity component.
    ///
    /// # Returns
    /// A new `World` with no bodies or joints.
    pub fn new(gx: f32, gy: f32) -> Self {
        World {
            bodies: Vec::new(),
            body_handles: Vec::new(),
            collider_handles: Vec::new(),
            extra_collider_handles: Vec::new(),
            collider_to_body: HashMap::new(),
            cached_shapes: Vec::new(),
            cached_restitutions: Vec::new(),
            cached_layers: Vec::new(),
            cached_frictions: Vec::new(),
            pipeline: PhysicsPipeline::new(),
            gravity: Vector::new(gx, gy),
            params: IntegrationParameters::default(),
            islands: IslandManager::new(),
            broad_phase: BroadPhaseBvh::new(),
            narrow_phase: NarrowPhase::new(),
            rbodies: RigidBodySet::new(),
            rcolliders: ColliderSet::new(),
            impulse_joints: ImpulseJointSet::new(),
            multibody_joints: MultibodyJointSet::new(),
            ccd_solver: CCDSolver::new(),
            joint_handles: Vec::new(),
            collision_events: Vec::new(),
            begin_contact_events: Vec::new(),
            end_contact_events: Vec::new(),
            joint_types: Vec::new(),
            mouse_joint_anchors: HashMap::new(),
            pixels_per_meter: 1.0,
        }
    }

    // ── Internal helpers ──────────────────────────────────────────────────────

    fn rapier_body_type(bt: BodyType) -> RigidBodyType {
        match bt {
            BodyType::Static | BodyType::Sensor => RigidBodyType::Fixed,
            BodyType::Dynamic => RigidBodyType::Dynamic,
            BodyType::Kinematic => RigidBodyType::KinematicPositionBased,
        }
    }

    fn make_collider(body: &Body) -> Collider {
        let is_sensor = body.body_type == BodyType::Sensor;
        let memberships = Group::from_bits_truncate(body.layer);
        let filters = Group::from_bits_truncate(body.mask);
        let groups = InteractionGroups::new(memberships, filters, InteractionTestMode::And);
        let builder = if let Some(ref shape_ext) = body.shape_ext {
            shape_ext
                .to_rapier_collider()
                .unwrap_or_else(|| match body.shape {
                    BodyShape::Rect { width, height } => {
                        ColliderBuilder::cuboid(width / 2.0, height / 2.0)
                    }
                    BodyShape::Circle { radius } => ColliderBuilder::ball(radius),
                })
        } else {
            match body.shape {
                BodyShape::Rect { width, height } => {
                    ColliderBuilder::cuboid(width / 2.0, height / 2.0)
                }
                BodyShape::Circle { radius } => ColliderBuilder::ball(radius),
            }
        };
        builder
            .sensor(is_sensor)
            .restitution(body.restitution)
            .friction(body.friction)
            .collision_groups(groups)
            .active_events(ActiveEvents::COLLISION_EVENTS)
            .build()
    }

    /// Rebuilds the rapier collider for body `id` after a shape or property change.
    fn rebuild_collider(&mut self, id: usize) {
        let old_handle = self.collider_handles[id];
        let body_handle = self.body_handles[id];

        // Extract before mutating self.
        let (shape, shape_ext, restitution, friction, layer, mask, is_sensor) = {
            let b = &self.bodies[id];
            (
                b.shape,
                b.shape_ext.clone(),
                b.restitution,
                b.friction,
                b.layer,
                b.mask,
                b.body_type == BodyType::Sensor,
            )
        };

        self.rcolliders
            .remove(old_handle, &mut self.islands, &mut self.rbodies, true);

        let memberships = Group::from_bits_truncate(layer);
        let filters = Group::from_bits_truncate(mask);
        let groups = InteractionGroups::new(memberships, filters, InteractionTestMode::And);

        let builder = if let Some(ref ext) = shape_ext {
            ext.to_rapier_collider().unwrap_or_else(|| match shape {
                BodyShape::Rect { width, height } => {
                    ColliderBuilder::cuboid(width / 2.0, height / 2.0)
                }
                BodyShape::Circle { radius } => ColliderBuilder::ball(radius),
            })
        } else {
            match shape {
                BodyShape::Rect { width, height } => {
                    ColliderBuilder::cuboid(width / 2.0, height / 2.0)
                }
                BodyShape::Circle { radius } => ColliderBuilder::ball(radius),
            }
        };
        let collider = builder
            .sensor(is_sensor)
            .restitution(restitution)
            .friction(friction)
            .collision_groups(groups)
            .active_events(ActiveEvents::COLLISION_EVENTS)
            .build();

        let new_handle =
            self.rcolliders
                .insert_with_parent(collider, body_handle, &mut self.rbodies);
        // Update reverse map: remove old, insert new
        self.collider_to_body.remove(&old_handle);
        self.collider_to_body.insert(new_handle, id);
        self.collider_handles[id] = new_handle;
        self.cached_shapes[id] = shape;
        self.cached_restitutions[id] = restitution;
        self.cached_frictions[id] = friction;
        self.cached_layers[id] = (layer, mask);
    }

    /// Returns the body index for a given collider handle, or `None`.
    fn body_for_collider(&self, handle: ColliderHandle) -> Option<usize> {
        self.collider_to_body.get(&handle).copied()
    }

    // ── Body management ───────────────────────────────────────────────────────

    /// Adds a `body` to the world and returns its stable integer id.
    ///
    /// # Parameters
    /// - `body` — The body to add.
    ///
    /// # Returns
    /// The stable body index.
    pub fn add_body(&mut self, body: Body) -> usize {
        let id = self.bodies.len();

        let rb = RigidBodyBuilder::new(Self::rapier_body_type(body.body_type))
            .translation(Vector::new(body.position.x, body.position.y))
            .linvel(Vector::new(body.velocity.x, body.velocity.y))
            .build();
        let body_handle = self.rbodies.insert(rb);

        let collider = Self::make_collider(&body);
        let collider_handle =
            self.rcolliders
                .insert_with_parent(collider, body_handle, &mut self.rbodies);

        self.cached_shapes.push(body.shape);
        self.cached_restitutions.push(body.restitution);
        self.cached_frictions.push(body.friction);
        self.cached_layers.push((body.layer, body.mask));
        self.body_handles.push(body_handle);
        self.collider_handles.push(collider_handle);
        self.extra_collider_handles.push(Vec::new());
        self.collider_to_body.insert(collider_handle, id);
        self.bodies.push(body);
        id
    }

    /// Adds an extra fixture (collider) to an existing body.
    ///
    /// Returns the fixture index (0 = primary, 1+ = extra fixtures).
    ///
    /// # Parameters
    /// - `body_id` — Index of the body to attach to.
    /// - `shape` — Collision shape for the fixture.
    /// - `density` — Mass density.
    /// - `friction` — Surface friction coefficient.
    /// - `restitution` — Bounciness coefficient.
    /// - `sensor` — Whether this fixture is a sensor (no physical response).
    ///
    /// # Returns
    /// The fixture index (0 = primary, 1+ = extras).
    pub fn add_fixture(
        &mut self,
        body_id: usize,
        shape: Shape,
        density: f32,
        friction: f32,
        restitution: f32,
        sensor: bool,
    ) -> usize {
        let body_handle = match self.body_handles.get(body_id).copied() {
            Some(h) => h,
            None => return 0,
        };

        let builder = shape
            .to_rapier_collider()
            .unwrap_or_else(|| ColliderBuilder::cuboid(0.5, 0.5));

        let collider = builder
            .density(density)
            .friction(friction)
            .restitution(restitution)
            .sensor(sensor)
            .active_events(ActiveEvents::COLLISION_EVENTS)
            .build();

        let handle = self
            .rcolliders
            .insert_with_parent(collider, body_handle, &mut self.rbodies);
        self.collider_to_body.insert(handle, body_id);

        let extras = &mut self.extra_collider_handles[body_id];
        extras.push(handle);
        extras.len() // fixture index (1-based for extras, 0 is primary)
    }

    /// Returns the number of fixtures on a body (1 = primary only).
    ///
    /// # Parameters
    /// - `body_id` — Index of the body.
    ///
    /// # Returns
    /// Fixture count (1 if only the primary fixture exists).
    pub fn fixture_count(&self, body_id: usize) -> usize {
        if body_id >= self.bodies.len() {
            return 0;
        }
        1 + self.extra_collider_handles[body_id].len()
    }

    /// Sets the friction of a fixture by index.
    ///
    /// Index 0 = primary fixture, 1+ = extra fixtures.
    ///
    /// # Parameters
    /// - `body_id` — Index of the body.
    /// - `fixture_idx` — Fixture index (0 = primary).
    /// - `friction` — New friction coefficient.
    pub fn set_fixture_friction(&mut self, body_id: usize, fixture_idx: usize, friction: f32) {
        let handle = if fixture_idx == 0 {
            self.collider_handles.get(body_id).copied()
        } else {
            self.extra_collider_handles
                .get(body_id)
                .and_then(|v| v.get(fixture_idx - 1))
                .copied()
        };
        if let Some(h) = handle {
            if let Some(col) = self.rcolliders.get_mut(h) {
                col.set_friction(friction);
            }
        }
    }

    /// Sets the restitution of a fixture by index.
    ///
    /// # Parameters
    /// - `body_id` — Index of the body.
    /// - `fixture_idx` — Fixture index (0 = primary).
    /// - `restitution` — New restitution coefficient.
    pub fn set_fixture_restitution(
        &mut self,
        body_id: usize,
        fixture_idx: usize,
        restitution: f32,
    ) {
        let handle = if fixture_idx == 0 {
            self.collider_handles.get(body_id).copied()
        } else {
            self.extra_collider_handles
                .get(body_id)
                .and_then(|v| v.get(fixture_idx - 1))
                .copied()
        };
        if let Some(h) = handle {
            if let Some(col) = self.rcolliders.get_mut(h) {
                col.set_restitution(restitution);
            }
        }
    }

    /// Sets whether a fixture is a sensor. Replaces the current fixture sensor value; callers hold responsibility for maintaining consistency with related fields.
    ///
    /// # Parameters
    /// - `body_id` — Index of the body.
    /// - `fixture_idx` — Fixture index (0 = primary).
    /// - `sensor` — Whether the fixture should be a sensor.
    pub fn set_fixture_sensor(&mut self, body_id: usize, fixture_idx: usize, sensor: bool) {
        let handle = if fixture_idx == 0 {
            self.collider_handles.get(body_id).copied()
        } else {
            self.extra_collider_handles
                .get(body_id)
                .and_then(|v| v.get(fixture_idx - 1))
                .copied()
        };
        if let Some(h) = handle {
            if let Some(col) = self.rcolliders.get_mut(h) {
                col.set_sensor(sensor);
            }
        }
    }

    /// Returns an immutable reference to body `id`, or `None` if out of range.
    ///
    /// # Parameters
    /// - `id` — Body index.
    ///
    /// # Returns
    /// A reference to the body, or `None`.
    pub fn get_body(&self, id: usize) -> Option<&Body> {
        self.bodies.get(id)
    }

    /// Returns a mutable reference to body `id`, or `None` if out of range.
    ///
    /// Shape, restitution, layer, mask, velocity, and position mutations are
    /// flushed into the rapier simulation on the next `step()` call.
    ///
    /// # Parameters
    /// - `id` — Body index.
    ///
    /// # Returns
    /// A mutable reference to the body, or `None`.
    pub fn get_body_mut(&mut self, id: usize) -> Option<&mut Body> {
        self.bodies.get_mut(id)
    }

    /// Returns the total number of bodies.
    ///
    /// # Returns
    /// The body count.
    pub fn body_count(&self) -> usize {
        self.bodies.len()
    }

    // ── Joint creation ────────────────────────────────────────────────────────

    /// Creates a revolute (pin) joint between two bodies at a local anchor on body_a.
    ///
    /// Returns a stable joint id.
    ///
    /// # Parameters
    /// - `body_a` — Index of the first body.
    /// - `body_b` — Index of the second body.
    /// - `anchor_x` — Local anchor X on body_a.
    /// - `anchor_y` — Local anchor Y on body_a.
    ///
    /// # Returns
    /// The joint index.
    pub fn add_revolute_joint(
        &mut self,
        body_a: usize,
        body_b: usize,
        anchor_x: f32,
        anchor_y: f32,
    ) -> usize {
        let ha = match self.body_handles.get(body_a).copied() {
            Some(h) => h,
            None => return 0,
        };
        let hb = match self.body_handles.get(body_b).copied() {
            Some(h) => h,
            None => return 0,
        };
        let joint = RevoluteJointBuilder::new()
            .local_anchor1(Vector::new(anchor_x, anchor_y))
            .local_anchor2(Vector::new(0.0_f32, 0.0_f32))
            .build();
        let handle = self.impulse_joints.insert(ha, hb, joint, true);
        let id = self.joint_handles.len();
        self.joint_handles.push(handle);
        self.joint_types.push("revolute");
        id
    }

    // ── Raycast ───────────────────────────────────────────────────────────────

    /// Casts a ray from `(x1, y1)` toward `(x2, y2)` and returns the nearest hit.
    ///
    /// Uses a brute-force O(n) test against all colliders.
    ///
    /// # Parameters
    /// - `x1` — Ray origin X.
    /// - `y1` — Ray origin Y.
    /// - `x2` — Ray target X.
    /// - `y2` — Ray target Y.
    ///
    /// # Returns
    /// The nearest `RaycastHit`, or `None`.
    pub fn raycast(&self, x1: f32, y1: f32, x2: f32, y2: f32) -> Option<RaycastHit> {
        let dir = Vector::new(x2 - x1, y2 - y1);
        let max_toi = dir.length();
        if max_toi < 1e-6 {
            return None;
        }
        let unit_dir = dir / max_toi;
        let ray = Ray::new(Vector::new(x1, y1), unit_dir);

        let mut best_toi = max_toi;
        let mut best_hit: Option<RaycastHit> = None;

        for (i, &col_handle) in self.collider_handles.iter().enumerate() {
            if let Some(col) = self.rcolliders.get(col_handle) {
                if let Some(ri) =
                    col.shape()
                        .cast_ray_and_get_normal(col.position(), &ray, best_toi, true)
                {
                    let toi = ri.time_of_impact;
                    let pt_x = ray.origin.x + ray.dir.x * toi;
                    let pt_y = ray.origin.y + ray.dir.y * toi;
                    best_toi = toi;
                    best_hit = Some(RaycastHit {
                        body_id: i,
                        point: (pt_x, pt_y),
                        normal: (ri.normal.x, ri.normal.y),
                        toi,
                    });
                }
            }
        }

        best_hit
    }

    // ── Simulation step ───────────────────────────────────────────────────────

    /// Advances the simulation by `dt` seconds.
    ///
    /// 1. Rebuild rapier colliders for bodies with changed shape/properties.
    /// 2. Push all body positions/velocities into rapier.
    /// 3. Step the rapier pipeline.
    /// 4. Read back positions/velocities for Dynamic bodies.
    /// 5. Record collision events.
    ///
    /// # Parameters
    /// - `dt` — Time step in seconds.
    pub fn step(&mut self, dt: f32) {
        self.params.dt = dt;
        self.collision_events.clear();
        self.begin_contact_events.clear();
        self.end_contact_events.clear();

        let n = self.bodies.len();

        // ① Detect property changes and rebuild colliders.
        let rebuild_ids: Vec<usize> = (0..n)
            .filter(|&i| {
                let b = &self.bodies[i];
                b.shape != self.cached_shapes[i]
                    || (b.restitution - self.cached_restitutions[i]).abs() > 1e-6
                    || (b.friction - self.cached_frictions[i]).abs() > 1e-6
                    || (b.layer, b.mask) != self.cached_layers[i]
            })
            .collect();
        for i in rebuild_ids {
            self.rebuild_collider(i);
        }

        // ② Push position / velocity to rapier.
        // Collect first to avoid aliased borrows on self.
        let sync: Vec<(f32, f32, f32, f32, f32, f32, BodyType)> = self
            .bodies
            .iter()
            .map(|b| {
                (
                    b.position.x,
                    b.position.y,
                    b.velocity.x,
                    b.velocity.y,
                    b.angle,
                    b.angular_velocity,
                    b.body_type,
                )
            })
            .collect();

        for (i, &(px, py, vx, vy, angle, angvel, bt)) in sync.iter().enumerate() {
            let handle = self.body_handles[i];
            if let Some(rb) = self.rbodies.get_mut(handle) {
                match bt {
                    BodyType::Dynamic => {
                        rb.set_translation(Vector::new(px, py), true);
                        rb.set_rotation(Rotation::new(angle), true);
                        rb.set_linvel(Vector::new(vx, vy), true);
                        rb.set_angvel(angvel, true);
                    }
                    BodyType::Kinematic => {
                        rb.set_next_kinematic_translation(Vector::new(px, py));
                        rb.set_next_kinematic_rotation(Rotation::new(angle));
                    }
                    _ => {
                        rb.set_translation(Vector::new(px, py), true);
                        rb.set_rotation(Rotation::new(angle), true);
                    }
                }
            }
        }

        // ③ Step rapier.
        let event_col = LocalEventCollector::new();
        self.pipeline.step(
            self.gravity,
            &self.params,
            &mut self.islands,
            &mut self.broad_phase,
            &mut self.narrow_phase,
            &mut self.rbodies,
            &mut self.rcolliders,
            &mut self.impulse_joints,
            &mut self.multibody_joints,
            &mut self.ccd_solver,
            &(),
            &event_col,
        );

        // ④ Read back dynamic and kinematic body state.
        for i in 0..n {
            let bt = self.bodies[i].body_type;
            if bt != BodyType::Dynamic && bt != BodyType::Kinematic {
                continue;
            }
            let handle = self.body_handles[i];
            let (tx, ty, vx, vy, angle, angvel) = match self.rbodies.get(handle) {
                Some(rb) => {
                    let t = rb.translation();
                    let v = rb.linvel();
                    (t.x, t.y, v.x, v.y, rb.rotation().angle(), rb.angvel())
                }
                None => continue,
            };
            self.bodies[i].position.x = tx;
            self.bodies[i].position.y = ty;
            self.bodies[i].velocity.x = vx;
            self.bodies[i].velocity.y = vy;
            self.bodies[i].angle = angle;
            self.bodies[i].angular_velocity = angvel;
        }

        // ⑤ Map rapier events to integer body IDs.
        for event in event_col.drain() {
            let ca = event.collider1();
            let cb = event.collider2();
            let id_a = self.body_for_collider(ca);
            let id_b = self.body_for_collider(cb);
            if let (Some(a), Some(b)) = (id_a, id_b) {
                if event.started() {
                    self.collision_events.push(BodyContact {
                        body_a: a,
                        body_b: b,
                    });
                    self.begin_contact_events.push((a, b));
                } else {
                    self.end_contact_events.push((a, b));
                }
            }
        }
    }

    /// Applies a linear impulse directly to a body in the rapier simulation.
    ///
    /// Has no effect on static or sensor bodies.
    ///
    /// # Parameters
    /// - `id` — Body index.
    /// - `ix` — Impulse X component.
    /// - `iy` — Impulse Y component.
    pub fn apply_impulse(&mut self, id: usize, ix: f32, iy: f32) {
        // Mirror the impulse into body.velocity so that step ②'s sync carries
        // it into rapier even though rapier's own linvel would otherwise be
        // overwritten.  F = m·a → Δv = impulse / mass.
        if let Some(body) = self.bodies.get_mut(id) {
            if body.body_type == BodyType::Dynamic {
                let inv_mass = if body.mass > 0.0 {
                    1.0 / body.mass
                } else {
                    0.0
                };
                body.velocity.x += ix * inv_mass;
                body.velocity.y += iy * inv_mass;
            }
        }
        if let Some(&handle) = self.body_handles.get(id) {
            if let Some(rb) = self.rbodies.get_mut(handle) {
                rb.apply_impulse(Vector::new(ix, iy), true);
            }
        }
    }

    /// Returns all collision events that occurred during the last `step()` call.
    ///
    /// # Returns
    /// A slice of `BodyContact` events.
    pub fn get_collision_events(&self) -> &[BodyContact] {
        &self.collision_events
    }

    /// Returns begin-contact events from the last `step()`.
    ///
    /// # Returns
    /// A slice of `(body_a, body_b)` pairs.
    pub fn get_begin_contact_events(&self) -> &[(usize, usize)] {
        &self.begin_contact_events
    }

    /// Returns end-contact events from the last `step()`.
    ///
    /// # Returns
    /// A slice of `(body_a, body_b)` pairs.
    pub fn get_end_contact_events(&self) -> &[(usize, usize)] {
        &self.end_contact_events
    }

    // ── Extended body properties ──────────────────────────────────────────────

    /// Teleports a body to a new position. Replaces the current body position value; callers hold responsibility for maintaining consistency with related fields.
    ///
    /// # Parameters
    /// - `id` — Body index.
    /// - `x` — New X position.
    /// - `y` — New Y position.
    pub fn set_body_position(&mut self, id: usize, x: f32, y: f32) {
        if let Some(body) = self.bodies.get_mut(id) {
            body.position.x = x;
            body.position.y = y;
        }
        if let Some(&handle) = self.body_handles.get(id) {
            if let Some(rb) = self.rbodies.get_mut(handle) {
                rb.set_translation(Vector::new(x, y), true);
            }
        }
    }

    /// Applies a continuous force to a body (accumulated over the next step).
    ///
    /// # Parameters
    /// - `id` — Body index.
    /// - `fx` — Force X component.
    /// - `fy` — Force Y component.
    pub fn apply_force(&mut self, id: usize, fx: f32, fy: f32) {
        if let Some(&handle) = self.body_handles.get(id) {
            if let Some(rb) = self.rbodies.get_mut(handle) {
                rb.add_force(Vector::new(fx, fy), true);
            }
        }
    }

    /// Applies a torque (rotational force) to a body.
    ///
    /// # Parameters
    /// - `id` — Body index.
    /// - `torque` — Torque value.
    pub fn apply_torque(&mut self, id: usize, torque: f32) {
        if let Some(&handle) = self.body_handles.get(id) {
            if let Some(rb) = self.rbodies.get_mut(handle) {
                rb.add_torque(torque, true);
            }
        }
    }

    /// Sets the angular velocity (spin rate) of a body.
    ///
    /// # Parameters
    /// - `id` — Body index.
    /// - `omega` — Angular velocity in radians per second.
    pub fn set_angular_velocity(&mut self, id: usize, omega: f32) {
        if let Some(body) = self.bodies.get_mut(id) {
            body.angular_velocity = omega;
        }
        if let Some(&handle) = self.body_handles.get(id) {
            if let Some(rb) = self.rbodies.get_mut(handle) {
                rb.set_angvel(omega, true);
            }
        }
    }

    /// Returns the angular velocity of a body. This accessor incurs no allocation; call it freely in hot paths.
    ///
    /// # Parameters
    /// - `id` — Body index.
    ///
    /// # Returns
    /// Angular velocity in radians per second.
    pub fn get_angular_velocity(&self, id: usize) -> f32 {
        self.bodies.get(id).map_or(0.0, |b| b.angular_velocity)
    }

    /// Returns the angle (rotation) of a body in radians.
    ///
    /// # Parameters
    /// - `id` — Body index.
    ///
    /// # Returns
    /// The angle in radians.
    pub fn get_body_angle(&self, id: usize) -> f32 {
        self.bodies.get(id).map_or(0.0, |b| b.angle)
    }

    /// Sets the angle (rotation) of a body in radians.
    ///
    /// # Parameters
    /// - `id` — Body index.
    /// - `angle` — New angle in radians.
    pub fn set_body_angle(&mut self, id: usize, angle: f32) {
        if let Some(body) = self.bodies.get_mut(id) {
            body.angle = angle;
        }
        if let Some(&handle) = self.body_handles.get(id) {
            if let Some(rb) = self.rbodies.get_mut(handle) {
                rb.set_rotation(Rotation::new(angle), true);
            }
        }
    }

    /// Returns the mass of a body. This accessor incurs no allocation; call it freely in hot paths.
    ///
    /// # Parameters
    /// - `id` — Body index.
    ///
    /// # Returns
    /// The body mass.
    pub fn get_body_mass(&self, id: usize) -> f32 {
        self.bodies.get(id).map_or(0.0, |b| b.mass)
    }

    /// Sets the mass of a body. Replaces the current body mass value; callers hold responsibility for maintaining consistency with related fields.
    ///
    /// # Parameters
    /// - `id` — Body index.
    /// - `mass` — New mass value.
    pub fn set_body_mass(&mut self, id: usize, mass: f32) {
        if let Some(body) = self.bodies.get_mut(id) {
            body.mass = mass;
        }
        if let Some(&handle) = self.body_handles.get(id) {
            if let Some(rb) = self.rbodies.get_mut(handle) {
                let props = rb.mass_properties();
                rb.set_additional_mass(mass - props.local_mprops.mass(), true);
            }
        }
    }

    /// Sets the per-body gravity multiplier. Replaces the current gravity scale value; callers hold responsibility for maintaining consistency with related fields.
    ///
    /// # Parameters
    /// - `id` — Body index.
    /// - `scale` — Gravity scale factor.
    pub fn set_gravity_scale(&mut self, id: usize, scale: f32) {
        if let Some(&handle) = self.body_handles.get(id) {
            if let Some(rb) = self.rbodies.get_mut(handle) {
                rb.set_gravity_scale(scale, true);
            }
        }
    }

    /// Locks or unlocks rotation for a body. Replaces the current fixed rotation value; callers hold responsibility for maintaining consistency with related fields.
    ///
    /// # Parameters
    /// - `id` — Body index.
    /// - `fixed` — `true` to lock rotation.
    pub fn set_fixed_rotation(&mut self, id: usize, fixed: bool) {
        if let Some(&handle) = self.body_handles.get(id) {
            if let Some(rb) = self.rbodies.get_mut(handle) {
                rb.set_enabled_rotations(false, false, !fixed, true);
            }
        }
    }

    /// Sets linear damping (air resistance) for a body.
    ///
    /// # Parameters
    /// - `id` — Body index.
    /// - `damping` — Damping coefficient.
    pub fn set_linear_damping(&mut self, id: usize, damping: f32) {
        if let Some(&handle) = self.body_handles.get(id) {
            if let Some(rb) = self.rbodies.get_mut(handle) {
                rb.set_linear_damping(damping);
            }
        }
    }

    /// Sets angular damping (rotational resistance) for a body.
    ///
    /// # Parameters
    /// - `id` — Body index.
    /// - `damping` — Damping coefficient.
    pub fn set_angular_damping(&mut self, id: usize, damping: f32) {
        if let Some(&handle) = self.body_handles.get(id) {
            if let Some(rb) = self.rbodies.get_mut(handle) {
                rb.set_angular_damping(damping);
            }
        }
    }

    /// Returns the gravity scale multiplier for a body.
    ///
    /// # Parameters
    /// - `id` — Body index.
    ///
    /// # Returns
    /// The gravity scale.
    pub fn get_gravity_scale(&self, id: usize) -> f32 {
        if let Some(&handle) = self.body_handles.get(id) {
            if let Some(rb) = self.rbodies.get(handle) {
                return rb.gravity_scale();
            }
        }
        1.0
    }

    /// Returns `true` if the body has rotation locked.
    ///
    /// # Parameters
    /// - `id` — Body index.
    ///
    /// # Returns
    /// `true` if rotation is locked.
    pub fn is_fixed_rotation(&self, id: usize) -> bool {
        if let Some(&handle) = self.body_handles.get(id) {
            if let Some(rb) = self.rbodies.get(handle) {
                return rb.is_rotation_locked();
            }
        }
        false
    }

    /// Returns the linear damping coefficient for a body.
    ///
    /// # Parameters
    /// - `id` — Body index.
    ///
    /// # Returns
    /// The linear damping coefficient.
    pub fn get_linear_damping(&self, id: usize) -> f32 {
        if let Some(&handle) = self.body_handles.get(id) {
            if let Some(rb) = self.rbodies.get(handle) {
                return rb.linear_damping();
            }
        }
        0.0
    }

    /// Returns the angular damping coefficient for a body.
    ///
    /// # Parameters
    /// - `id` — Body index.
    ///
    /// # Returns
    /// The angular damping coefficient.
    pub fn get_angular_damping(&self, id: usize) -> f32 {
        if let Some(&handle) = self.body_handles.get(id) {
            if let Some(rb) = self.rbodies.get(handle) {
                return rb.angular_damping();
            }
        }
        0.0
    }

    /// Enables or disables continuous collision detection (CCD) for a body.
    ///
    /// # Parameters
    /// - `id` — Body index.
    /// - `bullet` — `true` to enable CCD.
    pub fn set_bullet(&mut self, id: usize, bullet: bool) {
        if let Some(&handle) = self.body_handles.get(id) {
            if let Some(rb) = self.rbodies.get_mut(handle) {
                rb.enable_ccd(bullet);
            }
        }
    }

    /// Returns whether CCD is enabled for a body.
    ///
    /// # Parameters
    /// - `id` — Body index.
    ///
    /// # Returns
    /// `true` if CCD is enabled.
    pub fn is_bullet(&self, id: usize) -> bool {
        if let Some(&handle) = self.body_handles.get(id) {
            if let Some(rb) = self.rbodies.get(handle) {
                return rb.is_ccd_enabled();
            }
        }
        false
    }

    /// Applies a force at a specific world-space point on a body.
    ///
    /// A force applied off-centre generates torque in addition to linear acceleration.
    ///
    /// # Parameters
    /// - `id` — Body index.
    /// - `fx` — Force X component.
    /// - `fy` — Force Y component.
    /// - `px` — Application point X.
    /// - `py` — Application point Y.
    pub fn apply_force_at_point(&mut self, id: usize, fx: f32, fy: f32, px: f32, py: f32) {
        if let Some(&handle) = self.body_handles.get(id) {
            if let Some(rb) = self.rbodies.get_mut(handle) {
                rb.add_force_at_point(Vector::new(fx, fy), Vector::new(px, py), true);
            }
        }
    }

    /// Applies an angular (rotational) impulse to a body.
    ///
    /// Mirrors the resulting angular velocity into the body cache so that
    /// the next `step()` sync does not discard it.
    ///
    /// # Parameters
    /// - `id` — Body index.
    /// - `impulse` — Angular impulse value.
    pub fn apply_angular_impulse(&mut self, id: usize, impulse: f32) {
        if let Some(&handle) = self.body_handles.get(id) {
            if let Some(rb) = self.rbodies.get_mut(handle) {
                rb.apply_torque_impulse(impulse, true);
                let new_angvel = rb.angvel();
                if let Some(body) = self.bodies.get_mut(id) {
                    body.angular_velocity = new_angvel;
                }
            }
        }
    }

    /// Returns all active body IDs in insertion order (including destroyed slots).
    ///
    /// # Returns
    /// A vector of body indices.
    pub fn get_body_ids(&self) -> Vec<usize> {
        (0..self.bodies.len()).collect()
    }

    /// Returns all active joint IDs in insertion order.
    ///
    /// # Returns
    /// A vector of joint indices.
    pub fn get_joint_ids(&self) -> Vec<usize> {
        (0..self.joint_handles.len()).collect()
    }

    /// Returns the body type as a string. This accessor incurs no allocation; call it freely in hot paths.
    ///
    /// # Parameters
    /// - `id` — Body index.
    ///
    /// # Returns
    /// One of `"static"`, `"dynamic"`, `"kinematic"`, or `"sensor"`.
    pub fn get_body_type_str(&self, id: usize) -> &'static str {
        self.bodies
            .get(id)
            .map_or("dynamic", |b| match b.body_type {
                BodyType::Static => "static",
                BodyType::Dynamic => "dynamic",
                BodyType::Kinematic => "kinematic",
                BodyType::Sensor => "sensor",
            })
    }

    /// Changes the body type of an existing body.
    ///
    /// # Parameters
    /// - `id` — Body index.
    /// - `bt` — New body type.
    pub fn set_body_type(&mut self, id: usize, bt: BodyType) {
        if let Some(body) = self.bodies.get_mut(id) {
            body.body_type = bt;
        }
        if let Some(&handle) = self.body_handles.get(id) {
            if let Some(rb) = self.rbodies.get_mut(handle) {
                rb.set_body_type(Self::rapier_body_type(bt), true);
            }
        }
        // Sensor status may have changed — rebuild collider.
        if id < self.bodies.len() {
            self.rebuild_collider(id);
        }
    }

    // ── Gravity management ────────────────────────────────────────────────────

    /// Returns the current gravity vector `(gx, gy)`.
    ///
    /// # Returns
    /// A tuple `(gx, gy)`.
    pub fn get_gravity(&self) -> (f32, f32) {
        (self.gravity.x, self.gravity.y)
    }

    /// Sets the gravity vector. Replaces the current gravity value; callers hold responsibility for maintaining consistency with related fields.
    ///
    /// # Parameters
    /// - `gx` — Horizontal gravity component.
    /// - `gy` — Vertical gravity component.
    pub fn set_gravity(&mut self, gx: f32, gy: f32) {
        self.gravity = Vector::new(gx, gy);
    }

    // ── World sleeping / management ───────────────────────────────────────────

    /// Destroys all bodies and joints, resetting the world to an empty state.
    pub fn clear(&mut self) {
        self.bodies.clear();
        self.body_handles.clear();
        self.collider_handles.clear();
        self.extra_collider_handles.clear();
        self.collider_to_body.clear();
        self.cached_shapes.clear();
        self.cached_restitutions.clear();
        self.cached_layers.clear();
        self.cached_frictions.clear();
        self.joint_handles.clear();
        self.joint_types.clear();
        self.mouse_joint_anchors.clear();
        self.collision_events.clear();
        self.begin_contact_events.clear();
        self.end_contact_events.clear();
        self.rbodies = RigidBodySet::new();
        self.rcolliders = ColliderSet::new();
        self.impulse_joints = ImpulseJointSet::new();
        self.multibody_joints = MultibodyJointSet::new();
        self.islands = IslandManager::new();
        self.broad_phase = BroadPhaseBvh::new();
        self.narrow_phase = NarrowPhase::new();
    }

    // ── Body destruction ──────────────────────────────────────────────────────

    /// Sets whether sleeping is allowed for a body.
    ///
    /// When sleeping is allowed, the physics engine can deactivate stationary
    /// bodies to save CPU. When disabled, the body stays awake indefinitely.
    ///
    /// # Parameters
    /// - `id` — Body index.
    /// - `allowed` — `true` to allow sleeping, `false` to force always-awake.
    pub fn set_sleeping_allowed(&mut self, id: usize, allowed: bool) {
        if let Some(&handle) = self.body_handles.get(id) {
            if let Some(rb) = self.rbodies.get_mut(handle) {
                if allowed {
                    *rb.activation_mut() = RigidBodyActivation::default();
                } else {
                    *rb.activation_mut() = RigidBodyActivation::cannot_sleep();
                    rb.wake_up(true);
                }
            }
        }
    }

    /// Returns whether sleeping is allowed for a body.
    ///
    /// # Parameters
    /// - `id` — Body index.
    ///
    /// # Returns
    /// `true` if the body can sleep, `false` if it is forced awake.
    pub fn is_sleeping_allowed(&self, id: usize) -> bool {
        self.body_handles
            .get(id)
            .and_then(|&h| self.rbodies.get(h))
            .map(|rb| rb.activation().angular_threshold >= 0.0)
            .unwrap_or(true)
    }

    /// Removes a body from the world by disabling it in rapier.
    ///
    /// The body slot is kept to preserve stable IDs. The body is set to Static
    /// and its rapier rigid body is disabled.
    ///
    /// # Parameters
    /// - `id` — Body index to destroy.
    pub fn destroy_body(&mut self, id: usize) {
        if id >= self.bodies.len() {
            return;
        }
        // Remove extra fixture colliders from rapier and the reverse map.
        if let Some(extras) = self.extra_collider_handles.get(id) {
            let extra_handles: Vec<ColliderHandle> = extras.clone();
            for h in extra_handles {
                self.rcolliders
                    .remove(h, &mut self.islands, &mut self.rbodies, true);
                self.collider_to_body.remove(&h);
            }
        }
        if id < self.extra_collider_handles.len() {
            self.extra_collider_handles[id].clear();
        }
        // Remove primary collider from reverse map.
        if let Some(&primary) = self.collider_handles.get(id) {
            self.collider_to_body.remove(&primary);
        }
        if let Some(&handle) = self.body_handles.get(id) {
            if let Some(rb) = self.rbodies.get_mut(handle) {
                rb.set_enabled(false);
            }
        }
        // Mark as static so it no longer participates in sync.
        self.bodies[id].body_type = BodyType::Static;
    }

    // ── Extended joint API ────────────────────────────────────────────────────

    /// Returns the total number of joints.
    ///
    /// # Returns
    /// The joint count.
    pub fn joint_count(&self) -> usize {
        self.joint_handles.len()
    }

    /// Creates a distance joint that tries to maintain a fixed distance between two bodies.
    ///
    /// # Parameters
    /// - `body_a` — Index of the first body.
    /// - `body_b` — Index of the second body.
    /// - `ax1` — Local anchor X on body_a.
    /// - `ay1` — Local anchor Y on body_a.
    /// - `ax2` — Local anchor X on body_b.
    /// - `ay2` — Local anchor Y on body_b.
    /// - `length` — Rest length of the joint.
    ///
    /// # Returns
    /// The joint index.
    #[allow(clippy::too_many_arguments)]
    pub fn add_distance_joint(
        &mut self,
        body_a: usize,
        body_b: usize,
        ax1: f32,
        ay1: f32,
        ax2: f32,
        ay2: f32,
        length: f32,
    ) -> usize {
        let ha = match self.body_handles.get(body_a).copied() {
            Some(h) => h,
            None => return 0,
        };
        let hb = match self.body_handles.get(body_b).copied() {
            Some(h) => h,
            None => return 0,
        };
        let joint = RopeJointBuilder::new(length)
            .local_anchor1(Vector::new(ax1, ay1))
            .local_anchor2(Vector::new(ax2, ay2))
            .build();
        let handle = self.impulse_joints.insert(ha, hb, joint, true);
        let jid = self.joint_handles.len();
        self.joint_handles.push(handle);
        self.joint_types.push("distance");
        jid
    }

    /// Creates a prismatic (slider) joint allowing motion along one axis.
    ///
    /// # Parameters
    /// - `body_a` — Index of the first body.
    /// - `body_b` — Index of the second body.
    /// - `anchor_x` — Local anchor X.
    /// - `anchor_y` — Local anchor Y.
    /// - `axis_x` — Slide axis X component.
    /// - `axis_y` — Slide axis Y component.
    ///
    /// # Returns
    /// The joint index.
    pub fn add_prismatic_joint(
        &mut self,
        body_a: usize,
        body_b: usize,
        anchor_x: f32,
        anchor_y: f32,
        axis_x: f32,
        axis_y: f32,
    ) -> usize {
        let ha = match self.body_handles.get(body_a).copied() {
            Some(h) => h,
            None => return 0,
        };
        let hb = match self.body_handles.get(body_b).copied() {
            Some(h) => h,
            None => return 0,
        };
        let axis = Vector::new(axis_x, axis_y);
        let joint = PrismaticJointBuilder::new(axis)
            .local_anchor1(Vector::new(anchor_x, anchor_y))
            .local_anchor2(Vector::new(0.0, 0.0))
            .build();
        let handle = self.impulse_joints.insert(ha, hb, joint, true);
        let jid = self.joint_handles.len();
        self.joint_handles.push(handle);
        self.joint_types.push("prismatic");
        jid
    }

    /// Creates a weld (rigid) joint that locks two bodies together.
    ///
    /// # Parameters
    /// - `body_a` — Index of the first body.
    /// - `body_b` — Index of the second body.
    /// - `anchor_x` — Local anchor X.
    /// - `anchor_y` — Local anchor Y.
    ///
    /// # Returns
    /// The joint index.
    pub fn add_weld_joint(
        &mut self,
        body_a: usize,
        body_b: usize,
        anchor_x: f32,
        anchor_y: f32,
    ) -> usize {
        let ha = match self.body_handles.get(body_a).copied() {
            Some(h) => h,
            None => return 0,
        };
        let hb = match self.body_handles.get(body_b).copied() {
            Some(h) => h,
            None => return 0,
        };
        let joint = FixedJointBuilder::new()
            .local_anchor1(Vector::new(anchor_x, anchor_y))
            .local_anchor2(Vector::new(0.0, 0.0))
            .build();
        let handle = self.impulse_joints.insert(ha, hb, joint, true);
        let jid = self.joint_handles.len();
        self.joint_handles.push(handle);
        self.joint_types.push("weld");
        jid
    }

    /// Creates a rope joint with a maximum distance constraint.
    ///
    /// # Parameters
    /// - `body_a` — Index of the first body.
    /// - `body_b` — Index of the second body.
    /// - `ax1` — Local anchor X on body_a.
    /// - `ay1` — Local anchor Y on body_a.
    /// - `ax2` — Local anchor X on body_b.
    /// - `ay2` — Local anchor Y on body_b.
    /// - `max_length` — Maximum distance between anchors.
    ///
    /// # Returns
    /// The joint index.
    #[allow(clippy::too_many_arguments)]
    pub fn add_rope_joint(
        &mut self,
        body_a: usize,
        body_b: usize,
        ax1: f32,
        ay1: f32,
        ax2: f32,
        ay2: f32,
        max_length: f32,
    ) -> usize {
        let ha = match self.body_handles.get(body_a).copied() {
            Some(h) => h,
            None => return 0,
        };
        let hb = match self.body_handles.get(body_b).copied() {
            Some(h) => h,
            None => return 0,
        };
        let joint = RopeJointBuilder::new(max_length)
            .local_anchor1(Vector::new(ax1, ay1))
            .local_anchor2(Vector::new(ax2, ay2))
            .build();
        let handle = self.impulse_joints.insert(ha, hb, joint, true);
        let jid = self.joint_handles.len();
        self.joint_handles.push(handle);
        self.joint_types.push("rope");
        jid
    }

    /// Returns the two body IDs connected by a joint.
    ///
    /// # Parameters
    /// - `joint_id` — Joint index.
    ///
    /// # Returns
    /// A tuple `(body_a, body_b)`, or `None` if invalid.
    pub fn get_joint_bodies(&self, joint_id: usize) -> Option<(usize, usize)> {
        let &handle = self.joint_handles.get(joint_id)?;
        let joint = self.impulse_joints.get(handle)?;
        let id_a = self.body_handles.iter().position(|&h| h == joint.body1)?;
        let id_b = self.body_handles.iter().position(|&h| h == joint.body2)?;
        Some((id_a, id_b))
    }

    /// Removes a joint from the world. After this call the associated key is invalid and must not be reused.
    ///
    /// # Parameters
    /// - `joint_id` — Joint index to remove.
    pub fn destroy_joint(&mut self, joint_id: usize) {
        if let Some(&handle) = self.joint_handles.get(joint_id) {
            self.impulse_joints.remove(handle, true);
        }
    }

    // ── Enhanced raycasting ───────────────────────────────────────────────────

    /// Casts a ray and returns the closest hit using the query pipeline.
    /// Helper to create a query pipeline from the broad phase.
    fn query_pipeline(&self) -> QueryPipeline<'_> {
        self.broad_phase.as_query_pipeline(
            self.narrow_phase.query_dispatcher(),
            &self.rbodies,
            &self.rcolliders,
            QueryFilter::default(),
        )
    }

    /// Casts a ray and returns the closest hit using the query pipeline.
    ///
    /// # Parameters
    /// - `x1` — Ray origin X.
    /// - `y1` — Ray origin Y.
    /// - `dx` — Ray direction X.
    /// - `dy` — Ray direction Y.
    /// - `max_dist` — Maximum ray distance.
    ///
    /// # Returns
    /// The closest `RaycastHit`, or `None`.
    pub fn raycast_closest(
        &self,
        x1: f32,
        y1: f32,
        dx: f32,
        dy: f32,
        max_dist: f32,
    ) -> Option<RaycastHit> {
        let dir_len = (dx * dx + dy * dy).sqrt();
        if dir_len < 1e-6 {
            return None;
        }
        let unit_dir = Vector::new(dx / dir_len, dy / dir_len);
        let ray = Ray::new(Vector::new(x1, y1), unit_dir);

        let qp = self.query_pipeline();
        let (col_handle, toi_result) = qp.cast_ray_and_get_normal(&ray, max_dist, true)?;

        let body_id = self
            .collider_handles
            .iter()
            .position(|&h| h == col_handle)?;
        let pt_x = x1 + unit_dir.x * toi_result.time_of_impact;
        let pt_y = y1 + unit_dir.y * toi_result.time_of_impact;
        Some(RaycastHit {
            body_id,
            point: (pt_x, pt_y),
            normal: (toi_result.normal.x, toi_result.normal.y),
            toi: toi_result.time_of_impact,
        })
    }

    /// Casts a ray and returns all hits along it.
    ///
    /// # Parameters
    /// - `x1` — Ray origin X.
    /// - `y1` — Ray origin Y.
    /// - `dx` — Ray direction X.
    /// - `dy` — Ray direction Y.
    /// - `max_dist` — Maximum ray distance.
    ///
    /// # Returns
    /// A vector of `RaycastHit` results.
    pub fn raycast_all(
        &self,
        x1: f32,
        y1: f32,
        dx: f32,
        dy: f32,
        max_dist: f32,
    ) -> Vec<RaycastHit> {
        let dir_len = (dx * dx + dy * dy).sqrt();
        if dir_len < 1e-6 {
            return Vec::new();
        }
        let unit_dir = Vector::new(dx / dir_len, dy / dir_len);
        let ray = Ray::new(Vector::new(x1, y1), unit_dir);

        let qp = self.query_pipeline();
        let mut hits = Vec::new();
        for (col_handle, _co, ri) in qp.intersect_ray(ray, max_dist, true) {
            if let Some(body_id) = self.body_for_collider(col_handle) {
                let pt_x = x1 + unit_dir.x * ri.time_of_impact;
                let pt_y = y1 + unit_dir.y * ri.time_of_impact;
                hits.push(RaycastHit {
                    body_id,
                    point: (pt_x, pt_y),
                    normal: (ri.normal.x, ri.normal.y),
                    toi: ri.time_of_impact,
                });
            }
        }
        hits
    }

    // ── Spatial queries ───────────────────────────────────────────────────────

    /// Returns body IDs with colliders intersecting the given AABB.
    ///
    /// # Parameters
    /// - `x` — AABB min X.
    /// - `y` — AABB min Y.
    /// - `w` — AABB width.
    /// - `h` — AABB height.
    ///
    /// # Returns
    /// A vector of body indices inside the AABB.
    pub fn query_aabb(&self, x: f32, y: f32, w: f32, h: f32) -> Vec<usize> {
        let aabb = Aabb {
            mins: Vector::new(x, y),
            maxs: Vector::new(x + w, y + h),
        };
        let qp = self.query_pipeline();
        let mut results = Vec::new();
        for (col_handle, _co) in qp.intersect_aabb_conservative(aabb) {
            if let Some(body_id) = self.body_for_collider(col_handle) {
                results.push(body_id);
            }
        }
        results
    }

    /// Returns the first body whose collider contains the given world-space point.
    ///
    /// Uses a point-sized AABB query filter.
    ///
    /// # Parameters
    /// - `x` — World-space X coordinate.
    /// - `y` — World-space Y coordinate.
    ///
    /// # Returns
    /// `Option<usize>` — body index, or `None` if no body at that point.
    pub fn get_body_at_point(&self, x: f32, y: f32) -> Option<usize> {
        let epsilon = 0.01;
        let aabb = Aabb {
            mins: Vector::new(x - epsilon, y - epsilon),
            maxs: Vector::new(x + epsilon, y + epsilon),
        };
        let qp = self.query_pipeline();
        for (col_handle, _co) in qp.intersect_aabb_conservative(aabb) {
            if let Some(body_id) = self.body_for_collider(col_handle) {
                return Some(body_id);
            }
        }
        None
    }

    // ── Extended joint types ──────────────────────────────────────────────────

    /// Creates a wheel joint (prismatic + rotation) between two bodies.
    ///
    /// Allows translation along the given axis and free rotation.
    ///
    /// # Parameters
    /// - `body_a` — Index of the first body.
    /// - `body_b` — Index of the second body.
    /// - `anchor_x` — Local anchor X.
    /// - `anchor_y` — Local anchor Y.
    /// - `axis_x` — Slide axis X component.
    /// - `axis_y` — Slide axis Y component.
    ///
    /// # Returns
    /// The joint index.
    #[allow(clippy::too_many_arguments)]
    pub fn add_wheel_joint(
        &mut self,
        body_a: usize,
        body_b: usize,
        anchor_x: f32,
        anchor_y: f32,
        axis_x: f32,
        axis_y: f32,
    ) -> usize {
        let ha = match self.body_handles.get(body_a).copied() {
            Some(h) => h,
            None => return 0,
        };
        let hb = match self.body_handles.get(body_b).copied() {
            Some(h) => h,
            None => return 0,
        };
        let axis = Vector::new(axis_x, axis_y);
        let mut joint = PrismaticJointBuilder::new(axis)
            .local_anchor1(Vector::new(anchor_x, anchor_y))
            .local_anchor2(Vector::new(0.0, 0.0))
            .build();
        // Unlock the angular axis to allow rotation (wheel behavior).
        // Prismatic locks Y + AngX; we only want Y locked.
        joint.data.locked_axes = JointAxesMask::LIN_Y;
        let handle = self.impulse_joints.insert(ha, hb, joint, true);
        let jid = self.joint_handles.len();
        self.joint_handles.push(handle);
        self.joint_types.push("wheel");
        jid
    }

    /// Creates a friction joint that resists relative motion between two bodies.
    ///
    /// Uses a fixed joint with velocity motors tuned to the given force/torque limits.
    ///
    /// # Parameters
    /// - `body_a` — Index of the first body.
    /// - `body_b` — Index of the second body.
    /// - `anchor_x` — Local anchor X.
    /// - `anchor_y` — Local anchor Y.
    /// - `max_force` — Maximum linear force.
    /// - `max_torque` — Maximum angular torque.
    ///
    /// # Returns
    /// The joint index.
    #[allow(clippy::too_many_arguments)]
    pub fn add_friction_joint(
        &mut self,
        body_a: usize,
        body_b: usize,
        anchor_x: f32,
        anchor_y: f32,
        max_force: f32,
        max_torque: f32,
    ) -> usize {
        let ha = match self.body_handles.get(body_a).copied() {
            Some(h) => h,
            None => return 0,
        };
        let hb = match self.body_handles.get(body_b).copied() {
            Some(h) => h,
            None => return 0,
        };
        let mut joint = FixedJointBuilder::new()
            .local_anchor1(Vector::new(anchor_x, anchor_y))
            .local_anchor2(Vector::new(0.0, 0.0))
            .build();
        // Configure motors to resist motion (target velocity = 0, damping = max force).
        joint
            .data
            .set_motor(JointAxis::LinX, 0.0, 0.0, 0.0, max_force);
        joint
            .data
            .set_motor(JointAxis::LinY, 0.0, 0.0, 0.0, max_force);
        joint
            .data
            .set_motor(JointAxis::AngX, 0.0, 0.0, 0.0, max_torque);
        let handle = self.impulse_joints.insert(ha, hb, joint, true);
        let jid = self.joint_handles.len();
        self.joint_handles.push(handle);
        self.joint_types.push("friction");
        jid
    }

    /// Creates a motor joint that drives body_b toward body_a's frame.
    ///
    /// The correction factor controls how aggressively the motor corrects position.
    ///
    /// # Parameters
    /// - `body_a` — Index of the first body.
    /// - `body_b` — Index of the second body.
    /// - `correction_factor` — Motor correction stiffness.
    ///
    /// # Returns
    /// The joint index.
    pub fn add_motor_joint(
        &mut self,
        body_a: usize,
        body_b: usize,
        correction_factor: f32,
    ) -> usize {
        let ha = match self.body_handles.get(body_a).copied() {
            Some(h) => h,
            None => return 0,
        };
        let hb = match self.body_handles.get(body_b).copied() {
            Some(h) => h,
            None => return 0,
        };
        let mut joint = FixedJointBuilder::new()
            .local_anchor1(Vector::new(0.0, 0.0))
            .local_anchor2(Vector::new(0.0, 0.0))
            .build();
        // Position-based motor with correction_factor as stiffness.
        joint
            .data
            .set_motor(JointAxis::LinX, 0.0, 0.0, correction_factor, 1.0);
        joint
            .data
            .set_motor(JointAxis::LinY, 0.0, 0.0, correction_factor, 1.0);
        joint
            .data
            .set_motor(JointAxis::AngX, 0.0, 0.0, correction_factor, 1.0);
        let handle = self.impulse_joints.insert(ha, hb, joint, true);
        let jid = self.joint_handles.len();
        self.joint_handles.push(handle);
        self.joint_types.push("motor");
        jid
    }

    /// Creates a mouse joint that connects a body to a target point via a spring.
    ///
    /// Internally creates a kinematic anchor body at the target position
    /// and a spring joint between the body and the anchor.
    ///
    /// # Parameters
    /// - `body_id` — Index of the body to attach.
    /// - `target_x` — Initial target X.
    /// - `target_y` — Initial target Y.
    /// - `max_force` — Maximum spring force.
    ///
    /// # Returns
    /// The joint index.
    pub fn add_mouse_joint(
        &mut self,
        body_id: usize,
        target_x: f32,
        target_y: f32,
        max_force: f32,
    ) -> usize {
        // Create a small kinematic body as the mouse anchor.
        let mut anchor = Body::new(target_x, target_y, BodyType::Kinematic);
        anchor.shape = BodyShape::Circle { radius: 0.1 };
        anchor.width = 0.2;
        anchor.height = 0.2;
        let anchor_id = self.add_body(anchor);

        let ha = self.body_handles[body_id];
        let hb = self.body_handles[anchor_id];

        // Use a stiff spring joint.
        let stiffness = max_force;
        let damping = max_force * 0.7;
        let joint = SpringJointBuilder::new(0.0, stiffness, damping)
            .local_anchor1(Vector::new(0.0, 0.0))
            .local_anchor2(Vector::new(0.0, 0.0))
            .build();

        let handle = self.impulse_joints.insert(ha, hb, joint, true);
        let jid = self.joint_handles.len();
        self.joint_handles.push(handle);
        self.joint_types.push("mouse");

        self.mouse_joint_anchors.insert(jid, anchor_id);
        jid
    }

    /// Updates the target position of a mouse joint.
    ///
    /// # Parameters
    /// - `joint_id` — Joint index.
    /// - `x` — New target X.
    /// - `y` — New target Y.
    pub fn set_mouse_joint_target(&mut self, joint_id: usize, x: f32, y: f32) {
        if let Some(&anchor_id) = self.mouse_joint_anchors.get(&joint_id) {
            self.set_body_position(anchor_id, x, y);
        }
    }

    /// Stub: pulley joint is not supported by rapier2d. Returns a fixed joint fallback.
    ///
    /// # Parameters
    /// - `body_a` — Index of the first body.
    /// - `body_b` — Index of the second body.
    /// - `anchor_x` — Local anchor X.
    /// - `anchor_y` — Local anchor Y.
    ///
    /// # Returns
    /// The joint index.
    pub fn add_pulley_joint(
        &mut self,
        body_a: usize,
        body_b: usize,
        anchor_x: f32,
        anchor_y: f32,
    ) -> usize {
        log_msg!(warn, P001_PULLEY_JOINT_FALLBACK);
        self.add_weld_joint(body_a, body_b, anchor_x, anchor_y)
    }

    /// Stub: gear joint is not supported by rapier2d. Returns a fixed joint fallback.
    ///
    /// # Parameters
    /// - `body_a` — Index of the first body.
    /// - `body_b` — Index of the second body.
    /// - `anchor_x` — Local anchor X.
    /// - `anchor_y` — Local anchor Y.
    ///
    /// # Returns
    /// The joint index.
    pub fn add_gear_joint(
        &mut self,
        body_a: usize,
        body_b: usize,
        anchor_x: f32,
        anchor_y: f32,
    ) -> usize {
        log_msg!(warn, P002_GEAR_JOINT_FALLBACK);
        self.add_weld_joint(body_a, body_b, anchor_x, anchor_y)
    }

    // ── Joint property accessors ──────────────────────────────────────────────

    /// Sets the motor speed on the angular axis of a joint.
    ///
    /// # Parameters
    /// - `joint_id` — Joint index.
    /// - `speed` — Target angular velocity.
    pub fn set_joint_motor_speed(&mut self, joint_id: usize, speed: f32) {
        if let Some(&handle) = self.joint_handles.get(joint_id) {
            if let Some(joint) = self.impulse_joints.get_mut(handle, true) {
                joint.data.set_motor(JointAxis::AngX, 0.0, speed, 0.0, 1e6);
            }
        }
    }

    /// Returns the motor target velocity on the angular axis of a joint.
    ///
    /// # Parameters
    /// - `joint_id` — Joint index.
    ///
    /// # Returns
    /// The motor target velocity.
    pub fn get_joint_motor_speed(&self, joint_id: usize) -> f32 {
        if let Some(&handle) = self.joint_handles.get(joint_id) {
            if let Some(joint) = self.impulse_joints.get(handle) {
                if let Some(motor) = joint.data.motor(JointAxis::AngX) {
                    return motor.target_vel;
                }
            }
        }
        0.0
    }

    /// Enables or disables limits on the angular axis of a joint.
    ///
    /// # Parameters
    /// - `joint_id` — Joint index.
    /// - `enabled` — `true` to enable angular limits.
    pub fn set_joint_limits_enabled(&mut self, joint_id: usize, enabled: bool) {
        if let Some(&handle) = self.joint_handles.get(joint_id) {
            if let Some(joint) = self.impulse_joints.get_mut(handle, true) {
                if enabled {
                    // Set limits to current values or default range.
                    let limits = joint
                        .data
                        .limits(JointAxis::AngX)
                        .map_or([-std::f32::consts::PI, std::f32::consts::PI], |l| {
                            [l.min, l.max]
                        });
                    joint.data.set_limits(JointAxis::AngX, limits);
                } else {
                    // Remove limits by setting a very wide range.
                    joint.data.set_limits(JointAxis::AngX, [-1e10, 1e10]);
                }
            }
        }
    }

    /// Sets the angular limits (lower, upper) on a joint in radians.
    ///
    /// # Parameters
    /// - `joint_id` — Joint index.
    /// - `lower` — Lower angular limit.
    /// - `upper` — Upper angular limit.
    pub fn set_joint_limits(&mut self, joint_id: usize, lower: f32, upper: f32) {
        if let Some(&handle) = self.joint_handles.get(joint_id) {
            if let Some(joint) = self.impulse_joints.get_mut(handle, true) {
                joint.data.set_limits(JointAxis::AngX, [lower, upper]);
            }
        }
    }

    /// Returns the angular limits `(lower, upper)` on a joint.
    ///
    /// # Parameters
    /// - `joint_id` — Joint index.
    ///
    /// # Returns
    /// A tuple `(lower, upper)` in radians.
    pub fn get_joint_limits(&self, joint_id: usize) -> (f32, f32) {
        if let Some(&handle) = self.joint_handles.get(joint_id) {
            if let Some(joint) = self.impulse_joints.get(handle) {
                if let Some(limits) = joint.data.limits(JointAxis::AngX) {
                    return (limits.min, limits.max);
                }
            }
        }
        (0.0, 0.0)
    }

    /// Returns the type name of a joint. This accessor incurs no allocation; call it freely in hot paths.
    ///
    /// # Parameters
    /// - `joint_id` — Joint index.
    ///
    /// # Returns
    /// One of `"revolute"`, `"distance"`, `"prismatic"`, `"weld"`, `"rope"`, etc.
    pub fn get_joint_type(&self, joint_id: usize) -> &'static str {
        self.joint_types.get(joint_id).copied().unwrap_or("unknown")
    }

    // ── Meter scaling ─────────────────────────────────────────────────────────

    /// Sets the pixels-per-meter scaling factor.
    ///
    /// # Parameters
    /// - `ppm` — Pixels per meter.
    pub fn set_meter(&mut self, ppm: f32) {
        self.pixels_per_meter = ppm;
    }

    /// Returns the pixels-per-meter scaling factor.
    ///
    /// # Returns
    /// The current pixels-per-meter value.
    pub fn get_meter(&self) -> f32 {
        self.pixels_per_meter
    }

    /// Converts a pixel value to physics units.
    ///
    /// # Parameters
    /// - `px` — Pixel value.
    ///
    /// # Returns
    /// The equivalent physics-unit value.
    pub fn to_physics(&self, px: f32) -> f32 {
        if self.pixels_per_meter > 0.0 {
            px / self.pixels_per_meter
        } else {
            px
        }
    }

    /// Converts a physics-unit value to pixels.
    ///
    /// # Parameters
    /// - `m` — Physics-unit value.
    ///
    /// # Returns
    /// The equivalent pixel value.
    pub fn to_pixels(&self, m: f32) -> f32 {
        m * self.pixels_per_meter
    }

    // ── Contact queries ───────────────────────────────────────────────────────

    /// Returns all contact pairs from the narrow phase.
    ///
    /// # Returns
    /// A vector of `ContactInfo` entries.
    pub fn get_contacts(&self) -> Vec<ContactInfo> {
        let mut contacts = Vec::new();
        for pair in self.narrow_phase.contact_pairs() {
            let id_a = self
                .collider_handles
                .iter()
                .position(|&h| h == pair.collider1);
            let id_b = self
                .collider_handles
                .iter()
                .position(|&h| h == pair.collider2);
            if let (Some(a), Some(b)) = (id_a, id_b) {
                let is_touching = pair.has_any_active_contact();
                let (nx, ny) = pair
                    .manifolds
                    .first()
                    .map(|m| (m.local_n1.x, m.local_n1.y))
                    .unwrap_or((0.0, 0.0));
                contacts.push(ContactInfo {
                    body_a: a,
                    body_b: b,
                    normal_x: nx,
                    normal_y: ny,
                    is_touching,
                });
            }
        }
        contacts
    }

    /// Returns contacts involving a specific body.
    ///
    /// # Parameters
    /// - `body_id` — Body index to filter by.
    ///
    /// # Returns
    /// A vector of `ContactInfo` entries involving the body.
    pub fn get_body_contacts(&self, body_id: usize) -> Vec<ContactInfo> {
        self.get_contacts()
            .into_iter()
            .filter(|c| c.body_a == body_id || c.body_b == body_id)
            .collect()
    }
}
