// Autogenerated to group integration tests
#[path = "rust/config/config_tests.rs"]
mod config_tests;
#[path = "rust/ext/graphics_ext_tests.rs"]
mod graphics_ext_tests;
#[path = "rust/ext/graphics_runtime_smoke_tests.rs"]
mod graphics_runtime_smoke_tests;
#[path = "rust/ext/math_ext_tests.rs"]
mod math_ext_tests;
#[path = "rust/ext/terminal_demo_smoke_tests.rs"]
mod terminal_demo_smoke_tests;
#[path = "rust/security/security_tests.rs"]
mod security_tests;
#[path = "rust/stress/compute_stress_tests.rs"]
mod compute_stress_tests;
#[path = "rust/stress/data_stress_tests.rs"]
mod data_stress_tests;
#[path = "rust/stress/image_stress_tests.rs"]
mod image_stress_tests;
#[path = "rust/stress/physics_stress_tests.rs"]
mod physics_stress_tests;
#[path = "rust/integration/ai_tests.rs"]
mod ai_tests;
#[path = "rust/integration/animation_tests.rs"]
mod animation_tests;
#[path = "rust/integration/audio_sound_tests.rs"]
mod audio_sound_tests;
#[path = "rust/integration/audio_tests.rs"]
mod audio_tests;
#[path = "rust/integration/automation_tests.rs"]
mod automation_tests;
#[path = "rust/integration/camera_tests.rs"]
mod camera_tests;
#[path = "rust/integration/compute_tests.rs"]
mod compute_tests;
#[path = "rust/integration/dataframe_tests.rs"]
mod dataframe_tests;
#[path = "rust/integration/data_tests.rs"]
mod data_tests;
#[path = "rust/integration/debugbridge_tests.rs"]
mod debugbridge_tests;
#[path = "rust/integration/devtools_tests.rs"]
mod devtools_tests;
#[path = "rust/integration/docs_tests.rs"]
mod docs_tests;
#[path = "rust/integration/engine_tests.rs"]
mod engine_tests;
#[path = "rust/integration/entity_tests.rs"]
mod entity_tests;
#[path = "rust/integration/event_tests.rs"]
mod event_tests;
#[path = "rust/integration/filesystem_tests.rs"]
mod filesystem_tests;
#[path = "rust/integration/fx_screen_tests.rs"]
mod fx_screen_tests;
#[path = "rust/integration/fx_tests.rs"]
mod fx_tests;
#[path = "rust/integration/graphics_tests.rs"]
mod graphics_tests;
#[path = "rust/integration/graph_tests.rs"]
mod graph_tests;
#[path = "rust/integration/gui_tests.rs"]
mod gui_tests;
#[path = "rust/integration/image_tests.rs"]
mod image_tests;
#[path = "rust/integration/input_tests.rs"]
mod input_tests;
#[path = "rust/integration/light_tests.rs"]
mod light_tests;
#[path = "rust/integration/localization_tests.rs"]
mod localization_tests;
#[path = "rust/integration/log_tests.rs"]
mod log_tests;
#[path = "rust/integration/math_tests.rs"]
mod math_tests;
#[path = "rust/integration/messages_tests.rs"]
mod messages_tests;
#[path = "rust/integration/modding_tests.rs"]
mod modding_tests;
#[path = "rust/integration/network_tests.rs"]
mod network_tests;
#[path = "rust/integration/overlay_tests.rs"]
mod overlay_tests;
#[path = "rust/integration/particle_tests.rs"]
mod particle_tests;
#[path = "rust/integration/pathfinding_tests.rs"]
mod pathfinding_tests;
#[path = "rust/integration/patterns_tests.rs"]
mod patterns_tests;
#[path = "rust/integration/physics_tests.rs"]
mod physics_tests;
#[path = "rust/integration/pipeline_tests.rs"]
mod pipeline_tests;
#[path = "rust/integration/postfx_tests.rs"]
mod postfx_tests;
#[path = "rust/integration/procgen_tests.rs"]
mod procgen_tests;
#[path = "rust/integration/raycaster_tests.rs"]
mod raycaster_tests;
#[path = "rust/integration/savegame_tests.rs"]
mod savegame_tests;
#[path = "rust/integration/scene_tests.rs"]
mod scene_tests;
#[path = "rust/integration/serial_tests.rs"]
mod serial_tests;
#[path = "rust/integration/spine_tests.rs"]
mod spine_tests;
#[path = "rust/integration/terminal_tests.rs"]
mod terminal_tests;
#[path = "rust/integration/thread_tests.rs"]
mod thread_tests;
#[path = "rust/integration/tilemap_tests.rs"]
mod tilemap_tests;
#[path = "rust/integration/timer_tests.rs"]
mod timer_tests;
#[path = "rust/integration/tween_tests.rs"]
mod tween_tests;
#[path = "rust/integration/window_tests.rs"]
mod window_tests;
