// Autogenerated to group integration tests

// ── ext tests ──────────────────────────────────────────────────────────────────
#[path = "rust/ext/graphics_ext_tests.rs"]
mod graphics_ext_tests;
#[path = "rust/ext/graphics_runtime_smoke_tests.rs"]
mod graphics_runtime_smoke_tests;
#[path = "rust/ext/math_ext_tests.rs"]
mod math_ext_tests;
#[path = "rust/ext/terminal_demo_smoke_tests.rs"]
mod terminal_demo_smoke_tests;

// ── unit tests (one module per engine subsystem) ───────────────────────────────
#[path = "rust/unit/ai_tests.rs"]
mod ai_tests;
#[path = "rust/unit/animation_tests.rs"]
mod animation_tests;
#[path = "rust/unit/app_tests.rs"]
mod app_tests;
#[path = "rust/unit/audio_tests.rs"]
mod audio_tests;
#[path = "rust/unit/automation_tests.rs"]
mod automation_tests;
#[path = "rust/unit/camera_tests.rs"]
mod camera_tests;
#[path = "rust/unit/compute_tests.rs"]
mod compute_tests;
#[path = "rust/unit/data_tests.rs"]
mod data_tests;
#[path = "rust/unit/dataframe_tests.rs"]
mod dataframe_tests;
#[path = "rust/unit/debugbridge_tests.rs"]
mod debugbridge_tests;
#[path = "rust/unit/devtools_tests.rs"]
mod devtools_tests;
#[path = "rust/unit/docs_tests.rs"]
mod docs_tests;
#[path = "rust/unit/ecs_tests.rs"]
mod ecs_tests;
#[path = "rust/unit/effect_tests.rs"]
mod effect_tests;
#[path = "rust/unit/event_tests.rs"]
mod event_tests;
#[path = "rust/unit/filesystem_tests.rs"]
mod filesystem_tests;
#[path = "rust/unit/globe_tests.rs"]
mod globe_tests;
#[path = "rust/unit/graph_tests.rs"]
mod graph_tests;
#[path = "rust/unit/gui_tests.rs"]
mod gui_tests;
#[path = "rust/unit/i18n_tests.rs"]
mod i18n_tests;
#[path = "rust/unit/image_tests.rs"]
mod image_tests;
#[path = "rust/unit/input_tests.rs"]
mod input_tests;
#[path = "rust/unit/light_tests.rs"]
mod light_tests;
#[path = "rust/unit/log_tests.rs"]
mod log_tests;
#[path = "rust/unit/math_tests.rs"]
mod math_tests;
#[path = "rust/unit/minimap_tests.rs"]
mod minimap_tests;
#[path = "rust/unit/mods_tests.rs"]
mod mods_tests;
#[path = "rust/unit/network_tests.rs"]
mod network_tests;
#[path = "rust/unit/parallax_tests.rs"]
mod parallax_tests;
#[path = "rust/unit/particle_tests.rs"]
mod particle_tests;
#[path = "rust/unit/pathfind_tests.rs"]
mod pathfind_tests;
#[path = "rust/unit/patterns_tests.rs"]
mod patterns_tests;
#[path = "rust/unit/physics_tests.rs"]
mod physics_tests;
#[path = "rust/unit/pipeline_tests.rs"]
mod pipeline_tests;
#[path = "rust/unit/procgen_tests.rs"]
mod procgen_tests;
#[path = "rust/unit/raycaster_tests.rs"]
mod raycaster_tests;
#[path = "rust/unit/render_tests.rs"]
mod render_tests;
#[path = "rust/unit/runtime_tests.rs"]
mod runtime_tests;
#[path = "rust/unit/save_tests.rs"]
mod save_tests;
#[path = "rust/unit/scene_tests.rs"]
mod scene_tests;
#[path = "rust/unit/serial_tests.rs"]
mod serial_tests;
#[path = "rust/unit/spine_tests.rs"]
mod spine_tests;
#[path = "rust/unit/sprite_tests.rs"]
mod sprite_tests;
#[path = "rust/unit/terminal_tests.rs"]
mod terminal_tests;
#[path = "rust/unit/thread_tests.rs"]
mod thread_tests;
#[path = "rust/unit/tilemap_tests.rs"]
mod tilemap_tests;
#[path = "rust/unit/timer_tests.rs"]
mod timer_tests;
#[path = "rust/unit/tween_tests.rs"]
mod tween_tests;
#[path = "rust/unit/ui_tests.rs"]
mod ui_tests;
#[path = "rust/unit/window_tests.rs"]
mod window_tests;
