#!/usr/bin/env python3
"""
add_lua_docstrings_auto.py — Automatically inject /// docstrings above every
undocumented add_method / add_function / .set() call in src/lua_api/*.rs.

Docstrings are generated by:
 - Splitting the camelCase method name into words
 - Inferring intent from common prefixes (get/set/is/has/new/add/remove/…)
 - Parsing the Rust closure parameter list for param names and types
 - Using the context struct name to provide class-aware descriptions

Usage:
    python tools/add_lua_docstrings_auto.py [--dry-run] [--file FILE]

    --dry-run   Print how many insertions would be made; do not write files.
    --file FILE Process only this one file (relative to src/lua_api/).
"""

import re
import sys
import pathlib
import argparse
from typing import List, Tuple, Optional

WORKSPACE = pathlib.Path(__file__).resolve().parent.parent.parent.parent
LUA_API_DIR = WORKSPACE / "src" / "lua_api"

# ── camelCase splitter ────────────────────────────────────────────────────────

def _split_camel(name: str) -> List[str]:
    """'setMaxSpeed' → ['set', 'Max', 'Speed']"""
    parts = re.sub(r'([A-Z])', r' \1', name).split()
    return parts


def _camel_to_words(name: str) -> str:
    """'setMaxSpeed' → 'max speed'"""
    parts = _split_camel(name)
    if not parts:
        return name.lower()
    # skip first word (verb) to get the subject
    return " ".join(p.lower() for p in parts[1:]) if len(parts) > 1 else parts[0].lower()


# ── Rust type → Lua type ──────────────────────────────────────────────────────

RUST_TO_LUA = {
    "f32": "number", "f64": "number",
    "i8": "integer", "i16": "integer", "i32": "integer", "i64": "integer",
    "u8": "integer", "u16": "integer", "u32": "integer", "u64": "integer",
    "usize": "integer", "isize": "integer",
    "String": "string", "LuaString": "string",
    "bool": "boolean",
    "LuaTable": "table",
    "LuaValue": "any",
    "LuaAnyUserData": "userdata",
    "LuaFunction": "function",
    "()": "nil",
}

def rust_to_lua_type(t: str) -> str:
    t = t.strip()
    m = re.match(r'Option<(.+)>', t)
    if m:
        return rust_to_lua_type(m.group(1)) + "?"
    m = re.match(r'Vec<(.+)>', t)
    if m:
        return "table"
    return RUST_TO_LUA.get(t, t)


# ── Closure parameter extraction ─────────────────────────────────────────────

def parse_closure_params(lines: List[str], decl_idx: int) -> List[Tuple[str, str]]:
    """
    Parse the closure parameter list from lines starting at decl_idx.
    Returns a list of (name, lua_type) pairs. Empty list if no params or unparseable.
    """
    # Collect up to 8 lines of context for multi-line closures
    window = " ".join(l.strip() for l in lines[decl_idx: decl_idx + 8])

    # Pattern 1: |_, this, (a, b, c): (T1, T2, T3)| or |_, this, (a,): (T1,)|
    m = re.search(r'\|[^|]*?,\s*(?:\w+,\s*)?\(([^)]+)\):\s*\(([^)]+)\)', window)
    if m:
        names_raw = m.group(1).split(',')
        types_raw = m.group(2).split(',')
        result = []
        for n, t in zip(names_raw, types_raw):
            name = re.sub(r'^_+', '', n.strip())
            lua_t = rust_to_lua_type(t.strip())
            if name and lua_t:
                result.append((name, lua_t))
        return result

    # Pattern 2: single param with tuple wrap: (a,): (T,)
    m = re.search(r'\|[^|]*?,\s*(?:\w+,\s*)?\((\w+)\s*,\s*\):\s*\(([^)]+),\s*\)', window)
    if m:
        name = re.sub(r'^_+', '', m.group(1))
        lua_t = rust_to_lua_type(m.group(2).strip())
        return [(name, lua_t)]

    # Pattern 3: scalar param: |_, this, name: Type|
    m = re.search(r'\|[^|]*?,\s*(?:\w+,\s*)?(\w+):\s*([A-Za-z][A-Za-z0-9_<>, &]+?)\|', window)
    if m:
        name = re.sub(r'^_+', '', m.group(1))
        lua_t = rust_to_lua_type(m.group(2).strip())
        if name not in ('lua', '_lua', 'this', '_'):
            return [(name, lua_t)]

    # Pattern 4: truly no params: |_, ()| or |_, this, ()|
    m = re.search(r'\|[^|]*?,\s*(?:\w+,\s*)?\(\s*\)\|', window)
    if m:
        return []

    # Fallback: assume no params
    return []


# ── Description generation ────────────────────────────────────────────────────

VERB_OVERRIDES = {
    "update": ("Advances the simulation by `dt` seconds.",),
    "draw": ("Draws to the current render target.",),
    "render": ("Renders to the current render target.",),
    "play": ("Starts playback.",),
    "stop": ("Stops playback.",),
    "pause": ("Pauses playback.",),
    "resume": ("Resumes paused playback.",),
    "rewind": ("Seeks to the beginning without stopping.",),
    "reset": ("Resets state to initial values.",),
    "clear": ("Removes all entries.",),
    "flush": ("Flushes pending data.",),
    "clone": ("Returns a deep copy of this object.",),
    "destroy": ("Releases all associated resources.",),
    "release": ("Releases the underlying resource handle.",),
    "attach": ("Applies this object's transform for subsequent draw calls.",),
    "detach": ("Restores the previous transform after drawing.",),
    "enable": ("Enables this component.",),
    "disable": ("Disables this component.",),
    "serialize": ("Serializes this object to a string representation.",),
    "deserialize": ("Populates this object from a serialized string.",),
    "encode": ("Encodes data as a string.",),
    "decode": ("Decodes a string back into data.",),
    "save": ("Writes state to persistent storage.",),
    "load": ("Loads state from persistent storage.",),
    "scan": ("Scans the directory for available items.",),
    "tick": ("Advances internal state by one logic tick.",),
    "step": ("Advances the simulation by one physics step.",),
    "advance": ("Advances to the next item.",),
    "next": ("Moves to the next entry.",),
    "previous": ("Moves to the previous entry.",),
    "prev": ("Moves to the previous entry.",),
    "sort": ("Sorts the collection.",),
    "shuffle": ("Randomly reorders the collection.",),
    "copy": ("Returns a shallow copy.",),
    "clone": ("Returns a deep copy of this object.",),
    "cast": ("Casts a ray and returns all intersection results.",),
    "process": ("Processes one full cycle.",),
    "evaluate": ("Evaluates all conditions and returns a decision.",),
    "train": ("Runs one learning iteration.",),
    "predict": ("Returns the predicted best action given current state.",),
    "plan": ("Computes an action sequence to reach the goal state.",),
    "path": ("Computes the shortest path between nodes.",),
    "init": ("Initializes internal state.",),
    "setup": ("Configures the component with default values.",),
    "build": ("Builds and returns the completed object.",),
    "compile": ("Compiles and validates internal data.",),
    "start": ("Begins execution.",),
    "finish": ("Marks current execution as complete.",),
    "cancel": ("Cancels the current operation.",),
    "complete": ("Marks the current task as complete.",),
    "fail": ("Marks the current task as failed.",),
    "trigger": ("Fires an event or transition.",),
    "dispatch": ("Dispatches an event to registered listeners.",),
    "emit": ("Emits an event.",),
    "on": ("Registers an event listener callback.",),
    "off": ("Removes a previously registered event listener.",),
    "once": ("Registers a callback invoked only once.",),
    "select": ("Returns filtered rows or items matching the query.",),
    "filter": ("Returns a filtered subset.",),
    "find": ("Searches for and returns the first matching item.",),
    "query": ("Runs a query and returns matching results.",),
    "apply": ("Applies this effect to the target.",),
    "inject": ("Injects data into the pipeline.",),
    "project": ("Projects world coordinates to screen space.",),
    "unproject": ("Projects screen coordinates to world space.",),
    "snap": ("Snaps the value to the nearest grid point.",),
    "clamp": ("Clamps the value within the allowed range.",),
    "lerp": ("Interpolates between start and target values.",),
    "mark": ("Marks the specified cell or region.",),
    "unmark": ("Clears any mark from the specified cell or region.",),
    "reveal": ("Reveals the specified area through fog of war.",),
    "ping": ("Places a temporary ping marker at the given position.",),
    "seek": ("Seeks playback to the given position.",),
}


def verb_prefix(name: str) -> Optional[str]:
    """Return the leading verb word if name matches a known prefix."""
    parts = _split_camel(name)
    if not parts:
        return None
    v = parts[0].lower()
    return v


def generate_description(lua_name: str, params: List[Tuple[str, str]], class_name: str) -> str:
    """Generate a one-line description for a method given its name, params, and owning class."""
    parts = _split_camel(lua_name)
    if not parts:
        return f"Calls `{lua_name}`."

    verb = parts[0].lower()
    subject_words = " ".join(p.lower() for p in parts[1:]) if len(parts) > 1 else ""

    # Exact overrides
    if lua_name.lower() in VERB_OVERRIDES:
        return VERB_OVERRIDES[lua_name.lower()][0]

    # Verb-based inference
    if verb in ("get", "fetch", "read"):
        return f"Returns the {subject_words or 'value'}." if subject_words else "Returns the current value."
    if verb in ("set", "write"):
        return f"Sets the {subject_words or 'value'}." if subject_words else "Sets the value."
    if verb in ("is", "has", "can", "was", "should", "will"):
        desc = subject_words or lua_name[len(verb):]
        return f"Returns `true` if {desc or 'the condition is met'}."
    if verb in ("add", "append", "push", "insert", "register", "attach"):
        return f"Adds {subject_words or 'an entry'} to the collection."
    if verb in ("remove", "delete", "erase", "pop", "unregister", "detach"):
        return f"Removes {subject_words or 'the entry'} from the collection."
    if verb in ("new", "create", "make", "spawn", "instantiate"):
        return f"Creates a new {subject_words or class_name} instance."
    if verb in ("count", "size", "length", "num"):
        return f"Returns the number of {subject_words or 'items'}."

    # Full override map lookup (verb_overrides may contain full names)
    if lua_name in VERB_OVERRIDES:
        return VERB_OVERRIDES[lua_name][0]

    # Default
    full_name_words = " ".join(p.lower() for p in parts)
    return f"{full_name_words.capitalize()} on this {class_name}."


def generate_docstring(lua_name: str, params: List[Tuple[str, str]], class_name: str, indent: str) -> str:
    """Return the full /// docstring block as a string (without trailing newline)."""
    desc = generate_description(lua_name, params, class_name)
    lines = [f"{indent}/// {desc}"]

    if params:
        lines.append(f"{indent}///")
        lines.append(f"{indent}/// # Parameters")
        for pname, ptype in params:
            optional = ptype.endswith("?")
            type_display = ptype.rstrip("?")
            if optional:
                lines.append(f"{indent}/// - `{pname}` — `{type_display}` optional.")
            else:
                lines.append(f"{indent}/// - `{pname}` — `{type_display}`.")

    # Add Returns section only for getter-like methods
    verb = _split_camel(lua_name)[0].lower() if _split_camel(lua_name) else ""
    getter_verbs = {"get", "fetch", "read", "is", "has", "can", "was", "count", "size", "num"}
    if verb in getter_verbs or not params:
        # Infer return type description
        if verb in ("is", "has", "can", "was"):
            ret_desc = "`boolean`."
        elif verb in ("count", "size", "num", "length"):
            ret_desc = "`integer`."
        elif verb in ("get", "fetch", "read"):
            subject = _camel_to_words(lua_name)
            ret_desc = f"The current {subject}."
        elif not params:
            ret_desc = "The result."
        else:
            ret_desc = "The result."

        lines.append(f"{indent}///")
        lines.append(f"{indent}/// # Returns")
        lines.append(f"{indent}/// {ret_desc}")

    return "\n".join(lines)


# ── Line analysis ─────────────────────────────────────────────────────────────

BINDING_RE = re.compile(
    r'(?:add_method_mut|add_method|add_function|add_function_mut)\s*\(\s*"([^"]+)"'
)
SET_RE = re.compile(r'\.set\s*\(\s*"([^"]+)"')
STRUCT_RE = re.compile(r'impl(?:\s+LuaUserData\s+for\s+Lua)?(\w+)')


def line_has_doc_above(lines: List[str], idx: int) -> bool:
    """Return True if there is a /// doc comment immediately above line idx."""
    j = idx - 1
    while j >= 0:
        s = lines[j].strip()
        if s.startswith("///"):
            return True
        if s == "" or s.startswith("#[") or s.startswith("//!"):
            j -= 1
            continue
        if re.match(r'^let\s+\w+\s*=\s*\w+(?:\.\w+)*\s*\(\s*\)\s*;$', s):
            j -= 1
            continue
        if s.startswith("//") and not s.startswith("///"):
            j -= 1
            continue
        break
    return False


def current_struct_name(lines: List[str], idx: int) -> str:
    """Walk backwards from idx to find the most recent 'impl LuaUserData for LuaXxx'."""
    for j in range(idx - 1, -1, -1):
        m = re.search(r'impl\s+LuaUserData\s+for\s+Lua(\w+)', lines[j])
        if m:
            return m.group(1)
        m2 = re.search(r'struct\s+Lua(\w+)', lines[j])
        if m2:
            return m2.group(1)
    return "Object"


# ── File processor ────────────────────────────────────────────────────────────

def process_file(path: pathlib.Path, dry_run: bool = False) -> int:
    """Process one Rust source file; return number of docstrings inserted."""
    text = path.read_text(encoding='utf-8')
    lines = text.splitlines()
    insertions: List[Tuple[int, str]] = []  # (line_idx, docstring_text)

    for i, line in enumerate(lines):
        m = BINDING_RE.search(line) or SET_RE.search(line)
        if not m:
            continue
        lua_name = m.group(1)
        # Skip internal infrastructure names
        if lua_name in ('__index', '__newindex', '__tostring', '__len',
                        '__eq', '__lt', '__le', '__call', '__gc',
                        'type', 'is_a', 'inherits', 'super'):
            continue
        if line_has_doc_above(lines, i):
            continue

        params = parse_closure_params(lines, i)
        class_name = current_struct_name(lines, i)
        indent = re.match(r'^(\s*)', line).group(1)
        doc = generate_docstring(lua_name, params, class_name, indent)
        insertions.append((i, doc))

    if not insertions:
        return 0

    if dry_run:
        return len(insertions)

    # Insert in reverse order so line indices remain valid
    for idx, doc in reversed(insertions):
        lines.insert(idx, doc)

    path.write_text("\n".join(lines) + "\n", encoding='utf-8')
    return len(insertions)


# ── CLI ───────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--dry-run', action='store_true', help='Print counts only')
    parser.add_argument('--file', help='Process single file name (relative to src/lua_api/)')
    args = parser.parse_args()

    if args.file:
        files = [LUA_API_DIR / args.file]
    else:
        files = sorted(LUA_API_DIR.glob('*.rs'))

    total = 0
    for f in files:
        n = process_file(f, dry_run=args.dry_run)
        if n:
            verb = "would insert" if args.dry_run else "inserted"
            print(f"  {f.name}: {verb} {n} docstrings")
            total += n

    print(f"\nTotal: {total} docstrings {'would be ' if args.dry_run else ''}inserted.")
    return 0


if __name__ == '__main__':
    sys.exit(main())
