"""One-shot cleanup of content/examples/network.lua.

Removes:
- Garbled section headers (NetworkHost methods / NetworkRuntime methods)
- COVERAGE banner blocks generated by example_add_missing.py
- Duplicate lurek.network.newHost stub
- Bare separator comment (-- NetworkRuntime methods)
- Broken LNetworkHost:type and LNetworkHost:typeOf stubs (replaced with correct versions)
"""

from pathlib import Path

p = Path("content/examples/network.lua")
lines = p.read_text("utf-8").split("\n")

# 0-indexed lines to skip
skip: set[int] = set()

# garbled section headers and preceding blank lines
for i, l in enumerate(lines):
    if "NetworkHost methods" in l or "NetworkRuntime methods" in l:
        skip.add(i)
        if i > 0 and lines[i - 1].strip() == "":
            skip.add(i - 1)

# COVERAGE banners: any run of lines starting with '-- =====...' or '-- COVERAGE' or '-- Generated' etc.
in_banner = False
for i, l in enumerate(lines):
    if l.startswith("-- ============="):
        in_banner = True
    if in_banner:
        skip.add(i)
    if in_banner and l.startswith("-- =============") and i > 0 and lines[i - 1].startswith("-- ====="):
        # closing line
        in_banner = False
    # also skip the blank line immediately after a banner closing line
# simpler: find banner blocks as contiguous runs of lines that start with '-- =='
i = 0
skip_banner: set[int] = set()
while i < len(lines):
    if lines[i].startswith("-- ============="):
        j = i
        while j < len(lines) and (lines[j].startswith("-- ") or lines[j] == ""):
            skip_banner.add(j)
            if lines[j].startswith("-- =============") and j > i:
                j += 1
                break
            j += 1
        i = j
    else:
        i += 1

skip.update(skip_banner)

# Now find and skip the duplicate lurek.network.newHost stub
# (the first occurrence at lines 5-11 stays, remove later occurrences)
first_seen = False
i = 0
while i < len(lines):
    l = lines[i]
    if l.strip() == "--@api-stub: lurek.network.newHost":
        if not first_seen:
            first_seen = True
        else:
            # skip this stub: marker, optional desc, do...end
            j = i
            # skip marker + any comment lines
            while j < len(lines) and (lines[j].startswith("--") or lines[j].strip() == ""):
                skip.add(j)
                if lines[j].strip() == "" and j > i:
                    break
                j += 1
            # skip do...end block
            if j < len(lines) and lines[j].strip() == "do":
                depth = 0
                while j < len(lines):
                    skip.add(j)
                    if lines[j].strip() == "do":
                        depth += 1
                    elif lines[j].strip() == "end":
                        depth -= 1
                        if depth == 0:
                            j += 1
                            break
                    j += 1
            i = j
            continue
    i += 1

# Find and skip broken LNetworkHost:type and LNetworkHost:typeOf stubs
for stub_name in ("LNetworkHost:type", "LNetworkHost:typeOf"):
    i = 0
    while i < len(lines):
        if lines[i].strip() == f"--@api-stub: {stub_name}":
            j = i
            # skip until end of do block
            while j < len(lines) and not lines[j].strip() == "do":
                skip.add(j)
                j += 1
            # skip do...end
            if j < len(lines) and lines[j].strip() == "do":
                depth = 0
                while j < len(lines):
                    skip.add(j)
                    if lines[j].strip() == "do":
                        depth += 1
                    elif lines[j].strip() == "end":
                        depth -= 1
                        if depth == 0:
                            j += 1
                            break
                    j += 1
            i = j
            continue
        i += 1

# Build filtered output
out = [l for i, l in enumerate(lines) if i not in skip]

# Insert correct LNetworkHost:type and LNetworkHost:typeOf before LNetworkRuntime:type
FIXED_STUBS = [
    "--@api-stub: LNetworkHost:type",
    "-- Returns the Lua-visible type name for this network host handle",
    "do",
    "  local host = lurek.network.newServer{ port = 5573, maxPeers = 4 }",
    '  lurek.log.info("LNetworkHost:type = " .. host:type(), "net")',
    "  host:destroy()",
    "end",
    "--@api-stub: LNetworkHost:typeOf",
    "-- Returns whether this network host handle matches a supported type name",
    "do",
    "  local host = lurek.network.newServer{ port = 5574, maxPeers = 4 }",
    '  lurek.log.info("is host: " .. tostring(host:typeOf("LNetworkHost")), "net")',
    "  host:destroy()",
    "end",
]

insert_idx = next(
    (i for i, l in enumerate(out) if l.strip() == "--@api-stub: LNetworkRuntime:type"),
    len(out),
)
out = out[:insert_idx] + FIXED_STUBS + out[insert_idx:]

# Strip excess trailing blank lines
while len(out) > 1 and out[-1].strip() == "" and out[-2].strip() == "":
    out.pop()
if not out or out[-1].strip() != "":
    out.append("")

result = "\n".join(out)
p.write_text(result, "utf-8")
print(f"Done. {len(lines)} -> {len(out)} lines")
