#!/usr/bin/env python3
"""
tools/fix/strip_instance_method_comments.py
Remove the '-- X instance methods (variable: x)' comment lines that are
generated by expand_examples.py. These are redundant given the section
header above each class block.
"""
import re
from pathlib import Path

ROOT     = Path(__file__).resolve().parents[2]
EXAMPLES = ROOT / "examples"

# Matches: -- Foo instance methods (variable: bar)
_PATTERN = re.compile(r'^-- \S.*? instance methods \(variable: \w+\)\s*$', re.MULTILINE)


def fix_file(path: Path) -> bool:
    src = path.read_text(encoding="utf-8")
    new_src, n = _PATTERN.subn("", src)
    if n:
        # Clean up any double-blank-lines introduced by the removal
        new_src = re.sub(r'\n{3,}', '\n\n', new_src)
        path.write_text(new_src, encoding="utf-8")
        return True
    return False


def main():
    fixed = 0
    for p in sorted(EXAMPLES.glob("*.lua")):
        if fix_file(p):
            fixed += 1
            print(f"[FIX] {p.name}")
    print(f"\nFixed {fixed} file(s)")


if __name__ == "__main__":
    main()
