-- Luna2D PostFX API Tests (headless - tests API existence and parameters only)

describe("luna.postfx module exists", function()
    it("luna.postfx is a table", function()
        expect_type("table", luna.postfx)
    end)
end)

describe("luna.postfx factory functions", function()
    it("newEffect is a function", function()
        expect_type("function", luna.postfx.newEffect)
    end)

    it("newPass is a function", function()
        expect_type("function", luna.postfx.newPass)
    end)

    it("newStack is a function", function()
        expect_type("function", luna.postfx.newStack)
    end)

    it("getEffectTypes is a function", function()
        expect_type("function", luna.postfx.getEffectTypes)
    end)
end)

describe("luna.postfx.newEffect built-in types", function()
    it("creates bloom effect", function()
        local e = luna.postfx.newEffect("bloom")
        expect_eq("bloom", e:getEffectType())
        expect_eq(true, e:isBuiltIn())
    end)

    it("creates blur effect", function()
        local e = luna.postfx.newEffect("blur")
        expect_eq("blur", e:getEffectType())
    end)

    it("creates crt effect", function()
        local e = luna.postfx.newEffect("crt")
        expect_eq("crt", e:getEffectType())
    end)

    it("creates godrays effect", function()
        local e = luna.postfx.newEffect("godrays")
        expect_eq("godrays", e:getEffectType())
    end)

    it("creates vignette effect", function()
        local e = luna.postfx.newEffect("vignette")
        expect_eq("vignette", e:getEffectType())
    end)

    it("creates colourgrade effect", function()
        local e = luna.postfx.newEffect("colourgrade")
        expect_eq("colourgrade", e:getEffectType())
    end)

    it("creates chromatic effect", function()
        local e = luna.postfx.newEffect("chromatic")
        expect_eq("chromatic", e:getEffectType())
    end)

    it("rejects invalid effect type", function()
        expect_error(function()
            luna.postfx.newEffect("invalid_type")
        end)
    end)
end)

describe("luna.postfx.newPass custom effects", function()
    it("creates custom pass", function()
        local p = luna.postfx.newPass(1)
        expect_eq("custom", p:getEffectType())
        expect_eq(false, p:isBuiltIn())
    end)
end)

describe("luna.postfx.getEffectTypes", function()
    it("returns table of 7 types", function()
        local types = luna.postfx.getEffectTypes()
        expect_type("table", types)
        expect_eq(7, #types)
    end)

    it("contains bloom", function()
        local types = luna.postfx.getEffectTypes()
        local found = false
        for _, t in ipairs(types) do
            if t == "bloom" then found = true end
        end
        expect_eq(true, found)
    end)
end)

describe("PostFxEffect parameters", function()
    it("bloom has default threshold", function()
        local bloom = luna.postfx.newEffect("bloom")
        expect_eq(true, bloom:hasParameter("threshold"))
    end)

    it("getParameter returns value", function()
        local bloom = luna.postfx.newEffect("bloom")
        local t = bloom:getParameter("threshold")
        expect_type("number", t)
    end)

    it("setParameter changes value", function()
        local bloom = luna.postfx.newEffect("bloom")
        bloom:setParameter("threshold", 0.5)
        local v = bloom:getParameter("threshold")
        expect_eq(true, math.abs(v - 0.5) < 0.001)
    end)

    it("getParameter uses default for missing", function()
        local bloom = luna.postfx.newEffect("bloom")
        local v = bloom:getParameter("nonexistent", 42.0)
        expect_eq(true, math.abs(v - 42.0) < 0.001)
    end)

    it("getParameterNames returns sorted list", function()
        local bloom = luna.postfx.newEffect("bloom")
        local names = bloom:getParameterNames()
        expect_type("table", names)
        expect_eq(true, #names >= 2)
    end)
end)

describe("PostFxEffect convenience setters", function()
    it("setThreshold works", function()
        local bloom = luna.postfx.newEffect("bloom")
        expect_no_error(function() bloom:setThreshold(0.8) end)
        expect_eq(true, math.abs(bloom:getParameter("threshold") - 0.8) < 0.001)
    end)

    it("setIntensity works", function()
        local bloom = luna.postfx.newEffect("bloom")
        expect_no_error(function() bloom:setIntensity(2.0) end)
        expect_eq(true, math.abs(bloom:getParameter("intensity") - 2.0) < 0.001)
    end)

    it("setRadius works on blur", function()
        local blur = luna.postfx.newEffect("blur")
        expect_no_error(function() blur:setRadius(5.0) end)
        expect_eq(true, math.abs(blur:getParameter("radius") - 5.0) < 0.001)
    end)

    it("setStrength works on vignette", function()
        local vig = luna.postfx.newEffect("vignette")
        expect_no_error(function() vig:setStrength(0.8) end)
        expect_eq(true, math.abs(vig:getParameter("strength") - 0.8) < 0.001)
    end)

    it("setScanlineStrength works on crt", function()
        local crt = luna.postfx.newEffect("crt")
        expect_no_error(function() crt:setScanlineStrength(0.4) end)
        expect_eq(true, math.abs(crt:getParameter("scanline_strength") - 0.4) < 0.001)
    end)

    it("setOffset works on chromatic", function()
        local chr = luna.postfx.newEffect("chromatic")
        expect_no_error(function() chr:setOffset(3.0) end)
        expect_eq(true, math.abs(chr:getParameter("offset") - 3.0) < 0.001)
    end)

    it("setBrightness works on colourgrade", function()
        local cg = luna.postfx.newEffect("colourgrade")
        expect_no_error(function() cg:setBrightness(1.5) end)
        expect_eq(true, math.abs(cg:getParameter("brightness") - 1.5) < 0.001)
    end)

    it("setContrast works on colourgrade", function()
        local cg = luna.postfx.newEffect("colourgrade")
        expect_no_error(function() cg:setContrast(0.9) end)
        expect_eq(true, math.abs(cg:getParameter("contrast") - 0.9) < 0.001)
    end)

    it("setSaturation works on colourgrade", function()
        local cg = luna.postfx.newEffect("colourgrade")
        expect_no_error(function() cg:setSaturation(0.7) end)
        expect_eq(true, math.abs(cg:getParameter("saturation") - 0.7) < 0.001)
    end)
end)

describe("PostFxEffect enable/disable", function()
    it("is enabled by default", function()
        local bloom = luna.postfx.newEffect("bloom")
        expect_eq(true, bloom:isEnabled())
    end)

    it("setEnabled false", function()
        local bloom = luna.postfx.newEffect("bloom")
        bloom:setEnabled(false)
        expect_eq(false, bloom:isEnabled())
    end)

    it("setEnabled true after false", function()
        local bloom = luna.postfx.newEffect("bloom")
        bloom:setEnabled(false)
        bloom:setEnabled(true)
        expect_eq(true, bloom:isEnabled())
    end)
end)

describe("PostFxEffect type() method", function()
    it("returns PostFxEffect", function()
        local bloom = luna.postfx.newEffect("bloom")
        expect_eq("PostFxEffect", bloom:type())
    end)

    it("custom pass also returns PostFxEffect", function()
        local pass = luna.postfx.newPass(1)
        expect_eq("PostFxEffect", pass:type())
    end)
end)

describe("luna.postfx.newStack", function()
    it("creates stack with default dimensions", function()
        local stack = luna.postfx.newStack()
        expect_eq(800, stack:getWidth())
        expect_eq(600, stack:getHeight())
    end)

    it("creates stack with custom dimensions", function()
        local stack = luna.postfx.newStack(1920, 1080)
        expect_eq(1920, stack:getWidth())
        expect_eq(1080, stack:getHeight())
    end)

    it("starts empty", function()
        local stack = luna.postfx.newStack()
        expect_eq(0, stack:getEffectCount())
    end)

    it("type is PostFxStack", function()
        local stack = luna.postfx.newStack()
        expect_eq("PostFxStack", stack:type())
    end)
end)

describe("PostFxStack add/remove", function()
    it("add increases count", function()
        local stack = luna.postfx.newStack()
        local bloom = luna.postfx.newEffect("bloom")
        stack:add(bloom)
        expect_eq(1, stack:getEffectCount())
    end)

    it("add multiple effects", function()
        local stack = luna.postfx.newStack()
        stack:add(luna.postfx.newEffect("bloom"))
        stack:add(luna.postfx.newEffect("blur"))
        stack:add(luna.postfx.newEffect("crt"))
        expect_eq(3, stack:getEffectCount())
    end)

    it("remove decreases count", function()
        local stack = luna.postfx.newStack()
        local bloom = luna.postfx.newEffect("bloom")
        stack:add(bloom)
        stack:remove(bloom)
        expect_eq(0, stack:getEffectCount())
    end)
end)

describe("PostFxStack insert", function()
    it("insert at position 1", function()
        local stack = luna.postfx.newStack()
        local bloom = luna.postfx.newEffect("bloom")
        local blur = luna.postfx.newEffect("blur")
        stack:add(bloom)
        stack:insert(1, blur)
        expect_eq(2, stack:getEffectCount())
        -- blur should be at position 1, bloom at position 2
        local e1 = stack:getEffect(1)
        expect_eq("blur", e1:getEffectType())
    end)
end)

describe("PostFxStack dimensions", function()
    it("getDimensions returns both", function()
        local stack = luna.postfx.newStack(800, 600)
        local w, h = stack:getDimensions()
        expect_eq(800, w)
        expect_eq(600, h)
    end)

    it("resize changes dimensions", function()
        local stack = luna.postfx.newStack(800, 600)
        stack:resize(1920, 1080)
        expect_eq(1920, stack:getWidth())
        expect_eq(1080, stack:getHeight())
    end)
end)

describe("PostFxStack capturing state", function()
    it("not capturing by default", function()
        local stack = luna.postfx.newStack()
        expect_eq(false, stack:isCapturing())
    end)
end)
