-- Lurek2D Validation Test: Invalid API Arguments
-- Tests that API functions handle bad inputs without crashing

describe("validation: physics invalid args", function()
    it("rejects nil world ID", function()
        expect_error(function()
            lurek.physics.step(nil, 0.016)
        end, "nil world ID")
    end)

    it("handles negative dt without crash", function()
        local world_id = lurek.physics.newWorld(0, 100)
        -- Negative dt should not crash
        expect_no_error(function()
            lurek.physics.step(world_id, -1.0)
        end, "negative dt should not crash")
    end)

    it("handles invalid body type string", function()
        local world_id = lurek.physics.newWorld(0, 100)
        -- Engine may accept or coerce invalid types
        expect_no_error(function()
            lurek.physics.newBody(world_id, 0, 0, "invalid_type")
        end, "invalid body type should not crash")
    end)

    it("handles NaN position gracefully", function()
        local world_id = lurek.physics.newWorld(0, 100)
        expect_no_error(function()
            lurek.physics.newBody(world_id, 0/0, 0/0, "dynamic")
        end)
    end)

    it("handles huge velocity without crash", function()
        local world_id = lurek.physics.newWorld(0, 100)
        local body = lurek.physics.newBody(world_id, 0, 0, "dynamic")
        expect_no_error(function()
            lurek.physics.setBodyVelocity(world_id, body, 1e10, 1e10)
            lurek.physics.step(world_id, 0.016)
        end, "huge velocity should not crash")
    end)

    it("handles destroyed world gracefully", function()
        local world_id = lurek.physics.newWorld(0, 100)
        lurek.physics.destroyWorld(world_id)
        -- Operations on destroyed world may not crash
        expect_no_error(function()
            lurek.physics.step(world_id, 0.016)
        end, "step on destroyed world should not crash")
    end)
end)

describe("validation: compute invalid args", function()
    it("rejects zero-dimension array", function()
        expect_error(function()
            lurek.compute.zeros({0}, "float32")
        end, "zero dimension should error")
    end)

    it("rejects negative dimension", function()
        expect_error(function()
            lurek.compute.zeros({-5}, "float32")
        end, "negative dimension should error")
    end)

    it("rejects invalid dtype string", function()
        expect_error(function()
            lurek.compute.zeros({10}, "invalid_type")
        end, "invalid dtype should error")
    end)

    it("rejects too many dimensions", function()
        expect_error(function()
            lurek.compute.zeros({2, 3, 4, 5}, "float32")
        end, "4D should error")
    end)
end)

describe("validation: dataframe invalid ops", function()
    it("rejects removing nonexistent column", function()
        local df = lurek.dataframe.newDataFrame()
        df:addColumn("real", 0)
        expect_error(function()
            df:removeColumn("nonexistent")
        end, "remove nonexistent column should error")
    end)

    it("rejects out-of-range row access", function()
        local df = lurek.dataframe.newDataFrame()
        df:addColumn("val", 0)
        df:addRow({val = 1})
        expect_error(function()
            df:getValue(999, "val")
        end, "out of range row should error")
    end)

    it("rejects duplicate column names", function()
        local df = lurek.dataframe.newDataFrame()
        df:addColumn("name", "")
        expect_error(function()
            df:addColumn("name", "")
        end, "duplicate column should error")
    end)
end)

describe("validation: graph invalid operations", function()
    it("rejects edge with invalid node", function()
        local g = lurek.graph.newGraph()
        local n1 = g:addNode("processor", 100)
        -- Passing a number instead of node userdata should error
        expect_error(function()
            g:addEdge(n1, 999)
        end, "edge to invalid node should error")
    end)

    it("accepts negative capacity", function()
        local g = lurek.graph.newGraph()
        expect_no_error(function()
            g:addNode("processor", -1)
        end)
    end)
end)

describe("validation: entity invalid operations", function()
    it("handles kill of nonexistent entity", function()
        local universe = lurek.entity.newUniverse()
        expect_no_error(function()
            universe:kill(99999)
        end, "kill nonexistent should not crash")
    end)

    it("handles get on dead entity", function()
        local universe = lurek.entity.newUniverse()
        local id = universe:spawn()
        universe:kill(id)
        expect_false(universe:isAlive(id), "dead entity is not alive")
    end)

    it("handles set on dead entity", function()
        local universe = lurek.entity.newUniverse()
        local id = universe:spawn()
        universe:kill(id)
        expect_error(function()
            universe:set(id, "comp", 42)
        end, "set on dead entity should error")
    end)
end)

describe("validation: image invalid operations", function()
    it("handles zero-size image gracefully", function()
        -- Engine may accept zero-size image without error
        expect_no_error(function()
            lurek.img.newImageData(0, 0)
        end, "zero size image should not crash")
    end)

    it("rejects loading nonexistent file", function()
        expect_error(function()
            lurek.img.newImageData("nonexistent_file.png")
        end, "nonexistent file should error")
    end)
end)

describe("validation: tilemap invalid operations", function()
    it("handles out-of-bounds tile access", function()
        local map = lurek.tilemap.newTileMap(32, 32, 16)
        local ts = lurek.tilemap.newTileSet(1, 16, 4, 32, 32, 0, 0)
        map:addTileSet(ts)
        map:addLayer("ground", 10, 10)
        -- Out of bounds should return 0 or error, not crash
        expect_no_error(function()
            local tile = map:getTile(1, 999, 999)
        end, "out of bounds tile access should not crash")
    end)
end)
