-- Lurek2D Security Test: API Fuzz / Nil Spam
-- Tests that core APIs handle nil, wrong types, and edge cases gracefully
-- @security nil-spam
-- @security type-confusion

describe("fuzz: nil arguments to core APIs", function()
    it("lurek.gfx.setColor handles nil gracefully", function()
        expect_error(function()
            lurek.gfx.setColor(nil, nil, nil)
        end)
    end)

    it("lurek.gfx.rectangle handles nil gracefully", function()
        expect_error(function()
            lurek.gfx.rectangle(nil, nil, nil, nil, nil)
        end)
    end)

    it("lurek.gfx.circle handles nil gracefully", function()
        expect_error(function()
            lurek.gfx.circle(nil, nil, nil, nil)
        end)
    end)

    it("lurek.gfx.line handles nil gracefully", function()
        expect_error(function()
            lurek.gfx.line(nil, nil, nil, nil)
        end)
    end)
end)

describe("fuzz: wrong types to physics", function()
    it("lurek.physics.newWorld rejects string gravity", function()
        expect_error(function()
            lurek.physics.newWorld("hello", "world")
        end)
    end)

    it("lurek.physics.newBody rejects nil world", function()
        expect_error(function()
            lurek.physics.newBody(nil, 0, 0, "dynamic")
        end)
    end)

    it("lurek.physics.step rejects nil world", function()
        expect_error(function()
            lurek.physics.step(nil, 0.016)
        end)
    end)

    it("lurek.physics.step rejects string dt", function()
        local world = lurek.physics.newWorld(0, 10)
        expect_error(function()
            lurek.physics.step(world, "not_a_number")
        end)
        lurek.physics.destroyWorld(world)
    end)
end)

describe("fuzz: wrong types to entity system", function()
    it("universe:set with nil entity id", function()
        local universe = lurek.entity.newUniverse()
        expect_error(function()
            universe:set(nil, "key", "value")
        end)
    end)

    it("universe:get with nil entity id", function()
        local universe = lurek.entity.newUniverse()
        expect_error(function()
            universe:get(nil, "key")
        end)
    end)

    it("universe:kill with nil entity id", function()
        local universe = lurek.entity.newUniverse()
        expect_error(function()
            universe:kill(nil)
        end)
    end)

    it("universe:isAlive with nil entity id", function()
        local universe = lurek.entity.newUniverse()
        expect_error(function()
            universe:isAlive(nil)
        end)
    end)
end)

describe("fuzz: wrong types to data module", function()
    it("lurek.data.encode rejects nil format", function()
        expect_error(function()
            lurek.data.encode(nil, { a = 1 })
        end)
    end)

    it("lurek.data.decode rejects nil format", function()
        expect_error(function()
            lurek.data.decode(nil, "{}")
        end)
    end)

    it("lurek.data.decode rejects malformed JSON", function()
        expect_error(function()
            lurek.data.decode("json", "{{{{not json!!!")
        end)
    end)

    it("lurek.data.compress rejects nil", function()
        expect_error(function()
            lurek.data.compress(nil)
        end)
    end)

    it("lurek.data.decompress rejects garbage", function()
        expect_error(function()
            lurek.data.decompress("not compressed data at all!!")
        end)
    end)
end)

describe("fuzz: wrong types to AI module", function()
    it("fsm:addState with nil name", function()
        local fsm = lurek.ai.newStateMachine()
        expect_error(function()
            fsm:addState(nil, { onUpdate = function() end })
        end)
    end)

    it("fsm:forceState with non-existent state", function()
        local fsm = lurek.ai.newStateMachine()
        fsm:addState("idle", { onUpdate = function() end })
        expect_error(function()
            fsm:forceState("nonexistent_state_xyz")
        end)
    end)
end)

describe("fuzz: wrong types to math module", function()
    it("Vec2 rejects string args", function()
        expect_error(function()
            lurek.math.Vec2("hello", "world")
        end)
    end)

    it("sin rejects nil", function()
        expect_error(function()
            lurek.math.sin(nil)
        end)
    end)

    it("lerp rejects nil", function()
        expect_error(function()
            lurek.math.lerp(nil, nil, nil)
        end)
    end)
end)

describe("fuzz: wrong types to audio module", function()
    it("setMasterVolume rejects string", function()
        expect_error(function()
            lurek.audio.setMasterVolume("loud")
        end)
    end)

    it("setMasterVolume rejects nil", function()
        expect_error(function()
            lurek.audio.setMasterVolume(nil)
        end)
    end)
end)

describe("fuzz: edge case numbers", function()
    it("math handles very large numbers", function()
        expect_no_error(function()
            lurek.math.sin(1e15)
            lurek.math.cos(1e15)
        end)
    end)

    it("math handles very small numbers", function()
        expect_no_error(function()
            lurek.math.sin(1e-15)
            lurek.math.cos(1e-15)
        end)
    end)

    it("math handles negative zero", function()
        expect_no_error(function()
            lurek.math.sin(-0.0)
            lurek.math.sqrt(0.0)
        end)
    end)

    it("Vec2 handles inf", function()
        -- Should not crash even with inf
        expect_no_error(function()
            local v = lurek.math.Vec2(1/0, 0)
        end)
    end)
end)

test_summary()
