#!/usr/bin/env python3
#!/usr/bin/env python3
"""
count_gaps.py — Count undocumented public API items per lurek.* module.

Reads docs/reports/coverage_gaps.md (generated by gen_coverage_gaps.py) and
prints a ranked breakdown of how many missing-doc items each lurek.* module
owns. Useful for prioritising docstring-writing sprints.

Usage:
    python tools/audit/count_gaps.py                # prints module gap counts
"""
import re
from collections import Counter
from pathlib import Path

c = Path("docs/reports/coverage_gaps.md").read_text(encoding="utf-8")
mods = Counter()
for line in c.splitlines():
    line = line.strip()
    m = re.match(r"\| (lurek\.\w+)\.\w+", line)
    if m:
        mods[m.group(1)] += 1

total = sum(mods.values())
print(f"Total Section 3 items: {total}")
print()
for mod, cnt in mods.most_common(30):
    print(f"  {mod}: {cnt}")
