#!/usr/bin/env python3
"""
gen_lua_contract_tests.py — generate Lua contract smoke tests from lua_api_data.json.

Generates a single file under tests/lua/unit/ that verifies the existence of
top-level lurek.* functions from the canonical API metadata.
"""

from __future__ import annotations

import json
from pathlib import Path

WORKSPACE_ROOT = Path(__file__).resolve().parent.parent.parent
API_DATA = WORKSPACE_ROOT / "logs" / "data" / "lua_api_data.json"
OUT_FILE = WORKSPACE_ROOT / "tests" / "lua" / "unit" / "test_lua_contract_generated_unit.lua"


def load_functions() -> list[str]:
    data = json.loads(API_DATA.read_text(encoding="utf-8"))
    modules = data.get("lua_api", {}).get("modules", {})
    names: list[str] = []

    for _, mod in sorted(modules.items()):
        for fn in mod.get("functions", []):
            lua_name = fn.get("lua_name", "")
            if lua_name.startswith("lurek."):
                names.append(lua_name)

    return sorted(set(names))


def emit(names: list[str]) -> str:
    lines: list[str] = []
    lines.append("-- Auto-generated by tools/audit/gen_lua_contract_tests.py")
    lines.append("-- Do not edit manually.")
    lines.append("")
    lines.append("-- @describe generated: top-level lurek contract")
    lines.append("describe(\"generated: top-level lurek contract\", function()")

    for name in names:
        lines.append(f"    -- @covers {name}")
        lines.append(f"    it(\"{name} exists\", function()")
        lines.append(f"        expect_type(\"function\", {name})")
        lines.append("    end)")
        lines.append("")

    lines.append("end)")
    lines.append("")
    lines.append("test_summary()")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    names = load_functions()
    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text(emit(names), encoding="utf-8")
    print(f"[OK] Generated {OUT_FILE}")
    print(f"[INFO] Functions covered: {len(names)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
