-- content/examples/collision.lua
-- Lurek2D lurek.collision API Reference
-- Run with: cargo run -- content/examples/collision

-- =============================================================================
-- STUBS: 4 uncovered lurek.collision API item(s)
-- Generated by tools/audit/example_add_missing.py
-- REQUIRED: replace every --@api-stub: block below with a real scenario.
-- Run .github/prompts/flesh-out-example.prompt.md for instructions.
-- The final committed file must contain ZERO --@api-stub: lines.
-- =============================================================================

-- ---- Stub: lurek.collision.testAABB --------------------------------------
--@api-stub: lurek.collision.testAABB
-- Use each frame to test whether a projectile's bounding box overlaps an enemy.
-- Both boxes are defined as top-left corner + width + height.
local playerX, playerY, playerW, playerH = 10, 10, 32, 32
local wallX,   wallY,   wallW,   wallH   = 30, 30, 64, 16

local touching = lurek.collision.testAABB(
  playerX, playerY, playerW, playerH,
  wallX,   wallY,   wallW,   wallH
)
print("Player touches wall:", touching)  -- true: overlapping rectangles

local farBox = lurek.collision.testAABB(0, 0, 10, 10, 200, 200, 10, 10)
print("Far boxes overlap:", farBox)      -- false

-- ---- Stub: lurek.collision.testCircles -----------------------------------
--@api-stub: lurek.collision.testCircles
-- Use for coin pickups or soft-body overlap where AABB would be too aggressive
-- at diagonal approach angles.  Takes centre points and radii for both circles.
local bulletX, bulletY, bulletR = 50, 50, 4
local enemyX,  enemyY,  enemyR  = 55, 52, 16

local hit = lurek.collision.testCircles(bulletX, bulletY, bulletR, enemyX, enemyY, enemyR)
print("Bullet hits enemy:", hit)         -- true: radii overlap

local missX, missY = 120, 120
print("Bullet misses far enemy:",
  lurek.collision.testCircles(missX, missY, bulletR, enemyX, enemyY, enemyR))  -- false

-- ---- Stub: lurek.collision.testPoint -------------------------------------
--@api-stub: lurek.collision.testPoint
-- Use for mouse-over UI button detection: feed the cursor position and the
-- button's screen rectangle, no physics world required.
local mouseX, mouseY = 45, 45
local buttonX, buttonY, buttonW, buttonH = 40, 40, 80, 20

local clicked = lurek.collision.testPoint(mouseX, mouseY, buttonX, buttonY, buttonW, buttonH)
print("Mouse clicked button:", clicked)  -- true: point is inside

print("Mouse outside button:",
  lurek.collision.testPoint(200, 200, buttonX, buttonY, buttonW, buttonH))  -- false

-- ---- Stub: lurek.collision.testCircleAABB --------------------------------
--@api-stub: lurek.collision.testCircleAABB
-- Use when an explosion (circle) should damage rectangular crates or wall tiles.
-- The test accounts for the circle reaching into box corners correctly.
local explosionX, explosionY, explosionR = 100, 100, 50
local crateX, crateY, crateW, crateH    = 90, 110, 24, 24

local blasted = lurek.collision.testCircleAABB(
  explosionX, explosionY, explosionR,
  crateX, crateY, crateW, crateH
)
print("Explosion reaches crate:", blasted)  -- true: circle overlaps AABB corner

local safeX, safeY = 300, 300
print("Far crate safe:",
  lurek.collision.testCircleAABB(safeX, safeY, explosionR, crateX, crateY, crateW, crateH))  -- false
