-- content/examples/collision.lua
-- Lurek2D lurek.collision API Reference
-- Run with: cargo run -- content/examples/collision

-- =============================================================================
-- STUBS: 4 uncovered lurek.collision API item(s)
-- Generated by tools/audit/example_add_missing.py
-- REQUIRED: replace every --@api-stub: block below with a real scenario.
-- Run .github/prompts/flesh-out-example.prompt.md for instructions.
-- The final committed file must contain ZERO --@api-stub: lines.
-- =============================================================================

-- ---- Stub: lurek.collision.testAABB --------------------------------------
--@api-stub: lurek.collision.testAABB
-- Returns true when two axis-aligned bounding boxes overlap.
-- TODO: replace this stub with a real scenario. See flesh-out-example.prompt.md
lurek.collision.testAABB(ax, ay, aw, ah, bx, by, bw, bh)  -- -> boolean

-- ---- Stub: lurek.collision.testCircles -----------------------------------
--@api-stub: lurek.collision.testCircles
-- Returns true when two circles overlap.
-- TODO: replace this stub with a real scenario. See flesh-out-example.prompt.md
lurek.collision.testCircles(ax, ay, ar, bx, by, br)  -- -> boolean

-- ---- Stub: lurek.collision.testPoint -------------------------------------
--@api-stub: lurek.collision.testPoint
-- Returns true when point (px, py) lies inside the AABB.
-- TODO: replace this stub with a real scenario. See flesh-out-example.prompt.md
lurek.collision.testPoint(px, py, ax, ay, aw, ah)  -- -> boolean

-- ---- Stub: lurek.collision.testCircleAABB --------------------------------
--@api-stub: lurek.collision.testCircleAABB
-- Returns true when a circle overlaps an AABB.
-- TODO: replace this stub with a real scenario. See flesh-out-example.prompt.md
lurek.collision.testCircleAABB(cx, cy, cr, ax, ay, aw, ah)  -- -> boolean
