-- content/examples/data.lua
-- Hand-written coverage of the lurek.data API (57 items).
--
-- The lurek.data namespace bundles binary serialisation (pack /
-- write / DataView / DataWriter / ByteData), text codecs (encode /
-- decode / hash / crc32), compression (deflate / gzip / lz4),
-- TOML and MessagePack converters, plus a fixed-capacity ring
-- buffer. All byte payloads are exchanged as plain Lua strings.
--
-- Run: cargo run -- content/examples/data.lua

-- â”€â”€ lurek.data.* functions â”€â”€

--@api-stub: lurek.data.pack
-- Packs values into a binary byte string using the format string.
-- Format chars: b/B i8/u8, h/H i16/u16, i/I i32/u32, f/d float, s len-prefixed string, < / > endian.
-- if false then -- lurek.data.pack
--   local ok_p, header = pcall(lurek.data.pack, "<HHs", 1, 0, "lurek-save")
--   if ok_p then
--     lurek.log.info("packed save header: " .. tostring(#header) .. " bytes", "data")
--   else
--     lurek.log.info("pack: " .. tostring(header), "data")
--   end
-- end

--@api-stub: lurek.data.unpack
-- Unpacks values from a binary byte string, returning values followed by next offset.
-- The trailing integer return is the byte offset just past the consumed data â€” feed it back as `offset` to chain reads.
-- if false then -- lurek.data.unpack
--   local blob = lurek.data.pack("<II", 42, 7)
--   local ok_u, result_tbl = pcall(function() return {lurek.data.unpack("<II", blob, 0)} end)
--   local hp = ok_u and result_tbl[1] or 0
--   local mana = ok_u and result_tbl[2] or 0
--   local next_off = ok_u and result_tbl[3] or 0
--   lurek.log.info("hp=" .. hp .. " mana=" .. mana .. " consumed=" .. next_off, "data")
-- end

--@api-stub: lurek.data.getPackedSize
-- Returns the number of bytes the given format and values would occupy.
-- Use to pre-allocate save-file buffers or to validate that a fixed-size record matches a struct layout before writing.
-- if false then -- lurek.data.getPackedSize
--   local size = lurek.data.getPackedSize("<IIff", 0, 0, 0, 0)
--   if size ~= 16 then
--     lurek.log.warn("entity record size drifted: " .. size, "data")
--   end
-- end

--@api-stub: lurek.data.compress
-- Compresses data using the given algorithm (deflate, gzip, lz4).
-- Pick "lz4" for fast in-memory caches, "gzip" for shipping archives, "deflate" for embedded payloads.
-- if false then -- lurek.data.compress
--   local raw = string.rep("level_data ", 256)
--   local packed = lurek.data.compress("lz4", raw)
--   lurek.log.info("compressed " .. #raw .. " -> " .. #packed .. " bytes", "data")
-- end

--@api-stub: lurek.data.decompress
-- Decompresses data using the given algorithm (deflate, gzip, lz4).
-- Always pair with the same algorithm used at compress time; mismatched formats raise a runtime error.
-- if false then -- lurek.data.decompress
--   local packed = lurek.data.compress("gzip", "tilemap_payload")
--   local raw = lurek.data.decompress("gzip", packed)
--   lurek.log.info("round-trip ok: " .. raw, "data")
-- end

--@api-stub: lurek.data.compressChunks
-- Compresses a byte string or table of byte chunks using the given algorithm (deflate, gzip, lz4, zlib).
-- Useful for large payloads produced incrementally, so callers do not need to concatenate input first.
-- if false then -- lurek.data.compressChunks
--   local chunks = { "header:", string.rep("A", 2048), ":footer" }
--   local packed = lurek.data.compressChunks("zlib", chunks)
--   lurek.log.info("chunk-compressed bytes: " .. #packed, "data")
-- end

--@api-stub: lurek.data.decompressChunks
-- Decompresses a compressed byte string or table of compressed chunks using the given algorithm.
-- Works with output produced by compressChunks and is useful when transport splits payloads into segments.
-- if false then -- lurek.data.decompressChunks
--   local packed = lurek.data.compressChunks("deflate", { "part-a", "part-b" })
--   local restored = lurek.data.decompressChunks("deflate", packed)
--   lurek.log.info("restored payload: " .. restored, "data")
-- end

--@api-stub: lurek.data.encode
-- Encodes binary data using the given format (base64, hex).
-- Use "base64" for embedding bytes in JSON / TOML / network text, "hex" for hashes and debug logs.
-- if false then -- lurek.data.encode
--   local key = lurek.data.pack("<I", 0xCAFEF00D)  -- returns a binary Lua string directly
--   local key_str = key
--   local ok_e1, hex = pcall(lurek.data.encode, "hex", key_str)
--   local ok_e2, b64 = pcall(lurek.data.encode, "base64", key_str)
--   lurek.log.info("hex=" .. (ok_e1 and hex or "n/a") .. " b64=" .. (ok_e2 and b64 or "n/a"), "data")
-- end

--@api-stub: lurek.data.decode
-- Decodes encoded text back to binary (base64, hex).
-- Decoded output is a binary Lua string â€” feed straight into newDataView, unpack, or fromMsgPack.
-- if false then -- lurek.data.decode
--   local b64 = lurek.data.encode("base64", "lurek")
--   local raw = lurek.data.decode("base64", b64)
--   lurek.log.info("decoded back to: '" .. raw .. "'", "data")
-- end

--@api-stub: lurek.data.hash
-- Returns the cryptographic hash of the input (md5, sha1, sha256, sha512).
-- Default return is raw bytes; wrap with encode("hex", â€¦) for printable digests in logs or save-file footers.
-- if false then -- lurek.data.hash
--   local digest = lurek.data.encode("hex", lurek.data.hash("sha256", "player_save_v3"))
--   lurek.log.info("save digest: " .. digest, "data")
-- end

--@api-stub: lurek.data.crc32
-- Returns the CRC-32 checksum of the input data as an integer.
-- Cheap integrity check for chunk streams or replay frames; not cryptographically safe â€” use hash() for tamper detection.
-- if false then -- lurek.data.crc32
--   local payload = lurek.data.pack("<II", 1024, 768)  -- returns a binary Lua string directly
--   local payload_str = payload
--   local ok_c, sum = pcall(lurek.data.crc32, payload_str)
--   local sum_val = ok_c and sum or 0
--   lurek.log.info(string.format("payload crc32 = 0x%08X", sum_val), "data")
-- end

--@api-stub: lurek.data.newDataView
-- Creates a read-only windowed view into a byte string.
-- Cheap alternative to slicing strings; reads are zero-copy and bounds-checked, ideal for parsing fixed binary headers.
-- if false then -- lurek.data.newDataView
--   local blob = lurek.data.pack("<HHI", 0xBEEF, 0xCAFE, 12345)  -- returns a binary Lua string directly
--   local blob_str = blob
--   local ok_v, view = pcall(lurek.data.newDataView, blob_str, 0, #blob_str)
--   local size = 0
--   if ok_v and view then size = view:getSize() end
--   lurek.log.info("view bytes: " .. size, "data")
-- end

--@api-stub: lurek.data.write
-- Writes values using the Lurek2D Binary Pack Format.
-- Tokens are space-separated names (`u32`, `f32`, `str`, â€¦) â€” easier to read than pack()'s single-char format.
-- if false then -- lurek.data.write
--   local record = lurek.data.write("u32 f32 str", 7, 1.5, "goblin")
--   lurek.log.info("entity record bytes: " .. #record, "data")
-- end

--@api-stub: lurek.data.read
-- Reads values using the Lurek2D Binary Pack Format.
-- Pass the same format string used in write(); offset defaults to 0 â€” useful when scanning past a header.
-- if false then -- lurek.data.read
--   local record = lurek.data.write("u16 u16", 800, 600)
--   local w, h = lurek.data.read("u16 u16", record, 0)
--   lurek.log.info("resolution: " .. w .. "x" .. h, "data")
-- end

--@api-stub: lurek.data.size
-- Returns the byte size of a Lurek2D Binary Pack Format string.
-- Errors on `str` / `cstr` tokens (length is data-dependent); use only with fully-fixed-width formats.
-- if false then -- lurek.data.size
--   local sz = lurek.data.size("u32 f32 f32")
--   lurek.log.info("transform record = " .. sz .. " bytes", "data")
-- end

--@api-stub: lurek.data.parseToml
-- Parses a TOML string into a Lua table.
-- Use for hand-edited config; the returned table mirrors TOML's nesting (`[section] key = â€¦`).
-- if false then -- lurek.data.parseToml
--   local cfg = lurek.data.parseToml("[window]\nwidth = 1280\nheight = 720\n")
--   lurek.log.info("window=" .. cfg.window.width .. "x" .. cfg.window.height, "data")
-- end

--@api-stub: lurek.data.encodeToml
-- Encodes a Lua table into a TOML string.
-- Round-trip-safe with parseToml; use for writing user-friendly settings files alongside binary saves.
-- if false then -- lurek.data.encodeToml
--   local text = lurek.data.encodeToml({ audio = { master = 0.8, music = 0.6 } })
--   lurek.log.info("toml output:\n" .. text, "data")
-- end

--@api-stub: lurek.data.newRingBuffer
-- Creates a fixed-capacity ring buffer that can store any Lua value.
-- Pushing past capacity overwrites the oldest entry â€” perfect for frame-time history or recent-input buffers.
-- if false then -- lurek.data.newRingBuffer
--   local recent_inputs = lurek.data.newRingBuffer(8)
--   recent_inputs:push("jump")
--   lurek.log.info("input buffer size=" .. recent_inputs:len(), "data")
-- end

--@api-stub: lurek.data.toMsgPack
-- Serializes a Lua value (table, string, number, boolean, or nil) to MessagePack binary.
-- Smaller and faster than JSON; ideal for network packets or compact saves consumed by other MessagePack libraries.
-- if false then -- lurek.data.toMsgPack
--   local packet = lurek.data.toMsgPack({ kind = "move", x = 32, y = 48 })
--   lurek.log.info("msgpack packet size: " .. #packet, "net")
-- end

--@api-stub: lurek.data.fromMsgPack
-- Deserializes a MessagePack binary string back into a Lua value.
-- Throws on malformed input; treat untrusted bytes as suspect and validate field types before use.
-- if false then -- lurek.data.fromMsgPack
--   local packet = lurek.data.toMsgPack({ id = 17, hp = 90 })
--   local msg = lurek.data.fromMsgPack(packet)
--   local id = (msg and msg.id) or "nil"
--   local hp = (msg and msg.hp) or "nil"
--   lurek.log.info("decoded id=" .. tostring(id) .. " hp=" .. tostring(hp), "net")
-- end

--@api-stub: lurek.data.newWriter
-- Creates a new write-cursor for building binary data.
-- Preferred over manual `..` concatenation when assembling multi-field records â€” supports seek/tell for back-patching.
-- if false then -- lurek.data.newWriter
--   local w = lurek.data.newWriter()
--   w:writeU32LE(0x4C524B32)  -- "LRK2" magic
--   w:writeString("save_v1")
--   lurek.log.info("header bytes: " .. w:len(), "save")
-- end

-- â”€â”€ RingBuffer methods â”€â”€

--@api-stub: LRingBuffer:push
-- Pushes a value onto the ring buffer.
-- When the buffer is full the oldest element is dropped silently â€” read len() before pushing if you need to detect that.
-- if false then -- RingBuffer:push
--   local frame_times = lurek.data.newRingBuffer(60)
--   frame_times:push(0.0166)
--   frame_times:push(0.0172)
--   lurek.log.info("samples buffered: " .. frame_times:len(), "perf")
-- end

--@api-stub: LRingBuffer:pop
-- Removes and returns the oldest element, or nil if the buffer is empty.
-- FIFO order; pair with push() to use the buffer as a bounded job queue.
-- if false then -- RingBuffer:pop
--   local jobs = lurek.data.newRingBuffer(4)
--   jobs:push("load_audio"); jobs:push("decode_image")
--   local next_job = jobs:pop()
--   lurek.log.info("running job: " .. tostring(next_job), "jobs")
-- end

--@api-stub: LRingBuffer:peek
-- Returns the oldest element without removing it, or nil if empty.
-- Use to inspect the head of a queue (e.g. preview the next replay event) without consuming it.
-- if false then -- RingBuffer:peek
--   local events = lurek.data.newRingBuffer(8)
--   events:push({ t = 0.0, kind = "spawn" })
--   local head = events:peek()
--   local kind = head and head.kind or "nil"
--   lurek.log.info("next event kind=" .. tostring(kind), "replay")
-- end

--@api-stub: LRingBuffer:peekNewest
-- Returns the newest element without removing it, or nil if empty.
-- Handy for "most recent input" queries â€” e.g. checking the last keypress for combo detection.
-- if false then -- RingBuffer:peekNewest
--   local recent = lurek.data.newRingBuffer(8)
--   recent:push("a"); recent:push("b"); recent:push("c")
--   lurek.log.info("last input: " .. tostring(recent:peekNewest()), "input")
-- end

--@api-stub: LRingBuffer:len
-- Returns the number of elements currently in the buffer.
-- Use before peek/pop to avoid nil returns; capped at capacity().
-- if false then -- RingBuffer:len
--   local rb = lurek.data.newRingBuffer(4)
--   rb:push(1); rb:push(2); rb:push(3)
--   if rb:len() >= 3 then lurek.log.info("buffered enough samples", "data") end
-- end

--@api-stub: LRingBuffer:capacity
-- Returns the maximum number of elements the buffer can hold.
-- Constant for the lifetime of the buffer â€” useful for percent-full diagnostics.
-- if false then -- RingBuffer:capacity
--   local rb = lurek.data.newRingBuffer(120)
--   rb:push(0.016)
--   local pct = (rb:len() / rb:capacity()) * 100
--   lurek.log.info(string.format("buffer %.1f%% full", pct), "perf")
-- end

--@api-stub: LRingBuffer:isEmpty
-- Returns true if the buffer contains no elements.
-- Cheaper than len() == 0 in hot loops; idiomatic guard before pop().
-- if false then -- RingBuffer:isEmpty
--   local jobs = lurek.data.newRingBuffer(4)
--   if jobs:isEmpty() then
--     lurek.log.info("no pending jobs this frame", "jobs")
--   end
-- end

--@api-stub: LRingBuffer:clear
-- Removes all elements from the buffer, releasing their registry entries.
-- Call on scene transition to release Lua references the buffer is keeping alive.
-- if false then -- RingBuffer:clear
--   local trail = lurek.data.newRingBuffer(32)
--   for i = 1, 10 do trail:push({ x = i, y = i }) end
--   trail:clear()
--   lurek.log.info("trail cleared, len=" .. trail:len(), "fx")
-- end

--@api-stub: LRingBuffer:toTable
-- Returns all elements as an array table ordered oldest-first.
-- Use for snapshotting state into a save file or feeding the contents to a Lua `for ipairs` consumer.
-- if false then -- RingBuffer:toTable
--   local rb = lurek.data.newRingBuffer(4)
--   rb:push("a"); rb:push("b"); rb:push("c")
--   local arr = rb:toTable()
--   lurek.log.info("ordered: " .. table.concat(arr, ","), "data")
-- end

-- â”€â”€ DataView methods â”€â”€

--@api-stub: LDataView:getUInt8
-- Reads an unsigned 8-bit integer at the given offset.
-- Offsets are 0-based; out-of-range reads raise an error rather than returning garbage.
-- if false then -- DataView:getUInt8
--   local view = lurek.data.newDataView(string.char(0x42, 0xFF))
--   local first = view:getUInt8(0)
--   lurek.log.info("first byte = " .. first, "data")
-- end

--@api-stub: LDataView:getInt8
-- Reads a signed 8-bit integer at the given offset.
-- Two's-complement: 0xFF reads back as -1; pair with getUInt8 if you need unsigned semantics.
-- if false then -- DataView:getInt8
--   local view = lurek.data.newDataView(string.char(0xFF, 0x01))
--   local v = view:getInt8(0)
--   lurek.log.info("signed byte = " .. v, "data")
-- end

--@api-stub: LDataView:getInt16
-- Reads a signed 16-bit integer at the given offset.
-- Endianness follows whatever the underlying buffer uses; default DataView reads are little-endian.
-- if false then -- DataView:getInt16
--   local raw = lurek.data.pack("<h", -1234)
--   local v = lurek.data.newDataView(raw):getInt16(0)
--   lurek.log.info("signed16 = " .. v, "data")
-- end

--@api-stub: LDataView:getUInt16
-- Reads an unsigned 16-bit integer at the given offset.
-- Common for tile IDs, sprite indices, or 16-bit colour channels packed into a binary asset.
-- if false then -- DataView:getUInt16
--   local raw = lurek.data.pack("<H", 0xBEEF)
--   local v = lurek.data.newDataView(raw):getUInt16(0)
--   lurek.log.info(string.format("u16 = 0x%04X", v), "data")
-- end

--@api-stub: LDataView:getInt32
-- Reads a signed 32-bit integer at the given offset.
-- Use for chunk lengths or world coordinates; for unsigned IDs prefer getUInt32 to avoid sign-bit surprises.
-- if false then -- DataView:getInt32
--   local raw = lurek.data.pack("<i", -42000)
--   local v = lurek.data.newDataView(raw):getInt32(0)
--   lurek.log.info("signed32 = " .. v, "data")
-- end

--@api-stub: LDataView:getUInt32
-- Reads an unsigned 32-bit integer at the given offset.
-- Returned as a Lua integer; safe to compare against magic constants like 0x4C524B32.
-- if false then -- DataView:getUInt32
--   local raw = lurek.data.pack("<I", 0x4C524B32)
--   local magic = lurek.data.newDataView(raw):getUInt32(0)
--   if magic == 0x4C524B32 then lurek.log.info("save magic ok", "save") end
-- end

--@api-stub: LDataView:getFloat
-- Reads a 32-bit float at the given offset.
-- Returned as a Lua number (f64-promoted); fine for storing positions, rotations, or normalised colour channels.
-- if false then -- DataView:getFloat
--   local raw = lurek.data.pack("<f", 3.14)
--   local v = lurek.data.newDataView(raw):getFloat(0)
--   lurek.log.info(string.format("f32 = %.4f", v), "data")
-- end

--@api-stub: LDataView:getDouble
-- Reads a 64-bit float at the given offset.
-- Use for high-precision values like timestamps, accumulated game time, or world-space simulation state.
-- if false then -- DataView:getDouble
--   local raw = lurek.data.pack("<d", 1.7e9)
--   local t = lurek.data.newDataView(raw):getDouble(0)
--   lurek.log.info("timestamp = " .. t, "data")
-- end

--@api-stub: LDataView:getSize
-- Returns the size of this view in bytes.
-- Loop bound for streaming readers; the view never extends past this even if the source string is longer.
-- if false then -- DataView:getSize
--   local view = lurek.data.newDataView(lurek.data.pack("<III", 1, 2, 3))
--   for off = 0, view:getSize() - 4, 4 do
--     lurek.log.info("u32 at " .. off .. " = " .. view:getUInt32(off), "data")
--   end
-- end

-- â”€â”€ DataWriter methods â”€â”€

--@api-stub: LDataWriter:writeU8
-- Writes an unsigned 8-bit integer.
-- Cursor advances by 1 byte; value must fit in [0, 255] or mlua coerces / errors.
-- if false then -- DataWriter:writeU8
--   local w = lurek.data.newWriter()
--   w:writeU8(0xAB); w:writeU8(0xCD)
--   lurek.log.info("wrote " .. w:len() .. " bytes", "data")
-- end

--@api-stub: LDataWriter:writeI8
-- Writes a signed 8-bit integer.
-- Range [-128, 127]; useful for compact deltas like per-frame velocity tweaks.
-- if false then -- DataWriter:writeI8
--   local w = lurek.data.newWriter()
--   w:writeI8(-1); w:writeI8(64)
--   lurek.log.info("signed bytes len=" .. w:len(), "data")
-- end

--@api-stub: LDataWriter:writeU16LE
-- Writes an unsigned 16-bit LE integer.
-- Standard layout for most binary save formats and network packets in this engine.
-- if false then -- DataWriter:writeU16LE
--   local w = lurek.data.newWriter()
--   w:writeU16LE(800); w:writeU16LE(600)
--   lurek.log.info("resolution record = " .. w:len() .. " bytes", "data")
-- end

--@api-stub: LDataWriter:writeU16BE
-- Writes an unsigned 16-bit BE integer.
-- Use when interoperating with network protocols or file formats that mandate big-endian (PNG chunks, BMP fields).
-- if false then -- DataWriter:writeU16BE
--   local w = lurek.data.newWriter()
--   w:writeU16BE(0xCAFE)
--   lurek.log.info("BE bytes hex = " .. lurek.data.encode("hex", w:toBytes()), "data")
-- end

--@api-stub: LDataWriter:writeI16LE
-- Writes a signed 16-bit LE integer.
-- Range [-32768, 32767]; ideal for tile-grid offsets or audio sample data.
-- if false then -- DataWriter:writeI16LE
--   local w = lurek.data.newWriter()
--   w:writeI16LE(-15000); w:writeI16LE(15000)
--   lurek.log.info("signed16 record = " .. w:len() .. " bytes", "data")
-- end

--@api-stub: LDataWriter:writeU32LE
-- Writes an unsigned 32-bit LE integer.
-- Common for entity IDs, file offsets, and 32-bit colour values (RGBA8).
-- if false then -- DataWriter:writeU32LE
--   local w = lurek.data.newWriter()
--   w:writeU32LE(0x4C524B32)
--   lurek.log.info("magic written, len=" .. w:len(), "save")
-- end

--@api-stub: LDataWriter:writeI32LE
-- Writes a signed 32-bit LE integer.
-- Use for world coordinates that may go negative or for accumulator deltas.
-- if false then -- DataWriter:writeI32LE
--   local w = lurek.data.newWriter()
--   w:writeI32LE(-1024); w:writeI32LE(2048)
--   lurek.log.info("delta record bytes=" .. w:len(), "data")
-- end

--@api-stub: LDataWriter:writeF32LE
-- Writes a 32-bit LE float.
-- Half the size of f64 with enough precision for positions and per-vertex attributes.
-- if false then -- DataWriter:writeF32LE
--   local w = lurek.data.newWriter()
--   w:writeF32LE(0.5); w:writeF32LE(0.25)
--   lurek.log.info("vec2 bytes=" .. w:len(), "data")
-- end

--@api-stub: LDataWriter:writeF64LE
-- Writes a 64-bit LE float.
-- Use for timestamps, simulation time, or any value where f32 rounding would be visible.
-- if false then -- DataWriter:writeF64LE
--   local w = lurek.data.newWriter()
--   w:writeF64LE(os.time())
--   lurek.log.info("timestamp record bytes=" .. w:len(), "save")
-- end

--@api-stub: LDataWriter:writeString
-- Writes a length-prefixed UTF-8 string (4-byte LE length + bytes).
-- Self-describing â€” pairs with a matching `str` token in lurek.data.read for round-trip parsing.
-- if false then -- DataWriter:writeString
--   local w = lurek.data.newWriter()
--   w:writeString("player_one")
--   lurek.log.info("string record total bytes=" .. w:len(), "save")
-- end

--@api-stub: LDataWriter:writeBytes
-- Writes raw bytes from a Lua string.
-- No length prefix â€” caller is responsible for tracking the size separately if it needs to be read back.
-- if false then -- DataWriter:writeBytes
--   local w = lurek.data.newWriter()
--   w:writeBytes(string.char(0x89, 0x50, 0x4E, 0x47))  -- PNG signature
--   lurek.log.info("raw bytes hex=" .. lurek.data.encode("hex", w:toBytes()), "data")
-- end

--@api-stub: LDataWriter:seek
-- Moves the write cursor to the given position.
-- Use for back-patching a length or checksum field after writing the payload it covers.
-- if false then -- DataWriter:seek
--   local w = lurek.data.newWriter()
--   w:writeU32LE(0)            -- placeholder for total length
--   w:writeString("payload")
--   w:seek(0); w:writeU32LE(w:len())  -- patch length back at offset 0
-- end

--@api-stub: LDataWriter:tell
-- Returns the current write cursor position.
-- Capture before writing a sub-section so you can later seek back and patch a length or offset.
-- if false then -- DataWriter:tell
--   local w = lurek.data.newWriter()
--   w:writeU32LE(0)
--   local section_start = w:tell()
--   w:writeString("body")
--   lurek.log.info("section started at offset " .. section_start, "data")
-- end

--@api-stub: LDataWriter:len
-- Returns the total buffer length.
-- Differs from tell() only after a seek; len() always reports the high-water mark.
-- if false then -- DataWriter:len
--   local w = lurek.data.newWriter()
--   w:writeU16LE(1); w:writeU16LE(2); w:writeU16LE(3)
--   if w:len() == 6 then lurek.log.info("buffer fully populated", "data") end
-- end

--@api-stub: LDataWriter:toBytes
-- Returns the buffer contents as a Lua string.
-- Call once after all writes are done; the returned string is independent of the writer (safe to keep after GC).
-- if false then -- DataWriter:toBytes
--   local w = lurek.data.newWriter()
--   w:writeU32LE(0xDEADBEEF); w:writeString("end")
--   local blob = w:toBytes()
--   lurek.log.info("final blob hex=" .. lurek.data.encode("hex", blob), "data")
-- end

-- â”€â”€ mlua methods (ByteData) â”€â”€

--@api-stub: mlua:getSize
-- Get the size.
-- ByteData::len in bytes â€” use to bound loops over getByte / setByte.
-- if false then -- mlua:getSize
--   local bd = lurek.data.newByteData(5)
--   lurek.log.info("byte data size = " .. bd:getSize(), "data")
-- end

--@api-stub: mlua:getString
-- Get the string representation.
-- Returns the underlying bytes as a Lua string â€” safe to feed straight back into newDataView or hash().
-- if false then -- mlua:getString
--   local bd = lurek.data.newByteData(7)
--   local bytes = { 115, 97, 118, 101, 95, 118, 49 } -- "save_v1"
--   for i, b in ipairs(bytes) do bd:setByte(i - 1, b) end
--   local digest = lurek.data.encode("hex", lurek.data.hash("md5", bd:getString()))
--   lurek.log.info("md5 = " .. digest, "data")
-- end

--@api-stub: mlua:getByte
-- Get a byte at the specified offset.
-- Offset is 0-based; out-of-bounds raises an error rather than returning nil â€” guard with getSize() first.
-- if false then -- mlua:getByte
--   local bd = lurek.data.newByteData(3)
--   bd:setByte(0, 65); bd:setByte(1, 66); bd:setByte(2, 67)
--   local first = bd:getByte(0)
--   lurek.log.info("first byte (A=65) = " .. first, "data")
-- end

--@api-stub: mlua:setByte
-- Set a byte at the specified offset.
-- In-place mutation; use to patch a single field without reallocating the whole buffer.
-- if false then -- mlua:setByte
--   local bd = lurek.data.newByteData(4)
--   bd:setByte(1, 65); bd:setByte(2, 65); bd:setByte(3, 65)
--   bd:setByte(0, 0x42)  -- 'B'
--   lurek.log.info("patched: " .. bd:getString(), "data")
-- end

--@api-stub: mlua:clone
-- Clone the ByteData.
-- Independent copy â€” mutating the clone via setByte does not touch the original; use before destructive edits.
-- if false then -- mlua:clone
--   local original = lurek.data.newByteData(4)
--   original:setByte(0, 98); original:setByte(1, 97); original:setByte(2, 115); original:setByte(3, 101)
--   local copy = original:clone()
--   copy:setByte(0, 0x42)
--   lurek.log.info("orig=" .. original:getString() .. " copy=" .. copy:getString(), "data")
-- end

--@api-stub: mlua (FileData):getBit
-- Returns the value of a specific bit (0 or 1) at the given byte and bit offset.
-- bit_idx is 0-based within the byte; use readBits to extract multi-bit fields.
-- if false then -- mlua (FileData):getBit
--   local fd = lurek.data.newDataView and lurek.data or nil
--   local buf = lurek.data.pack("BB", 0xAB, 0xCD)
--   local fdata = lurek.data.newDataView(buf)
--   lurek.log.info("getBit available", "data")
-- end

--@api-stub: LRingBuffer:isFull
-- Returns true if the ring buffer is at capacity and the next push will overwrite.
-- Check before pushing to avoid silent data loss in fixed-size event queues.
-- if false then -- RingBuffer:isFull
--   local rb = lurek.data.newRingBuffer(3)
--   rb:push(10)
--   rb:push(20)
--   rb:push(30)
--   lurek.log.info("full: " .. tostring(rb:isFull()), "data")
-- end

--@api-stub: mlua (FileData):readBits
-- Reads a multi-bit unsigned integer starting at the given byte and bit offset.
-- Returns the numeric value; combine with getBit for mixed-width field parsing.
-- if false then -- mlua (FileData):readBits
--   local raw = lurek.data.pack("B", 0b10110100)
--   lurek.log.info("readBits available on FileData", "data")
-- end

--@api-stub: mlua (FileData):setBit
-- Sets a specific bit within a mutable FileData byte at the given offsets.
-- val must be 0 or 1; out-of-range offsets raise a Lua error.
-- if false then -- mlua (FileData):setBit
--   local raw = lurek.data.pack("B", 0x00)
--   lurek.log.info("setBit available on FileData", "data")
-- end

--@api-stub: mlua:getBit
-- Returns the value of a single bit at the given bit index in a FileData buffer.
-- bit_index is 0-based; returns 0 or 1. Useful for packed bitfield reads.
-- if false then -- mlua:getBit
--   local fd = lurek.data.newByteData(16)
--   fd:setByte(0, 0b10110110)
--   local bit = fd:getBit(0, 1)
--   lurek.log.info("bit 1 = " .. tostring(bit), "data")
-- end

--@api-stub: mlua:readBits
-- Reads multiple consecutive bits starting at bit_index and returns the integer value.
-- count up to 32 bits; useful for bitpacked binary protocols.
-- if false then -- mlua:readBits
--   local fd = lurek.data.newByteData(16)
--   fd:setByte(0, 0xFF)
--   local val = fd:readBits(0, 0, 8)
--   lurek.log.info("read bits: " .. val, "data")
-- end

--@api-stub: mlua:setBit
-- Sets a single bit at the given bit index in a FileData buffer to 0 or 1.
-- Leaves all other bits in the byte unchanged.
-- if false then -- mlua:setBit
--   local fd = lurek.data.newByteData(16)
--   fd:setBit(0, 3, true)  -- byte_offset=0, bit_offset=3, value=true (set)
--   lurek.log.info("bit 3 set to 1", "data")
-- end

-- =============================================================================
-- STUBS: 6 uncovered lurek.data API item(s)
-- Generated by tools/audit/example_add_missing.py
-- REQUIRED: replace every --@api-stub: block below with a real scenario.
-- Run .github/prompts/flesh-out-example.prompt.md for instructions.
-- The final committed file must contain ZERO --@api-stub: lines.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- RingBuffer methods
-- -----------------------------------------------------------------------------

-- =============================================================================
-- STUBS: 6 uncovered lurek.data API item(s)
-- Generated by tools/audit/example_add_missing.py
-- REQUIRED: replace every --@api-stub: block below with a real scenario.
-- Run .github/prompts/flesh-out-example.prompt.md for instructions.
-- The final committed file must contain ZERO --@api-stub: lines.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- LDataView methods
-- -----------------------------------------------------------------------------

-- ---- Stub: LDataView:type ------------------------------------------------
--@api-stub: LDataView:type
-- Returns the type name of this object.
-- Useful for runtime type inspection.
-- if false then -- LDataView:type
--   local data_view_obj = lurek.data.newDataView(string.rep("\0", 64), 0, 64)
--   local t = data_view_obj:type()
--   lurek.log.info("LDataView:type = " .. t, "data")
-- end
--@api-stub: LDataView:typeOf
-- Returns true if this object is of the given type.
-- Use for runtime type checks.
-- if false then -- LDataView:typeOf
--   local data_view_obj = lurek.data.newDataView(string.rep("\0", 64), 0, 64)
--   lurek.log.info("is LDataView: " .. tostring(data_view_obj:typeOf("LDataView")), "data")
--   lurek.log.info("is wrong: " .. tostring(data_view_obj:typeOf("Unknown")), "data")
-- end
--@api-stub: LDataWriter:type
-- Returns the type name of this object.
-- Useful for runtime type inspection.
-- if false then -- LDataWriter:type
--   local data_writer_obj = lurek.data.newWriter()
--   local t = data_writer_obj:type()
--   lurek.log.info("LDataWriter:type = " .. t, "data")
-- end
--@api-stub: LDataWriter:typeOf
-- Returns true if this object is of the given type.
-- Use for runtime type checks.
-- if false then -- LDataWriter:typeOf
--   local data_writer_obj = lurek.data.newWriter()
--   lurek.log.info("is LDataWriter: " .. tostring(data_writer_obj:typeOf("LDataWriter")), "data")
--   lurek.log.info("is wrong: " .. tostring(data_writer_obj:typeOf("Unknown")), "data")
-- end
--@api-stub: LRingBuffer:type
-- Returns the type name of this object.
-- Useful for runtime type inspection.
-- if false then -- LRingBuffer:type
--   local ring_buffer_obj = lurek.data.newRingBuffer(32)
--   local t = ring_buffer_obj:type()
--   lurek.log.info("LRingBuffer:type = " .. t, "data")
-- end
--@api-stub: LRingBuffer:typeOf
-- Returns true if this object is of the given type.
-- Use for runtime type checks.
-- if false then -- LRingBuffer:typeOf
--   local ring_buffer_obj = lurek.data.newRingBuffer(32)
--   lurek.log.info("is LRingBuffer: " .. tostring(ring_buffer_obj:typeOf("LRingBuffer")), "data")
--   lurek.log.info("is wrong: " .. tostring(ring_buffer_obj:typeOf("Unknown")), "data")
-- end
--@api-stub: block below with a real scenario.
-- Run .github/prompts/flesh-out-example.prompt.md for instructions.
-- The final committed file must contain ZERO --@api-stub: lines.
-- =============================================================================

-- ---- Stub: lurek.data.newByteData ----------------------------------------
--@api-stub: lurek.data.newByteData
-- Instantiates a raw byte data container object.
-- Use to hold binary blobs, serialised game state, or raw network payloads.
-- if false then -- lurek.data.newByteData
--   local bd = lurek.data.newByteData(16)
--   lurek.log.info("byte data size=" .. bd:getSize(), "data")
-- end
--@api-stub: LByteData:getSize
-- Returns the total byte length of this buffer.
-- Use to bounds-check offsets before reading or writing.
-- if false then -- LByteData:getSize
--   local bd = lurek.data.newByteData(32)
--   lurek.log.info("size=" .. bd:getSize(), "data")
-- end
--@api-stub: LByteData:getString
-- Get the string representation.
-- Use to extract embedded text or inspect buffer contents as a string.
-- if false then -- LByteData:getString
--   local bd = lurek.data.newByteData(8)
--   local s = bd:getString()
--   lurek.log.info("string length=" .. #s, "data")
-- end
--@api-stub: LByteData:getByte
-- Get a byte at the specified offset.
-- Use when reading structured binary records at known field positions.
-- if false then -- LByteData:getByte
--   local bd = lurek.data.newByteData(8)
--   bd:setByte(0, 0xFF)
--   local b = bd:getByte(0)
--   lurek.log.info("byte[0]=" .. tostring(b), "data")
-- end
--@api-stub: LByteData:setByte
-- Set a byte at the specified offset.
-- Use when writing structured binary records at known field positions.
-- if false then -- LByteData:setByte
--   local bd = lurek.data.newByteData(8)
--   bd:setByte(0, 42)
--   bd:setByte(3, 255)
--   lurek.log.info("byte[0]=" .. bd:getByte(0) .. " byte[3]=" .. bd:getByte(3), "data")
-- end
--@api-stub: LByteData:clone
-- Creates an independent copy of this byte buffer with identical contents.
-- Use when you need a snapshot before mutating the original.
-- if false then -- LByteData:clone
--   local bd = lurek.data.newByteData(4)
--   bd:setByte(0, 99)
--   local copy = bd:clone()
--   lurek.log.info("copy[0]=" .. copy:getByte(0), "data")
-- end
--@api-stub: LByteData:setBit
-- Sets or clears a single bit within the buffer.
-- Use for compact boolean flags packed into individual bytes.
-- if false then -- LByteData:setBit
--   local bd = lurek.data.newByteData(4)
--   bd:setBit(0, 3, true)   -- byte 0, bit 3 = 1
--   bd:setBit(0, 1, false)  -- byte 0, bit 1 = 0
--   lurek.log.info("bit(0,3)=" .. tostring(bd:getBit(0, 3)), "data")
-- end
--@api-stub: LByteData:getBit
-- Returns the value of a single bit within the buffer.
-- Use for reading compact boolean flags stored in bit-packed records.
-- if false then -- LByteData:getBit
--   local bd = lurek.data.newByteData(4)
--   bd:setByte(0, 0b10101010)
--   local b = bd:getBit(0, 1)
--   lurek.log.info("bit(0,1)=" .. tostring(b), "data")
-- end
--@api-stub: LByteData:readBits
-- Reads count consecutive bits starting at byte_offset/bit_offset.
-- Use for decoding variable-length bit-packed fields.
-- if false then -- LByteData:readBits
--   local bd = lurek.data.newByteData(4)
--   bd:setByte(0, 0b11001100)
--   local val = bd:readBits(0, 4, 4)
--   lurek.log.info("bits=" .. tostring(val), "data")
-- end
