-- content/examples/engine.lua
-- Lurek2D lurek.engine API Reference
-- Run with: cargo run -- content/examples/engine

-- =============================================================================
-- STUBS: 10 uncovered lurek.engine API item(s)
-- Generated by tools/audit/example_add_missing.py
-- REQUIRED: replace every --@api-stub: block below with a real scenario.
-- Run .github/prompts/flesh-out-example.prompt.md for instructions.
-- The final committed file must contain ZERO --@api-stub: lines.
-- =============================================================================

-- ---- Stub: lurek.engine.getVersion ---------------------------------------
--@api-stub: lurek.engine.getVersion
-- Returns the engine version string (from `Cargo.toml`).
-- TODO: replace this stub with a real scenario. See flesh-out-example.prompt.md
lurek.engine.getVersion()  -- -> string

-- ---- Stub: lurek.engine.getFrameBudget -----------------------------------
--@api-stub: lurek.engine.getFrameBudget
-- Returns the target frame budget in milliseconds (default: 1000 / 60 â‰ 16.667 ms).
-- TODO: replace this stub with a real scenario. See flesh-out-example.prompt.md
lurek.engine.getFrameBudget()  -- -> number

-- ---- Stub: lurek.engine.memoryUsage --------------------------------------
--@api-stub: lurek.engine.memoryUsage
-- Returns a table with `lua_bytes` (Lua GC heap usage in bytes) and
-- TODO: replace this stub with a real scenario. See flesh-out-example.prompt.md
lurek.engine.memoryUsage()  -- -> table

-- ---- Stub: lurek.engine.platform -----------------------------------------
--@api-stub: lurek.engine.platform
-- Returns a string identifying the host operating system:
-- TODO: replace this stub with a real scenario. See flesh-out-example.prompt.md
lurek.engine.platform()  -- -> string

-- ---- Stub: lurek.engine.uptime -------------------------------------------
--@api-stub: lurek.engine.uptime
-- Returns the total engine uptime in seconds (sum of all processed deltas).
-- TODO: replace this stub with a real scenario. See flesh-out-example.prompt.md
lurek.engine.uptime()  -- -> number

-- ---- Stub: lurek.engine.fps ----------------------------------------------
--@api-stub: lurek.engine.fps
-- Returns the current measured frames-per-second.
-- TODO: replace this stub with a real scenario. See flesh-out-example.prompt.md
lurek.engine.fps()  -- -> number

-- ---- Stub: lurek.engine.frameCount ---------------------------------------
--@api-stub: lurek.engine.frameCount
-- Returns the total number of frames processed since engine start.
-- TODO: replace this stub with a real scenario. See flesh-out-example.prompt.md
lurek.engine.frameCount()  -- -> integer

-- ---- Stub: lurek.engine.isDebug ------------------------------------------
--@api-stub: lurek.engine.isDebug
-- Returns `true` if the engine was compiled in debug mode.
-- TODO: replace this stub with a real scenario. See flesh-out-example.prompt.md
lurek.engine.isDebug()  -- -> boolean

-- ---- Stub: lurek.engine.setResourceBudget --------------------------------
--@api-stub: lurek.engine.setResourceBudget
-- Sets the maximum resident texture memory budget in bytes.
-- TODO: replace this stub with a real scenario. See flesh-out-example.prompt.md
lurek.engine.setResourceBudget(budget_bytes)

-- ---- Stub: lurek.engine.getResourceStats ---------------------------------
--@api-stub: lurek.engine.getResourceStats
-- Returns a table with resident resource memory statistics.
-- TODO: replace this stub with a real scenario. See flesh-out-example.prompt.md
lurek.engine.getResourceStats()  -- -> table
