-- content/examples/province.lua
-- Lurek2D lurek.province API Reference
-- Run with: cargo run -- content/examples/province

-- =============================================================================
-- COVERAGE: 29 uncovered lurek.province API item(s)
-- Generated by tools/audit/example_add_missing.py
-- REQUIRED: replace every --@api-stub: block below with a real scenario.
-- Run .github/prompts/flesh-out-example.prompt.md for instructions.
-- The final committed file must contain ZERO --@api-stub: lines.
-- =============================================================================

-- ---- Example: lurek.province.newFromPng -------------------------------------
--@api-stub: lurek.province.newFromPng
-- Creates and stores a named province registry from a PNG map.
-- lurek.province.newFromPng("hero", png_path)  -- -> ProvinceRegistry

-- ---- Example: lurek.province.get --------------------------------------------
--@api-stub: lurek.province.get
-- Gets a named province registry handle.
-- lurek.province.get("hero")  -- -> ProvinceRegistry

-- ---- Example: lurek.province.exists -----------------------------------------
--@api-stub: lurek.province.exists
-- Checks whether a named registry exists.
-- lurek.province.exists("hero")  -- -> boolean

-- ---- Example: lurek.province.remove -----------------------------------------
--@api-stub: lurek.province.remove
-- Removes a named registry.
-- lurek.province.remove("hero")  -- -> boolean

-- ---- Example: lurek.province.setActive --------------------------------------
--@api-stub: lurek.province.setActive
-- Sets active registry name.
-- lurek.province.setActive("hero")  -- -> boolean

-- ---- Example: lurek.province.getActive --------------------------------------
--@api-stub: lurek.province.getActive
-- Returns active registry handle.
-- lurek.province.getActive()  -- -> ProvinceRegistry

-- -----------------------------------------------------------------------------
-- LProvinceRegistry methods
-- -----------------------------------------------------------------------------

-- ---- Example: LProvinceRegistry:getName -------------------------------------
--@api-stub: LProvinceRegistry:getName
-- Returns registry name.
-- lProvinceRegistry_Example:getName()  -- -> string
-- (replace lProvinceRegistry_example with your real LProvinceRegistry instance above)

-- ---- Example: LProvinceRegistry:getWidth ------------------------------------
--@api-stub: LProvinceRegistry:getWidth
-- Returns source map width in pixels.
-- lProvinceRegistry_Example:getWidth()  -- -> integer
-- (replace lProvinceRegistry_example with your real LProvinceRegistry instance above)

-- ---- Example: LProvinceRegistry:getHeight -----------------------------------
--@api-stub: LProvinceRegistry:getHeight
-- Returns source map height in pixels.
-- lProvinceRegistry_Example:getHeight()  -- -> integer
-- (replace lProvinceRegistry_example with your real LProvinceRegistry instance above)

-- ---- Example: LProvinceRegistry:getAt ---------------------------------------
--@api-stub: LProvinceRegistry:getAt
-- Returns province id at pixel coordinate.
-- lProvinceRegistry_Example:getAt(0.0, 0.0)  -- -> integer
-- (replace lProvinceRegistry_example with your real LProvinceRegistry instance above)

-- ---- Example: LProvinceRegistry:provinceCount -------------------------------
--@api-stub: LProvinceRegistry:provinceCount
-- Returns number of provinces.
-- lProvinceRegistry_Example:provinceCount()  -- -> integer
-- (replace lProvinceRegistry_example with your real LProvinceRegistry instance above)

-- ---- Example: LProvinceRegistry:provinceIds ---------------------------------
--@api-stub: LProvinceRegistry:provinceIds
-- Returns sorted province ids.
-- lProvinceRegistry_Example:provinceIds()  -- -> table
-- (replace lProvinceRegistry_example with your real LProvinceRegistry instance above)

-- ---- Example: LProvinceRegistry:adjacencies ---------------------------------
--@api-stub: LProvinceRegistry:adjacencies
-- Returns adjacency pairs as records `{ province_a, province_b }`.
-- lProvinceRegistry_Example:adjacencies()  -- -> table
-- (replace lProvinceRegistry_example with your real LProvinceRegistry instance above)

-- ---- Example: LProvinceRegistry:provinceSpans -------------------------------
--@api-stub: LProvinceRegistry:provinceSpans
-- Returns span geometry records `{ province_id, y, x0, x1 }`.
-- lProvinceRegistry_Example:provinceSpans()  -- -> table
-- (replace lProvinceRegistry_example with your real LProvinceRegistry instance above)

-- ---- Example: LProvinceRegistry:borderSegments ------------------------------
--@api-stub: LProvinceRegistry:borderSegments
-- Returns border segment geometry records `{ province_a, province_b, x0, y0, x1, y1 }`.
-- lProvinceRegistry_Example:borderSegments()  -- -> table
-- (replace lProvinceRegistry_example with your real LProvinceRegistry instance above)

-- ---- Example: LProvinceRegistry:getRevision ---------------------------------
--@api-stub: LProvinceRegistry:getRevision
-- Returns registry revision counter.
-- lProvinceRegistry_Example:getRevision()  -- -> integer
-- (replace lProvinceRegistry_example with your real LProvinceRegistry instance above)

-- ---- Example: LProvinceRegistry:getProvince ---------------------------------
--@api-stub: LProvinceRegistry:getProvince
-- Returns province snapshot table or nil.
-- lProvinceRegistry_Example:getProvince(1)  -- -> table
-- (replace lProvinceRegistry_example with your real LProvinceRegistry instance above)

-- ---- Example: LProvinceRegistry:getNeighbors --------------------------------
--@api-stub: LProvinceRegistry:getNeighbors
-- Returns neighbor ids for a province.
-- lProvinceRegistry_Example:getNeighbors(1)  -- -> table
-- (replace lProvinceRegistry_example with your real LProvinceRegistry instance above)

-- ---- Example: LProvinceRegistry:getBorderClass ------------------------------
--@api-stub: LProvinceRegistry:getBorderClass
-- Returns border class token between provinces or nil.
-- lProvinceRegistry_Example:getBorderClass(1.0, 0.2)  -- -> string
-- (replace lProvinceRegistry_example with your real LProvinceRegistry instance above)

-- ---- Example: LProvinceRegistry:setBorderClass ------------------------------
--@api-stub: LProvinceRegistry:setBorderClass
-- Sets border class between provinces.
-- lProvinceRegistry_Example:setBorderClass(1.0, 0.2, class)
-- (replace lProvinceRegistry_example with your real LProvinceRegistry instance above)

-- ---- Example: LProvinceRegistry:setPoliticalColor ---------------------------
--@api-stub: LProvinceRegistry:setPoliticalColor
-- Sets political color for one province.
-- lProvinceRegistry_Example:setPoliticalColor(1, 1.0, 0.8, 0.2, [a])  -- -> boolean
-- (replace lProvinceRegistry_example with your real LProvinceRegistry instance above)

-- ---- Example: LProvinceRegistry:setTerrainType ------------------------------
--@api-stub: LProvinceRegistry:setTerrainType
-- Sets terrain type for one province.
-- lProvinceRegistry_Example:setTerrainType(1, terrain_type)  -- -> boolean
-- (replace lProvinceRegistry_example with your real LProvinceRegistry instance above)

-- ---- Example: LProvinceRegistry:setBorderStyle ------------------------------
--@api-stub: LProvinceRegistry:setBorderStyle
-- Sets border style id for one province.
-- lProvinceRegistry_Example:setBorderStyle(1, border_style)  -- -> boolean
-- (replace lProvinceRegistry_example with your real LProvinceRegistry instance above)

-- ---- Example: LProvinceRegistry:setFogState ---------------------------------
--@api-stub: LProvinceRegistry:setFogState
-- Sets fog state byte for one province.
-- lProvinceRegistry_Example:setFogState(1, fog_state)  -- -> boolean
-- (replace lProvinceRegistry_example with your real LProvinceRegistry instance above)

-- ---- Example: LProvinceRegistry:setVisibilityState --------------------------
--@api-stub: LProvinceRegistry:setVisibilityState
-- Sets visibility byte for one province.
-- lProvinceRegistry_Example:setVisibilityState(1, visibility_state)  -- -> boolean
-- (replace lProvinceRegistry_example with your real LProvinceRegistry instance above)

-- ---- Example: LProvinceRegistry:setAttr -------------------------------------
--@api-stub: LProvinceRegistry:setAttr
-- Sets freeform attribute on a province.
-- lProvinceRegistry_Example:setAttr(1, "player_score", 42)  -- -> boolean
-- (replace lProvinceRegistry_example with your real LProvinceRegistry instance above)

-- ---- Example: LProvinceRegistry:getChangesSince -----------------------------
--@api-stub: LProvinceRegistry:getChangesSince
-- Returns revisioned change records for incremental sync.
-- lProvinceRegistry_Example:getChangesSince(revision)  -- -> table
-- (replace lProvinceRegistry_example with your real LProvinceRegistry instance above)

-- ---- Example: LProvinceRegistry:type ----------------------------------------
--@api-stub: LProvinceRegistry:type
-- Returns Lua type name.
-- lProvinceRegistry_Example:type()  -- -> string
-- (replace lProvinceRegistry_example with your real LProvinceRegistry instance above)

-- ---- Example: LProvinceRegistry:typeOf --------------------------------------
--@api-stub: LProvinceRegistry:typeOf
-- Returns true when type token matches this userdata.
-- lProvinceRegistry_Example:typeOf("hero")  -- -> boolean
-- (replace lProvinceRegistry_example with your real LProvinceRegistry instance above)

-- ---- Example: lurek.province.zoomCameraAt --------------------------------
--@api-stub: lurek.province.zoomCameraAt
-- do
-- 	local cam_x, cam_y = 0.0, 0.0
-- 	local new_x, new_y = lurek.province.zoomCameraAt(320.0, 240.0, cam_x, cam_y, 1.0, 1.2)
-- 	lurek.log.debug("zoom anchor camera: " .. tostring(new_x) .. "," .. tostring(new_y), "province")
-- end

-- ---- Example: LProvinceRegistry fit/pick helpers -------------------------
--@api-stub: LProvinceRegistry:fitCamera
--@api-stub: LProvinceRegistry:screenToMap
--@api-stub: LProvinceRegistry:screenToProvince
-- do
-- 	local path = "content/games/strategy/eu2/map.png"
-- 	local reg = lurek.province.newFromPng("example-province-view", path)
-- 	local cam_x, cam_y, zoom = reg:fitCamera(1280, 720, 1.0)
-- 	local mx, my = reg:screenToMap(640, 360, cam_x, cam_y, zoom, 1.0)
-- 	local pid = reg:screenToProvince(640, 360, cam_x, cam_y, zoom, 1.0)
-- 	lurek.log.debug("map=" .. tostring(mx) .. "," .. tostring(my) .. " pid=" .. tostring(pid), "province")
-- 	lurek.province.remove("example-province-view")
-- end

-- =============================================================================
-- COVERAGE: 4 uncovered lurek.province API item(s)
-- Generated by tools/audit/example_add_missing.py
-- REQUIRED: replace every --@api-stub: block below with a real scenario.
-- Run .github/prompts/flesh-out-example.prompt.md for instructions.
-- The final committed file must contain ZERO --@api-stub: lines.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- LProvinceRegistry methods
-- -----------------------------------------------------------------------------

-- ---- Example: LProvinceRegistry:setCapital ----------------------------------
--@api-stub: LProvinceRegistry:setCapital
-- Sets province capital marker position.
-- lProvinceRegistry_Example:setCapital(1, 0.0, 0.0)  -- -> boolean
-- (replace lProvinceRegistry_example with your real LProvinceRegistry instance above)

-- ---- Example: LProvinceRegistry:setLabelLine --------------------------------
--@api-stub: LProvinceRegistry:setLabelLine
-- Sets province label guide line from two points.
-- lProvinceRegistry_Example:setLabelLine(1, ax, ay, bx, by)  -- -> boolean
-- (replace lProvinceRegistry_example with your real LProvinceRegistry instance above)

-- ---- Example: LProvinceRegistry:setLabelText --------------------------------
--@api-stub: LProvinceRegistry:setLabelText
-- Sets province display label text.
-- lProvinceRegistry_Example:setLabelText(1, "Hello, world!")  -- -> boolean
-- (replace lProvinceRegistry_example with your real LProvinceRegistry instance above)

-- ---- Example: LProvinceRegistry:render --------------------------------------
--@api-stub: LProvinceRegistry:render
-- Enqueues Rust-generated GPU draw commands for province rendering.
-- lProvinceRegistry_Example:render([opts])
-- (replace lProvinceRegistry_example with your real LProvinceRegistry instance above)

-- ---- Example: sanitize + import metadata pipeline -------------------------
do
	local sanitized = "save/example_province/map_sanitized.png"
	lurek.province.sanitizeMarkedPng("content/games/strategy/eu2/map.png", sanitized)

	local reg = lurek.province.newFromPng("example-province-import", sanitized)
	reg:importMetadataFromFiles({
		color_map_png = sanitized,
		marker_png = "content/games/strategy/eu2/map.png",
		color_csv = "content/games/strategy/eu2/prov_cols.csv",
		province_toml = "content/games/strategy/eu2/province.toml",
		water_terrain_tokens = { "sea", "river" },
		water_terrain_type = 0,
		land_terrain_type = 1,
	})

	local snap = reg:getProvince(1)
	if snap and snap.attrs then
		lurek.log.debug(
			"imported province #1 name=" .. tostring(snap.attrs.name) ..
			" terrain=" .. tostring(snap.attrs.terrain),
			"province"
		)
	end

	lurek.province.remove("example-province-import")
end

--@api-stub: LProvinceRegistry:importMetadataFromFiles
do -- LProvinceRegistry:importMetadataFromFiles
	local reg = lurek.province.get("example-province-import")
	if reg then
		reg:importMetadataFromFiles("content/provinces/meta")
	end
end

--@api-stub: lurek.province.sanitizeMarkedPng
do -- lurek.province.sanitizeMarkedPng
	local ok = pcall(lurek.province.sanitizeMarkedPng, "in_marked.png", "out_marked.png")
end
