-- content/examples/save.lua
-- Lurek2D lurek.save API Reference
-- Run with: cargo run -- content/examples/save

-- =============================================================================
-- STUBS: 23 uncovered lurek.save API item(s)
-- Generated by tools/audit/example_add_missing.py
-- REQUIRED: replace every --@api-stub: block below with a real scenario.
-- Run .github/prompts/flesh-out-example.prompt.md for instructions.
-- The final committed file must contain ZERO --@api-stub: lines.
-- =============================================================================

-- ---- Stub: lurek.save.newSaveManager -------------------------------------
--@api-stub: lurek.save.newSaveManager
-- One manager handles all save slots for the game.  Register per-system
-- collectors and restorers on it, then call save/load from your menu.
local mgr = lurek.save.newSaveManager()

-- -----------------------------------------------------------------------------
-- SaveManager methods
-- -----------------------------------------------------------------------------

-- ---- Stub: SaveManager:unregister ----------------------------------------
--@api-stub: SaveManager:unregister
-- Call this when a game system is torn down mid-session (e.g. the player
-- leaves a multiplayer lobby) so its data is not included in future saves.
mgr:unregister("inventory")
print("inventory module removed from save scope")

-- ---- Stub: SaveManager:setSchemaVersion ----------------------------------
--@api-stub: SaveManager:setSchemaVersion
-- Increment this whenever you add or remove fields that require a migration
-- step so older save files can be detected and upgraded automatically.
mgr:setSchemaVersion(3)
print("schema version set to 3")

-- ---- Stub: SaveManager:getSchemaVersion ----------------------------------
--@api-stub: SaveManager:getSchemaVersion
-- Read this when loading a save file to decide whether a migration function
-- needs to run before restoring data into the live game systems.
local ver = mgr:getSchemaVersion()
print("current schema version:", ver)
if ver < 3 then
    -- run_migration_v2_to_v3(data)
end

-- ---- Stub: SaveManager:collect -------------------------------------------
--@api-stub: SaveManager:collect
-- Use this when you want to inspect or serialise the save payload manually,
-- for example to display a "what will be saved" preview in the UI.
local payload = mgr:collect()
print("save payload has", #payload, "top-level keys")

-- ---- Stub: SaveManager:restore -------------------------------------------
--@api-stub: SaveManager:restore
-- Pass a raw payload table (e.g. from a unit test or a remote sync) instead
-- of loading from a file -- useful for testing migration logic in isolation.
local test_payload = { schema_version = 2, player = { hp = 80, gold = 500 } }
mgr:restore(test_payload)
print("state restored from test payload")

-- ---- Stub: SaveManager:markDirty -----------------------------------------
--@api-stub: SaveManager:markDirty
-- Call this after any significant state change (level up, boss killed) so
-- the auto-save timer knows there is unsaved progress worth persisting.
mgr:markDirty()
-- the manager will now schedule an auto-save on the next update() tick

-- ---- Stub: SaveManager:isDirty -------------------------------------------
--@api-stub: SaveManager:isDirty
-- Check this before showing the "quit to menu" dialog to warn the player
-- about unsaved progress if there are pending changes.
if mgr:isDirty() then
    print("unsaved progress -- show 'Save before quitting?' dialog")
else
    print("no unsaved changes -- safe to quit")
end

-- ---- Stub: SaveManager:disableAutoSave -----------------------------------
--@api-stub: SaveManager:disableAutoSave
-- Use this during cutscenes or boss fights where an auto-save mid-action
-- would interrupt the experience or capture an undesirable game state.
mgr:disableAutoSave()
print("auto-save disabled for boss fight duration")

-- ---- Stub: SaveManager:update --------------------------------------------
--@api-stub: SaveManager:update
-- Call this every frame from lurek.process(dt).  When the interval fires it
-- returns the slot name so you can show a brief "Saving..." indicator.
--[[
function lurek.process(dt)
    local triggered_slot = mgr:update(dt)
    if triggered_slot then
        print("auto-saved to", triggered_slot)
        -- show_autosave_icon(2.0)  -- display for 2 seconds
    end
end
]]

-- ---- Stub: SaveManager:setSummary ----------------------------------------
--@api-stub: SaveManager:setSummary
-- Write a human-readable summary just before saving so the load-game screen
-- can show "Level 3 - Ironforge Dungeon  |  4h 22m" without loading the full file.
mgr:setSummary("Level 3 - Ironforge Dungeon  |  4h 22m")
print("summary written to save metadata")

-- ---- Stub: SaveManager:getSummary ----------------------------------------
--@api-stub: SaveManager:getSummary
-- Read this to display a preview line in the save-slot selection screen
-- without deserialising the full save payload.
local summary = mgr:getSummary()
print("slot preview:", summary)   -- "Level 3 - Ironforge Dungeon  |  4h 22m"

-- ---- Stub: SaveManager:reset ---------------------------------------------
--@api-stub: SaveManager:reset
-- Call this when starting a New Game so stale collector/restorer registrations
-- from a previous play session do not bleed into the fresh game state.
mgr:reset()
-- re-register all modules after reset:
-- register_player_module(mgr)
-- register_inventory_module(mgr)
print("save manager reset for new game")

-- ---- Stub: SaveManager:setCompress ---------------------------------------
--@api-stub: SaveManager:setCompress
-- Enable compression for release builds to reduce save file sizes;
-- disable it during development so save files remain human-readable JSON.
local is_release = false   -- set to true in release builds
mgr:setCompress(is_release)
print("compression:", is_release)

-- ---- Stub: SaveManager:isCompressed --------------------------------------
--@api-stub: SaveManager:isCompressed
-- Read this before writing a debug dump so you know whether to decompress
-- the raw bytes first when inspecting the file in a hex editor.
if mgr:isCompressed() then
    print("save data is LZ4-compressed -- decompress before inspecting")
else
    print("save data is plain JSON -- open directly in a text editor")
end

-- ---- Stub: SaveManager:onBeforeSave --------------------------------------
--@api-stub: SaveManager:onBeforeSave
-- Use this to flush in-flight transactions, update the play-time counter,
-- or set the summary string just before data is collected.
mgr:onBeforeSave(function()
    mgr:setSummary("Level 3  |  4h 22m")  -- ensure summary is current
    print("before-save: summary updated")
end)

-- ---- Stub: SaveManager:onAfterLoad ---------------------------------------
--@api-stub: SaveManager:onAfterLoad
-- Use this to rebuild derived state that is not serialised directly,
-- such as re-creating pathfinding grids or refreshing the minimap.
mgr:onAfterLoad(function()
    print("after-load: rebuilding minimap from restored world state")
    -- minimap:rebuild(world)
end)

-- ---- Stub: SaveManager:save ----------------------------------------------
--@api-stub: SaveManager:save
-- Call this from the save-game menu.  The slot name becomes the filename;
-- use a numbered scheme ("slot1", "slot2", "autosave") for player-facing slots.
mgr:save("slot1")
print("game saved to slot1")

-- ---- Stub: SaveManager:load ----------------------------------------------
--@api-stub: SaveManager:load
-- Call this when the player selects a slot in the continue-game screen.
-- Migrations run automatically based on the schema version in the file.
mgr:load("slot1")
print("slot1 loaded and game state restored")

-- ---- Stub: SaveManager:delete --------------------------------------------
--@api-stub: SaveManager:delete
-- Call this when the player confirms "Delete save" in the save management
-- screen.  Check exists() first to avoid a no-op on an empty slot.
if mgr:exists("slot3") then
    mgr:delete("slot3")
    print("slot3 deleted")
else
    print("slot3 does not exist, nothing to delete")
end

-- ---- Stub: SaveManager:exists --------------------------------------------
--@api-stub: SaveManager:exists
-- Use this to decide whether to show "Continue" or "New Game" on the main
-- menu, and to grey out empty slots in the save-slot selection screen.
local has_save = mgr:exists("slot1")
if has_save then
    print("slot1 found -- show Continue button")
else
    print("no save in slot1 -- show New Game button")
end

-- ---- Stub: SaveManager:getSlots ------------------------------------------
--@api-stub: SaveManager:getSlots
-- Use this to build the save-slot selection screen: iterate the list and
-- display each slot's summary, timestamp, and play-time.
local slots = mgr:getSlots()
for _, slot_info in ipairs(slots) do
    print(string.format("slot: %-8s  summary: %s",
        slot_info.name, slot_info.summary or "(no summary)"))
end

-- ---- Stub: SaveManager:getSlotInfo ---------------------------------------
--@api-stub: SaveManager:getSlotInfo
-- Call this when the player hovers over a slot to show a detailed tooltip
-- (play-time, location, character name) without loading the full payload.
local info = mgr:getSlotInfo("slot1")
if info then
    print("slot1 summary:", info.summary)
    print("slot1 saved at:", info.timestamp)
else
    print("slot1 is empty")
end
