-- content/examples/sprite.lua
-- Lurek2D lurek.sprite API Reference
-- Run with: cargo run -- content/examples/sprite

-- =============================================================================
-- STUBS: 18 uncovered lurek.sprite API item(s)
-- Generated by tools/audit/example_add_missing.py
-- REQUIRED: replace every --@api-stub: block below with a real scenario.
-- Run .github/prompts/flesh-out-example.prompt.md for instructions.
-- The final committed file must contain ZERO --@api-stub: lines.
-- =============================================================================

-- ---- Stub: lurek.sprite.newSheet -----------------------------------------
--@api-stub: lurek.sprite.newSheet
-- Provide the total texture size (tw, th) and the size of one cell (fw, fh).
-- All frames are numbered left-to-right, top-to-bottom starting from 0.
local sheet = lurek.sprite.newSheet(256, 128, 32, 32)
-- sheet now has (256/32) * (128/32) = 8 * 4 = 32 frames
print("frame count:", sheet:getFrameCount())  -- 32

-- ---- Stub: lurek.sprite.newRPGMakerSheet ---------------------------------
--@api-stub: lurek.sprite.newRPGMakerSheet
-- The layout is fixed: row 0 = down, row 1 = left, row 2 = right, row 3 = up.
-- Use getGroupFrames("down") to get the three walk frames for that direction.
local rpg_sheet = lurek.sprite.newRPGMakerSheet(96, 128)
local down_frames = rpg_sheet:getGroupFrames("down")
print("walk-down frame count:", #down_frames)  -- 3

-- ---- Stub: lurek.sprite.parseAtlas ---------------------------------------
--@api-stub: lurek.sprite.parseAtlas
-- Export your atlas from TexturePacker with "JSON (Hash)" format, then read
-- the .json file and pass its contents here to get named region lookups.
local atlas_json = lurek.filesystem.readFile("assets/ui_atlas.json")
local atlas = lurek.sprite.parseAtlas(atlas_json)
print("atlas loaded, regions:", atlas:entryCount())

-- ---- Stub: lurek.sprite.newAtlasSheet ------------------------------------
--@api-stub: lurek.sprite.newAtlasSheet
-- Use this when your packed atlas has named animation frames ("hero_walk_01",
-- "hero_walk_02", ...) and you want to address them as ordered sheet frames.
local atlas_sheet = lurek.sprite.newAtlasSheet(atlas, 512, 512)
print("atlas sheet frames:", atlas_sheet:getFrameCount())

-- ---- Stub: lurek.sprite.parseAsepriteAtlas -------------------------------
--@api-stub: lurek.sprite.parseAsepriteAtlas
-- Export from Aseprite via File > Export Sprite Sheet with JSON output checked.
-- The returned atlas supports named frame lookups by tag name.
local ase_json = lurek.filesystem.readFile("assets/hero_spritesheet.json")
local ase_atlas = lurek.sprite.parseAsepriteAtlas(ase_json)
print("aseprite atlas regions:", ase_atlas:entryCount())

-- -----------------------------------------------------------------------------
-- SpriteAtlas methods
-- -----------------------------------------------------------------------------

-- ---- Stub: SpriteAtlas:getEntry ------------------------------------------
--@api-stub: SpriteAtlas:getEntry
-- Use this to position a HUD icon by name without hard-coding pixel offsets.
local health_region = atlas:getEntry("icon_health")
if health_region then
    print(string.format("health icon at x=%d y=%d  size=%dx%d",
        health_region.x, health_region.y,
        health_region.w, health_region.h))
end

-- ---- Stub: SpriteAtlas:getByIndex ----------------------------------------
--@api-stub: SpriteAtlas:getByIndex
-- Use this when you need to iterate all regions in insertion order,
-- for example to build a preview grid in an asset browser.
local first = atlas:getByIndex(1)
if first then
    print("first atlas entry:", first.name)
end

for i = 1, atlas:entryCount() do
    local r = atlas:getByIndex(i)
    -- build_preview_cell(r.x, r.y, r.w, r.h, r.name)
end

-- ---- Stub: SpriteAtlas:entryCount ----------------------------------------
--@api-stub: SpriteAtlas:entryCount
-- Check this after loading to confirm the atlas file has the expected region
-- count, which can catch a wrong export configuration early.
local n = atlas:entryCount()
print("atlas loaded with", n, "regions")
if n == 0 then
    error("atlas is empty -- check the TexturePacker export settings")
end

-- ---- Stub: SpriteAtlas:entryNames ----------------------------------------
--@api-stub: SpriteAtlas:entryNames
-- Use this to populate a drop-down list of available sprites in a level editor
-- or to validate that every expected region name is present after an import.
local names = atlas:entryNames()
for _, name in ipairs(names) do
    print("  region:", name)
end

-- -----------------------------------------------------------------------------
-- SpriteSheet methods
-- -----------------------------------------------------------------------------

-- ---- Stub: SpriteSheet:getFrame ------------------------------------------
--@api-stub: SpriteSheet:getFrame
-- The quad table contains {x, y, w, h} ready to pass to the renderer as a
-- source rect.  Frame 0 is top-left; frames increase left-to-right, top-to-bottom.
local frame0 = sheet:getFrame(0)
local frame5 = sheet:getFrame(5)
if frame5 then
    print(string.format("frame 5 quad: x=%d y=%d  %dx%d",
        frame5.x, frame5.y, frame5.w, frame5.h))
end

-- ---- Stub: SpriteSheet:getFrameCount -------------------------------------
--@api-stub: SpriteSheet:getFrameCount
-- Use this as the modulus when advancing an animation timer to loop cleanly
-- without going out of range.
local total_frames = sheet:getFrameCount()
local anim_timer = 0.0
local anim_fps   = 12.0
-- each frame, advance timer and compute current frame:
-- anim_timer = anim_timer + dt
-- local current = math.floor(anim_timer * anim_fps) % total_frames
print("sheet has", total_frames, "frames")

-- ---- Stub: SpriteSheet:getRow --------------------------------------------
--@api-stub: SpriteSheet:getRow
-- Row indices are 0-based.  Use this to grab all frames of a horizontal
-- strip animation (e.g. the three walk-cycle frames on row 0).
local walk_frames = sheet:getRow(0)
print("row 0 has", #walk_frames, "frames")
for i, quad in ipairs(walk_frames) do
    -- render each quad with lurek.render.drawSprite
end

-- ---- Stub: SpriteSheet:getColumn -----------------------------------------
--@api-stub: SpriteSheet:getColumn
-- Column indices are 0-based.  Use this to grab all variation frames stacked
-- vertically in a shared column (e.g. colour variants of the same pose).
local col0_frames = sheet:getColumn(0)
print("column 0 has", #col0_frames, "frames")
for _, quad in ipairs(col0_frames) do
    print(string.format("  frame x=%d y=%d", quad.x, quad.y))
end

-- ---- Stub: SpriteSheet:getGroupFrames ------------------------------------
--@api-stub: SpriteSheet:getGroupFrames
-- RPGMaker sheets have built-in groups "down" / "left" / "right" / "up".
-- Custom groups can be defined when building an atlas sheet.
local run_frames = rpg_sheet:getGroupFrames("down")
if run_frames then
    print("down-walk group has", #run_frames, "frames")
    -- drive animation: local q = run_frames[frame_idx]
    -- lurek.render.drawSprite(texture_key, q, player_x, player_y)
end

-- ---- Stub: SpriteSheet:getGroupNames -------------------------------------
--@api-stub: SpriteSheet:getGroupNames
-- Use this to populate the animation-clip dropdown in a character editor or
-- to assert that all expected groups were exported before loading a level.
local groups = rpg_sheet:getGroupNames()
for _, g in ipairs(groups) do
    print("available animation group:", g)
end

-- ---- Stub: SpriteSheet:getFrameSize --------------------------------------
--@api-stub: SpriteSheet:getFrameSize
-- Use this to calculate hitbox dimensions or to scale a sprite uniformly
-- without hard-coding the source frame size in game logic.
local fw, fh = sheet:getFrameSize()
print(string.format("each frame is %d x %d pixels", fw, fh))
-- hitbox width = fw * 0.8  (80% of the frame, centred)

-- ---- Stub: SpriteSheet:getGridSize ---------------------------------------
--@api-stub: SpriteSheet:getGridSize
-- Use this to compute the frame index of a specific (col, row) cell without
-- relying on magic numbers: index = row * cols + col.
local cols, rows = sheet:getGridSize()
print(string.format("grid: %d columns x %d rows", cols, rows))
local target_col, target_row = 2, 1
local frame_idx = target_row * cols + target_col
print("frame index for (col=2, row=1):", frame_idx)

-- ---- Stub: SpriteSheet:drawToImage ---------------------------------------
--@api-stub: SpriteSheet:drawToImage
-- Use this during development to visually verify that the grid alignment is
-- correct before connecting the sheet to an animation controller.
local preview = sheet:drawToImage(256, 128)
-- pass preview to lurek.image.loadFromData and then lurek.render.drawImage
-- to display the full sheet grid on screen for inspection
