-- content/examples/system.lua
-- Lurek2D lurek.system API Reference
-- Run with: cargo run -- content/examples/system

-- =============================================================================
-- STUBS: 26 uncovered lurek.system API item(s)
-- Generated by tools/audit/example_add_missing.py
-- REQUIRED: replace every --@api-stub: block below with a real scenario.
-- Run .github/prompts/flesh-out-example.prompt.md for instructions.
-- The final committed file must contain ZERO --@api-stub: lines.
-- =============================================================================

-- ---- Stub: lurek.system.getOS --------------------------------------------
--@api-stub: lurek.system.getOS
-- Returns the host operating system name ('Windows', 'Linux', 'macOS').
-- TODO: replace this stub with a real scenario. See flesh-out-example.prompt.md
lurek.system.getOS()  -- -> string

-- ---- Stub: lurek.system.getVersion ---------------------------------------
--@api-stub: lurek.system.getVersion
-- Returns the Lurek2D engine version string.
-- TODO: replace this stub with a real scenario. See flesh-out-example.prompt.md
lurek.system.getVersion()  -- -> string

-- ---- Stub: lurek.system.getProcessorCount --------------------------------
--@api-stub: lurek.system.getProcessorCount
-- Returns the number of logical CPU cores available.
-- TODO: replace this stub with a real scenario. See flesh-out-example.prompt.md
lurek.system.getProcessorCount()  -- -> integer

-- ---- Stub: lurek.system.getMemorySize ------------------------------------
--@api-stub: lurek.system.getMemorySize
-- Returns the total amount of installed system RAM in megabytes.
-- TODO: replace this stub with a real scenario. See flesh-out-example.prompt.md
lurek.system.getMemorySize()  -- -> integer

-- ---- Stub: lurek.system.openURL ------------------------------------------
--@api-stub: lurek.system.openURL
-- Opens a URL in the system's default browser.
-- TODO: replace this stub with a real scenario. See flesh-out-example.prompt.md
lurek.system.openURL(url)  -- -> boolean

-- ---- Stub: lurek.system.getPreferredLocales ------------------------------
--@api-stub: lurek.system.getPreferredLocales
-- Returns an ordered list of the user's preferred locale strings (e.g. 'en-US').
-- TODO: replace this stub with a real scenario. See flesh-out-example.prompt.md
lurek.system.getPreferredLocales()  -- -> table

-- ---- Stub: lurek.system.getPowerInfo -------------------------------------
--@api-stub: lurek.system.getPowerInfo
-- Returns battery state, percentage charged, and estimated time remaining.
-- TODO: replace this stub with a real scenario. See flesh-out-example.prompt.md
lurek.system.getPowerInfo()  -- -> table

-- ---- Stub: lurek.system.getInfo ------------------------------------------
--@api-stub: lurek.system.getInfo
-- Returns a table of system information including OS name, CPU model, and installed RAM.
-- TODO: replace this stub with a real scenario. See flesh-out-example.prompt.md
lurek.system.getInfo()  -- -> table

-- ---- Stub: lurek.system.getMessage ---------------------------------------
--@api-stub: lurek.system.getMessage
-- Resolves a stable runtime message ID such as 'L001' to its human-readable text.
-- TODO: replace this stub with a real scenario. See flesh-out-example.prompt.md
lurek.system.getMessage(1)  -- -> string

-- ---- Stub: lurek.system.hasMessage ---------------------------------------
--@api-stub: lurek.system.hasMessage
-- Returns true when the runtime message catalog contains the given stable message ID.
-- TODO: replace this stub with a real scenario. See flesh-out-example.prompt.md
lurek.system.hasMessage(1)  -- -> boolean

-- ---- Stub: lurek.system.getMessageCount ----------------------------------
--@api-stub: lurek.system.getMessageCount
-- Returns the total number of message entries loaded into the runtime message catalog.
-- TODO: replace this stub with a real scenario. See flesh-out-example.prompt.md
lurek.system.getMessageCount()  -- -> integer

-- ---- Stub: lurek.system.setClipboardText ---------------------------------
--@api-stub: lurek.system.setClipboardText
-- Replaces the system clipboard contents with the given string.
-- TODO: replace this stub with a real scenario. See flesh-out-example.prompt.md
lurek.system.setClipboardText("Hello, world!")

-- ---- Stub: lurek.system.getClipboardText ---------------------------------
--@api-stub: lurek.system.getClipboardText
-- Returns the current contents of the system clipboard.
-- TODO: replace this stub with a real scenario. See flesh-out-example.prompt.md
lurek.system.getClipboardText()  -- -> string

-- ---- Stub: lurek.system.setDebugOverlay ----------------------------------
--@api-stub: lurek.system.setDebugOverlay
-- Shows or hides the FPS/draw-call debug overlay.
-- TODO: replace this stub with a real scenario. See flesh-out-example.prompt.md
lurek.system.setDebugOverlay(true)

-- ---- Stub: lurek.system.getDebugOverlay ----------------------------------
--@api-stub: lurek.system.getDebugOverlay
-- Returns whether the debug overlay is currently visible.
-- TODO: replace this stub with a real scenario. See flesh-out-example.prompt.md
lurek.system.getDebugOverlay()

-- ---- Stub: lurek.system.setLogLevel --------------------------------------
--@api-stub: lurek.system.setLogLevel
-- Sets the minimum severity level for runtime log messages.
-- TODO: replace this stub with a real scenario. See flesh-out-example.prompt.md
lurek.system.setLogLevel(level)

-- ---- Stub: lurek.system.getLogLevel --------------------------------------
--@api-stub: lurek.system.getLogLevel
-- Returns the name of the current minimum log level for runtime messages.
-- TODO: replace this stub with a real scenario. See flesh-out-example.prompt.md
lurek.system.getLogLevel()

-- ---- Stub: lurek.system.log ----------------------------------------------
--@api-stub: lurek.system.log
-- Emit a log message from Lua at the specified level.
-- TODO: replace this stub with a real scenario. See flesh-out-example.prompt.md
lurek.system.log(level, message)

-- ---- Stub: lurek.system.getLastError -------------------------------------
--@api-stub: lurek.system.getLastError
-- Returns the last unhandled error message, or nil.
-- TODO: replace this stub with a real scenario. See flesh-out-example.prompt.md
lurek.system.getLastError()  -- -> table?

-- ---- Stub: lurek.system.errorSnapshot ------------------------------------
--@api-stub: lurek.system.errorSnapshot
-- Serialises an engine error message to a compact JSON string.
-- TODO: replace this stub with a real scenario. See flesh-out-example.prompt.md
lurek.system.errorSnapshot("level_complete")  -- -> string

-- ---- Stub: lurek.system.getArch ------------------------------------------
--@api-stub: lurek.system.getArch
-- Returns the CPU architecture string for the current machine.
-- TODO: replace this stub with a real scenario. See flesh-out-example.prompt.md
lurek.system.getArch()  -- -> string

-- ---- Stub: lurek.system.getEnv -------------------------------------------
--@api-stub: lurek.system.getEnv
-- Returns the value of an environment variable, or nil if not set.
-- TODO: replace this stub with a real scenario. See flesh-out-example.prompt.md
lurek.system.getEnv("hero")

-- ---- Stub: lurek.system.getArgs ------------------------------------------
--@api-stub: lurek.system.getArgs
-- Returns the command-line arguments as a table.
-- TODO: replace this stub with a real scenario. See flesh-out-example.prompt.md
lurek.system.getArgs()  -- -> table

-- ---- Stub: lurek.system.parseArgs ----------------------------------------
--@api-stub: lurek.system.parseArgs
-- Parses a command-line argument string and returns a structured key/value table.
-- TODO: replace this stub with a real scenario. See flesh-out-example.prompt.md
lurek.system.parseArgs([args])  -- -> table

-- ---- Stub: lurek.system.runBatch -----------------------------------------
--@api-stub: lurek.system.runBatch
-- Runs a list of shell commands in parallel and returns immediately without blocking.
-- TODO: replace this stub with a real scenario. See flesh-out-example.prompt.md
lurek.system.runBatch(tasks, [opts])  -- -> table

-- ---- Stub: lurek.system.getBatchResults ----------------------------------
--@api-stub: lurek.system.getBatchResults
-- Returns the output table from the most recently completed runBatch call.
-- TODO: replace this stub with a real scenario. See flesh-out-example.prompt.md
lurek.system.getBatchResults(results)  -- -> integer
