-- content/examples/thread.lua
-- Lurek2D lurek.thread API Reference
-- Run with: cargo run -- content/examples/thread

-- =============================================================================
-- STUBS: 37 uncovered lurek.thread API item(s)
-- Generated by tools/audit/example_add_missing.py
-- REQUIRED: replace every --@api-stub: block below with a real scenario.
-- Run .github/prompts/flesh-out-example.prompt.md for instructions.
-- The final committed file must contain ZERO --@api-stub: lines.
-- =============================================================================

-- ---- Stub: lurek.thread.newThread ----------------------------------------
--@api-stub: lurek.thread.newThread
-- Run heavy work (pathfinding, world gen, parsing) off the main Lua VM so the
-- game loop never stalls waiting for a long computation to finish.
local worker_code = [[
    local ch_in  = lurek.thread.getChannel("work_in")
    local ch_out = lurek.thread.getChannel("work_out")
    while true do
        local job = ch_in:demand()
        if job == nil then break end
        ch_out:push(job * job)  -- square the number as a demo
    end
]]
local worker = lurek.thread.newThread(worker_code)

-- ---- Stub: lurek.thread.newChannel ---------------------------------------
--@api-stub: lurek.thread.newChannel
-- Create a private, unnamed channel when only the current script needs it --
-- useful for one-off producer/consumer pairs inside a single module.
local ch = lurek.thread.newChannel()
ch:push(100)
print("channel created, items:", ch:getCount())

-- ---- Stub: lurek.thread.getChannel ---------------------------------------
--@api-stub: lurek.thread.getChannel
-- Named channels are global and persist across calls -- use them to wire
-- a background worker to the main loop without passing channel refs around.
local results_ch = lurek.thread.getChannel("results")
print("named channel 'results' retrieved, items:", results_ch:getCount())

-- ---- Stub: lurek.thread.newPool ------------------------------------------
--@api-stub: lurek.thread.newPool
-- Spawn N identical worker VMs to process a queue of jobs in parallel --
-- ideal for batch tile loading, parallel path-finding, or noise generation.
local tile_worker = [[
    local inp = lurek.thread.getChannel("tiles_in")
    local out = lurek.thread.getChannel("tiles_out")
    while true do
        local id = inp:demand()
        if id == nil then break end
        out:push({ id = id, data = "generated" })
    end
]]
local pool = lurek.thread.newPool(4, tile_worker)
print("pool of 4 tile-gen workers created")

-- ---- Stub: lurek.thread.async --------------------------------------------
--@api-stub: lurek.thread.async
-- Fire-and-forget one-shot background computation -- the returned Promise
-- lets the main loop stay responsive while the work runs in the background.
local code = "return { sum = 1 + 2 + 3 + 4 + 5 }"
local promise = lurek.thread.async(code, {})
print("async computation started, promise:", promise:type())

-- -----------------------------------------------------------------------------
-- Channel methods
-- -----------------------------------------------------------------------------

-- ---- Stub: Channel:type --------------------------------------------------
--@api-stub: Channel:type
-- Use to confirm that an object returned from a helper function is a Channel
-- before calling channel-specific methods on it.
print(ch:type())  -- "Channel"

-- ---- Stub: Channel:typeOf ------------------------------------------------
--@api-stub: Channel:typeOf
-- Check membership before dispatching -- useful when a generic helper
-- receives either a Channel or a ThreadPool as an argument.
print(ch:typeOf("Channel"))  -- true
print(ch:typeOf("Thread"))   -- false

-- ---- Stub: Channel:push --------------------------------------------------
--@api-stub: Channel:push
-- Returns the new item count after the push -- useful for back-pressure
-- checks: if the count is too high, throttle the producer.
local count = ch:push("tile_job_42")
print("items in channel after push:", count)

-- ---- Stub: Channel:pop ---------------------------------------------------
--@api-stub: Channel:pop
-- Non-blocking: returns nil immediately if the channel is empty, so call
-- this from the main-loop process callback to drain results without stalling.
local result = ch:pop()
if result ~= nil then
    print("got result from worker:", result)
end

-- ---- Stub: Channel:peek --------------------------------------------------
--@api-stub: Channel:peek
-- Read the front value without consuming it -- use to decide whether to pop
-- based on the value type before actually removing it.
local front = ch:peek()
print("next value (not removed):", front)

-- ---- Stub: Channel:demand ------------------------------------------------
--@api-stub: Channel:demand
-- Blocking pop with optional timeout -- use inside a worker VM where you
-- want the thread to sleep until a job arrives rather than busy-spinning.
local job = ch:demand(5.0)  -- wait up to 5 seconds
if job == nil then
    print("no job arrived within timeout")
else
    print("job received:", job)
end

-- ---- Stub: Channel:getCount ----------------------------------------------
--@api-stub: Channel:getCount
-- Check queue depth for back-pressure control -- if count grows too large
-- the producer should pause before pushing more work.
print("pending jobs:", ch:getCount())

-- ---- Stub: Channel:clear -------------------------------------------------
--@api-stub: Channel:clear
-- Flush the channel before reuse -- call this when restarting a level to
-- discard stale results left over from the previous session.
print("items before clear:", ch:getCount())
ch:clear()
print("items after clear:", ch:getCount())  -- 0

-- ---- Stub: Channel:supply ------------------------------------------------
--@api-stub: Channel:supply
-- Like push but blocks when the channel is full -- use inside a worker to
-- prevent the output queue from growing unbounded under heavy load.
ch:supply("result_99")  -- blocks until there is room
print("value supplied to channel")

-- ---- Stub: Channel:pushTable ---------------------------------------------
--@api-stub: Channel:pushTable
-- Serialise a structured job description to send to a worker -- the worker
-- calls popTable() to get a proper Lua table on the other side.
local job_count = ch:pushTable({ type = "generate_tile", x = 5, y = 3 })
print("table job queued, queue depth:", job_count)

-- ---- Stub: Channel:popTable ----------------------------------------------
--@api-stub: Channel:popTable
-- Receive a structured result from a worker -- always pair with pushTable()
-- on the sender side so the data survives the serialisation round-trip.
local tile_data = ch:popTable()
if tile_data then
    print("tile received: x =", tile_data.x, "y =", tile_data.y)
end

-- ---- Stub: Channel:pushBytes ---------------------------------------------
--@api-stub: Channel:pushBytes
-- Send raw binary data (e.g. compressed chunk data) to a worker without
-- the overhead of Lua table serialisation.
local raw = "\0\1\2\3\4\5"
local depth = ch:pushBytes(raw)
print("binary blob pushed, queue depth:", depth)

-- ---- Stub: Channel:popBytes ----------------------------------------------
--@api-stub: Channel:popBytes
-- Receive the raw byte blob pushed by the producer side -- returned as a
-- Lua string so you can pass it to a decompressor or binary parser.
local blob = ch:popBytes()
if blob then
    print("received", #blob, "bytes")
end

-- -----------------------------------------------------------------------------
-- Promise methods
-- -----------------------------------------------------------------------------

-- ---- Stub: Promise:type --------------------------------------------------
--@api-stub: Promise:type
-- Confirm the object is a Promise before calling isDone() or result() --
-- helpful when a function returns either a Promise or an error string.
print(promise:type())  -- "Promise"

-- ---- Stub: Promise:typeOf ------------------------------------------------
--@api-stub: Promise:typeOf
-- Verify object kind in a generic dispatch function that handles
-- both Channel and Promise objects uniformly.
print(promise:typeOf("Promise"))  -- true

-- ---- Stub: Promise:isDone ------------------------------------------------
--@api-stub: Promise:isDone
-- Poll this from the main-loop process callback each frame -- the result
-- is ready only when isDone() returns true.
if promise:isDone() then
    local r = promise:result()
    print("async task finished, result:", r)
end

-- ---- Stub: Promise:result ------------------------------------------------
--@api-stub: Promise:result
-- Call only after isDone() returns true -- returns nil if the task errored
-- (check getError() in that case) or hasn't finished yet.
local res = promise:result()
if res ~= nil then
    print("computed sum:", res.sum)
end

-- ---- Stub: Promise:getError ----------------------------------------------
--@api-stub: Promise:getError
-- Always check getError() after isDone() to catch worker crashes and log
-- them before the promise is garbage-collected.
local err = promise:getError()
if err then
    print("async task failed:", err)
end

-- -----------------------------------------------------------------------------
-- ThreadHandle methods
-- -----------------------------------------------------------------------------

-- ---- Stub: ThreadHandle:type ---------------------------------------------
--@api-stub: ThreadHandle:type
-- Useful for generic dispatch or debug logging to confirm the variable
-- holds a ThreadHandle rather than a Pool or Promise.
print(worker:type())  -- "Thread"

-- ---- Stub: ThreadHandle:typeOf -------------------------------------------
--@api-stub: ThreadHandle:typeOf
-- Use in an assertion or guard before calling thread-specific methods
-- when a function can receive multiple object types.
print(worker:typeOf("Thread"))  -- true

-- ---- Stub: ThreadHandle:start --------------------------------------------
--@api-stub: ThreadHandle:start
-- Launch the thread after configuring shared channels -- passing args via
-- the named channel pattern is more explicit than varargs.
worker:start()
print("worker thread launched")

-- ---- Stub: ThreadHandle:wait ---------------------------------------------
--@api-stub: ThreadHandle:wait
-- Block the calling VM until the worker finishes -- only safe to call from a
-- dedicated worker VM or during loading screens, never from the game loop.
worker:wait()
print("worker finished")

-- ---- Stub: ThreadHandle:isRunning ----------------------------------------
--@api-stub: ThreadHandle:isRunning
-- Poll this from the main loop to decide when to drain the output channel
-- or to display a progress indicator during a long background operation.
if worker:isRunning() then
    print("worker still running...")
else
    print("worker has stopped")
end

-- ---- Stub: ThreadHandle:getError -----------------------------------------
--@api-stub: ThreadHandle:getError
-- Always check getError() after a worker stops unexpectedly to surface
-- crashes that would otherwise silently discard results.
local err = worker:getError()
if err then
    print("worker failed:", err)
end

-- -----------------------------------------------------------------------------
-- ThreadPool methods
-- -----------------------------------------------------------------------------

-- ---- Stub: ThreadPool:type -----------------------------------------------
--@api-stub: ThreadPool:type
-- Use to confirm a variable holds a pool before calling pool-specific
-- methods (submit, collect, join) on it.
print(pool:type())  -- "ThreadPool"

-- ---- Stub: ThreadPool:typeOf ---------------------------------------------
--@api-stub: ThreadPool:typeOf
-- Guard a generic dispatch function that can receive either a single
-- Thread or a ThreadPool so it calls the right API variant.
print(pool:typeOf("ThreadPool"))  -- true

-- ---- Stub: ThreadPool:submit ---------------------------------------------
--@api-stub: ThreadPool:submit
-- Send a job into the pool's shared input channel -- workers pick up jobs
-- in FIFO order; if all workers are busy the call returns immediately.
for i = 1, 16 do
    pool:submit({ tile_x = i, tile_y = 1 })
end
print("16 tile-generation jobs submitted to the pool")

-- ---- Stub: ThreadPool:collect --------------------------------------------
--@api-stub: ThreadPool:collect
-- Non-blocking drain of completed results -- call in the main-loop process
-- callback each frame to integrate finished work without stalling.
local result = pool:collect()
if result then
    print("tile ready: x =", result.tile_x)
end

-- ---- Stub: ThreadPool:size -----------------------------------------------
--@api-stub: ThreadPool:size
-- Read pool size to decide how many jobs to batch-submit to keep all
-- workers busy without swamping the input channel.
local workers = pool:size()
print("pool has", workers, "worker threads")
print("submit batches of", workers * 4, "jobs for optimal throughput")

-- ---- Stub: ThreadPool:join -----------------------------------------------
--@api-stub: ThreadPool:join
-- Block until every worker finishes -- use during a loading screen after
-- submitting all jobs to ensure results are ready before the game starts.
pool:join()
print("all pool workers finished -- world generation complete")

-- ---- Stub: ThreadPool:getInputChannel ------------------------------------
--@api-stub: ThreadPool:getInputChannel
-- Access the raw input channel to perform batch pushTable() calls or to
-- share the channel reference with a producer that lives in another module.
local inp = pool:getInputChannel()
inp:pushTable({ task = "generate", seed = 42 })
print("input channel queue depth:", inp:getCount())

-- ---- Stub: ThreadPool:getOutputChannel -----------------------------------
--@api-stub: ThreadPool:getOutputChannel
-- Access the raw output channel to call popTable() or drain all pending
-- results in a loop without using the convenience collect() wrapper.
local out = pool:getOutputChannel()
while out:getCount() > 0 do
    local item = out:popTable()
    print("worker result:", item)
end
