-- content/examples/tween.lua
-- Lurek2D lurek.tween API Reference
-- Run with: cargo run -- content/examples/tween

-- =============================================================================
-- STUBS: 35 uncovered lurek.tween API item(s)
-- Generated by tools/audit/example_add_missing.py
-- REQUIRED: replace every --@api-stub: block below with a real scenario.
-- Run .github/prompts/flesh-out-example.prompt.md for instructions.
-- The final committed file must contain ZERO --@api-stub: lines.
-- =============================================================================

-- ---- Stub: lurek.tween.update --------------------------------------------
--@api-stub: lurek.tween.update
-- Call this every frame from lurek.process(dt) -- without it no tween or
-- spring value will ever change no matter how many animations you started.
local demo_dt = 1 / 60
lurek.tween.update(demo_dt)
print("tween pool ticked, active:", lurek.tween.getActiveCount())

-- ---- Stub: lurek.tween.tween ---------------------------------------------
--@api-stub: lurek.tween.tween
-- Animate any numeric field on a Lua table smoothly to a target value.
-- Returns a Tween handle you can pause, repeat, or monitor for completion.
local player = { x = 0.0, y = 200.0, alpha = 1.0 }
local move_tween = lurek.tween.tween(player, { x = 640.0 }, 1.2, "easeOutCubic")
print("player.x will reach 640 in 1.2 s")

-- ---- Stub: lurek.tween.sequence ------------------------------------------
--@api-stub: lurek.tween.sequence
-- Chain animations so each step starts only after the previous one finishes --
-- ideal for cutscenes, dialog reveals, or multi-phase enemy entrances.
local enemy = { x = -80.0, y = 300.0, alpha = 0.0 }
local seq = lurek.tween.sequence()
seq:tween(enemy, { alpha = 1.0 }, 0.3, "linear")
seq:tween(enemy, { x = 200.0 }, 0.8, "easeOutBack")
seq:callback(function() print("enemy reached position") end)
seq:start()

-- ---- Stub: lurek.tween.parallel ------------------------------------------
--@api-stub: lurek.tween.parallel
-- Run multiple tweens simultaneously and get one handle for the whole group --
-- useful when you animate position + alpha + scale at the same time.
local panel = { x = 0.0, y = -100.0, alpha = 0.0 }
local par = lurek.tween.parallel()
par:tween(panel, { y = 0.0 }, 0.5, "easeOutQuad")
par:tween(panel, { alpha = 1.0 }, 0.5, "linear")
par:start()

-- ---- Stub: lurek.tween.delay ---------------------------------------------
--@api-stub: lurek.tween.delay
-- Fire a callback after a fixed delay without managing a manual timer --
-- or use delay() as a named pause step inside a TweenSequence.
local respawn_timer = lurek.tween.delay(3.0, function()
    print("3 s elapsed -- enemy respawned")
end)
print("respawn delay registered:", respawn_timer)

-- ---- Stub: lurek.tween.cancelAll -----------------------------------------
--@api-stub: lurek.tween.cancelAll
-- Stop every running animation in one call -- use when changing scenes to
-- prevent stale tweens from writing into freed or replaced game tables.
print("active before scene change:", lurek.tween.getActiveCount())
lurek.tween.cancelAll()
print("active after cancelAll:", lurek.tween.getActiveCount())  -- 0

-- ---- Stub: lurek.tween.getActiveCount ------------------------------------
--@api-stub: lurek.tween.getActiveCount
-- Use as a cheap per-frame diagnostic gauge to confirm animations drain
-- correctly and are not leaking across scene transitions.
local budget = 64
local n = lurek.tween.getActiveCount()
print(string.format("tween pool: %d / %d slots used", n, budget))
if n > budget then
    print("warning: tween budget exceeded -- check for infinite-repeat leaks")
end

-- ---- Stub: lurek.tween.registerEasing ------------------------------------
--@api-stub: lurek.tween.registerEasing
-- Register a custom curve so you can reference it by name in any tween call --
-- keeps animation code readable instead of embedding inline math functions.
lurek.tween.registerEasing("punchIn", function(t)
    -- sharp overshoot ease-in curve
    return t * t * ((2.70158 + 1) * t - 2.70158)
end)
print("custom 'punchIn' easing registered")

-- ---- Stub: lurek.tween.getEasingNames ------------------------------------
--@api-stub: lurek.tween.getEasingNames
-- Enumerate all available easings to populate a curve picker in an editor
-- or to confirm a required custom easing was registered before use.
local names = lurek.tween.getEasingNames()
print("available easing functions:")
for _, name in ipairs(names) do
    print("  " .. name)
end
print("total:", #names)

-- ---- Stub: lurek.tween.newState ------------------------------------------
--@api-stub: lurek.tween.newState
-- Use a bare TweenState when you want to drive interpolation manually --
-- for example to animate a shader uniform or run a custom blink effect.
local flicker_state = lurek.tween.newState(0.5, "easeInOutSine")
print("TweenState created: 0.5 s easeInOutSine")
-- advance manually each frame:
-- flicker_state:tick(dt)
-- local brightness = flicker_state:lerp(0.4, 1.0)

-- ---- Stub: lurek.tween.to ------------------------------------------------
--@api-stub: lurek.tween.to
-- Reads like "animate TO these values" -- prefer to() when the target table
-- already exists and you want concise, left-to-right readable code.
local coin = { x = 400.0, y = 50.0, alpha = 1.0 }
local collect_tween = lurek.tween.to(coin, { y = 600.0, alpha = 0.0 }, 0.5, "easeInQuad")
print("coin flying to HUD collection point over 0.5 s")

-- ---- Stub: lurek.tween.spring --------------------------------------------
--@api-stub: lurek.tween.spring
-- A spring converges to its target with natural overshoot and settling --
-- ideal for camera follow, cursor lag, or any "heavy object" motion feel.
local cam = { x = 0.0, y = 0.0 }
local spring = lurek.tween.spring(cam, { x = 320.0, y = 240.0 }, { stiffness = 80, damping = 12 })
print("camera spring started; cam will overshoot then settle at (320, 240)")

-- -----------------------------------------------------------------------------
-- Spring methods
-- -----------------------------------------------------------------------------

-- ---- Stub: Spring:update -------------------------------------------------
--@api-stub: Spring:update
-- Tick the spring forward in your process loop -- it writes new values into
-- the target table and returns false once the spring has fully settled.
local still_moving = spring:update(0.016)
if not still_moving then
    print("spring settled at", cam.x, cam.y)
end

-- ---- Stub: Spring:isSettled ----------------------------------------------
--@api-stub: Spring:isSettled
-- Settled means all axes are within a tiny threshold of the target --
-- poll this to trigger a landing sound or snap to the exact pixel position.
if spring:isSettled() then
    cam.x = math.floor(cam.x + 0.5)  -- snap to nearest pixel
    cam.y = math.floor(cam.y + 0.5)
    print("camera snapped to exact target")
end

-- ---- Stub: Spring:isActive -----------------------------------------------
--@api-stub: Spring:isActive
-- A cancelled spring is immediately inactive; a settled spring stays active
-- until explicitly cancelled.  Skip update() calls once the spring is done.
if spring:isActive() then
    spring:update(0.016)
else
    print("spring finished -- no need to tick it further")
end

-- ---- Stub: Spring:setTarget ----------------------------------------------
--@api-stub: Spring:setTarget
-- Redirect the spring mid-flight -- it smoothly steers toward the new target
-- while preserving current velocity so the motion stays continuous.
spring:setTarget({ x = 500.0, y = 300.0 })
print("camera spring redirected to (500, 300)")

-- ---- Stub: Spring:setStiffness -------------------------------------------
--@api-stub: Spring:setStiffness
-- Higher stiffness means faster response with more overshoot; lower values
-- give a heavy, sluggish feel.  Typical range: 20 (floaty) to 200 (snappy).
spring:setStiffness(120)
print("spring stiffness raised to 120 -- snappier camera response")

-- ---- Stub: Spring:setDamping ---------------------------------------------
--@api-stub: Spring:setDamping
-- Low damping = bouncy overshoot; high = overdamped with no oscillation.
-- Rule of thumb: critical damping is roughly 2 * sqrt(stiffness).
spring:setDamping(20)
print("spring damping lowered -- camera will bounce slightly on target changes")

-- ---- Stub: Spring:cancel -------------------------------------------------
--@api-stub: Spring:cancel
-- Remove the spring from the pool -- it is dropped on the next update(dt).
-- Call this when the player teleports or the tracked object is destroyed.
spring:cancel()
print("camera spring cancelled -- position is now static")

-- ---- Stub: Spring:getPosition --------------------------------------------
--@api-stub: Spring:getPosition
-- Read the live interpolated position of a single named axis without relying
-- on the target table write-back -- useful for debugging or compositing.
local cur_x = spring:getPosition("x")
local cur_y = spring:getPosition("y")
if cur_x and cur_y then
    print(string.format("spring pos: (%.1f, %.1f)", cur_x, cur_y))
end

-- -----------------------------------------------------------------------------
-- Tween methods
-- -----------------------------------------------------------------------------

-- ---- Stub: Tween:pause ---------------------------------------------------
--@api-stub: Tween:pause
-- Freeze the tween without cancelling it -- use while the game is paused so
-- movement or UI animations do not advance while input is blocked.
move_tween:pause()
print("move tween paused; player.x frozen at", player.x)

-- ---- Stub: Tween:resume --------------------------------------------------
--@api-stub: Tween:resume
-- Continue from the exact elapsed time the tween was at when paused --
-- the animation does not restart from the beginning.
move_tween:resume()
print("move tween resumed from", player.x)

-- ---- Stub: Tween:isActive ------------------------------------------------
--@api-stub: Tween:isActive
-- Gate follow-up actions on isActive so they only fire after the animation
-- fully completes rather than requiring a manual completion flag.
if move_tween:isActive() then
    print("player still moving, progress:", move_tween:getProgress())
else
    print("player arrived at x =", player.x)
end

-- ---- Stub: Tween:getProgress ---------------------------------------------
--@api-stub: Tween:getProgress
-- Raw 0..1 progress ignores easing and yoyo -- use it to drive a loading bar
-- that advances linearly while the animated property uses a curved easing.
local pct = move_tween:getProgress() * 100
print(string.format("player move: %.0f%% through its duration", pct))

-- ---- Stub: Tween:setRepeat -----------------------------------------------
--@api-stub: Tween:setRepeat
-- 0 = play once (default).  -1 = loop forever.  N = N extra cycles.
-- Combine with setYoyo(true) for a seamless ping-pong loop.
local pulse = lurek.tween.tween(player, { alpha = 0.2 }, 0.5, "easeInOutSine")
pulse:setRepeat(-1)  -- loop forever
pulse:setYoyo(true)  -- 1.0 -> 0.2 -> 1.0 -> ...
print("infinite pulse alpha tween started")

-- ---- Stub: Tween:setYoyo -------------------------------------------------
--@api-stub: Tween:setYoyo
-- Yoyo plays forward then backward each cycle, making looped animations
-- like hovering NPCs or breathing lights look seamless without a jump cut.
local hover = lurek.tween.tween(player, { y = player.y - 12 }, 0.7, "easeInOutSine")
hover:setRepeat(-1)
hover:setYoyo(true)
print("hover tween running: player bobs 12 px up and down")

-- -----------------------------------------------------------------------------
-- TweenParallel methods
-- -----------------------------------------------------------------------------

-- ---- Stub: TweenParallel:cancel ------------------------------------------
--@api-stub: TweenParallel:cancel
-- Stops all child tweens at once -- call this when the UI element the parallel
-- was animating gets destroyed before the group finished.
if par:isActive() then
    par:cancel()
    print("HUD panel entrance animation cancelled mid-flight")
end

-- ---- Stub: TweenParallel:isActive ----------------------------------------
--@api-stub: TweenParallel:isActive
-- True until every child tween in the group completes or the group is cancelled.
-- Use to gate follow-up actions that must wait for all animations to finish.
if par:isActive() then
    print("HUD panel still animating in...")
else
    print("HUD panel fully visible -- enable input")
end

-- -----------------------------------------------------------------------------
-- TweenSequence methods
-- -----------------------------------------------------------------------------

-- ---- Stub: TweenSequence:cancel ------------------------------------------
--@api-stub: TweenSequence:cancel
-- Abort all remaining steps immediately -- use when the player skips a
-- cutscene or the actor the sequence was driving is removed from the scene.
if seq:isActive() then
    seq:cancel()
    print("enemy entrance sequence cancelled by skip")
end

-- ---- Stub: TweenSequence:isActive ----------------------------------------
--@api-stub: TweenSequence:isActive
-- True while any step is still pending or running -- gate triggers that must
-- wait for the full sequence, like enabling a hitbox after a door-open anim.
if seq:isActive() then
    print("cutscene sequence in progress -- inputs locked")
else
    print("sequence complete -- gameplay resumed")
end

-- -----------------------------------------------------------------------------
-- TweenState methods
-- -----------------------------------------------------------------------------

-- ---- Stub: TweenState:tick -----------------------------------------------
--@api-stub: TweenState:tick
-- Manually advance the timing state each frame -- returns true when done so
-- you know when to stop ticking or reset for the next animation cycle.
local finished = flicker_state:tick(0.016)
if finished then
    print("flicker animation completed")
end

-- ---- Stub: TweenState:isComplete -----------------------------------------
--@api-stub: TweenState:isComplete
-- Use isComplete to decide when to restart the animation or advance to the
-- next step in a manual multi-stage effect pipeline.
if flicker_state:isComplete() then
    flicker_state:reset()  -- loop the effect
    print("flicker restarted")
end

-- ---- Stub: TweenState:t --------------------------------------------------
--@api-stub: TweenState:t
-- Raw un-eased 0..1 progress -- use to drive a progress bar that advances
-- linearly even when the animated value uses a curved easing function.
local raw_t = flicker_state:t()
print(string.format("flicker timeline: %.0f%%", raw_t * 100))

-- ---- Stub: TweenState:lerp -----------------------------------------------
--@api-stub: TweenState:lerp
-- Drive any numeric property using the easing baked into this state --
-- handy for shader uniforms or raw colour values needing a curved transition.
local brightness = flicker_state:lerp(0.3, 1.0)
print(string.format("light brightness: %.2f", brightness))
-- lurek.render.setShaderUniform("u_bright", brightness)

-- ---- Stub: TweenState:reset ----------------------------------------------
--@api-stub: TweenState:reset
-- Rewind to t=0 without recreating the object -- cheaper than newState() and
-- avoids GC pressure when the same animation loops many times per session.
flicker_state:reset()
print("flicker state rewound for the next animation cycle")
