-- Audio Bus and MidiPlayer integration tests (headless-safe)

describe("luna.audio.newBus", function()
    it("creates a bus with the given name", function()
        local bus = luna.audio.newBus("music")
        expect_equal(bus:getName(), "music")
    end)

    it("has default volume 1.0", function()
        local bus = luna.audio.newBus("test")
        expect_near(bus:getVolume(), 1.0, 1e-5)
    end)

    it("has default pitch 1.0", function()
        local bus = luna.audio.newBus("test")
        expect_near(bus:getPitch(), 1.0, 1e-5)
    end)

    it("is not paused by default", function()
        local bus = luna.audio.newBus("test")
        expect_false(bus:isPaused())
    end)
end)

describe("Bus:setVolume / getVolume", function()
    it("sets and gets volume", function()
        local bus = luna.audio.newBus("test")
        bus:setVolume(0.7)
        expect_near(bus:getVolume(), 0.7, 1e-5)
    end)

    it("clamps negative volume to 0", function()
        local bus = luna.audio.newBus("test")
        bus:setVolume(-1.0)
        expect_near(bus:getVolume(), 0.0, 1e-5)
    end)
end)

describe("Bus:setPitch / getPitch", function()
    it("sets and gets pitch", function()
        local bus = luna.audio.newBus("test")
        bus:setPitch(1.5)
        expect_near(bus:getPitch(), 1.5, 1e-5)
    end)

    it("clamps negative pitch to 0", function()
        local bus = luna.audio.newBus("test")
        bus:setPitch(-0.5)
        expect_near(bus:getPitch(), 0.0, 1e-5)
    end)
end)

describe("Bus:pause / resume / isPaused", function()
    it("pauses and resumes", function()
        local bus = luna.audio.newBus("test")
        bus:pause()
        expect_true(bus:isPaused())
        bus:resume()
        expect_false(bus:isPaused())
    end)
end)

describe("Bus type system", function()
    it("reports type as Bus", function()
        local bus = luna.audio.newBus("test")
        expect_equal(bus:type(), "Bus")
    end)

    it("typeOf returns true for Bus and Object", function()
        local bus = luna.audio.newBus("test")
        expect_true(bus:typeOf("Bus"))
        expect_true(bus:typeOf("Object"))
    end)
end)

describe("luna.audio.getMaxSources", function()
    it("returns 64", function()
        expect_equal(luna.audio.getMaxSources(), 64)
    end)
end)

describe("luna.audio.setListener2D / getListener2D stubs", function()
    it("setListener2D does not error", function()
        luna.audio.setListener2D(1.0, 2.0)
    end)

    it("getListener2D returns 0, 0", function()
        local x, y = luna.audio.getListener2D()
        expect_near(x, 0.0, 1e-5)
        expect_near(y, 0.0, 1e-5)
    end)
end)

describe("luna.audio.setMeter / getMeter stubs", function()
    it("setMeter does not error", function()
        luna.audio.setMeter(2.0)
    end)

    it("getMeter returns 1.0", function()
        expect_near(luna.audio.getMeter(), 1.0, 1e-5)
    end)
end)

describe("luna.audio.newMidiPlayer", function()
    it("creates a MidiPlayer", function()
        local midi = luna.audio.newMidiPlayer()
        expect_false(midi:isLoaded())
    end)

    it("is not playing by default", function()
        local midi = luna.audio.newMidiPlayer()
        expect_false(midi:isPlaying())
    end)

    it("has default volume 1.0", function()
        local midi = luna.audio.newMidiPlayer()
        expect_near(midi:getVolume(), 1.0, 1e-5)
    end)

    it("has default tempo scale 1.0", function()
        local midi = luna.audio.newMidiPlayer()
        expect_near(midi:getTempoScale(), 1.0, 1e-5)
    end)

    it("has 0 tracks when unloaded", function()
        local midi = luna.audio.newMidiPlayer()
        expect_equal(midi:getTrackCount(), 0)
    end)

    it("has 0 note count when unloaded", function()
        local midi = luna.audio.newMidiPlayer()
        expect_equal(midi:getNoteCount(), 0)
    end)
end)

describe("MidiPlayer volume", function()
    it("sets and gets volume", function()
        local midi = luna.audio.newMidiPlayer()
        midi:setVolume(0.5)
        expect_near(midi:getVolume(), 0.5, 1e-5)
    end)
end)

describe("MidiPlayer tempo", function()
    it("sets and gets tempo scale", function()
        local midi = luna.audio.newMidiPlayer()
        midi:setTempoScale(2.0)
        expect_near(midi:getTempoScale(), 2.0, 1e-5)
    end)

    it("getOriginalTempo returns 120 when unloaded", function()
        local midi = luna.audio.newMidiPlayer()
        expect_near(midi:getOriginalTempo(), 120.0, 1e-5)
    end)
end)

describe("MidiPlayer looping", function()
    it("toggles looping", function()
        local midi = luna.audio.newMidiPlayer()
        expect_false(midi:isLooping())
        midi:setLooping(true)
        expect_true(midi:isLooping())
        midi:setLooping(false)
        expect_false(midi:isLooping())
    end)
end)

describe("MidiPlayer channel control", function()
    it("sets and gets channel volume (1-indexed)", function()
        local midi = luna.audio.newMidiPlayer()
        midi:setChannelVolume(1, 0.5)
        expect_near(midi:getChannelVolume(1), 0.5, 1e-5)
    end)

    it("mutes and unmutes channel", function()
        local midi = luna.audio.newMidiPlayer()
        expect_false(midi:isChannelMuted(1))
        midi:setChannelMuted(1, true)
        expect_true(midi:isChannelMuted(1))
        midi:setChannelMuted(1, false)
        expect_false(midi:isChannelMuted(1))
    end)

    it("sets and gets channel instrument", function()
        local midi = luna.audio.newMidiPlayer()
        midi:setChannelInstrument(1, 42)
        expect_equal(midi:getChannelInstrument(1), 42)
    end)

    it("soloChannel mutes all others", function()
        local midi = luna.audio.newMidiPlayer()
        midi:soloChannel(5)
        expect_false(midi:isChannelMuted(5))
        expect_true(midi:isChannelMuted(1))
        expect_true(midi:isChannelMuted(16))
    end)

    it("unsoloAll unmutes all", function()
        local midi = luna.audio.newMidiPlayer()
        midi:soloChannel(5)
        midi:unsoloAll()
        expect_false(midi:isChannelMuted(1))
        expect_false(midi:isChannelMuted(5))
        expect_false(midi:isChannelMuted(16))
    end)
end)

describe("MidiPlayer stubs", function()
    it("setSoundFont does not error", function()
        local midi = luna.audio.newMidiPlayer()
        midi:setSoundFont("path/to/sf2")
    end)

    it("useDefaultSoundFont does not error", function()
        local midi = luna.audio.newMidiPlayer()
        midi:useDefaultSoundFont()
    end)

    it("getSoundFontPath returns nil", function()
        local midi = luna.audio.newMidiPlayer()
        expect_equal(midi:getSoundFontPath(), nil)
    end)

    it("setOnNoteOn does not error", function()
        local midi = luna.audio.newMidiPlayer()
        midi:setOnNoteOn(function() end)
    end)

    it("setOnNoteOff does not error", function()
        local midi = luna.audio.newMidiPlayer()
        midi:setOnNoteOff(function() end)
    end)

    it("setOnEnd does not error", function()
        local midi = luna.audio.newMidiPlayer()
        midi:setOnEnd(function() end)
    end)
end)

describe("MidiPlayer type system", function()
    it("reports type as MidiPlayer", function()
        local midi = luna.audio.newMidiPlayer()
        expect_equal(midi:type(), "MidiPlayer")
    end)

    it("typeOf returns true for MidiPlayer and Object", function()
        local midi = luna.audio.newMidiPlayer()
        expect_true(midi:typeOf("MidiPlayer"))
        expect_true(midi:typeOf("Object"))
    end)
end)

describe("MidiPlayer seek/tell", function()
    it("seek and tell work", function()
        local midi = luna.audio.newMidiPlayer()
        midi:seek(5.0)
        expect_near(midi:tell(), 5.0, 1e-5)
    end)

    it("seek clamps negative to 0", function()
        local midi = luna.audio.newMidiPlayer()
        midi:seek(-1.0)
        expect_near(midi:tell(), 0.0, 1e-5)
    end)
end)

describe("MidiPlayer getDuration", function()
    it("returns 0 when unloaded", function()
        local midi = luna.audio.newMidiPlayer()
        expect_near(midi:getDuration(), 0.0, 1e-5)
    end)
end)

test_summary()
