-- tests/lua/unit/test_raycaster_sprite_manager.lua
-- BDD tests for lurek.raycaster.newSpriteManager batch depth-sorting.

describe("raycaster sprite manager", function()
  it("newSpriteManager returns a userdata", function()
    local sm = lurek.raycaster.newSpriteManager()
    expect_equal(type(sm), "userdata")
  end)

  it("type() returns SpriteManager", function()
    local sm = lurek.raycaster.newSpriteManager()
    expect_equal(sm:type(), "SpriteManager")
  end)

  it("add returns a numeric id", function()
    local sm = lurek.raycaster.newSpriteManager()
    local id = sm:add(10, 10, "barrel.png")
    expect_equal(type(id), "number")
  end)

  it("ids are unique and incrementing", function()
    local sm = lurek.raycaster.newSpriteManager()
    local a = sm:add(1, 1, "a.png")
    local b = sm:add(2, 2, "b.png")
    expect_equal(a ~= b, true)
  end)

  it("remove does not error when id exists", function()
    local sm = lurek.raycaster.newSpriteManager()
    local id = sm:add(10, 10, "barrel.png")
    sm:remove(id)
    expect_equal(true, true)
  end)

  it("remove is silent for unknown id", function()
    local sm = lurek.raycaster.newSpriteManager()
    sm:remove(9999)
    expect_equal(true, true)
  end)

  it("clear empties all sprites", function()
    local sm = lurek.raycaster.newSpriteManager()
    sm:add(1, 1, "a.png")
    sm:add(2, 2, "b.png")
    sm:clear()
    local proj = sm:sortAndProject(0, 0, 0.0)
    expect_equal(#proj, 0)
  end)

  it("sortAndProject returns a table", function()
    local sm = lurek.raycaster.newSpriteManager()
    sm:add(5, 5, "enemy.png")
    local projected = sm:sortAndProject(0, 0, 0.0)
    expect_equal(type(projected), "table")
  end)

  it("sortAndProject result has correct length", function()
    local sm = lurek.raycaster.newSpriteManager()
    sm:add(2, 0, "near.png")
    sm:add(10, 0, "far.png")
    local proj = sm:sortAndProject(0, 0, 0.0)
    expect_equal(#proj, 2)
  end)

  it("sortAndProject sorts far sprites first (back-to-front)", function()
    local sm = lurek.raycaster.newSpriteManager()
    sm:add(2, 0, "near.png")
    sm:add(10, 0, "far.png")
    local proj = sm:sortAndProject(0, 0, 0.0)
    expect_equal(proj[1].texture, "far.png")
    expect_equal(proj[2].texture, "near.png")
  end)

  it("sortAndProject entry contains distance field", function()
    local sm = lurek.raycaster.newSpriteManager()
    sm:add(3, 4, "enemy.png")   -- 5 units from origin
    local proj = sm:sortAndProject(0, 0, 0.0)
    expect_equal(#proj, 1)
    expect_near(proj[1].distance, 5.0, 0.01)
  end)

  it("setPosition updates world coordinates", function()
    local sm = lurek.raycaster.newSpriteManager()
    local id = sm:add(0, 0, "item.png")
    sm:setPosition(id, 3, 4)
    local proj = sm:sortAndProject(0, 0, 0.0)
    expect_near(proj[1].distance, 5.0, 0.01)
  end)

  it("setVisible(false) hides sprite from projection", function()
    local sm = lurek.raycaster.newSpriteManager()
    local id = sm:add(5, 5, "ghost.png")
    sm:setVisible(id, false)
    local proj = sm:sortAndProject(0, 0, 0.0)
    expect_equal(#proj, 0)
  end)

  it("setVisible(true) re-shows hidden sprite", function()
    local sm = lurek.raycaster.newSpriteManager()
    local id = sm:add(5, 5, "ghost.png")
    sm:setVisible(id, false)
    sm:setVisible(id, true)
    local proj = sm:sortAndProject(0, 0, 0.0)
    expect_equal(#proj, 1)
  end)
end)

test_summary()
