-- tests/lua/unit/test_image.lua
-- BDD tests for lurek.image ImageData APIs, including image construction, layered images, save/load helpers, and effect-method coverage in the headless VM.

-- The headless VM has no filesystem, GPU, audio, or window APIs.
-- All tests use lurek.image.newImageData(w, h) for image construction.

-- =============================================================================
-- Compressed API (existing tests)
-- =============================================================================

describe("lurek.image compressed API", function()
    -- @covers lurek.image.isCompressed
    -- @covers lurek.image.loadImage
    -- @covers lurek.image.loadLayered
    -- @covers lurek.image.newCompressedData
    -- @covers lurek.image.newImageData
    -- @covers lurek.image.newLayeredImage
    -- @covers lurek.image.saveImage
    -- @covers lurek.image.saveLayered
    it("lurek.image is a table", function()
        expect_type("table", lurek.image)
    end)

    it("newCompressedData is a function", function()
        expect_type("function", lurek.image.newCompressedData)
    end)

    it("isCompressed is a function", function()
        expect_type("function", lurek.image.isCompressed)
    end)

    it("newCompressedData errors on missing file", function()
        expect_error(function()
            lurek.image.newCompressedData("nonexistent_file.dds")
        end)
    end)

    it("isCompressed returns false for a missing path", function()
        local result = lurek.image.isCompressed("nonexistent_file.dds")
        expect_equal(result, false)
    end)
end)

-- =============================================================================
-- Basic API (existing tests)
-- =============================================================================

describe("lurek.image existing API still works", function()
    it("newImageData is a function", function()
        expect_type("function", lurek.image.newImageData)
    end)

    it("newImageData creates a blank buffer", function()
        local img = lurek.image.newImageData(4, 4)
        expect_type("userdata", img)
    end)
end)

-- =============================================================================
-- Effect method existence  - one it per effect
-- =============================================================================

describe("ImageData effect method existence", function()
    local img
    before_each(function()
        img = lurek.image.newImageData(4, 4)
    end)

    it("brightness is a function", function()
        expect_type("function", img.brightness)
    end)

    it("contrast is a function", function()
        expect_type("function", img.contrast)
    end)

    it("saturation is a function", function()
        expect_type("function", img.saturation)
    end)

    it("gamma is a function", function()
        expect_type("function", img.gamma)
    end)

    it("tint is a function", function()
        expect_type("function", img.tint)
    end)

    it("grayscale is a function", function()
        expect_type("function", img.grayscale)
    end)

    it("sepia is a function", function()
        expect_type("function", img.sepia)
    end)

    it("invert is a function", function()
        expect_type("function", img.invert)
    end)

    it("threshold is a function", function()
        expect_type("function", img.threshold)
    end)

    it("posterize is a function", function()
        expect_type("function", img.posterize)
    end)

    it("fill is a function", function()
        expect_type("function", img.fill)
    end)

    it("noise is a function", function()
        expect_type("function", img.noise)
    end)

    it("alphaMask is a function", function()
        expect_type("function", img.alphaMask)
    end)

    it("flipHorizontal is a function", function()
        expect_type("function", img.flipHorizontal)
    end)

    it("flipVertical is a function", function()
        expect_type("function", img.flipVertical)
    end)

    it("rotate90cw is a function", function()
        expect_type("function", img.rotate90cw)
    end)

    it("crop is a function", function()
        expect_type("function", img.crop)
    end)

    it("resizeNearest is a function", function()
        expect_type("function", img.resizeNearest)
    end)

    it("blur is a function", function()
        expect_type("function", img.blur)
    end)

    it("sharpen is a function", function()
        expect_type("function", img.sharpen)
    end)
end)

-- =============================================================================
-- Color / Tone effects
-- =============================================================================

describe("ImageData color/tone effects: brightness", function()
    it("brightness factor=2 brightens a mid-grey pixel", function()
        local img = lurek.image.newImageData(1, 1)
        img:setPixel(0, 0, 128, 128, 128, 255)
        img:brightness(2.0)
        local r, g, b, a = img:getPixel(0, 0)
        -- 128 * 2 = 256, clamped to 255
        expect_equal(r >= 200, true)
        expect_equal(g >= 200, true)
        expect_equal(b >= 200, true)
        expect_equal(a, 255)
    end)

    it("brightness factor=1 leaves pixel unchanged", function()
        local img = lurek.image.newImageData(1, 1)
        img:setPixel(0, 0, 100, 150, 200, 255)
        img:brightness(1.0)
        local r, g, b, a = img:getPixel(0, 0)
        expect_equal(r, 100)
        expect_equal(g, 150)
        expect_equal(b, 200)
        expect_equal(a, 255)
    end)

    it("brightness returns nil (in-place)", function()
        local img = lurek.image.newImageData(1, 1)
        local ret = img:brightness(1.0)
        expect_equal(ret, nil)
    end)
end)

describe("ImageData color/tone effects: contrast", function()
    it("contrast factor=1 leaves pixel unchanged", function()
        local img = lurek.image.newImageData(1, 1)
        img:setPixel(0, 0, 128, 200, 50, 255)
        -- ((ch - 128)*1 + 128) = ch exactly
        img:contrast(1.0)
        local r, g, b, a = img:getPixel(0, 0)
        expect_equal(r, 128)
        expect_equal(g, 200)
        expect_equal(b, 50)
        expect_equal(a, 255)
    end)

    it("contrast factor=2 increases distance from mid-grey", function()
        local img = lurek.image.newImageData(1, 1)
        img:setPixel(0, 0, 200, 200, 200, 255)
        img:contrast(2.0)
        local r, _, _, _ = img:getPixel(0, 0)
        -- ((200 - 128)*2 + 128) = 72*2 + 128 = 272, clamped to 255
        expect_equal(r, 255)
    end)

    it("contrast returns nil (in-place)", function()
        local img = lurek.image.newImageData(1, 1)
        local ret = img:contrast(1.0)
        expect_equal(ret, nil)
    end)
end)

describe("ImageData color/tone effects: saturation", function()
    it("saturation factor=0 desaturates a pure-red pixel to grey", function()
        local img = lurek.image.newImageData(1, 1)
        img:setPixel(0, 0, 255, 0, 0, 255)
        img:saturation(0.0)
        local r, g, b, a = img:getPixel(0, 0)
        -- All channels interpolated to luma  54; must be equal within rounding
        expect_equal(math.abs(r - g) <= 2, true)
        expect_equal(math.abs(g - b) <= 2, true)
        expect_equal(a, 255)
    end)

    it("saturation factor=1 leaves pixel unchanged", function()
        local img = lurek.image.newImageData(1, 1)
        img:setPixel(0, 0, 100, 150, 200, 255)
        img:saturation(1.0)
        local r, g, b, a = img:getPixel(0, 0)
        expect_equal(r, 100)
        expect_equal(g, 150)
        expect_equal(b, 200)
        expect_equal(a, 255)
    end)

    it("saturation returns nil (in-place)", function()
        local img = lurek.image.newImageData(1, 1)
        local ret = img:saturation(1.0)
        expect_equal(ret, nil)
    end)
end)

describe("ImageData color/tone effects: gamma", function()
    it("gamma 1.0 leaves pixel unchanged (within rounding)", function()
        local img = lurek.image.newImageData(1, 1)
        img:setPixel(0, 0, 100, 150, 200, 255)
        img:gamma(1.0)
        local r, g, b, a = img:getPixel(0, 0)
        -- (ch/255)^(1/1.0)*255 = ch exactly (up to rounding)
        expect_equal(math.abs(r - 100) <= 1, true)
        expect_equal(math.abs(g - 150) <= 1, true)
        expect_equal(math.abs(b - 200) <= 1, true)
        expect_equal(a, 255)
    end)

    it("gamma > 1 brightens mid-tones", function()
        local img = lurek.image.newImageData(1, 1)
        img:setPixel(0, 0, 128, 128, 128, 255)
        img:gamma(2.0)
        local r, _, _, _ = img:getPixel(0, 0)
        -- (128/255)^0.5 * 255  180; must be brighter than 128
        expect_equal(r > 128, true)
    end)

    it("gamma returns nil (in-place)", function()
        local img = lurek.image.newImageData(1, 1)
        local ret = img:gamma(1.0)
        expect_equal(ret, nil)
    end)
end)

describe("ImageData color/tone effects: tint", function()
    it("tint factor=1.0 replaces RGB with tint colour, preserving alpha", function()
        local img = lurek.image.newImageData(1, 1)
        img:setPixel(0, 0, 128, 64, 32, 200)
        img:tint(0, 255, 0, 1.0)
        local r, g, b, a = img:getPixel(0, 0)
        -- lerp(original, tint, 1.0) = tint exactly
        expect_equal(r, 0)
        expect_equal(g, 255)
        expect_equal(b, 0)
        expect_equal(a, 200)
    end)

    it("tint factor=0 leaves pixel unchanged", function()
        local img = lurek.image.newImageData(1, 1)
        img:setPixel(0, 0, 100, 150, 200, 255)
        img:tint(0, 255, 0, 0.0)
        local r, g, b, a = img:getPixel(0, 0)
        expect_equal(r, 100)
        expect_equal(g, 150)
        expect_equal(b, 200)
        expect_equal(a, 255)
    end)

    it("tint returns nil (in-place)", function()
        local img = lurek.image.newImageData(1, 1)
        local ret = img:tint(255, 0, 0, 0.5)
        expect_equal(ret, nil)
    end)
end)

-- =============================================================================
-- Filter effects
-- =============================================================================

describe("ImageData filter effects: grayscale", function()
    it("grayscale makes r==g==b for a pure-red pixel", function()
        local img = lurek.image.newImageData(1, 1)
        img:setPixel(0, 0, 255, 0, 0, 255)
        img:grayscale()
        local r, g, b, a = img:getPixel(0, 0)
        expect_equal(r, g)
        expect_equal(g, b)
        expect_equal(a, 255)
    end)

    it("grayscale makes r==g==b for a pure-blue pixel", function()
        local img = lurek.image.newImageData(1, 1)
        img:setPixel(0, 0, 0, 0, 255, 255)
        img:grayscale()
        local r, g, b, _ = img:getPixel(0, 0)
        expect_equal(r, g)
        expect_equal(g, b)
    end)

    it("grayscale returns nil (in-place)", function()
        local img = lurek.image.newImageData(1, 1)
        local ret = img:grayscale()
        expect_equal(ret, nil)
    end)
end)

describe("ImageData filter effects: sepia", function()
    it("sepia produces warm-toned output on a red pixel", function()
        local img = lurek.image.newImageData(1, 1)
        img:setPixel(0, 0, 255, 0, 0, 255)
        img:sepia()
        local r, g, b, a = img:getPixel(0, 0)
        -- sepia: r100, g89, b69  - all positive, r >= g >= b
        expect_equal(r > 0, true)
        expect_equal(g > 0, true)
        expect_equal(b > 0, true)
        expect_equal(r >= g, true)
        expect_equal(g >= b, true)
        expect_equal(a, 255)
    end)

    it("sepia leaves alpha unchanged", function()
        local img = lurek.image.newImageData(1, 1)
        img:setPixel(0, 0, 200, 100, 50, 128)
        img:sepia()
        local _, _, _, a = img:getPixel(0, 0)
        expect_equal(a, 128)
    end)

    it("sepia returns nil (in-place)", function()
        local img = lurek.image.newImageData(1, 1)
        local ret = img:sepia()
        expect_equal(ret, nil)
    end)
end)

describe("ImageData filter effects: invert", function()
    it("invert inverts RGB channels, leaving alpha unchanged", function()
        local img = lurek.image.newImageData(1, 1)
        img:setPixel(0, 0, 100, 150, 200, 255)
        img:invert()
        local r, g, b, a = img:getPixel(0, 0)
        -- 255 - 100 = 155, 255 - 150 = 105, 255 - 200 = 55
        expect_equal(math.abs(r - 155) <= 2, true)
        expect_equal(math.abs(g - 105) <= 2, true)
        expect_equal(math.abs(b - 55) <= 2, true)
        expect_equal(a, 255)
    end)

    it("invert applied twice returns to original", function()
        local img = lurek.image.newImageData(1, 1)
        img:setPixel(0, 0, 80, 120, 200, 200)
        img:invert()
        img:invert()
        local r, g, b, a = img:getPixel(0, 0)
        expect_equal(r, 80)
        expect_equal(g, 120)
        expect_equal(b, 200)
        expect_equal(a, 200)
    end)

    it("invert returns nil (in-place)", function()
        local img = lurek.image.newImageData(1, 1)
        local ret = img:invert()
        expect_equal(ret, nil)
    end)
end)

describe("ImageData filter effects: threshold", function()
    it("threshold above value produces white pixel", function()
        local img = lurek.image.newImageData(1, 1)
        img:setPixel(0, 0, 255, 255, 255, 255)  -- luma=255 >= 128
        img:threshold(128)
        local r, g, b, _ = img:getPixel(0, 0)
        expect_equal(r, 255)
        expect_equal(g, 255)
        expect_equal(b, 255)
    end)

    it("threshold below value produces black pixel", function()
        local img = lurek.image.newImageData(1, 1)
        img:setPixel(0, 0, 10, 10, 10, 255)  -- luma10 < 128
        img:threshold(128)
        local r, g, b, _ = img:getPixel(0, 0)
        expect_equal(r, 0)
        expect_equal(g, 0)
        expect_equal(b, 0)
    end)

    it("threshold leaves alpha unchanged", function()
        local img = lurek.image.newImageData(1, 1)
        img:setPixel(0, 0, 200, 200, 200, 99)
        img:threshold(128)
        local _, _, _, a = img:getPixel(0, 0)
        expect_equal(a, 99)
    end)

    it("threshold returns nil (in-place)", function()
        local img = lurek.image.newImageData(1, 1)
        local ret = img:threshold(128)
        expect_equal(ret, nil)
    end)
end)

describe("ImageData filter effects: posterize", function()
    it("posterize levels=2 maps each channel to 0 or 255", function()
        local img = lurek.image.newImageData(1, 1)
        img:setPixel(0, 0, 200, 50, 128, 255)
        img:posterize(2)
        local r, g, b, a = img:getPixel(0, 0)
        expect_equal(r == 0 or r == 255, true)
        expect_equal(g == 0 or g == 255, true)
        expect_equal(b == 0 or b == 255, true)
        expect_equal(a, 255)
    end)

    it("posterize leaves alpha unchanged", function()
        local img = lurek.image.newImageData(1, 1)
        img:setPixel(0, 0, 100, 100, 100, 77)
        img:posterize(4)
        local _, _, _, a = img:getPixel(0, 0)
        expect_equal(a, 77)
    end)

    it("posterize returns nil (in-place)", function()
        local img = lurek.image.newImageData(1, 1)
        local ret = img:posterize(4)
        expect_equal(ret, nil)
    end)
end)

describe("ImageData filter effects: fill", function()
    it("fill sets all pixels to the given RGBA colour", function()
        local img = lurek.image.newImageData(4, 4)
        img:fill(255, 0, 0, 255)
        local r, g, b, a = img:getPixel(0, 0)
        expect_equal(r, 255)
        expect_equal(g, 0)
        expect_equal(b, 0)
        expect_equal(a, 255)
    end)

    it("fill sets a corner pixel too", function()
        local img = lurek.image.newImageData(4, 4)
        img:fill(0, 128, 255, 200)
        local r, g, b, a = img:getPixel(3, 3)
        expect_equal(r, 0)
        expect_equal(g, 128)
        expect_equal(b, 255)
        expect_equal(a, 200)
    end)

    it("fill returns nil (in-place)", function()
        local img = lurek.image.newImageData(1, 1)
        local ret = img:fill(0, 0, 0, 255)
        expect_equal(ret, nil)
    end)
end)

describe("ImageData filter effects: noise", function()
    it("noise(0) leaves pixels exactly unchanged", function()
        local img = lurek.image.newImageData(1, 1)
        img:setPixel(0, 0, 100, 150, 200, 255)
        img:noise(0)
        local r, g, b, a = img:getPixel(0, 0)
        expect_equal(r, 100)
        expect_equal(g, 150)
        expect_equal(b, 200)
        expect_equal(a, 255)
    end)

    it("noise(0) leaves alpha unchanged on a transparent pixel", function()
        local img = lurek.image.newImageData(1, 1)
        img:setPixel(0, 0, 50, 50, 50, 128)
        img:noise(0)
        local _, _, _, a = img:getPixel(0, 0)
        expect_equal(a, 128)
    end)

    it("noise returns nil (in-place)", function()
        local img = lurek.image.newImageData(1, 1)
        local ret = img:noise(0)
        expect_equal(ret, nil)
    end)
end)

describe("ImageData filter effects: alphaMask", function()
    it("alphaMask(0.5) halves the alpha channel", function()
        local img = lurek.image.newImageData(1, 1)
        img:setPixel(0, 0, 128, 64, 255, 200)
        img:alphaMask(0.5)
        local r, g, b, a = img:getPixel(0, 0)
        -- alpha = floor/round(200 * 0.5) = 100; RGB unchanged
        expect_equal(math.abs(a - 100) <= 2, true)
        expect_equal(r, 128)
        expect_equal(g, 64)
        expect_equal(b, 255)
    end)

    it("alphaMask(1.0) leaves alpha unchanged", function()
        local img = lurek.image.newImageData(1, 1)
        img:setPixel(0, 0, 100, 100, 100, 180)
        img:alphaMask(1.0)
        local _, _, _, a = img:getPixel(0, 0)
        expect_equal(a, 180)
    end)

    it("alphaMask(0.0) makes pixel fully transparent", function()
        local img = lurek.image.newImageData(1, 1)
        img:setPixel(0, 0, 255, 255, 255, 200)
        img:alphaMask(0.0)
        local _, _, _, a = img:getPixel(0, 0)
        expect_equal(a, 0)
    end)

    it("alphaMask returns nil (in-place)", function()
        local img = lurek.image.newImageData(1, 1)
        local ret = img:alphaMask(1.0)
        expect_equal(ret, nil)
    end)
end)

-- =============================================================================
-- Geometric in-place effects
-- =============================================================================

describe("ImageData geometric in-place: flipHorizontal", function()
    it("flipHorizontal mirrors pixel from column 0 to column 3 in a 4-wide image", function()
        local img = lurek.image.newImageData(4, 1)
        img:setPixel(0, 0, 255, 0, 0, 255)    -- red at left
        img:setPixel(3, 0, 0, 0, 255, 255)    -- blue at right
        img:flipHorizontal()
        local r0, _, b0, _ = img:getPixel(0, 0)  -- was right edge  now blue
        local r3, _, b3, _ = img:getPixel(3, 0)  -- was left edge   now red
        expect_equal(b0, 255)
        expect_equal(r3, 255)
    end)

    it("flipHorizontal preserves image dimensions", function()
        local img = lurek.image.newImageData(4, 2)
        img:flipHorizontal()
        expect_equal(img:getWidth(), 4)
        expect_equal(img:getHeight(), 2)
    end)

    it("flipHorizontal applied twice returns to original", function()
        local img = lurek.image.newImageData(4, 1)
        img:setPixel(0, 0, 200, 100, 50, 255)
        img:flipHorizontal()
        img:flipHorizontal()
        local r, g, b, a = img:getPixel(0, 0)
        expect_equal(r, 200)
        expect_equal(g, 100)
        expect_equal(b, 50)
        expect_equal(a, 255)
    end)

    it("flipHorizontal returns nil (in-place)", function()
        local img = lurek.image.newImageData(2, 2)
        local ret = img:flipHorizontal()
        expect_equal(ret, nil)
    end)
end)

describe("ImageData geometric in-place: flipVertical", function()
    it("flipVertical mirrors pixel from row 0 to row 3 in a 4-tall image", function()
        local img = lurek.image.newImageData(1, 4)
        img:setPixel(0, 0, 255, 0, 0, 255)    -- red at top
        img:setPixel(0, 3, 0, 0, 255, 255)    -- blue at bottom
        img:flipVertical()
        local r0, _, b0, _ = img:getPixel(0, 0)  -- was bottom  now blue
        local r3, _, b3, _ = img:getPixel(0, 3)  -- was top     now red
        expect_equal(b0, 255)
        expect_equal(r3, 255)
    end)

    it("flipVertical preserves image dimensions", function()
        local img = lurek.image.newImageData(2, 4)
        img:flipVertical()
        expect_equal(img:getWidth(), 2)
        expect_equal(img:getHeight(), 4)
    end)

    it("flipVertical applied twice returns to original", function()
        local img = lurek.image.newImageData(1, 4)
        img:setPixel(0, 0, 200, 100, 50, 255)
        img:flipVertical()
        img:flipVertical()
        local r, g, b, a = img:getPixel(0, 0)
        expect_equal(r, 200)
        expect_equal(g, 100)
        expect_equal(b, 50)
        expect_equal(a, 255)
    end)

    it("flipVertical returns nil (in-place)", function()
        local img = lurek.image.newImageData(2, 2)
        local ret = img:flipVertical()
        expect_equal(ret, nil)
    end)
end)

-- =============================================================================
-- Geometric new-image effects
-- =============================================================================

describe("ImageData geometric new-image: rotate90cw", function()
    it("rotate90cw returns a new userdata", function()
        local img = lurek.image.newImageData(4, 2)
        local out = img:rotate90cw()
        expect_type("userdata", out)
    end)

    it("rotate90cw swaps dimensions (4x2  2x4)", function()
        local img = lurek.image.newImageData(4, 2)
        local out = img:rotate90cw()
        expect_equal(out:getWidth(), 2)
        expect_equal(out:getHeight(), 4)
    end)

    it("rotate90cw on a square returns the same dimensions", function()
        local img = lurek.image.newImageData(4, 4)
        local out = img:rotate90cw()
        expect_equal(out:getWidth(), 4)
        expect_equal(out:getHeight(), 4)
    end)

    it("rotate90cw returns a distinct object from the source", function()
        local img = lurek.image.newImageData(4, 4)
        local out = img:rotate90cw()
        -- Modify source after rotation; output must be unaffected
        img:fill(255, 0, 0, 255)
        local r, _, _, _ = out:getPixel(0, 0)
        expect_equal(r, 0)  -- out was blank before fill
    end)
end)

describe("ImageData geometric new-image: crop", function()
    it("crop returns a new userdata", function()
        local img = lurek.image.newImageData(4, 4)
        local out = img:crop(0, 0, 2, 2)
        expect_type("userdata", out)
    end)

    it("crop(0,0,2,2) on a 4x4 image produces a 2x2 image", function()
        local img = lurek.image.newImageData(4, 4)
        local out = img:crop(0, 0, 2, 2)
        expect_equal(out:getWidth(), 2)
        expect_equal(out:getHeight(), 2)
    end)

    it("crop copies pixel values from the source region", function()
        local img = lurek.image.newImageData(4, 4)
        img:setPixel(1, 1, 200, 100, 50, 255)
        local out = img:crop(1, 1, 2, 2)  -- region starting at (1,1)
        local r, g, b, a = out:getPixel(0, 0)  -- (1,1) in src  (0,0) in crop
        expect_equal(r, 200)
        expect_equal(g, 100)
        expect_equal(b, 50)
        expect_equal(a, 255)
    end)

    it("crop out-of-bounds raises an error", function()
        local img = lurek.image.newImageData(4, 4)
        expect_error(function()
            img:crop(3, 3, 5, 5)  -- 3+5=8 > 4, out of bounds
        end)
    end)

    it("crop zero-width raises an error", function()
        local img = lurek.image.newImageData(4, 4)
        expect_error(function()
            img:crop(0, 0, 0, 2)  -- w=0 is invalid
        end)
    end)
end)

describe("ImageData geometric new-image: resizeNearest", function()
    it("resizeNearest returns a new userdata", function()
        local img = lurek.image.newImageData(4, 4)
        local out = img:resizeNearest(2, 2)
        expect_type("userdata", out)
    end)

    it("resizeNearest(2,2) downscales a 4x4 to 2x2", function()
        local img = lurek.image.newImageData(4, 4)
        local out = img:resizeNearest(2, 2)
        expect_equal(out:getWidth(), 2)
        expect_equal(out:getHeight(), 2)
    end)

    it("resizeNearest(8,8) upscales a 4x4 to 8x8", function()
        local img = lurek.image.newImageData(4, 4)
        local out = img:resizeNearest(8, 8)
        expect_equal(out:getWidth(), 8)
        expect_equal(out:getHeight(), 8)
    end)

    it("resizeNearest preserves top-left pixel colour", function()
        local img = lurek.image.newImageData(4, 4)
        img:setPixel(0, 0, 200, 100, 50, 255)
        local out = img:resizeNearest(2, 2)
        local r, g, b, a = out:getPixel(0, 0)
        expect_equal(r, 200)
        expect_equal(g, 100)
        expect_equal(b, 50)
        expect_equal(a, 255)
    end)
end)

-- =============================================================================
-- Convolution effects
-- =============================================================================

describe("ImageData convolution: blur", function()
    it("blur(0) returns a new userdata", function()
        local img = lurek.image.newImageData(4, 4)
        local out = img:blur(0)
        expect_type("userdata", out)
    end)

    it("blur(0) returns an image with the same dimensions", function()
        local img = lurek.image.newImageData(4, 4)
        local out = img:blur(0)
        expect_equal(out:getWidth(), 4)
        expect_equal(out:getHeight(), 4)
    end)

    it("blur(1) returns an image with the same dimensions", function()
        local img = lurek.image.newImageData(4, 4)
        local out = img:blur(1)
        expect_equal(out:getWidth(), 4)
        expect_equal(out:getHeight(), 4)
    end)

    it("blur(0) preserves pixel values (returns a clone)", function()
        local img = lurek.image.newImageData(4, 4)
        img:fill(100, 150, 200, 255)
        local out = img:blur(0)
        local r, g, b, a = out:getPixel(1, 1)
        expect_equal(r, 100)
        expect_equal(g, 150)
        expect_equal(b, 200)
        expect_equal(a, 255)
    end)

    it("blur(1) on a solid-colour image preserves colour", function()
        local img = lurek.image.newImageData(4, 4)
        img:fill(80, 120, 160, 255)
        local out = img:blur(1)
        -- All neighbours are the same; box average = same value
        local r, g, b, a = out:getPixel(1, 1)
        expect_equal(r, 80)
        expect_equal(g, 120)
        expect_equal(b, 160)
        expect_equal(a, 255)
    end)
end)

describe("ImageData convolution: sharpen", function()
    it("sharpen returns a new userdata", function()
        local img = lurek.image.newImageData(4, 4)
        local out = img:sharpen()
        expect_type("userdata", out)
    end)

    it("sharpen returns an image with the same dimensions", function()
        local img = lurek.image.newImageData(4, 4)
        local out = img:sharpen()
        expect_equal(out:getWidth(), 4)
        expect_equal(out:getHeight(), 4)
    end)

    it("sharpen on a solid-colour image preserves pixel values", function()
        local img = lurek.image.newImageData(4, 4)
        img:fill(128, 64, 32, 255)
        local out = img:sharpen()
        -- 5*C - top - bottom - left - right = 5*C - 4*C = C for uniform colour
        local r, g, b, a = out:getPixel(1, 1)
        expect_equal(math.abs(r - 128) <= 2, true)
        expect_equal(math.abs(g - 64) <= 2, true)
        expect_equal(math.abs(b - 32) <= 2, true)
        expect_equal(a, 255)
    end)

    it("sharpen returns a distinct object from the source", function()
        local img = lurek.image.newImageData(4, 4)
        local out = img:sharpen()
        img:fill(255, 0, 0, 255)
        -- out was created before fill; its pixel 1,1 (blank=0) is unaffected
        local r, _, _, _ = out:getPixel(1, 1)
        expect_equal(r, 0)
    end)
end)

-- -----------------------------------------------------------------------
-- LayeredImage tests
-- -----------------------------------------------------------------------

describe("lurek.image.newLayeredImage", function()
    it("returns a LayeredImage userdata", function()
        local stack = lurek.image.newLayeredImage(64, 64)
        expect_equal(type(stack), "userdata")
    end)

    it("getWidth and getHeight return canvas dimensions", function()
        local stack = lurek.image.newLayeredImage(32, 48)
        expect_equal(stack:getWidth(), 32)
        expect_equal(stack:getHeight(), 48)
    end)

    it("layerCount starts at zero", function()
        local stack = lurek.image.newLayeredImage(4, 4)
        expect_equal(stack:layerCount(), 0)
    end)
end)

describe("LayeredImage:addLayer", function()
    it("addLayer with explicit name returns 1", function()
        local stack = lurek.image.newLayeredImage(4, 4)
        local idx = stack:addLayer("background")
        expect_equal(idx, 1)
    end)

    it("adding two layers increments index", function()
        local stack = lurek.image.newLayeredImage(4, 4)
        local a = stack:addLayer("a")
        local b = stack:addLayer("b")
        expect_equal(a, 1)
        expect_equal(b, 2)
        expect_equal(stack:layerCount(), 2)
    end)

    it("addLayer without name generates a default name", function()
        local stack = lurek.image.newLayeredImage(4, 4)
        stack:addLayer()
        local name = stack:getName(1)
        expect_equal(type(name), "string")
        expect_equal(#name > 0, true)
    end)
end)

describe("LayeredImage:removeLayer", function()
    it("removes existing layer and decrements count", function()
        local stack = lurek.image.newLayeredImage(4, 4)
        stack:addLayer("x")
        expect_equal(stack:removeLayer(1), true)
        expect_equal(stack:layerCount(), 0)
    end)

    it("returns false for out-of-range index", function()
        local stack = lurek.image.newLayeredImage(4, 4)
        expect_equal(stack:removeLayer(99), false)
    end)
end)

describe("LayeredImage opacity and visibility", function()
    it("setOpacity and getOpacity round-trip", function()
        local stack = lurek.image.newLayeredImage(4, 4)
        stack:addLayer("x")
        expect_equal(stack:setOpacity(1, 0.5), true)
        local op = stack:getOpacity(1)
        expect_equal(math.abs(op - 0.5) < 0.01, true)
    end)

    it("setOpacity clamps above 1.0", function()
        local stack = lurek.image.newLayeredImage(4, 4)
        stack:addLayer("x")
        stack:setOpacity(1, 5.0)
        expect_equal(math.abs(stack:getOpacity(1) - 1.0) < 0.01, true)
    end)

    it("setVisible and isVisible round-trip", function()
        local stack = lurek.image.newLayeredImage(4, 4)
        stack:addLayer("x")
        stack:setVisible(1, false)
        expect_equal(stack:isVisible(1), false)
        stack:setVisible(1, true)
        expect_equal(stack:isVisible(1), true)
    end)

    it("invalid index returns error from getOpacity", function()
        local stack = lurek.image.newLayeredImage(4, 4)
        expect_error(function() stack:getOpacity(99) end)
    end)
end)

describe("LayeredImage name operations", function()
    it("getName returns the layer name", function()
        local stack = lurek.image.newLayeredImage(4, 4)
        stack:addLayer("myName")
        expect_equal(stack:getName(1), "myName")
    end)

    it("setName renames a layer", function()
        local stack = lurek.image.newLayeredImage(4, 4)
        stack:addLayer("old")
        expect_equal(stack:setName(1, "new"), true)
        expect_equal(stack:getName(1), "new")
    end)
end)

describe("LayeredImage layer reordering", function()
    it("swapLayers exchanges two layer positions", function()
        local stack = lurek.image.newLayeredImage(4, 4)
        stack:addLayer("first")
        stack:addLayer("second")
        expect_equal(stack:swapLayers(1, 2), true)
        expect_equal(stack:getName(1), "second")
        expect_equal(stack:getName(2), "first")
    end)

    it("swapLayers returns false for out-of-range", function()
        local stack = lurek.image.newLayeredImage(4, 4)
        stack:addLayer("x")
        expect_equal(stack:swapLayers(1, 99), false)
    end)

    it("moveLayer repositions a layer", function()
        local stack = lurek.image.newLayeredImage(4, 4)
        stack:addLayer("a")
        stack:addLayer("b")
        stack:addLayer("c")
        expect_equal(stack:moveLayer(1, 3), true)
        -- a moves to 3, so order is b, c, a
        expect_equal(stack:getName(1), "b")
        expect_equal(stack:getName(3), "a")
    end)
end)

describe("LayeredImage pixel editing via getLayer/setLayer", function()
    it("getLayer returns an ImageData copy", function()
        local stack = lurek.image.newLayeredImage(4, 4)
        stack:addLayer("x")
        local img = stack:getLayer(1)
        expect_equal(type(img), "userdata")
        expect_equal(img:getWidth(), 4)
        expect_equal(img:getHeight(), 4)
    end)

    it("setLayer replaces layer pixels", function()
        local stack = lurek.image.newLayeredImage(4, 4)
        stack:addLayer("x")
        local src = lurek.image.newImageData(4, 4)
        src:fill(255, 0, 0, 255)
        expect_equal(stack:setLayer(1, src), true)
        local got = stack:getLayer(1)
        local r, g, b, a = got:getPixel(0, 0)
        expect_equal(r, 255)
        expect_equal(g, 0)
        expect_equal(b, 0)
        expect_equal(a, 255)
    end)

    it("getLayer with invalid index throws", function()
        local stack = lurek.image.newLayeredImage(4, 4)
        expect_error(function() stack:getLayer(99) end)
    end)
end)

describe("LayeredImage:merge", function()
    it("empty stack merges to fully transparent image", function()
        local stack = lurek.image.newLayeredImage(4, 4)
        local flat = stack:merge()
        local r, g, b, a = flat:getPixel(0, 0)
        expect_equal(a, 0)
    end)

    it("single opaque layer merges to that layer's pixels", function()
        local stack = lurek.image.newLayeredImage(4, 4)
        stack:addLayer("bg")
        local src = lurek.image.newImageData(4, 4)
        src:fill(200, 100, 50, 255)
        stack:setLayer(1, src)
        local flat = stack:merge()
        local r, g, b, a = flat:getPixel(0, 0)
        expect_equal(r, 200)
        expect_equal(g, 100)
        expect_equal(b, 50)
        expect_equal(a, 255)
    end)

    it("hidden layer does not appear in merge", function()
        local stack = lurek.image.newLayeredImage(4, 4)
        stack:addLayer("bg")
        local bg = lurek.image.newImageData(4, 4)
        bg:fill(255, 0, 0, 255)
        stack:setLayer(1, bg)
        stack:addLayer("fg")
        local fg = lurek.image.newImageData(4, 4)
        fg:fill(0, 0, 255, 255)
        stack:setLayer(2, fg)
        stack:setVisible(2, false)
        local flat = stack:merge()
        local r, _, _, _ = flat:getPixel(0, 0)
        expect_equal(r, 255)  -- red from bg; blue fg invisible
    end)

    it("opaque top layer fully covers bottom", function()
        local stack = lurek.image.newLayeredImage(4, 4)
        stack:addLayer("bg")
        local bg = lurek.image.newImageData(4, 4)
        bg:fill(255, 0, 0, 255)
        stack:setLayer(1, bg)
        stack:addLayer("fg")
        local fg = lurek.image.newImageData(4, 4)
        fg:fill(0, 0, 255, 255)
        stack:setLayer(2, fg)
        local flat = stack:merge()
        local r, g, b, a = flat:getPixel(0, 0)
        expect_equal(b, 255)
        expect_equal(r, 0)
    end)

    it("merge returns an ImageData of the same dimensions", function()
        local stack = lurek.image.newLayeredImage(8, 6)
        local flat = stack:merge()
        expect_equal(flat:getWidth(), 8)
        expect_equal(flat:getHeight(), 6)
    end)
end)

-- -----------------------------------------------------------------------
-- LIMG binary serialization tests
-- -----------------------------------------------------------------------

describe("lurek.image.saveImage / lurek.image.loadImage", function()
    it("saveImage and loadImage functions exist", function()
        expect_equal(type(lurek.image.saveImage), "function")
        expect_equal(type(lurek.image.loadImage), "function")
    end)
end)

describe("lurek.image.saveLayered / lurek.image.loadLayered", function()
    it("loadLayered function exists", function()
        expect_equal(type(lurek.image.loadLayered), "function")
    end)
end)

describe("LayeredImage:save", function()
    it("save method exists on LayeredImage userdata", function()
        local stack = lurek.image.newLayeredImage(4, 4)
        expect_equal(type(stack.save), "function")
    end)
end)

--  ImageEffect chain API (merged from test_image_effect.lua) 

---@param fx LImageEffect
---@param key integer|string
---@return LPostFxEffect
local function require_effect(fx, key)
    local effect = fx:getEffect(key)
    if effect == nil then
        error(("expected effect %s to exist"):format(tostring(key)), 2)
    end
    return effect
end

---@param img ImageData|nil
---@param context string
---@return ImageData
local function require_image_data(img, context)
    if img == nil then
        error(context .. " returned nil", 2)
    end
    return img
end

describe("lurek.effect.newImageEffect construction (empty)", function()
    -- @covers lurek.effect.newImageEffect
    it("newImageEffect is a function", function()
        expect_type("function", lurek.effect.newImageEffect)
    end)

    it("newImageEffect() returns non-nil", function()
        local fx = lurek.effect.newImageEffect()
        expect_equal(fx ~= nil, true)
    end)

    it("newImageEffect() returns object with effectCount method", function()
        local fx = lurek.effect.newImageEffect()
        expect_type("function", fx.effectCount)
    end)

    it("newImageEffect() returns object with addEffect method", function()
        local fx = lurek.effect.newImageEffect()
        expect_type("function", fx.addEffect)
    end)

    it("newImageEffect() returns object with getEffect method", function()
        local fx = lurek.effect.newImageEffect()
        expect_type("function", fx.getEffect)
    end)

    it("newImageEffect() returns object with removeEffect method", function()
        local fx = lurek.effect.newImageEffect()
        expect_type("function", fx.removeEffect)
    end)

    it("newImageEffect() returns object with clearEffects method", function()
        local fx = lurek.effect.newImageEffect()
        expect_type("function", fx.clearEffects)
    end)

    it("newImageEffect() returns object with clone method", function()
        local fx = lurek.effect.newImageEffect()
        expect_type("function", fx.clone)
    end)

    it("newImageEffect() returns object with save method", function()
        local fx = lurek.effect.newImageEffect()
        expect_type("function", fx.save)
    end)

    it("empty chain has effectCount == 0", function()
        local fx = lurek.effect.newImageEffect()
        expect_equal(fx:effectCount(), 0)
    end)
end)

describe("lurek.effect.newImageEffect construction (single name)", function()
    it("newImageEffect('blur') produces effectCount == 1", function()
        local fx = lurek.effect.newImageEffect("blur")
        expect_equal(fx:effectCount(), 1)
    end)

    it("first effect type is 'blur'", function()
        local fx = lurek.effect.newImageEffect("blur")
        local e = require_effect(fx, 1)
        expect_equal(e:getType(), "blur")
    end)

    it("newImageEffect('blur', {radius=4}) produces effectCount == 1", function()
        local fx = lurek.effect.newImageEffect("blur", { radius = 4 })
        expect_equal(fx:effectCount(), 1)
    end)

    it("newImageEffect('blur', {radius=4}) sets radius parameter", function()
        local fx = lurek.effect.newImageEffect("blur", { radius = 4 })
        local v = require_effect(fx, 1):getParameter("radius")
        expect_equal(math.abs(v - 4) < 0.001, true)
    end)
end)

describe("lurek.effect.newImageEffect construction (chain table)", function()
    it("two-element chain produces effectCount == 2", function()
        local fx = lurek.effect.newImageEffect({ { type = "blur", radius = 2 }, { type = "sepia" } })
        expect_equal(fx:effectCount(), 2)
    end)

    it("first effect in chain is 'blur'", function()
        local fx = lurek.effect.newImageEffect({ { type = "blur", radius = 2 }, { type = "sepia" } })
        expect_equal(require_effect(fx, 1):getType(), "blur")
    end)

    it("second effect in chain is 'sepia'", function()
        local fx = lurek.effect.newImageEffect({ { type = "blur", radius = 2 }, { type = "sepia" } })
        expect_equal(require_effect(fx, 2):getType(), "sepia")
    end)

    it("chain entry parameters are applied", function()
        local fx = lurek.effect.newImageEffect({ { type = "blur", radius = 2 } })
        local v = require_effect(fx, 1):getParameter("radius")
        expect_equal(math.abs(v - 2) < 0.001, true)
    end)
end)

describe("ImageEffect:addEffect", function()
    it("addEffect returns non-nil", function()
        local fx = lurek.effect.newImageEffect()
        local e = fx:addEffect("vignette")
        expect_equal(e ~= nil, true)
    end)

    it("addEffect returns PostFxEffect with correct type", function()
        local fx = lurek.effect.newImageEffect()
        local e = fx:addEffect("vignette")
        expect_equal(e:getType(), "vignette")
    end)

    it("addEffect increments effectCount", function()
        local fx = lurek.effect.newImageEffect()
        fx:addEffect("blur")
        expect_equal(fx:effectCount(), 1)
        fx:addEffect("sepia")
        expect_equal(fx:effectCount(), 2)
    end)

    it("addEffect appends to end of chain", function()
        local fx = lurek.effect.newImageEffect()
        fx:addEffect("blur")
        fx:addEffect("vignette")
        expect_equal(require_effect(fx, 2):getType(), "vignette")
    end)
end)

describe("ImageEffect:getEffect by index", function()
    it("getEffect(1) returns first effect", function()
        local fx = lurek.effect.newImageEffect()
        fx:addEffect("blur")
        fx:addEffect("sepia")
        expect_equal(require_effect(fx, 1):getType(), "blur")
    end)

    it("getEffect(2) returns second effect", function()
        local fx = lurek.effect.newImageEffect()
        fx:addEffect("blur")
        fx:addEffect("sepia")
        expect_equal(require_effect(fx, 2):getType(), "sepia")
    end)

    it("getEffect out-of-bounds returns nil or errors gracefully", function()
        local fx = lurek.effect.newImageEffect()
        fx:addEffect("blur")
        local ok = pcall(function()
            local e = fx:getEffect(99)
            expect_equal(e == nil, true)
        end)
        expect_equal(true, true)
    end)

    it("getEffect(0) returns nil or errors gracefully", function()
        local fx = lurek.effect.newImageEffect()
        fx:addEffect("blur")
        local ok = pcall(function()
            local e = fx:getEffect(0)
            expect_equal(e == nil, true)
        end)
        expect_equal(true, true)
    end)
end)

describe("ImageEffect:getEffect by name", function()
    it("getEffect('blur') returns the blur effect", function()
        local fx = lurek.effect.newImageEffect()
        fx:addEffect("blur")
        fx:addEffect("sepia")
        local e = fx:getEffect("blur")
        expect_equal(e ~= nil, true)
        expect_equal(require_effect(fx, "blur"):getType(), "blur")
    end)

    it("getEffect('sepia') returns the sepia effect", function()
        local fx = lurek.effect.newImageEffect()
        fx:addEffect("blur")
        fx:addEffect("sepia")
        local e = fx:getEffect("sepia")
        expect_equal(e ~= nil, true)
        expect_equal(require_effect(fx, "sepia"):getType(), "sepia")
    end)

    it("getEffect with unknown name returns nil or errors gracefully", function()
        local fx = lurek.effect.newImageEffect()
        fx:addEffect("blur")
        local ok = pcall(function()
            local e = fx:getEffect("nonexistent_effect")
            expect_equal(e == nil, true)
        end)
        expect_equal(true, true)
    end)
end)

describe("PostFxEffect setParameter / getParameter round-trip", function()
    it("setParameter radius then getParameter returns same value", function()
        local fx = lurek.effect.newImageEffect("blur")
        require_effect(fx, 1):setParameter("radius", 7.5)
        local v = require_effect(fx, 1):getParameter("radius")
        expect_equal(math.abs(v - 7.5) < 0.001, true)
    end)

    it("setParameter overwrites previous value", function()
        local fx = lurek.effect.newImageEffect("blur")
        require_effect(fx, 1):setParameter("radius", 3.0)
        require_effect(fx, 1):setParameter("radius", 9.0)
        local v = require_effect(fx, 1):getParameter("radius")
        expect_equal(math.abs(v - 9.0) < 0.001, true)
    end)

    it("getParameter on separate effects are independent", function()
        local fx = lurek.effect.newImageEffect()
        local e1 = fx:addEffect("blur")
        local e2 = fx:addEffect("blur")
        e1:setParameter("radius", 2.0)
        e2:setParameter("radius", 8.0)
        expect_equal(math.abs(e1:getParameter("radius") - 2.0) < 0.001, true)
        expect_equal(math.abs(e2:getParameter("radius") - 8.0) < 0.001, true)
    end)
end)

describe("ImageEffect:effectCount", function()
    it("starts at 0 for empty chain", function()
        local fx = lurek.effect.newImageEffect()
        expect_equal(fx:effectCount(), 0)
    end)

    it("increments by 1 after each addEffect", function()
        local fx = lurek.effect.newImageEffect()
        fx:addEffect("blur")
        expect_equal(fx:effectCount(), 1)
        fx:addEffect("vignette")
        expect_equal(fx:effectCount(), 2)
        fx:addEffect("sepia")
        expect_equal(fx:effectCount(), 3)
    end)

    it("decrements after removeEffect", function()
        local fx = lurek.effect.newImageEffect()
        fx:addEffect("blur")
        fx:addEffect("sepia")
        fx:removeEffect(1)
        expect_equal(fx:effectCount(), 1)
    end)
end)

describe("ImageEffect:removeEffect by index", function()
    it("removeEffect(1) decrements effectCount", function()
        local fx = lurek.effect.newImageEffect()
        fx:addEffect("blur")
        fx:addEffect("sepia")
        fx:removeEffect(1)
        expect_equal(fx:effectCount(), 1)
    end)

    it("remaining effect after removing index 1 is the second original", function()
        local fx = lurek.effect.newImageEffect()
        fx:addEffect("blur")
        fx:addEffect("sepia")
        fx:removeEffect(1)
        expect_equal(require_effect(fx, 1):getType(), "sepia")
    end)

    it("removeEffect(2) removes the second effect", function()
        local fx = lurek.effect.newImageEffect()
        fx:addEffect("blur")
        fx:addEffect("sepia")
        fx:removeEffect(2)
        expect_equal(fx:effectCount(), 1)
        expect_equal(require_effect(fx, 1):getType(), "blur")
    end)
end)

describe("ImageEffect:removeEffect by name", function()
    it("removeEffect('sepia') from [blur, sepia] -> effectCount == 1", function()
        local fx = lurek.effect.newImageEffect()
        fx:addEffect("blur")
        fx:addEffect("sepia")
        fx:removeEffect("sepia")
        expect_equal(fx:effectCount(), 1)
    end)

    it("remaining effect after removing 'sepia' is 'blur'", function()
        local fx = lurek.effect.newImageEffect()
        fx:addEffect("blur")
        fx:addEffect("sepia")
        fx:removeEffect("sepia")
        expect_equal(require_effect(fx, 1):getType(), "blur")
    end)

    it("removeEffect('blur') from [blur, sepia] -> remaining is 'sepia'", function()
        local fx = lurek.effect.newImageEffect()
        fx:addEffect("blur")
        fx:addEffect("sepia")
        fx:removeEffect("blur")
        expect_equal(fx:effectCount(), 1)
        expect_equal(require_effect(fx, 1):getType(), "sepia")
    end)
end)

describe("ImageEffect:clearEffects", function()
    it("clearEffects on populated chain produces effectCount == 0", function()
        local fx = lurek.effect.newImageEffect()
        fx:addEffect("blur")
        fx:addEffect("vignette")
        fx:addEffect("sepia")
        fx:clearEffects()
        expect_equal(fx:effectCount(), 0)
    end)

    it("clearEffects on empty chain is a no-op", function()
        local fx = lurek.effect.newImageEffect()
        fx:clearEffects()
        expect_equal(fx:effectCount(), 0)
    end)

    it("can addEffect again after clearEffects", function()
        local fx = lurek.effect.newImageEffect()
        fx:addEffect("blur")
        fx:clearEffects()
        fx:addEffect("sepia")
        expect_equal(fx:effectCount(), 1)
        expect_equal(require_effect(fx, 1):getType(), "sepia")
    end)
end)

describe("ImageEffect:clone", function()
    it("clone returns non-nil", function()
        local fx = lurek.effect.newImageEffect()
        fx:addEffect("blur")
        local copy = fx:clone()
        expect_equal(copy ~= nil, true)
    end)

    it("clone has the same effectCount as original", function()
        local fx = lurek.effect.newImageEffect()
        fx:addEffect("blur")
        fx:addEffect("sepia")
        local copy = fx:clone()
        expect_equal(copy:effectCount(), fx:effectCount())
    end)

    it("clone has the same effect types in order", function()
        local fx = lurek.effect.newImageEffect()
        fx:addEffect("blur")
        fx:addEffect("sepia")
        local copy = fx:clone()
        expect_equal(require_effect(copy, 1):getType(), "blur")
        expect_equal(require_effect(copy, 2):getType(), "sepia")
    end)

    it("modifying clone does not affect original effectCount", function()
        local fx = lurek.effect.newImageEffect()
        fx:addEffect("blur")
        local copy = fx:clone()
        copy:addEffect("vignette")
        expect_equal(fx:effectCount(), 1)
        expect_equal(copy:effectCount(), 2)
    end)

    it("modifying clone parameter does not affect original", function()
        local fx = lurek.effect.newImageEffect("blur")
        require_effect(fx, 1):setParameter("radius", 3.0)
        local copy = fx:clone()
        require_effect(copy, 1):setParameter("radius", 99.0)
        local orig_v = require_effect(fx, 1):getParameter("radius")
        expect_equal(math.abs(orig_v - 3.0) < 0.001, true)
    end)
end)

describe("lurek.effect.newImageEffect invalid effect name", function()
    it("rejects unknown effect name on construction", function()
        expect_error(function()
            lurek.effect.newImageEffect("not_a_real_effect")
        end)
    end)

    it("addEffect rejects unknown effect name", function()
        local fx = lurek.effect.newImageEffect()
        expect_error(function()
            fx:addEffect("not_a_real_effect")
        end)
    end)
end)

--  Extended ImageData ops: resize, blit, getRegion, diff, mapPixels (merged from test_image_extended.lua) 

local function make_solid(w, h, r, g, b, a)
    local img = lurek.image.newImageData(w, h)
    img:mapPixels(function(_, _, _, _, _, _) return r, g, b, a end)
    return img
end

describe("ImageData:resize", function()
    it("resize to same dimensions returns a copy", function()
        local img = make_solid(4, 4, 255, 0, 0, 255)
        local copy = require_image_data(img:resize(4, 4), "ImageData:resize(4, 4)")
        expect_equal(copy ~= nil, true)
        expect_equal(copy:getWidth(), 4)
        expect_equal(copy:getHeight(), 4)
    end)

    it("resize returns correct dimensions", function()
        local img = make_solid(8, 8, 0, 255, 0, 255)
        local small = require_image_data(img:resize(2, 3), "ImageData:resize(2, 3)")
        expect_equal(small:getWidth(), 2)
        expect_equal(small:getHeight(), 3)
    end)

    it("resize to zero returns nil", function()
        local img = make_solid(4, 4, 0, 0, 0, 255)
        local result = img:resize(0, 4)
        expect_equal(result, nil)
    end)
end)

describe("ImageData:blit", function()
    it("blit does not error for valid coordinates", function()
        local dst = make_solid(8, 8, 0, 0, 0, 255)
        local src = make_solid(2, 2, 255, 255, 255, 255)
        dst:blit(src, 3, 3)
    end)

    it("blit at (0,0) covers the top-left corner", function()
        local dst = make_solid(4, 4, 0, 0, 0, 255)
        local src = make_solid(2, 2, 200, 100, 50, 255)
        dst:blit(src, 0, 0)
        expect_equal(dst:getWidth(), 4)
    end)

    it("blit with negative offset does not error (clips out-of-bounds)", function()
        local dst = make_solid(4, 4, 0, 0, 0, 255)
        local src = make_solid(2, 2, 255, 0, 0, 255)
        dst:blit(src, -1, -1)
    end)
end)

describe("ImageData:getRegion", function()
    it("getRegion of full image returns same dimensions", function()
        local img = make_solid(6, 4, 128, 64, 32, 255)
        local region = require_image_data(img:getRegion(0, 0, 6, 4), "ImageData:getRegion(0, 0, 6, 4)")
        expect_equal(region ~= nil, true)
        expect_equal(region:getWidth(), 6)
        expect_equal(region:getHeight(), 4)
    end)

    it("getRegion of sub-rectangle returns correct dimensions", function()
        local img = make_solid(8, 8, 0, 0, 255, 255)
        local region = require_image_data(img:getRegion(2, 2, 4, 3), "ImageData:getRegion(2, 2, 4, 3)")
        expect_equal(region:getWidth(), 4)
        expect_equal(region:getHeight(), 3)
    end)

    it("getRegion outside bounds returns nil", function()
        local img = make_solid(4, 4, 0, 0, 0, 255)
        local result = img:getRegion(10, 10, 4, 4)
        expect_equal(result, nil)
    end)
end)

describe("ImageData:diff", function()
    it("diff of identical images is 0", function()
        local a = make_solid(4, 4, 100, 150, 200, 255)
        local b = make_solid(4, 4, 100, 150, 200, 255)
        local d = a:diff(b)
        expect_equal(d, 0)
    end)

    it("diff of different images is > 0", function()
        local a = make_solid(4, 4, 0, 0, 0, 255)
        local b = make_solid(4, 4, 255, 255, 255, 255)
        local d = a:diff(b)
        expect_equal(d > 0, true)
    end)

    it("diff of images with different dimensions is > 0", function()
        local a = make_solid(4, 4, 0, 0, 0, 255)
        local b = make_solid(2, 2, 0, 0, 0, 255)
        local d = a:diff(b)
        expect_equal(d > 0, true)
    end)
end)

describe("ImageData:mapPixels", function()
    it("mapPixels can invert all pixels", function()
        local img = make_solid(4, 4, 100, 150, 200, 255)
        img:mapPixels(function(_, _, r, g, b, a)
            return 255 - r, 255 - g, 255 - b, a
        end)
        expect_equal(img:getWidth(), 4)
    end)

    it("mapPixels identity function produces same diff as 0", function()
        local img_a = make_solid(4, 4, 42, 88, 177, 255)
        local img_b = make_solid(4, 4, 42, 88, 177, 255)
        img_a:mapPixels(function(_, _, r, g, b, a) return r, g, b, a end)
        local d = img_a:diff(img_b)
        expect_equal(d, 0)
    end)

    it("mapPixels can set all pixels to a constant colour", function()
        local img = make_solid(4, 4, 0, 0, 0, 255)
        img:mapPixels(function(_, _, _, _, _, _) return 1, 2, 3, 4 end)
        expect_equal(img:getWidth(), 4)
    end)
end)

-- =========================================================================
-- Additional API coverage
-- =========================================================================

describe("image palette and province coverage", function()
    -- @covers lurek.image.newPaletteLut
    -- @covers PaletteLUT:getColorCount
    it("newPaletteLut starts empty and counts entries", function()
        local lut = lurek.image.newPaletteLut()
        expect_equal(0, lut:getColorCount())
        lut:setColor(255, 0, 0, 255, 0, 255, 0, 255)
        expect_equal(1, lut:getColorCount())
        lut:setColor(0, 0, 255, 255, 255, 255, 0, 255)
        expect_equal(2, lut:getColorCount())
    end)

    -- @covers mlua:applyPaletteLut
    it("applyPaletteLut replaces matching pixels", function()
        local img = lurek.image.newImageData(2, 1)
        local lut = lurek.image.newPaletteLut()
        img:setPixel(0, 0, 255, 0, 0, 255)
        img:setPixel(1, 0, 0, 0, 255, 255)
        lut:setColor(255, 0, 0, 255, 0, 255, 0, 255)

        img:applyPaletteLut(lut)

        local r1, g1, b1, a1 = img:getPixel(0, 0)
        local r2, g2, b2, a2 = img:getPixel(1, 0)
        expect_equal(0, r1)
        expect_equal(255, g1)
        expect_equal(0, b1)
        expect_equal(255, a1)
        expect_equal(0, r2)
        expect_equal(0, g2)
        expect_equal(255, b2)
        expect_equal(255, a2)
    end)

    -- @covers lurek.image.savePNG
    -- @covers lurek.image.newProvinceGrid
    -- @covers ProvinceGrid:getWidth
    -- @covers ProvinceGrid:getHeight
    -- @covers ProvinceGrid:getAt
    -- @covers ProvinceGrid:provinceCount
    -- @covers ProvinceGrid:adjacencies
    it("savePNG and newProvinceGrid build a usable province map", function()
        local img = lurek.image.newImageData(4, 4)
        local path = "save/_province_grid_test.png"

        for y = 0, 1 do
            for x = 0, 1 do
                img:setPixel(x, y, 255, 0, 0, 255)
            end
        end
        for y = 0, 1 do
            for x = 2, 3 do
                img:setPixel(x, y, 0, 255, 0, 255)
            end
        end
        for x = 0, 3 do
            img:setPixel(x, 2, 0, 0, 255, 255)
        end

        lurek.image.savePNG(img, path)
        local grid = lurek.image.newProvinceGrid(path)
        local adj = grid:adjacencies()
        local red = grid:getAt(0, 0)
        local green = grid:getAt(2, 0)
        local blue = grid:getAt(0, 2)

        expect_equal(4, grid:getWidth())
        expect_equal(4, grid:getHeight())
        expect_equal(3, grid:provinceCount())
        expect_equal(red, grid:getAt(1, 1))
        expect_true(red > 0)
        expect_true(green > 0)
        expect_true(blue > 0)
        expect_true(red ~= green)
        expect_true(red ~= blue)
        expect_true(green ~= blue)
        expect_equal(0, grid:getAt(0, 3))
        expect_type("table", adj)
        expect_true(#adj >= 3)
        expect_type("number", adj[1].province_a)
        expect_type("number", adj[1].province_b)
        expect_type("number", adj[1].border_pixels)
    end)
end)

describe("image remaining explicit coverage", function()
    -- @covers CompressedImageData:getWidth
    -- @covers CompressedImageData:getHeight
    -- @covers CompressedImageData:getDimensions
    -- @covers CompressedImageData:getFormat
    it("CompressedImageData metadata methods report fixture state", function()
        local compressed = lurek.image.newCompressedData("tests/fixtures/test_dxt1.dds")
        local width, height = compressed:getDimensions()

        expect_true(compressed:getWidth() > 0)
        expect_true(compressed:getHeight() > 0)
        expect_equal(width, compressed:getWidth())
        expect_equal(height, compressed:getHeight())
        expect_type("string", compressed:getFormat())
        expect_true(#compressed:getFormat() > 0)
    end)

    -- @covers mlua:setRawData
    it("ImageData:setRawData replaces pixel bytes", function()
        local img = lurek.image.newImageData(1, 1)
        img:setRawData(string.char(7, 8, 9, 255))
        local r, g, b, a = img:getPixel(0, 0)

        expect_equal(r, 7)
        expect_equal(g, 8)
        expect_equal(b, 9)
        expect_equal(a, 255)
    end)

    -- @covers PaletteLUT:clear
    it("PaletteLUT:clear removes all mappings", function()
        local lut = lurek.image.newPaletteLut()
        lut:setColor(1, 2, 3, 255, 4, 5, 6, 255)
        lut:setColor(10, 20, 30, 255, 40, 50, 60, 255)
        expect_equal(2, lut:getColorCount())

        lut:clear()

        expect_equal(0, lut:getColorCount())
    end)
end)

test_summary()
