-- Luna2D Particle API Tests

describe("luna.particle module exists", function()
    it("luna.particle is a table", function()
        expect_type("table", luna.particle)
    end)
end)

describe("luna.particle.newSystem", function()
    it("newSystem returns userdata", function()
        local ps = luna.particle.newSystem()
        expect_type("userdata", ps)
    end)

    it("newSystem with no config uses defaults", function()
        local ps = luna.particle.newSystem()
        expect_type("userdata", ps)
        -- default system starts active
        expect_true(luna.particle.isActive(ps), "default system should be active")
    end)

    it("newSystem with config table", function()
        local ps = luna.particle.newSystem({ emissionRate = 50, maxParticles = 100 })
        expect_type("userdata", ps)
    end)

    it("newSystem backward compat: sizeStart/sizeEnd", function()
        local ps = luna.particle.newSystem({ sizeStart = 8.0, sizeEnd = 2.0 })
        expect_type("userdata", ps)
    end)

    it("newSystem backward compat: colorStart/colorEnd", function()
        local ps = luna.particle.newSystem({
            colorStart = {1, 0, 0, 1},
            colorEnd   = {1, 0, 0, 0}
        })
        expect_type("userdata", ps)
    end)
end)

describe("luna.particle lifecycle", function()
    it("isActive returns true for new system", function()
        local ps = luna.particle.newSystem()
        expect_true(luna.particle.isActive(ps), "new system should be active")
    end)

    it("isPaused returns false for new system", function()
        local ps = luna.particle.newSystem()
        expect_true(not luna.particle.isPaused(ps), "new system should not be paused")
    end)

    it("isStopped returns false for new (active) system", function()
        local ps = luna.particle.newSystem()
        expect_true(not luna.particle.isStopped(ps), "new system should not be stopped")
    end)

    it("stop sets isStopped", function()
        local ps = luna.particle.newSystem()
        luna.particle.stop(ps)
        expect_true(luna.particle.isStopped(ps), "stopped system should report isStopped")
    end)

    it("pause sets isPaused", function()
        local ps = luna.particle.newSystem()
        luna.particle.pause(ps)
        expect_true(luna.particle.isPaused(ps), "paused system should report isPaused")
    end)

    it("start after stop resumes active state", function()
        local ps = luna.particle.newSystem()
        luna.particle.stop(ps)
        luna.particle.start(ps)
        expect_true(luna.particle.isActive(ps), "started system should be active")
    end)

    it("reset clears particles and keeps active", function()
        local ps = luna.particle.newSystem({ emissionRate = 1000, maxParticles = 50 })
        luna.particle.update(ps, 1.0)
        luna.particle.reset(ps)
        expect_equal(0, luna.particle.getCount(ps), "count after reset")
    end)
end)

describe("luna.particle.getCount / isEmpty / isFull", function()
    it("getCount returns 0 before any update", function()
        local ps = luna.particle.newSystem()
        expect_equal(0, luna.particle.getCount(ps), "count before update")
    end)

    it("isEmpty returns true when count is 0", function()
        local ps = luna.particle.newSystem()
        expect_true(luna.particle.isEmpty(ps), "empty before update")
    end)

    it("isFull returns false for fresh system", function()
        local ps = luna.particle.newSystem({ maxParticles = 100 })
        expect_true(not luna.particle.isFull(ps), "not full before update")
    end)

    it("emit burst fills particles immediately", function()
        local ps = luna.particle.newSystem({ maxParticles = 100 })
        luna.particle.stop(ps)  -- stop continuous emission
        luna.particle.emit(ps, 10)
        expect_true(luna.particle.getCount(ps) > 0, "count should increase after emit")
    end)

    it("getCount increases after update with high emission rate", function()
        local ps = luna.particle.newSystem({ emissionRate = 500, maxParticles = 50 })
        luna.particle.update(ps, 0.1)
        expect_true(luna.particle.getCount(ps) > 0, "count should be positive after update")
    end)
end)

describe("luna.particle position", function()
    it("setPosition / getPosition round-trip", function()
        local ps = luna.particle.newSystem()
        luna.particle.setPosition(ps, 100, 200)
        local x, y = luna.particle.getPosition(ps)
        expect_true(math.abs(x - 100) < 0.001, "x position should match")
        expect_true(math.abs(y - 200) < 0.001, "y position should match")
    end)

    it("getPosition returns 0,0 by default", function()
        local ps = luna.particle.newSystem()
        local x, y = luna.particle.getPosition(ps)
        expect_true(math.abs(x) < 0.001, "default x should be 0")
        expect_true(math.abs(y) < 0.001, "default y should be 0")
    end)

    it("moveTo updates position", function()
        local ps = luna.particle.newSystem()
        luna.particle.moveTo(ps, 50, 75)
        local x, y = luna.particle.getPosition(ps)
        expect_true(math.abs(x - 50) < 0.001, "moveTo x")
        expect_true(math.abs(y - 75) < 0.001, "moveTo y")
    end)
end)

describe("luna.particle emission settings", function()
    it("setEmissionRate / getEmissionRate round-trip", function()
        local ps = luna.particle.newSystem()
        luna.particle.setEmissionRate(ps, 99.0)
        local rate = luna.particle.getEmissionRate(ps)
        expect_true(math.abs(rate - 99.0) < 0.001, "emission rate round-trip")
    end)

    it("setParticleLifetime / getParticleLifetime round-trip", function()
        local ps = luna.particle.newSystem()
        luna.particle.setParticleLifetime(ps, 0.5, 2.5)
        local mn, mx = luna.particle.getParticleLifetime(ps)
        expect_true(math.abs(mn - 0.5) < 0.001, "lifetime min")
        expect_true(math.abs(mx - 2.5) < 0.001, "lifetime max")
    end)

    it("setEmitterLifetime / getEmitterLifetime round-trip", function()
        local ps = luna.particle.newSystem()
        luna.particle.setEmitterLifetime(ps, 5.0)
        local t = luna.particle.getEmitterLifetime(ps)
        expect_true(math.abs(t - 5.0) < 0.001, "emitter lifetime")
    end)

    it("setSpeed / getSpeed round-trip", function()
        local ps = luna.particle.newSystem()
        luna.particle.setSpeed(ps, 20.0, 80.0)
        local mn, mx = luna.particle.getSpeed(ps)
        expect_true(math.abs(mn - 20.0) < 0.001, "speed min")
        expect_true(math.abs(mx - 80.0) < 0.001, "speed max")
    end)

    it("setDirection / getDirection round-trip", function()
        local ps = luna.particle.newSystem()
        luna.particle.setDirection(ps, 1.23)
        local d = luna.particle.getDirection(ps)
        expect_true(math.abs(d - 1.23) < 0.001, "direction")
    end)

    it("setSpread / getSpread round-trip", function()
        local ps = luna.particle.newSystem()
        luna.particle.setSpread(ps, 0.5)
        local s = luna.particle.getSpread(ps)
        expect_true(math.abs(s - 0.5) < 0.001, "spread")
    end)
end)

describe("luna.particle acceleration settings", function()
    it("setLinearAcceleration / getLinearAcceleration round-trip", function()
        local ps = luna.particle.newSystem()
        luna.particle.setLinearAcceleration(ps, -10, -50, 10, 50)
        local xmin, ymin, xmax, ymax = luna.particle.getLinearAcceleration(ps)
        expect_true(math.abs(xmin - (-10)) < 0.001, "accel xmin")
        expect_true(math.abs(ymin - (-50)) < 0.001, "accel ymin")
        expect_true(math.abs(xmax - 10) < 0.001, "accel xmax")
        expect_true(math.abs(ymax - 50) < 0.001, "accel ymax")
    end)

    it("setRadialAcceleration / getRadialAcceleration round-trip", function()
        local ps = luna.particle.newSystem()
        luna.particle.setRadialAcceleration(ps, -5.0, 5.0)
        local mn, mx = luna.particle.getRadialAcceleration(ps)
        expect_true(math.abs(mn - (-5.0)) < 0.001, "radial accel min")
        expect_true(math.abs(mx - 5.0) < 0.001, "radial accel max")
    end)

    it("setTangentialAcceleration / getTangentialAcceleration round-trip", function()
        local ps = luna.particle.newSystem()
        luna.particle.setTangentialAcceleration(ps, 1.0, 3.0)
        local mn, mx = luna.particle.getTangentialAcceleration(ps)
        expect_true(math.abs(mn - 1.0) < 0.001, "tangential accel min")
        expect_true(math.abs(mx - 3.0) < 0.001, "tangential accel max")
    end)

    it("setLinearDamping / getLinearDamping round-trip", function()
        local ps = luna.particle.newSystem()
        luna.particle.setLinearDamping(ps, 0.1, 0.9)
        local mn, mx = luna.particle.getLinearDamping(ps)
        expect_true(math.abs(mn - 0.1) < 0.001, "damping min")
        expect_true(math.abs(mx - 0.9) < 0.001, "damping max")
    end)
end)

describe("luna.particle size settings", function()
    it("setSizes with multiple keyframes / getSizes round-trip", function()
        local ps = luna.particle.newSystem()
        luna.particle.setSizes(ps, 8.0, 4.0, 2.0, 1.0)
        local sizes = luna.particle.getSizes(ps)
        expect_true(math.abs(sizes[1] - 8.0) < 0.001, "size[1]")
        expect_true(math.abs(sizes[2] - 4.0) < 0.001, "size[2]")
        expect_true(math.abs(sizes[3] - 2.0) < 0.001, "size[3]")
        expect_true(math.abs(sizes[4] - 1.0) < 0.001, "size[4]")
    end)

    it("setSizeVariation / getSizeVariation round-trip", function()
        local ps = luna.particle.newSystem()
        luna.particle.setSizeVariation(ps, 0.5)
        local v = luna.particle.getSizeVariation(ps)
        expect_true(math.abs(v - 0.5) < 0.001, "size variation")
    end)
end)

describe("luna.particle rotation settings", function()
    it("setRotation / getRotation round-trip", function()
        local ps = luna.particle.newSystem()
        luna.particle.setRotation(ps, 0.1, 0.9)
        local mn, mx = luna.particle.getRotation(ps)
        expect_true(math.abs(mn - 0.1) < 0.001, "rotation min")
        expect_true(math.abs(mx - 0.9) < 0.001, "rotation max")
    end)

    it("setSpin / getSpin round-trip", function()
        local ps = luna.particle.newSystem()
        luna.particle.setSpin(ps, 0.2, 1.5)
        local mn, mx = luna.particle.getSpin(ps)
        expect_true(math.abs(mn - 0.2) < 0.001, "spin min")
        expect_true(math.abs(mx - 1.5) < 0.001, "spin max")
    end)

    it("setSpinVariation / getSpinVariation round-trip", function()
        local ps = luna.particle.newSystem()
        luna.particle.setSpinVariation(ps, 0.75)
        local v = luna.particle.getSpinVariation(ps)
        expect_true(math.abs(v - 0.75) < 0.001, "spin variation")
    end)

    it("setRelativeRotation / hasRelativeRotation round-trip", function()
        local ps = luna.particle.newSystem()
        luna.particle.setRelativeRotation(ps, true)
        expect_true(luna.particle.hasRelativeRotation(ps), "relative rotation enabled")
        luna.particle.setRelativeRotation(ps, false)
        expect_true(not luna.particle.hasRelativeRotation(ps), "relative rotation disabled")
    end)
end)

describe("luna.particle color settings", function()
    it("setColors / getColors round-trip", function()
        local ps = luna.particle.newSystem()
        luna.particle.setColors(ps, {1, 0, 0, 1}, {0, 0, 1, 0})
        -- getColors returns a sequence of color tables: {{r,g,b,a}, {r,g,b,a}, ...}
        local colors = luna.particle.getColors(ps)
        local r1, g1, b1, a1 = colors[1][1], colors[1][2], colors[1][3], colors[1][4]
        local r2, g2, b2, a2 = colors[2][1], colors[2][2], colors[2][3], colors[2][4]
        expect_true(math.abs(r1 - 1.0) < 0.001, "color[1].r")
        expect_true(math.abs(g1 - 0.0) < 0.001, "color[1].g")
        expect_true(math.abs(b1 - 0.0) < 0.001, "color[1].b")
        expect_true(math.abs(a1 - 1.0) < 0.001, "color[1].a")
        expect_true(math.abs(r2 - 0.0) < 0.001, "color[2].r")
        expect_true(math.abs(b2 - 1.0) < 0.001, "color[2].b")
        expect_true(math.abs(a2 - 0.0) < 0.001, "color[2].a")
    end)
end)

describe("luna.particle rendering settings", function()
    it("setOffset / getOffset round-trip", function()
        local ps = luna.particle.newSystem()
        luna.particle.setOffset(ps, 4.0, 8.0)
        local ox, oy = luna.particle.getOffset(ps)
        expect_true(math.abs(ox - 4.0) < 0.001, "offset x")
        expect_true(math.abs(oy - 8.0) < 0.001, "offset y")
    end)

    it("setInsertMode / getInsertMode: top", function()
        local ps = luna.particle.newSystem()
        luna.particle.setInsertMode(ps, "top")
        expect_equal("top", luna.particle.getInsertMode(ps), "insert mode")
    end)

    it("setInsertMode / getInsertMode: bottom", function()
        local ps = luna.particle.newSystem()
        luna.particle.setInsertMode(ps, "bottom")
        expect_equal("bottom", luna.particle.getInsertMode(ps), "insert mode bottom")
    end)

    it("setInsertMode / getInsertMode: random", function()
        local ps = luna.particle.newSystem()
        luna.particle.setInsertMode(ps, "random")
        expect_equal("random", luna.particle.getInsertMode(ps), "insert mode random")
    end)

    it("setBufferSize / getBufferSize round-trip", function()
        local ps = luna.particle.newSystem({ maxParticles = 50 })
        luna.particle.setBufferSize(ps, 200)
        expect_equal(200, luna.particle.getBufferSize(ps), "buffer size")
    end)
end)

describe("luna.particle emission area", function()
    it("setEmissionArea / getEmissionArea: none", function()
        local ps = luna.particle.newSystem()
        luna.particle.setEmissionArea(ps, "none", 0, 0)
        local dist, w, h = luna.particle.getEmissionArea(ps)
        expect_equal("none", dist, "area distribution none")
    end)

    it("setEmissionArea: uniform rectangle", function()
        local ps = luna.particle.newSystem()
        luna.particle.setEmissionArea(ps, "uniform", 100, 50)
        local dist, w, h = luna.particle.getEmissionArea(ps)
        expect_equal("uniform", dist, "area distribution uniform")
        expect_true(math.abs(w - 100) < 0.001, "area width")
        expect_true(math.abs(h - 50) < 0.001, "area height")
    end)

    it("setEmissionArea: ellipse", function()
        local ps = luna.particle.newSystem()
        luna.particle.setEmissionArea(ps, "ellipse", 60, 30)
        local dist = luna.particle.getEmissionArea(ps)
        expect_equal("ellipse", dist, "area distribution ellipse")
    end)
end)

describe("luna.particle object-method syntax", function()
    it("ps:update(dt) is callable", function()
        local ps = luna.particle.newSystem()
        ps:update(0.016)
        expect_true(true, "object-method update works")
    end)

    it("ps:start() / ps:stop() / ps:pause() are callable", function()
        local ps = luna.particle.newSystem()
        ps:stop()
        expect_true(ps:isStopped(), "ps:isStopped after ps:stop")
        ps:start()
        expect_true(ps:isActive(), "ps:isActive after ps:start")
        ps:pause()
        expect_true(ps:isPaused(), "ps:isPaused after ps:pause")
    end)

    it("ps:emit(n) / ps:getCount() work", function()
        local ps = luna.particle.newSystem({ maxParticles = 20 })
        ps:stop()
        ps:emit(5)
        expect_true(ps:getCount() > 0, "count after ps:emit")
    end)

    it("ps:type() returns 'ParticleSystem'", function()
        local ps = luna.particle.newSystem()
        expect_equal("ParticleSystem", ps:type(), "type")
    end)

    it("ps:typeOf('Drawable') returns true", function()
        local ps = luna.particle.newSystem()
        expect_true(ps:typeOf("Drawable"), "typeOf Drawable")
    end)

    it("ps:typeOf('Object') returns true", function()
        local ps = luna.particle.newSystem()
        expect_true(ps:typeOf("Object"), "typeOf Object")
    end)

    it("ps:typeOf('NonExistent') returns false", function()
        local ps = luna.particle.newSystem()
        expect_true(not ps:typeOf("NonExistent"), "typeOf NonExistent false")
    end)
end)

describe("luna.particle.clone", function()
    it("clone returns a different userdata handle", function()
        local ps = luna.particle.newSystem({ emissionRate = 77.0 })
        local ps2 = luna.particle.clone(ps)
        expect_type("userdata", ps2)
        -- Clones share config but are independent objects
        local r1 = luna.particle.getEmissionRate(ps)
        local r2 = luna.particle.getEmissionRate(ps2)
        expect_true(math.abs(r1 - r2) < 0.001, "clone has same emission rate")
    end)
end)

describe("luna.particle.release", function()
    it("release returns true for valid handle", function()
        local ps = luna.particle.newSystem()
        local ok = luna.particle.release(ps)
        expect_equal(true, ok, "release returns true")
    end)

    it("accessing released handle raises an error", function()
        local ps = luna.particle.newSystem()
        luna.particle.release(ps)
        local ok, err = pcall(function() luna.particle.getCount(ps) end)
        expect_true(not ok, "accessing released handle should error")
    end)
end)

test_summary()
