-- tests/lua/unit/test_data.lua
-- BDD tests for luna.data.pack / unpack / getPackedSize / newDataView

describe("data.pack + data.unpack", function()
  it("round-trips f32", function()
    local b = luna.data.pack("<f", 3.14)
    local v = luna.data.unpack("<f", b)
    expect_near(v, 3.14, 0.01)
  end)

  it("round-trips u8 max", function()
    local b = luna.data.pack("B", 255)
    local v = luna.data.unpack("B", b)
    expect_equal(v, 255)
  end)

  it("round-trips u8 zero", function()
    local b = luna.data.pack("B", 0)
    local v = luna.data.unpack("B", b)
    expect_equal(v, 0)
  end)

  it("round-trips i8 negative", function()
    local b = luna.data.pack("b", -1)
    local v = luna.data.unpack("b", b)
    expect_equal(v, -1)
  end)

  it("round-trips u16", function()
    local b = luna.data.pack("<H", 1000)
    local v = luna.data.unpack("<H", b)
    expect_equal(v, 1000)
  end)

  it("round-trips i32", function()
    local b = luna.data.pack("<i", -123456)
    local v = luna.data.unpack("<i", b)
    expect_equal(v, -123456)
  end)

  it("round-trips u32", function()
    local b = luna.data.pack("<I", 123456)
    local v = luna.data.unpack("<I", b)
    expect_equal(v, 123456)
  end)

  it("round-trips f64 (double)", function()
    local b = luna.data.pack("<d", 1.23456789)
    local v = luna.data.unpack("<d", b)
    expect_near(v, 1.23456789, 1e-9)
  end)

  it("round-trips length-prefixed string", function()
    local b = luna.data.pack("s", "hello")
    local v = luna.data.unpack("s", b)
    expect_equal(v, "hello")
  end)

  it("round-trips null-terminated string", function()
    local b = luna.data.pack("z", "world")
    local v = luna.data.unpack("z", b)
    expect_equal(v, "world")
  end)

  it("returns next byte position", function()
    local b = luna.data.pack("BB", 10, 20)
    local v1, v2, pos = luna.data.unpack("BB", b)
    expect_equal(v1, 10)
    expect_equal(v2, 20)
    expect_equal(pos, 2)
  end)

  it("respects big-endian prefix", function()
    local b = luna.data.pack(">H", 0x0102)
    expect_equal(string.byte(b, 1), 0x01)
    expect_equal(string.byte(b, 2), 0x02)
  end)

  it("respects little-endian prefix", function()
    local b = luna.data.pack("<H", 0x0102)
    expect_equal(string.byte(b, 1), 0x02)
    expect_equal(string.byte(b, 2), 0x01)
  end)

  it("padding byte is zero", function()
    local b = luna.data.pack("xB", 42)
    expect_equal(string.len(b), 2)
    expect_equal(string.byte(b, 1), 0)
    expect_equal(string.byte(b, 2), 42)
  end)

  it("unpack with offset skips bytes", function()
    local b = luna.data.pack("BB", 11, 22)
    local v, pos = luna.data.unpack("B", b, 1)
    expect_equal(v, 22)
    expect_equal(pos, 2)
  end)
end)

describe("data.getPackedSize", function()
  it("returns 1 for B", function()
    expect_equal(luna.data.getPackedSize("B"), 1)
  end)

  it("returns 4 for f", function()
    expect_equal(luna.data.getPackedSize("f"), 4)
  end)

  it("returns 5 for Bf (1 + 4)", function()
    expect_equal(luna.data.getPackedSize("Bf"), 5)
  end)

  it("returns 8 for d (f64)", function()
    expect_equal(luna.data.getPackedSize("d"), 8)
  end)

  it("returns 2 for H", function()
    expect_equal(luna.data.getPackedSize("H"), 2)
  end)

  it("returns 4 for I", function()
    expect_equal(luna.data.getPackedSize("I"), 4)
  end)

  it("returns 8 for L (u64)", function()
    expect_equal(luna.data.getPackedSize("L"), 8)
  end)

  it("counts x padding byte", function()
    expect_equal(luna.data.getPackedSize("xB"), 2)
  end)
end)

describe("data.newDataView", function()
  it("DataView reads u8 written by pack", function()
    local b = luna.data.pack("B", 255)
    local dv = luna.data.newDataView(b)
    expect_equal(dv:getUInt8(0), 255)
  end)

  it("DataView getSize returns correct size", function()
    local b = luna.data.pack("BH", 1, 2)
    local dv = luna.data.newDataView(b)
    expect_equal(dv:getSize(), 3)
  end)

  it("DataView reads u16 from little-endian pack", function()
    local b = luna.data.pack("<H", 1000)
    local dv = luna.data.newDataView(b)
    expect_equal(dv:getUInt16(0), 1000)
  end)

  it("DataView reads f32 (getFloat)", function()
    local b = luna.data.pack("<f", 1.5)
    local dv = luna.data.newDataView(b)
    expect_near(dv:getFloat(0), 1.5, 0.0001)
  end)

  it("DataView reads f64 (getDouble)", function()
    local b = luna.data.pack("<d", 2.718281828)
    local dv = luna.data.newDataView(b)
    expect_near(dv:getDouble(0), 2.718281828, 1e-9)
  end)

  it("DataView reads u32", function()
    local b = luna.data.pack("<I", 100000)
    local dv = luna.data.newDataView(b)
    expect_equal(dv:getUInt32(0), 100000)
  end)

  it("DataView with offset reads sub-buffer", function()
    local b = luna.data.pack("BH", 99, 512)
    local dv = luna.data.newDataView(b, 1, 2)
    expect_equal(dv:getUInt16(0), 512)
    expect_equal(dv:getSize(), 2)
  end)

  it("DataView out-of-bounds access raises error", function()
    local b = luna.data.pack("B", 1)
    local dv = luna.data.newDataView(b)
    expect_error(function() dv:getUInt16(0) end)
  end)
end)

test_summary()
