-- Luna2D Audio API Tests

describe("luna.audio module exists", function()
    it("luna.audio is a table", function()
        expect_type("table", luna.audio)
    end)
end)

describe("luna.audio functions exist", function()
    it("setMasterVolume is a function", function()
        expect_type("function", luna.audio.setMasterVolume)
    end)

    it("getMasterVolume is a function", function()
        expect_type("function", luna.audio.getMasterVolume)
    end)

    it("newSource is a function", function()
        expect_type("function", luna.audio.newSource)
    end)
end)

describe("luna.audio volume", function()
    it("setMasterVolume accepts 0..1 range", function()
        expect_no_error(function()
            luna.audio.setMasterVolume(0.5)
        end)
    end)

    it("getMasterVolume returns a number", function()
        local vol = luna.audio.getMasterVolume()
        expect_type("number", vol)
    end)

    it("setMasterVolume/getMasterVolume roundtrip", function()
        luna.audio.setMasterVolume(0.75)
        expect_near(0.75, luna.audio.getMasterVolume(), 0.01)
        luna.audio.setMasterVolume(1.0) -- reset
    end)

    it("setMasterVolume clamps to valid range", function()
        luna.audio.setMasterVolume(0.0)
        expect_near(0.0, luna.audio.getMasterVolume(), 0.01)
        luna.audio.setMasterVolume(1.0)
        expect_near(1.0, luna.audio.getMasterVolume(), 0.01)
    end)
end)

describe("audio spatial", function()
    it("getDopplerScale returns 1 by default", function()
        expect_near(1.0, luna.audio.getDopplerScale(), 0.0001)
    end)
    it("setDopplerScale round-trips", function()
        luna.audio.setDopplerScale(2.0)
        expect_near(2.0, luna.audio.getDopplerScale(), 0.0001)
        luna.audio.setDopplerScale(1.0)  -- reset
    end)
    it("getDistanceModel returns a string", function()
        expect_type("string", luna.audio.getDistanceModel())
    end)
    it("setDistanceModel round-trips", function()
        luna.audio.setDistanceModel("linear")
        expect_equal("linear", luna.audio.getDistanceModel())
        luna.audio.setDistanceModel("inverse_clamped")  -- reset
    end)
    it("setListener / getListener round-trips", function()
        luna.audio.setListener(100, 50, 0)
        local x, y, z = luna.audio.getListener()
        expect_near(100, x, 0.001)
        expect_near(50, y, 0.001)
        expect_near(0, z, 0.001)
        luna.audio.setListener(0, 0, 0)  -- reset
    end)
    it("setListener2D / getListener2D backward compat", function()
        luna.audio.setListener2D(30, 40)
        local x, y = luna.audio.getListener2D()
        expect_near(30, x, 0.001)
        expect_near(40, y, 0.001)
        luna.audio.setListener2D(0, 0)  -- reset
    end)
end)

describe("audio.newDecoder", function()
  it("is a function", function()
    expect_type("function", luna.audio.newDecoder)
  end)
  it("errors on missing file", function()
    expect_error(function()
      luna.audio.newDecoder("nonexistent_file.wav")
    end, "nonexistent_file")
  end)
end)

describe("Decoder userdata methods", function()
  it("getChannelCount returns a number", function()
    local d = luna.audio.newDecoder("tests/fixtures/sine_mono_44100.wav")
    expect_type("number", d:getChannelCount())
  end)
  it("getChannelCount is 1 for mono fixture", function()
    local d = luna.audio.newDecoder("tests/fixtures/sine_mono_44100.wav")
    expect_equal(1, d:getChannelCount())
  end)
  it("getSampleRate returns a positive number", function()
    local d = luna.audio.newDecoder("tests/fixtures/sine_mono_44100.wav")
    local rate = d:getSampleRate()
    expect_type("number", rate)
    assert(rate > 0, "sample rate must be positive")
  end)
  it("getBitDepth returns a positive number", function()
    local d = luna.audio.newDecoder("tests/fixtures/sine_mono_44100.wav")
    local depth = d:getBitDepth()
    expect_type("number", depth)
    assert(depth > 0, "bit depth must be positive")
  end)
  it("getDuration returns a positive number", function()
    local d = luna.audio.newDecoder("tests/fixtures/sine_mono_44100.wav")
    local dur = d:getDuration()
    expect_type("number", dur)
    assert(dur > 0, "duration must be positive")
  end)
  it("isSeekable returns true", function()
    local d = luna.audio.newDecoder("tests/fixtures/sine_mono_44100.wav")
    expect_equal(true, d:isSeekable())
  end)
  it("tell starts at 0", function()
    local d = luna.audio.newDecoder("tests/fixtures/sine_mono_44100.wav")
    expect_near(0.0, d:tell(), 0.000001)
  end)
  it("seek and tell round-trip", function()
    local d = luna.audio.newDecoder("tests/fixtures/sine_mono_44100.wav")
    d:seek(0.01)
    expect_near(0.01, d:tell(), 0.001)
  end)
  it("decode returns userdata then nil at EOF", function()
    -- Use a large buffer so we hit EOF in one call
    local d = luna.audio.newDecoder("tests/fixtures/sine_mono_44100.wav", 1000000)
    local chunk = d:decode()
    -- chunk may be userdata (SoundData) or nil depending on file size
    assert(chunk ~= nil or chunk == nil, "decode must return userdata or nil")
    local eof = d:decode()
    -- second call after exhaustion must be nil
    assert(eof == nil, "decode at EOF must return nil")
  end)
  it("rewind resets position to 0", function()
    local d = luna.audio.newDecoder("tests/fixtures/sine_mono_44100.wav", 1000000)
    d:decode()  -- consume
    d:rewind()
    expect_near(0.0, d:tell(), 0.000001)
  end)
end)

-- Phase 15 — Queueable Sources
describe("audio.newQueueableSource", function()
  it("creates a queueable source and returns a number id", function()
    local q = luna.audio.newQueueableSource(44100, 16, 1, 4)
    expect_equal(type(q), "number")
  end)
  it("getFreeBufferCount returns buffer_count initially", function()
    local q = luna.audio.newQueueableSource(44100, 16, 1, 4)
    expect_equal(luna.audio.getFreeBufferCount(q), 4)
  end)
  it("getFreeBufferCount defaults to 4 buffers when omitted", function()
    local q = luna.audio.newQueueableSource(44100, 16, 1)
    expect_equal(luna.audio.getFreeBufferCount(q), 4)
  end)
  it("playQueueable does not error", function()
    local q = luna.audio.newQueueableSource(44100, 16, 1, 4)
    expect_no_error(function()
      luna.audio.playQueueable(q)
    end)
  end)
  it("stopQueueable resets free buffer count", function()
    local q = luna.audio.newQueueableSource(44100, 16, 1, 4)
    -- queue a SoundData buffer, then stop
    local sd = luna.audio.newSoundData(64, 44100, 1)
    luna.audio.queueSource(q, sd)
    -- after queuing, free count drops
    local after_queue = luna.audio.getFreeBufferCount(q)
    assert(after_queue < 4, "free count must decrease after queueSource")
    -- stop resets it
    luna.audio.stopQueueable(q)
    expect_equal(luna.audio.getFreeBufferCount(q), 4)
  end)
end)

-- Phase 18 — Playback Device Selection
describe("audio device selection", function()
  it("getPlaybackDevices returns a table", function()
    local devs = luna.audio.getPlaybackDevices()
    expect_equal(type(devs), "table")
  end)
  it("getPlaybackDevices has at least one entry", function()
    local devs = luna.audio.getPlaybackDevices()
    assert(#devs >= 1, "must have at least one device")
  end)
  it("getPlaybackDevice returns a string", function()
    expect_equal(type(luna.audio.getPlaybackDevice()), "string")
  end)
  it("setPlaybackDevice with valid name does not error", function()
    local devs = luna.audio.getPlaybackDevices()
    expect_no_error(function()
      luna.audio.setPlaybackDevice(devs[1])
    end)
  end)
  it("setPlaybackDevice with unknown name errors", function()
    expect_error(function()
      luna.audio.setPlaybackDevice("NonExistentDevice___XYZ")
    end, "Unknown audio device")
  end)
end)

test_summary()
