-- Lurek2D Lua BDD tests for lurek.spine
-- Headless: no GPU, no audio, no window.

describe("module interface", function()
    it("exposes newSkeleton factory", function()
        expect_type("function", lurek.spine.newSkeleton)
    end)
end)

describe("newSkeleton(name)", function()
    it("returns a userdata object", function()
        local sk = lurek.spine.newSkeleton("hero")
        expect_type("userdata", sk)
    end)

    it("starts with zero bones", function()
        local sk = lurek.spine.newSkeleton("test")
        expect_equal(0, sk:boneCount())
    end)

    it("starts with zero slots", function()
        local sk = lurek.spine.newSkeleton("test")
        expect_equal(0, sk:slotCount())
    end)
end)

describe("addBone(name, opts)", function()
    it("returns an index starting from 0", function()
        local sk = lurek.spine.newSkeleton("test")
        local idx = sk:addBone("root")
        expect_equal(0, idx)
    end)

    it("increments boneCount", function()
        local sk = lurek.spine.newSkeleton("test")
        sk:addBone("root")
        sk:addBone("torso")
        expect_equal(2, sk:boneCount())
    end)

    it("accepts opts table with x, y, rotation", function()
        local sk = lurek.spine.newSkeleton("test")
        sk:addBone("root", { x = 10, y = 20, rotation = 0.5 })
        expect_equal(1, sk:boneCount())
    end)
end)

describe("addChildBone(name, parent_idx, opts)", function()
    it("increments boneCount", function()
        local sk = lurek.spine.newSkeleton("test")
        local root = sk:addBone("root")
        sk:addChildBone("arm", root)
        expect_equal(2, sk:boneCount())
    end)
end)

describe("findBone(name)", function()
    it("returns the index of an existing bone", function()
        local sk = lurek.spine.newSkeleton("test")
        sk:addBone("root")
        sk:addBone("chest")
        local idx = sk:findBone("chest")
        expect_equal(1, idx)
    end)

    it("returns nil for unknown bone name", function()
        local sk = lurek.spine.newSkeleton("test")
        expect_equal(nil, sk:findBone("nonexistent"))
    end)
end)

describe("addSlot(name, bone_idx, attachment)", function()
    it("increments slotCount", function()
        local sk = lurek.spine.newSkeleton("test")
        local b = sk:addBone("root")
        sk:addSlot("slot0", b)
        expect_equal(1, sk:slotCount())
    end)

    it("accepts optional attachment name", function()
        local sk = lurek.spine.newSkeleton("test")
        local b = sk:addBone("root")
        sk:addSlot("slot0", b, "torso_skin")
        expect_equal(1, sk:slotCount())
    end)
end)

describe("findSlot(name)", function()
    it("returns the index of an existing slot", function()
        local sk = lurek.spine.newSkeleton("test")
        local b = sk:addBone("root")
        sk:addSlot("weapon_slot", b)
        local idx = sk:findSlot("weapon_slot")
        expect_equal(0, idx)
    end)

    it("returns nil for unknown slot name", function()
        local sk = lurek.spine.newSkeleton("test")
        expect_equal(nil, sk:findSlot("nope"))
    end)
end)

describe("setPosition(x, y)", function()
    it("does not error", function()
        local sk = lurek.spine.newSkeleton("test")
        sk:setPosition(50, 120)
    end)
end)

describe("updateWorldTransforms()", function()
    it("does not error", function()
        local sk = lurek.spine.newSkeleton("test")
        sk:addBone("root")
        sk:updateWorldTransforms()
    end)
end)

describe("getBoneWorld(idx)", function()
    it("returns a table with transform fields after updateWorldTransforms", function()
        local sk = lurek.spine.newSkeleton("test")
        local root = sk:addBone("root")
        sk:updateWorldTransforms()
        local t = sk:getBoneWorld(root)
        if t ~= nil then
            expect_type("number", t.x)
            expect_type("number", t.y)
            expect_type("number", t.rotation)
            expect_type("number", t.scale_x)
            expect_type("number", t.scale_y)
        end
    end)

    it("returns nil for out-of-bounds index", function()
        local sk = lurek.spine.newSkeleton("test")
        local result = sk:getBoneWorld(999)
        expect_equal(nil, result)
    end)
end)
describe("drawToImage(w, h)", function()
    it("is a function on skeleton", function()
        local sk = lurek.spine.newSkeleton("test")
        expect_type("function", function() sk:drawToImage(64, 64) end)
    end)

    it("returns a userdata (ImageData)", function()
        local sk = lurek.spine.newSkeleton("test")
        local img = sk:drawToImage(64, 64)
        expect_type("userdata", img)
    end)

    it("works with minimal dimensions 1x1", function()
        local sk = lurek.spine.newSkeleton("test")
        local img = sk:drawToImage(1, 1)
        expect_not_nil(img)
    end)
end)

--  Spine Extended API (merged from test_spine_ext.lua)

-- module interface

describe("new API factories", function()
    it("exposes newSkeletonAnimation factory", function()
        expect_type("function", lurek.spine.newSkeletonAnimation)
    end)
end)

-- animation playback

describe("skeleton animation playback", function()
    it("animation time advances after updateAnimation", function()
        local sk = lurek.spine.newSkeleton("test")
        sk:addBone("root")
        local anim = lurek.spine.newSkeletonAnimation("walk", 1.0)
        anim:addKeyframe(0, "x", 0.0, 0.0)
        anim:addKeyframe(0, "x", 1.0, 10.0)
        sk:addAnimation(anim)
        expect_true(sk:playAnimation("walk", true))
        sk:updateAnimation(0.1)
        local t = sk:getAnimationTime()
        expect_type("number", t)
        expect_true(t > 0.0, "time should advance once playback starts")
    end)

    it("stopAnimation freezes animation time", function()
        local sk = lurek.spine.newSkeleton("test")
        sk:addBone("root")
        local anim = lurek.spine.newSkeletonAnimation("walk", 1.0)
        anim:addKeyframe(0, "x", 0.0, 0.0)
        anim:addKeyframe(0, "x", 1.0, 10.0)
        sk:addAnimation(anim)
        expect_true(sk:playAnimation("walk", true))
        sk:updateAnimation(0.5)
        sk:stopAnimation()
        local stopped_at = sk:getAnimationTime()
        sk:updateAnimation(0.25)
        expect_near(0.5, stopped_at, 0.001)
        expect_near(stopped_at, sk:getAnimationTime(), 0.001)
    end)

    it("fresh skeleton has animation time of 0", function()
        local sk = lurek.spine.newSkeleton("new")
        expect_near(0.0, sk:getAnimationTime(), 0.001)
    end)
end)

-- SkeletonAnimation (timeline)

describe("SkeletonAnimation", function()
    it("returns a userdata", function()
        local sa = lurek.spine.newSkeletonAnimation("hero_walk", 1.0)
        expect_type("userdata", sa)
    end)

    it("getDuration returns the configured duration", function()
        local sa = lurek.spine.newSkeletonAnimation("run", 2.5)
        expect_near(2.5, sa:getDuration(), 0.001)
    end)

    it("getTimelineCount is 0 for new animation", function()
        local sa = lurek.spine.newSkeletonAnimation("idle", 1.0)
        expect_equal(0, sa:getTimelineCount())
    end)

    it("addKeyframe increments timeline count", function()
        local sa = lurek.spine.newSkeletonAnimation("run", 1.0)
        sa:addKeyframe(0, "x", 0.0, 0.0)
        expect_equal(1, sa:getTimelineCount())
    end)

    it("addKeyframe accepts optional easing parameter", function()
        local sa = lurek.spine.newSkeletonAnimation("run", 1.0)
        sa:addKeyframe(0, "x", 0.0, 10.0, "linear")
        sa:addKeyframe(0, "x", 1.0, 20.0, "ease_in_out")
        expect_equal(1, sa:getTimelineCount()) -- same bone-property = same timeline
    end)
end)

-- addAnimation (attach to skeleton)

describe("addAnimation()", function()
    it("does not error for a valid animation", function()
        local sk = lurek.spine.newSkeleton("hero")
        local sa = lurek.spine.newSkeletonAnimation("idle", 1.0)
        sk:addAnimation(sa) -- should not throw
        expect_equal(true, true)
    end)
end)

-- IK constraints

describe("IK constraints", function()
    it("addIKConstraint does not error", function()
        local sk = lurek.spine.newSkeleton("robot")
        sk:addIKConstraint("arm_ik", {0, 1}, true)
        expect_equal(true, true)
    end)

    it("setIKTarget does not error after addIKConstraint", function()
        local sk = lurek.spine.newSkeleton("robot")
        sk:addIKConstraint("arm_ik", {0, 1}, true)
        sk:setIKTarget("arm_ik", 100.0, 50.0)
        expect_equal(true, true)
    end)

    it("setIKTarget with unknown constraint returns false", function()
        local sk = lurek.spine.newSkeleton("robot")
        local ok = sk:setIKTarget("ghost_ik", 0.0, 0.0)
        expect_equal(false, ok)
    end)
end)

-- skins

describe("skeleton skins", function()
    it("getSkin returns the name from setSkin", function()
        local sk = lurek.spine.newSkeleton("char")
        sk:addSkin("hero")
        sk:setSkin("hero")
        expect_equal("hero", sk:getSkin())
    end)

    it("fresh skeleton has nil skin", function()
        local sk = lurek.spine.newSkeleton("char")
        expect_equal(nil, sk:getSkin())
    end)

    it("setSkin with unknown skin returns false", function()
        local sk = lurek.spine.newSkeleton("char")
        local ok = sk:setSkin("ghost_skin")
        expect_equal(false, ok)
    end)

    it("setSkinMapping does not error for known skin/slot", function()
        local sk = lurek.spine.newSkeleton("char")
        sk:addSkin("armor")
        sk:setSkinMapping("armor", "torso", "heavy_chest")
        expect_equal(true, true)
    end)
end)

describe("lurek.spine regression coverage", function()
    it("skeleton topology and world transform helpers stay consistent", function()
        local sk = lurek.spine.newSkeleton("rig")
        local root = sk:addBone("root", { x = 5, y = 10 })
        local arm = sk:addChildBone("arm", root, { x = 3, y = 4 })
        local slot = sk:addSlot("hand_slot", arm, "hand")

        sk:setPosition(20, 30)
        sk:updateWorldTransforms()

        local world = sk:getBoneWorld(arm)
        local image = sk:drawToImage(32, 32)

        expect_equal(root, sk:findBone("root"))
        expect_equal(arm, sk:findBone("arm"))
        expect_equal(slot, sk:findSlot("hand_slot"))
        expect_equal(2, sk:boneCount())
        expect_equal(1, sk:slotCount())
        expect_type("table", world)
        expect_type("number", world.x)
        expect_type("number", world.y)
        expect_type("userdata", image)
    end)

    it("SkeletonAnimation exposes duration timelines and event windows", function()
        local anim = lurek.spine.newSkeletonAnimation("wave", 1.5)
        anim:addKeyframe(0, "x", 0.0, 0.0)
        anim:addKeyframe(0, "x", 1.0, 10.0)
        anim:addEventKey(0.25, "start", 1.0)
        anim:addEventKey(0.75, "peak", 2.0)

        local events = anim:getEvents(0.0, 0.5)

        expect_near(1.5, anim:getDuration(), 0.001)
        expect_equal(1, anim:getTimelineCount())
        expect_equal(1, #events)
        expect_equal("start", events[1].name)
        expect_near(1.0, events[1].value, 0.001)
    end)

    it("skeleton playback and skin helpers work with a real animation", function()
        local sk = lurek.spine.newSkeleton("hero")
        sk:addBone("root")
        sk:addSkin("hero_skin")

        expect_true(sk:setSkin("hero_skin"))
        expect_equal("hero_skin", sk:getSkin())

        local anim = lurek.spine.newSkeletonAnimation("walk", 1.0)
        anim:addKeyframe(0, "x", 0.0, 0.0)
        anim:addKeyframe(0, "x", 1.0, 12.0)
        sk:addAnimation(anim)

        expect_true(sk:playAnimation("walk", false))

        sk:updateAnimation(0.5)
        expect_true(sk:getAnimationTime() > 0.0, "expected animation time to advance")

        sk:stopAnimation()
        local stopped_at = sk:getAnimationTime()
        sk:updateAnimation(0.25)
        expect_near(0.5, stopped_at, 0.001)
        expect_near(stopped_at, sk:getAnimationTime(), 0.001)
    end)
end)

-- =========================================================================
-- =========================================================================

describe("Skeleton:blendAnimation ", function()
    it("blendAnimation does not crash on a fresh skeleton", function()
        local skel = lurek.spine.newSkeleton("cov_blend_skel")
        local anim = lurek.spine.newSkeletonAnimation("idle", 1.0)
        local ok, _ = pcall(function()
            skel:blendAnimation(anim, 1.0, 0.0)
        end)
        expect_type("boolean", ok)
    end)
end)

describe("SkeletonAnimation:addEventKey ", function()
    it("addEventKey does not crash", function()
        local anim = lurek.spine.newSkeletonAnimation("cov_anim", 1.0)
        local ok, _ = pcall(function()
            anim:addEventKey(0.5, "footstep", 0)
        end)
        expect_type("boolean", ok)
    end)
end)
test_summary()
