-- tests/lua/unit/test_html_unit.lua
-- Unit tests for lurek.html (standalone HTML/CSS layout engine).
-- @covers lurek.html

local describe = describe or function(name, fn) print('describe: ' .. name) fn() end
local it = it or function(name, fn) print('  it: ' .. name) fn() end
local expect_type = function(v, t, msg) assert(type(v) == t, msg) end
local expect_not_nil = expect_not_nil or function(v, msg) assert(v ~= nil, msg) end
local expect_true = expect_true or function(v, msg) assert(v == true, msg) end
local expect_false = expect_false or function(v, msg) assert(v == false, msg) end
local expect_equal = expect_equal or function(a, b, msg) assert(a == b, msg) end
local test_summary = test_summary or function() end

-- =========================================================================
-- lurek.html Tests
-- =========================================================================

describe("lurek.html module table exists", function()
    -- @tests lurek.html
    -- @description the html sub-table is present and exposes the three top-level functions
    it("lurek.html is a table", function()
        expect_type(lurek.html, "table", "lurek.html must be a table")
    end)
    it("newDocument is a function", function()
        expect_type(lurek.html.newDocument, "function",
            "lurek.html.newDocument must be a function")
    end)
    it("loadDocument is a function", function()
        expect_type(lurek.html.loadDocument, "function",
            "lurek.html.loadDocument must be a function")
    end)
    it("supports is a function", function()
        expect_type(lurek.html.supports, "function",
            "lurek.html.supports must be a function")
    end)
end)

describe("lurek.html.newDocument constructor", function()
    -- @tests lurek.html.newDocument
    -- @description newDocument creates a valid HtmlDocument in all calling forms
    it("newDocument() returns a non-nil value", function()
        local doc = lurek.html.newDocument()
        expect_not_nil(doc, "newDocument() must return an HtmlDocument")
    end)
    it("returned document has setHtml method", function()
        local doc = lurek.html.newDocument()
        expect_type(doc.setHtml, "function", "HtmlDocument must have setHtml method")
    end)
    it("newDocument(html_string) succeeds without error", function()
        local ok, err = pcall(function()
            lurek.html.newDocument("<div id='hero'>Hello</div>")
        end)
        expect_true(ok, "newDocument(html) must not error: " .. tostring(err))
    end)
    it("newDocument with opts.width/height sets viewport", function()
        local doc = lurek.html.newDocument(nil, { width = 800, height = 600 })
        expect_not_nil(doc, "newDocument with opts must succeed")
        local w, h = doc:getViewport()
        expect_equal(w, 800, "viewport width must be 800")
        expect_equal(h, 600, "viewport height must be 600")
    end)
    it("newDocument with opts.css sets initial stylesheet without error", function()
        local ok = pcall(function()
            lurek.html.newDocument(nil, { css = "body { color: red; }" })
        end)
        expect_true(ok, "newDocument with opts.css must not error")
    end)
end)

describe("HtmlDocument content API", function()
    -- @tests HtmlDocument.setHtml HtmlDocument.getHtml HtmlDocument.setCss HtmlDocument.addCss HtmlDocument.clearCss HtmlDocument.isDirty HtmlDocument.relayout HtmlDocument.update
    -- @description set/get HTML and CSS content, dirty flag, layout pass
    local function make_doc()
        return lurek.html.newDocument()
    end

    it("setHtml then getHtml returns a string", function()
        local doc = make_doc()
        doc:setHtml("<p id='msg'>world</p>")
        local html = doc:getHtml()
        expect_type(html, "string", "getHtml must return string after setHtml")
    end)
    it("setCss does not error", function()
        local doc = make_doc()
        local ok, err = pcall(function() doc:setCss("p { font-size: 14px; }") end)
        expect_true(ok, "setCss must not error: " .. tostring(err))
    end)
    it("addCss does not error", function()
        local doc = make_doc()
        local ok, err = pcall(function() doc:addCss(".btn { background: #333; }") end)
        expect_true(ok, "addCss must not error: " .. tostring(err))
    end)
    it("clearCss does not error after setCss", function()
        local doc = make_doc()
        doc:setCss("p { color: blue; }")
        local ok, err = pcall(function() doc:clearCss() end)
        expect_true(ok, "clearCss must not error: " .. tostring(err))
    end)
    it("isDirty is true after setHtml", function()
        local doc = make_doc()
        doc:setHtml("<span>dirty</span>")
        expect_true(doc:isDirty(), "isDirty must be true after setHtml")
    end)
    it("relayout clears the dirty flag", function()
        local doc = make_doc()
        doc:setHtml("<span>test</span>")
        doc:relayout()
        expect_false(doc:isDirty(), "isDirty must be false after relayout")
    end)
    it("update(dt) does not error", function()
        local doc = make_doc()
        local ok, err = pcall(function() doc:update(1/60) end)
        expect_true(ok, "update(dt) must not error: " .. tostring(err))
    end)
end)

describe("HtmlDocument viewport API", function()
    -- @tests HtmlDocument.setViewport HtmlDocument.getViewport
    -- @description viewport controls document layout dimensions
    it("setViewport / getViewport round-trip", function()
        local doc = lurek.html.newDocument()
        doc:setViewport(1280, 720)
        local w, h = doc:getViewport()
        expect_equal(w, 1280, "viewport width must match")
        expect_equal(h, 720,  "viewport height must match")
    end)
    it("setViewport marks document dirty", function()
        local doc = lurek.html.newDocument()
        doc:relayout()
        doc:setViewport(640, 480)
        expect_true(doc:isDirty(), "setViewport must mark the document dirty")
    end)
end)

describe("HtmlDocument element access API", function()
    -- @tests HtmlDocument.getRoot HtmlDocument.getElementById HtmlDocument.query HtmlDocument.queryAll
    -- @description DOM traversal and element lookup
    local function make_doc_with_content()
        local doc = lurek.html.newDocument()
        doc:setHtml([[
            <div id="box" class="container">
                <span id="label" class="text">Hi</span>
                <span id="label2" class="text">Bye</span>
            </div>
        ]])
        doc:relayout()
        return doc
    end

    it("getRoot returns a non-nil element", function()
        local doc = make_doc_with_content()
        local root = doc:getRoot()
        expect_not_nil(root, "getRoot must return an HtmlElement")
    end)
    it("getRoot element has getTagName method", function()
        local doc = make_doc_with_content()
        local root = doc:getRoot()
        expect_type(root.getTagName, "function", "root must expose getTagName")
    end)
    it("getElementById finds element by id", function()
        local doc = make_doc_with_content()
        local el = doc:getElementById("box")
        expect_not_nil(el, "getElementById('box') must find the element")
    end)
    it("getElementById returns nil for missing id", function()
        local doc = make_doc_with_content()
        local el = doc:getElementById("nonexistent_id_xyz")
        expect_nil(el, "getElementById must return nil for a missing id")
    end)
    it("query('#id') returns the element", function()
        local doc = make_doc_with_content()
        local el = doc:query("#label")
        expect_not_nil(el, "query('#label') must find the element")
    end)
    it("queryAll('.class') returns a table", function()
        local doc = make_doc_with_content()
        local results = doc:queryAll(".text")
        expect_type(results, "table", "queryAll must return a table")
    end)
    it("queryAll('.class') finds all matching elements", function()
        local doc = make_doc_with_content()
        local results = doc:queryAll(".text")
        expect_true(#results >= 2, "queryAll('.text') must find at least 2 elements")
    end)
    it("queryAll with no matches returns empty table", function()
        local doc = make_doc_with_content()
        local results = doc:queryAll(".no-such-class-xyz")
        expect_type(results, "table", "queryAll must return a table even when empty")
        expect_equal(#results, 0, "queryAll with no match must return empty table")
    end)
end)

describe("HtmlDocument event and input API", function()
    -- @tests HtmlDocument.on HtmlDocument.off HtmlDocument.mousepressed HtmlDocument.mousereleased HtmlDocument.mousemoved HtmlDocument.wheelmoved HtmlDocument.keypressed HtmlDocument.textinput
    -- @description input forwarding and event subscription on the document
    local function make_doc()
        local doc = lurek.html.newDocument()
        doc:setHtml("<button id='btn'>Click</button>")
        doc:relayout()
        return doc
    end

    it("on() returns a non-nil handle", function()
        local doc = make_doc()
        local handle = doc:on("click", function() end)
        expect_not_nil(handle, "on() must return a handle")
    end)
    it("off(handle) does not error", function()
        local doc = make_doc()
        local handle = doc:on("click", function() end)
        local ok, err = pcall(function() doc:off(handle) end)
        expect_true(ok, "off(handle) must not error: " .. tostring(err))
    end)
    it("mousepressed returns a boolean", function()
        local result = make_doc():mousepressed(100, 100, 1)
        expect_type(result, "boolean", "mousepressed must return boolean")
    end)
    it("mousereleased returns a boolean", function()
        local result = make_doc():mousereleased(100, 100, 1)
        expect_type(result, "boolean", "mousereleased must return boolean")
    end)
    it("mousemoved returns a boolean", function()
        local result = make_doc():mousemoved(200, 150)
        expect_type(result, "boolean", "mousemoved must return boolean")
    end)
    it("wheelmoved returns a boolean", function()
        local result = make_doc():wheelmoved(0, -1)
        expect_type(result, "boolean", "wheelmoved must return boolean")
    end)
    it("keypressed returns a boolean", function()
        local result = make_doc():keypressed("return")
        expect_type(result, "boolean", "keypressed must return boolean")
    end)
    it("textinput returns a boolean", function()
        local result = make_doc():textinput("a")
        expect_type(result, "boolean", "textinput must return boolean")
    end)
end)

describe("HtmlElement DOM manipulation API", function()
    -- @tests HtmlElement.getDocument HtmlElement.getTagName HtmlElement.getId HtmlElement.setId HtmlElement.getText HtmlElement.setText HtmlElement.getHtml HtmlElement.setHtml HtmlElement.appendHtml HtmlElement.getAttribute HtmlElement.setAttribute HtmlElement.removeAttribute HtmlElement.hasClass HtmlElement.addClass HtmlElement.removeClass HtmlElement.toggleClass HtmlElement.getStyle HtmlElement.setStyle HtmlElement.getRect HtmlElement.focus HtmlElement.blur HtmlElement.query HtmlElement.queryAll HtmlElement.on HtmlElement.off HtmlElement.remove
    -- @description complete HtmlElement DOM API coverage
    local function make_el()
        local doc = lurek.html.newDocument()
        doc:setHtml([[
            <div id="root" class="wrapper">
                <p id="para" class="text">Hello</p>
            </div>
        ]])
        doc:relayout()
        return doc:getElementById("para"), doc
    end

    it("getTagName returns a string", function()
        local el = make_el()
        expect_type(el:getTagName(), "string", "getTagName must return a string")
    end)
    it("getId returns the element's id", function()
        local el = make_el()
        expect_equal(el:getId(), "para", "getId must return 'para'")
    end)
    it("setId updates the element id", function()
        local el = make_el()
        el:setId("para2")
        expect_equal(el:getId(), "para2", "setId must update the id")
    end)
    it("getText returns the text content", function()
        local el = make_el()
        expect_equal(el:getText(), "Hello", "getText must return 'Hello'")
    end)
    it("setText updates text content", function()
        local el = make_el()
        el:setText("World")
        expect_equal(el:getText(), "World", "setText must update text")
    end)
    it("getHtml returns a string", function()
        local el = make_el()
        expect_type(el:getHtml(), "string", "getHtml must return a string")
    end)
    it("setAttribute / getAttribute round-trip", function()
        local el = make_el()
        el:setAttribute("data-score", "42")
        expect_equal(el:getAttribute("data-score"), "42",
            "getAttribute must return the set value")
    end)
    it("removeAttribute clears the attribute", function()
        local el = make_el()
        el:setAttribute("data-tmp", "x")
        el:removeAttribute("data-tmp")
        expect_nil(el:getAttribute("data-tmp"),
            "getAttribute must return nil after removeAttribute")
    end)
    it("addClass adds the class; hasClass detects it", function()
        local el = make_el()
        el:addClass("active")
        expect_true(el:hasClass("active"), "hasClass must return true after addClass")
    end)
    it("removeClass removes the class", function()
        local el = make_el()
        el:addClass("active")
        el:removeClass("active")
        expect_false(el:hasClass("active"),
            "hasClass must return false after removeClass")
    end)
    it("toggleClass adds when not present and returns true", function()
        local el = make_el()
        local result = el:toggleClass("highlight")
        expect_true(result, "toggleClass must return true when adding")
        expect_true(el:hasClass("highlight"),
            "class must be present after toggle-add")
    end)
    it("toggleClass removes when already present and returns false", function()
        local el = make_el()
        el:addClass("highlight")
        local result = el:toggleClass("highlight")
        expect_false(result, "toggleClass must return false when removing")
        expect_false(el:hasClass("highlight"),
            "class must be absent after toggle-remove")
    end)
    it("setStyle / getStyle round-trip", function()
        local el = make_el()
        el:setStyle("color", "red")
        expect_equal(el:getStyle("color"), "red",
            "getStyle must return the set value")
    end)
    it("getRect returns four numbers", function()
        local el = make_el()
        local x, y, w, h = el:getRect()
        expect_type(x, "number", "getRect x must be a number")
        expect_type(y, "number", "getRect y must be a number")
        expect_type(w, "number", "getRect w must be a number")
        expect_type(h, "number", "getRect h must be a number")
    end)
    it("focus does not error", function()
        local el = make_el()
        local ok, err = pcall(function() el:focus() end)
        expect_true(ok, "focus() must not error: " .. tostring(err))
    end)
    it("blur does not error", function()
        local el = make_el()
        local ok, err = pcall(function() el:blur() end)
        expect_true(ok, "blur() must not error: " .. tostring(err))
    end)
    it("getDocument returns the owning HtmlDocument", function()
        local el, doc = make_el()
        local owner = el:getDocument()
        expect_not_nil(owner, "getDocument must return the owning document")
        -- The owner should also expose setHtml, confirming it's an HtmlDocument.
        expect_type(owner.setHtml, "function",
            "getDocument result must expose setHtml")
    end)
    it("element:query finds a descendant", function()
        local _, doc = make_el()
        local root = doc:getElementById("root")
        local child = root:query("#para")
        expect_not_nil(child, "element:query('#para') must find the child")
    end)
    it("element:queryAll returns a table", function()
        local _, doc = make_el()
        local root = doc:getElementById("root")
        local results = root:queryAll(".text")
        expect_type(results, "table",
            "element:queryAll must return a table")
    end)
    it("element:on returns a handle", function()
        local el = make_el()
        local h = el:on("click", function() end)
        expect_not_nil(h, "element:on must return a handle")
    end)
    it("element:off with handle does not error", function()
        local el = make_el()
        local h = el:on("click", function() end)
        local ok, err = pcall(function() el:off(h) end)
        expect_true(ok, "element:off must not error: " .. tostring(err))
    end)
    it("appendHtml adds content without replacing existing text", function()
        local el = make_el()
        el:appendHtml("<em>!</em>")
        local html = el:getHtml()
        expect_type(html, "string", "getHtml after appendHtml must be string")
        expect_true(html:len() > 0, "getHtml after appendHtml must be non-empty")
    end)
end)

describe("lurek.html.supports feature flags", function()
    -- @tests lurek.html.supports
    -- @description supports() returns true for known features and false for unknown ones
    it("supports('html') is true", function()
        expect_true(lurek.html.supports("html"),
            "supports('html') must be true")
    end)
    it("supports('css') is true", function()
        expect_true(lurek.html.supports("css"),
            "supports('css') must be true")
    end)
    it("supports('selectors') is true", function()
        expect_true(lurek.html.supports("selectors"),
            "supports('selectors') must be true")
    end)
    it("supports('pure-rust') is true", function()
        expect_true(lurek.html.supports("pure-rust"),
            "supports('pure-rust') must be true")
    end)
    it("supports('nonexistent-feature-xyz') is false", function()
        expect_false(lurek.html.supports("nonexistent-feature-xyz"),
            "supports must return false for unknown features")
    end)
end)

describe("lurek.html.loadDocument error handling", function()
    -- @tests lurek.html.loadDocument
    -- @description loadDocument with a nonexistent path must raise a Lua error
    it("loadDocument on missing file raises an error", function()
        local ok, err = pcall(function()
            lurek.html.loadDocument("nonexistent_file_xyzzy.rml")
        end)
        expect_false(ok, "loadDocument on missing file must raise an error")
        expect_true(err ~= nil and #tostring(err) > 0,
            "the error value must be present and stringify to a non-empty message")
    end)
end)

test_summary()
