-- BDD tests for luna.network and luna.net modules

-- ── luna.network (high-level API) ────────────────────────────────────

describe("luna.network", function()
  it("is a table", function()
    expect_equal(type(luna.network), "table")
  end)

  it("newHost is a function", function()
    expect_equal(type(luna.network.newHost), "function")
  end)
end)

describe("luna.network.newHost", function()
  it("creates a client host with no arguments", function()
    local host = luna.network.newHost()
    expect_equal(type(host), "userdata")
    host:destroy()
  end)

  it("creates a host with port option", function()
    local host = luna.network.newHost({ port = 0 })
    expect_equal(type(host), "userdata")
    host:destroy()
  end)

  it("creates a host with all options", function()
    local host = luna.network.newHost({
      port = 0,
      maxPeers = 4,
      channels = 2,
      inBandwidth = 0,
      outBandwidth = 0,
    })
    expect_equal(type(host), "userdata")
    host:destroy()
  end)

  it("clamps maxPeers to 8", function()
    -- Requesting more than MAX_PEERS should clamp, not error
    local host = luna.network.newHost({ maxPeers = 100 })
    expect_equal(type(host), "userdata")
    host:destroy()
  end)
end)

describe("luna.network host methods", function()
  it("service returns nil when no events", function()
    local host = luna.network.newHost()
    local event = host:service(0)
    expect_equal(event, nil)
    host:destroy()
  end)

  it("getAddress returns address and port", function()
    local host = luna.network.newHost()
    local addr, port = host:getAddress()
    expect_equal(type(addr), "string")
    expect_equal(type(port), "number")
    host:destroy()
  end)

  it("getPeerCount returns peer limit", function()
    local host = luna.network.newHost()
    local count = host:getPeerCount()
    expect_equal(4, count)
    host:destroy()
  end)

  it("flush succeeds with no pending data", function()
    local host = luna.network.newHost()
    local ok, err = pcall(function() host:flush() end)
    expect_equal(ok, true)
    host:destroy()
  end)

  it("destroy makes host unusable", function()
    local host = luna.network.newHost()
    host:destroy()
    local ok, err = pcall(function() host:service(0) end)
    expect_equal(ok, false)
  end)

  it("setBandwidthLimit does not error", function()
    local host = luna.network.newHost()
    local ok, err = pcall(function() host:setBandwidthLimit(100000, 50000) end)
    expect_equal(ok, true)
    host:destroy()
  end)

  it("getPeers returns empty table when no connections", function()
    local host = luna.network.newHost()
    local peers = host:getPeers()
    expect_equal(type(peers), "table")
    local count = 0
    for _ in pairs(peers) do count = count + 1 end
    expect_equal(count, 0)
    host:destroy()
  end)

  it("getStats returns a table", function()
    local host = luna.network.newHost()
    local stats = host:getStats()
    expect_equal(type(stats), "table")
    host:destroy()
  end)
end)

-- ── luna.net (raw ENet API) ──────────────────────────────────────────

describe("luna.net", function()
  it("is a table", function()
    expect_equal(type(luna.net), "table")
  end)

  it("host_create is a function", function()
    expect_equal(type(luna.net.host_create), "function")
  end)

  it("linked_version is a function", function()
    expect_equal(type(luna.net.linked_version), "function")
  end)
end)

describe("luna.net.linked_version", function()
  it("returns a string", function()
    local ver = luna.net.linked_version()
    expect_equal(type(ver), "string")
  end)
end)

describe("luna.net.host_create", function()
  it("creates a client host with no arguments", function()
    local host = luna.net.host_create()
    expect_equal(type(host), "userdata")
    host:destroy()
  end)

  it("creates a server host with bind address", function()
    local host = luna.net.host_create("*:0")
    expect_equal(type(host), "userdata")
    host:destroy()
  end)

  it("creates a host with peer count", function()
    local host = luna.net.host_create(nil, 6)
    expect_equal(type(host), "userdata")
    host:destroy()
  end)

  it("creates a host with all parameters", function()
    local host = luna.net.host_create("*:0", 4, 2, 0, 0)
    expect_equal(type(host), "userdata")
    host:destroy()
  end)
end)

describe("luna.net host methods", function()
  it("service returns nil when no events", function()
    local host = luna.net.host_create()
    local evt = host:service(0)
    expect_equal(evt, nil)
    host:destroy()
  end)

  it("get_socket_address returns address string", function()
    local host = luna.net.host_create()
    local addr = host:get_socket_address()
    expect_equal(type(addr), "string")
    host:destroy()
  end)

  it("connected_peers returns zero initially", function()
    local host = luna.net.host_create()
    local count = host:connected_peers()
    expect_equal(count, 0)
    host:destroy()
  end)

  it("flush succeeds with no pending data", function()
    local host = luna.net.host_create()
    local ok, err = pcall(function() host:flush() end)
    expect_equal(ok, true)
    host:destroy()
  end)

  it("destroy makes host unusable", function()
    local host = luna.net.host_create()
    host:destroy()
    local ok, err = pcall(function() host:service(0) end)
    expect_equal(ok, false)
  end)

  it("bandwidth_limit returns in and out", function()
    local host = luna.net.host_create()
    local in_bw, out_bw = host:bandwidth_limit()
    -- Default is unlimited (0 or nil)
    expect_equal(type(in_bw), "number")
    expect_equal(type(out_bw), "number")
    host:destroy()
  end)

  it("max_packet_size returns a number", function()
    local host = luna.net.host_create()
    local sz = host:max_packet_size()
    expect_equal(type(sz), "number")
    host:destroy()
  end)

  it("max_waiting_data returns a number", function()
    local host = luna.net.host_create()
    local wd = host:max_waiting_data()
    expect_equal(type(wd), "number")
    host:destroy()
  end)

  it("duplicate_peers returns a number", function()
    local host = luna.net.host_create()
    local dp = host:duplicate_peers()
    expect_equal(type(dp), "number")
    host:destroy()
  end)

  it("enable_checksum does not error", function()
    local host = luna.net.host_create()
    local ok = pcall(function() host:enable_checksum(true) end)
    expect_equal(ok, true)
    host:destroy()
  end)

  it("compress_with_range_coder does not error", function()
    local host = luna.net.host_create()
    local ok = pcall(function() host:compress_with_range_coder() end)
    expect_equal(ok, true)
    host:destroy()
  end)

  it("compress_disable does not error", function()
    local host = luna.net.host_create()
    local ok = pcall(function() host:compress_disable() end)
    expect_equal(ok, true)
    host:destroy()
  end)

  it("get_stats returns a table", function()
    local host = luna.net.host_create()
    local stats = host:get_stats()
    expect_equal(type(stats), "table")
    host:destroy()
  end)

  it("reset_stats does not error", function()
    local host = luna.net.host_create()
    local ok = pcall(function() host:reset_stats() end)
    expect_equal(ok, true)
    host:destroy()
  end)

  it("received_address returns a string", function()
    local host = luna.net.host_create()
    local addr = host:received_address()
    expect_equal(type(addr), "string")
    host:destroy()
  end)
end)

describe("luna.net time", function()
  it("time_get returns a number", function()
    local t = luna.net.time_get()
    expect_equal(type(t), "number")
  end)

  it("time_get increases monotonically", function()
    local t1 = luna.net.time_get()
    local t2 = luna.net.time_get()
    -- At minimum, t2 >= t1 (both from wall clock)
    expect_equal(t2 >= t1, true)
  end)
end)

describe("enet global alias", function()
  it("enet is a table", function()
    expect_equal(type(_G.enet), "table")
  end)

  it("enet.host_create is a function", function()
    expect_equal(type(_G.enet.host_create), "function")
  end)

  it("enet.linked_version returns a string", function()
    expect_equal(type(_G.enet.linked_version()), "string")
  end)
end)

test_summary()
