-- Lurek2D Particle API Tests

describe("lurek.particles module exists", function()
    it("lurek.particles is a table", function()
        expect_type("table", lurek.particles)
    end)
end)

describe("lurek.particles.newSystem", function()
    it("newSystem returns userdata", function()
        local ps = lurek.particles.newSystem()
        expect_type("userdata", ps)
    end)

    it("newSystem with no config uses defaults", function()
        local ps = lurek.particles.newSystem()
        expect_type("userdata", ps)
        -- default system starts active
        expect_true(lurek.particles.isActive(ps), "default system should be active")
    end)

    it("newSystem with config table", function()
        local ps = lurek.particles.newSystem({ emissionRate = 50, maxParticles = 100 })
        expect_type("userdata", ps)
    end)

    it("newSystem backward compat: sizeStart/sizeEnd", function()
        local ps = lurek.particles.newSystem({ sizeStart = 8.0, sizeEnd = 2.0 })
        expect_type("userdata", ps)
    end)

    it("newSystem backward compat: colorStart/colorEnd", function()
        local ps = lurek.particles.newSystem({
            colorStart = {1, 0, 0, 1},
            colorEnd   = {1, 0, 0, 0}
        })
        expect_type("userdata", ps)
    end)
end)

describe("lurek.particles lifecycle", function()
    it("isActive returns true for new system", function()
        local ps = lurek.particles.newSystem()
        expect_true(lurek.particles.isActive(ps), "new system should be active")
    end)

    it("isPaused returns false for new system", function()
        local ps = lurek.particles.newSystem()
        expect_true(not lurek.particles.isPaused(ps), "new system should not be paused")
    end)

    it("isStopped returns false for new (active) system", function()
        local ps = lurek.particles.newSystem()
        expect_true(not lurek.particles.isStopped(ps), "new system should not be stopped")
    end)

    it("stop sets isStopped", function()
        local ps = lurek.particles.newSystem()
        lurek.particles.stop(ps)
        expect_true(lurek.particles.isStopped(ps), "stopped system should report isStopped")
    end)

    it("pause sets isPaused", function()
        local ps = lurek.particles.newSystem()
        lurek.particles.pause(ps)
        expect_true(lurek.particles.isPaused(ps), "paused system should report isPaused")
    end)

    it("start after stop resumes active state", function()
        local ps = lurek.particles.newSystem()
        lurek.particles.stop(ps)
        lurek.particles.start(ps)
        expect_true(lurek.particles.isActive(ps), "started system should be active")
    end)

    it("reset clears particles and keeps active", function()
        local ps = lurek.particles.newSystem({ emissionRate = 1000, maxParticles = 50 })
        lurek.particles.update(ps, 1.0)
        lurek.particles.reset(ps)
        expect_equal(0, lurek.particles.getCount(ps), "count after reset")
    end)
end)

describe("lurek.particles.getCount / isEmpty / isFull", function()
    it("getCount returns 0 before any update", function()
        local ps = lurek.particles.newSystem()
        expect_equal(0, lurek.particles.getCount(ps), "count before update")
    end)

    it("isEmpty returns true when count is 0", function()
        local ps = lurek.particles.newSystem()
        expect_true(lurek.particles.isEmpty(ps), "empty before update")
    end)

    it("isFull returns false for fresh system", function()
        local ps = lurek.particles.newSystem({ maxParticles = 100 })
        expect_true(not lurek.particles.isFull(ps), "not full before update")
    end)

    it("emit burst fills particles immediately", function()
        local ps = lurek.particles.newSystem({ maxParticles = 100 })
        lurek.particles.stop(ps)  -- stop continuous emission
        lurek.particles.emit(ps, 10)
        expect_true(lurek.particles.getCount(ps) > 0, "count should increase after emit")
    end)

    it("getCount increases after update with high emission rate", function()
        local ps = lurek.particles.newSystem({ emissionRate = 500, maxParticles = 50 })
        lurek.particles.update(ps, 0.1)
        expect_true(lurek.particles.getCount(ps) > 0, "count should be positive after update")
    end)
end)

describe("lurek.particles position", function()
    it("setPosition / getPosition round-trip", function()
        local ps = lurek.particles.newSystem()
        lurek.particles.setPosition(ps, 100, 200)
        local x, y = lurek.particles.getPosition(ps)
        expect_true(math.abs(x - 100) < 0.001, "x position should match")
        expect_true(math.abs(y - 200) < 0.001, "y position should match")
    end)

    it("getPosition returns 0,0 by default", function()
        local ps = lurek.particles.newSystem()
        local x, y = lurek.particles.getPosition(ps)
        expect_true(math.abs(x) < 0.001, "default x should be 0")
        expect_true(math.abs(y) < 0.001, "default y should be 0")
    end)

    it("moveTo updates position", function()
        local ps = lurek.particles.newSystem()
        lurek.particles.moveTo(ps, 50, 75)
        local x, y = lurek.particles.getPosition(ps)
        expect_true(math.abs(x - 50) < 0.001, "moveTo x")
        expect_true(math.abs(y - 75) < 0.001, "moveTo y")
    end)
end)

describe("lurek.particles emission settings", function()
    it("setEmissionRate / getEmissionRate round-trip", function()
        local ps = lurek.particles.newSystem()
        lurek.particles.setEmissionRate(ps, 99.0)
        local rate = lurek.particles.getEmissionRate(ps)
        expect_true(math.abs(rate - 99.0) < 0.001, "emission rate round-trip")
    end)

    it("setParticleLifetime / getParticleLifetime round-trip", function()
        local ps = lurek.particles.newSystem()
        lurek.particles.setParticleLifetime(ps, 0.5, 2.5)
        local mn, mx = lurek.particles.getParticleLifetime(ps)
        expect_true(math.abs(mn - 0.5) < 0.001, "lifetime min")
        expect_true(math.abs(mx - 2.5) < 0.001, "lifetime max")
    end)

    it("setEmitterLifetime / getEmitterLifetime round-trip", function()
        local ps = lurek.particles.newSystem()
        lurek.particles.setEmitterLifetime(ps, 5.0)
        local t = lurek.particles.getEmitterLifetime(ps)
        expect_true(math.abs(t - 5.0) < 0.001, "emitter lifetime")
    end)

    it("setSpeed / getSpeed round-trip", function()
        local ps = lurek.particles.newSystem()
        lurek.particles.setSpeed(ps, 20.0, 80.0)
        local mn, mx = lurek.particles.getSpeed(ps)
        expect_true(math.abs(mn - 20.0) < 0.001, "speed min")
        expect_true(math.abs(mx - 80.0) < 0.001, "speed max")
    end)

    it("setDirection / getDirection round-trip", function()
        local ps = lurek.particles.newSystem()
        lurek.particles.setDirection(ps, 1.23)
        local d = lurek.particles.getDirection(ps)
        expect_true(math.abs(d - 1.23) < 0.001, "direction")
    end)

    it("setSpread / getSpread round-trip", function()
        local ps = lurek.particles.newSystem()
        lurek.particles.setSpread(ps, 0.5)
        local s = lurek.particles.getSpread(ps)
        expect_true(math.abs(s - 0.5) < 0.001, "spread")
    end)
end)

describe("lurek.particles acceleration settings", function()
    it("setLinearAcceleration / getLinearAcceleration round-trip", function()
        local ps = lurek.particles.newSystem()
        lurek.particles.setLinearAcceleration(ps, -10, -50, 10, 50)
        local xmin, ymin, xmax, ymax = lurek.particles.getLinearAcceleration(ps)
        expect_true(math.abs(xmin - (-10)) < 0.001, "accel xmin")
        expect_true(math.abs(ymin - (-50)) < 0.001, "accel ymin")
        expect_true(math.abs(xmax - 10) < 0.001, "accel xmax")
        expect_true(math.abs(ymax - 50) < 0.001, "accel ymax")
    end)

    it("setRadialAcceleration / getRadialAcceleration round-trip", function()
        local ps = lurek.particles.newSystem()
        lurek.particles.setRadialAcceleration(ps, -5.0, 5.0)
        local mn, mx = lurek.particles.getRadialAcceleration(ps)
        expect_true(math.abs(mn - (-5.0)) < 0.001, "radial accel min")
        expect_true(math.abs(mx - 5.0) < 0.001, "radial accel max")
    end)

    it("setTangentialAcceleration / getTangentialAcceleration round-trip", function()
        local ps = lurek.particles.newSystem()
        lurek.particles.setTangentialAcceleration(ps, 1.0, 3.0)
        local mn, mx = lurek.particles.getTangentialAcceleration(ps)
        expect_true(math.abs(mn - 1.0) < 0.001, "tangential accel min")
        expect_true(math.abs(mx - 3.0) < 0.001, "tangential accel max")
    end)

    it("setLinearDamping / getLinearDamping round-trip", function()
        local ps = lurek.particles.newSystem()
        lurek.particles.setLinearDamping(ps, 0.1, 0.9)
        local mn, mx = lurek.particles.getLinearDamping(ps)
        expect_true(math.abs(mn - 0.1) < 0.001, "damping min")
        expect_true(math.abs(mx - 0.9) < 0.001, "damping max")
    end)
end)

describe("lurek.particles size settings", function()
    it("setSizes with multiple keyframes / getSizes round-trip", function()
        local ps = lurek.particles.newSystem()
        lurek.particles.setSizes(ps, 8.0, 4.0, 2.0, 1.0)
        local sizes = lurek.particles.getSizes(ps)
        expect_true(math.abs(sizes[1] - 8.0) < 0.001, "size[1]")
        expect_true(math.abs(sizes[2] - 4.0) < 0.001, "size[2]")
        expect_true(math.abs(sizes[3] - 2.0) < 0.001, "size[3]")
        expect_true(math.abs(sizes[4] - 1.0) < 0.001, "size[4]")
    end)

    it("setSizeVariation / getSizeVariation round-trip", function()
        local ps = lurek.particles.newSystem()
        lurek.particles.setSizeVariation(ps, 0.5)
        local v = lurek.particles.getSizeVariation(ps)
        expect_true(math.abs(v - 0.5) < 0.001, "size variation")
    end)
end)

describe("lurek.particles rotation settings", function()
    it("setRotation / getRotation round-trip", function()
        local ps = lurek.particles.newSystem()
        lurek.particles.setRotation(ps, 0.1, 0.9)
        local mn, mx = lurek.particles.getRotation(ps)
        expect_true(math.abs(mn - 0.1) < 0.001, "rotation min")
        expect_true(math.abs(mx - 0.9) < 0.001, "rotation max")
    end)

    it("setSpin / getSpin round-trip", function()
        local ps = lurek.particles.newSystem()
        lurek.particles.setSpin(ps, 0.2, 1.5)
        local mn, mx = lurek.particles.getSpin(ps)
        expect_true(math.abs(mn - 0.2) < 0.001, "spin min")
        expect_true(math.abs(mx - 1.5) < 0.001, "spin max")
    end)

    it("setSpinVariation / getSpinVariation round-trip", function()
        local ps = lurek.particles.newSystem()
        lurek.particles.setSpinVariation(ps, 0.75)
        local v = lurek.particles.getSpinVariation(ps)
        expect_true(math.abs(v - 0.75) < 0.001, "spin variation")
    end)

    it("setRelativeRotation / hasRelativeRotation round-trip", function()
        local ps = lurek.particles.newSystem()
        lurek.particles.setRelativeRotation(ps, true)
        expect_true(lurek.particles.hasRelativeRotation(ps), "relative rotation enabled")
        lurek.particles.setRelativeRotation(ps, false)
        expect_true(not lurek.particles.hasRelativeRotation(ps), "relative rotation disabled")
    end)
end)

describe("lurek.particles color settings", function()
    it("setColors / getColors round-trip", function()
        local ps = lurek.particles.newSystem()
        lurek.particles.setColors(ps, {1, 0, 0, 1}, {0, 0, 1, 0})
        -- getColors returns a sequence of color tables: {{r,g,b,a}, {r,g,b,a}, ...}
        local colors = lurek.particles.getColors(ps)
        local r1, g1, b1, a1 = colors[1][1], colors[1][2], colors[1][3], colors[1][4]
        local r2, g2, b2, a2 = colors[2][1], colors[2][2], colors[2][3], colors[2][4]
        expect_true(math.abs(r1 - 1.0) < 0.001, "color[1].r")
        expect_true(math.abs(g1 - 0.0) < 0.001, "color[1].g")
        expect_true(math.abs(b1 - 0.0) < 0.001, "color[1].b")
        expect_true(math.abs(a1 - 1.0) < 0.001, "color[1].a")
        expect_true(math.abs(r2 - 0.0) < 0.001, "color[2].r")
        expect_true(math.abs(b2 - 1.0) < 0.001, "color[2].b")
        expect_true(math.abs(a2 - 0.0) < 0.001, "color[2].a")
    end)
end)

describe("lurek.particles rendering settings", function()
    it("setOffset / getOffset round-trip", function()
        local ps = lurek.particles.newSystem()
        lurek.particles.setOffset(ps, 4.0, 8.0)
        local ox, oy = lurek.particles.getOffset(ps)
        expect_true(math.abs(ox - 4.0) < 0.001, "offset x")
        expect_true(math.abs(oy - 8.0) < 0.001, "offset y")
    end)

    it("setInsertMode / getInsertMode: top", function()
        local ps = lurek.particles.newSystem()
        lurek.particles.setInsertMode(ps, "top")
        expect_equal("top", lurek.particles.getInsertMode(ps), "insert mode")
    end)

    it("setInsertMode / getInsertMode: bottom", function()
        local ps = lurek.particles.newSystem()
        lurek.particles.setInsertMode(ps, "bottom")
        expect_equal("bottom", lurek.particles.getInsertMode(ps), "insert mode bottom")
    end)

    it("setInsertMode / getInsertMode: random", function()
        local ps = lurek.particles.newSystem()
        lurek.particles.setInsertMode(ps, "random")
        expect_equal("random", lurek.particles.getInsertMode(ps), "insert mode random")
    end)

    it("setBufferSize / getBufferSize round-trip", function()
        local ps = lurek.particles.newSystem({ maxParticles = 50 })
        lurek.particles.setBufferSize(ps, 200)
        expect_equal(200, lurek.particles.getBufferSize(ps), "buffer size")
    end)
end)

describe("lurek.particles emission area", function()
    it("setEmissionArea / getEmissionArea: none", function()
        local ps = lurek.particles.newSystem()
        lurek.particles.setEmissionArea(ps, "none", 0, 0)
        local dist, w, h = lurek.particles.getEmissionArea(ps)
        expect_equal("none", dist, "area distribution none")
    end)

    it("setEmissionArea: uniform rectangle", function()
        local ps = lurek.particles.newSystem()
        lurek.particles.setEmissionArea(ps, "uniform", 100, 50)
        local dist, w, h = lurek.particles.getEmissionArea(ps)
        expect_equal("uniform", dist, "area distribution uniform")
        expect_true(math.abs(w - 100) < 0.001, "area width")
        expect_true(math.abs(h - 50) < 0.001, "area height")
    end)

    it("setEmissionArea: ellipse", function()
        local ps = lurek.particles.newSystem()
        lurek.particles.setEmissionArea(ps, "ellipse", 60, 30)
        local dist = lurek.particles.getEmissionArea(ps)
        expect_equal("ellipse", dist, "area distribution ellipse")
    end)
end)

describe("lurek.particles object-method syntax", function()
    it("ps:update(dt) is callable", function()
        local ps = lurek.particles.newSystem()
        ps:update(0.016)
        expect_true(true, "object-method update works")
    end)

    it("ps:start() / ps:stop() / ps:pause() are callable", function()
        local ps = lurek.particles.newSystem()
        ps:stop()
        expect_true(ps:isStopped(), "ps:isStopped after ps:stop")
        ps:start()
        expect_true(ps:isActive(), "ps:isActive after ps:start")
        ps:pause()
        expect_true(ps:isPaused(), "ps:isPaused after ps:pause")
    end)

    it("ps:emit(n) / ps:getCount() work", function()
        local ps = lurek.particles.newSystem({ maxParticles = 20 })
        ps:stop()
        ps:emit(5)
        expect_true(ps:getCount() > 0, "count after ps:emit")
    end)

    it("ps:type() returns 'ParticleSystem'", function()
        local ps = lurek.particles.newSystem()
        expect_equal("ParticleSystem", ps:type(), "type")
    end)

    it("ps:typeOf('Drawable') returns true", function()
        local ps = lurek.particles.newSystem()
        expect_true(ps:typeOf("Drawable"), "typeOf Drawable")
    end)

    it("ps:typeOf('Object') returns true", function()
        local ps = lurek.particles.newSystem()
        expect_true(ps:typeOf("Object"), "typeOf Object")
    end)

    it("ps:typeOf('NonExistent') returns false", function()
        local ps = lurek.particles.newSystem()
        expect_true(not ps:typeOf("NonExistent"), "typeOf NonExistent false")
    end)
end)

describe("lurek.particles.clone", function()
    it("clone returns a different userdata handle", function()
        local ps = lurek.particles.newSystem({ emissionRate = 77.0 })
        local ps2 = lurek.particles.clone(ps)
        expect_type("userdata", ps2)
        -- Clones share config but are independent objects
        local r1 = lurek.particles.getEmissionRate(ps)
        local r2 = lurek.particles.getEmissionRate(ps2)
        expect_true(math.abs(r1 - r2) < 0.001, "clone has same emission rate")
    end)
end)

describe("lurek.particles.release", function()
    it("release returns true for valid handle", function()
        local ps = lurek.particles.newSystem()
        local ok = lurek.particles.release(ps)
        expect_equal(true, ok, "release returns true")
    end)

    it("accessing released handle raises an error", function()
        local ps = lurek.particles.newSystem()
        lurek.particles.release(ps)
        local ok, err = pcall(function() lurek.particles.getCount(ps) end)
        expect_true(not ok, "accessing released handle should error")
    end)
end)

-- Phase 8: Particle shape tests

describe("particle shapes", function()
    it("setShape and getShape round-trip for all shapes", function()
        local ps = lurek.particles.newSystem({ maxParticles = 10 })
        local shapes = {"square", "circle", "triangle", "spark", "diamond"}
        for _, s in ipairs(shapes) do
            ps:setShape(s)
            expect_equal(ps:getShape(), s)
        end
        lurek.particles.release(ps)
    end)

    it("invalid shape name raises error", function()
        local ps = lurek.particles.newSystem({ maxParticles = 10 })
        expect_error(function()
            ps:setShape("hexagon")
        end)
        lurek.particles.release(ps)
    end)

    it("default shape is square", function()
        local ps = lurek.particles.newSystem({ maxParticles = 10 })
        expect_equal(ps:getShape(), "square")
        lurek.particles.release(ps)
    end)

    it("setShape via object method matches getShape", function()
        local ps = lurek.particles.newSystem({ maxParticles = 10 })
        ps:setShape("diamond")
        expect_equal(ps:getShape(), "diamond")
        lurek.particles.release(ps)
    end)
end)

describe("particle gravity", function()
    it("gravity_y keeps particle alive after update", function()
        local ps = lurek.particles.newSystem({
            maxParticles = 5,
            emissionRate = 0,
            gravityY = 200.0,
            speedMin = 0,
            speedMax = 0,
            lifetimeMin = 10,
            lifetimeMax = 10,
        })
        lurek.particles.emit(ps, 1)
        lurek.particles.update(ps, 0.1)
        -- Particle should still be alive (lifetime=10s, only 0.1s elapsed)
        expect_equal(lurek.particles.getCount(ps), 1)
        lurek.particles.release(ps)
    end)

    it("gravityY config key is accepted", function()
        local ps = lurek.particles.newSystem({ gravityY = 100 })
        local gx, gy = lurek.particles.getGravity(ps)
        expect_true(math.abs(gy - 100) < 0.001, "gravityY config key sets gravity_y")
        lurek.particles.release(ps)
    end)
end)

test_summary()
