-- Luna2D Input API Tests

describe("luna.keyboard module exists", function()
    it("luna.keyboard is a table", function()
        expect_type("table", luna.keyboard)
    end)
end)

describe("luna.keyboard functions", function()
    it("isDown is a function", function()
        expect_type("function", luna.keyboard.isDown)
    end)

    it("isDown returns a boolean", function()
        local val = luna.keyboard.isDown("space")
        expect_type("boolean", val)
    end)

    it("isDown returns false for unpressed key", function()
        expect_false(luna.keyboard.isDown("space"))
        expect_false(luna.keyboard.isDown("a"))
        expect_false(luna.keyboard.isDown("escape"))
    end)

    it("isDown accepts multiple keys and returns false when none are pressed", function()
        expect_false(luna.keyboard.isDown("space", "a", "escape"))
    end)

    it("isScancodeDown is a function", function()
        expect_type("function", luna.keyboard.isScancodeDown)
    end)

    it("isScancodeDown returns false for an unpressed scancode", function()
        expect_false(luna.keyboard.isScancodeDown("space"))
    end)

    it("setKeyRepeat and hasKeyRepeat round-trip", function()
        expect_type("function", luna.keyboard.setKeyRepeat)
        expect_type("function", luna.keyboard.hasKeyRepeat)
        expect_false(luna.keyboard.hasKeyRepeat())
        luna.keyboard.setKeyRepeat(true)
        expect_true(luna.keyboard.hasKeyRepeat())
        luna.keyboard.setKeyRepeat(false)
        expect_false(luna.keyboard.hasKeyRepeat())
    end)

    it("setTextInput and hasTextInput round-trip", function()
        expect_type("function", luna.keyboard.setTextInput)
        expect_type("function", luna.keyboard.hasTextInput)
        expect_false(luna.keyboard.hasTextInput())
        luna.keyboard.setTextInput(true)
        expect_true(luna.keyboard.hasTextInput())
        luna.keyboard.setTextInput(false)
        expect_false(luna.keyboard.hasTextInput())
    end)

    it("phase 03 scancode lookup helpers exist", function()
        expect_type("function", luna.keyboard.getScancodeFromKey)
        expect_type("function", luna.keyboard.getKeyFromScancode)
    end)
end)

describe("luna.mouse module exists", function()
    it("luna.mouse is a table", function()
        expect_type("table", luna.mouse)
    end)
end)

describe("luna.mouse functions", function()
    it("getPosition is a function", function()
        expect_type("function", luna.mouse.getPosition)
    end)

    it("getPosition returns two numbers", function()
        local x, y = luna.mouse.getPosition()
        expect_type("number", x)
        expect_type("number", y)
    end)

    it("getX is a function", function()
        expect_type("function", luna.mouse.getX)
    end)

    it("getX returns a number", function()
        expect_type("number", luna.mouse.getX())
    end)

    it("getY is a function", function()
        expect_type("function", luna.mouse.getY)
    end)

    it("getY returns a number", function()
        expect_type("number", luna.mouse.getY())
    end)

    it("isDown is a function", function()
        expect_type("function", luna.mouse.isDown)
    end)

    it("isDown returns a boolean", function()
        local val = luna.mouse.isDown(1)
        expect_type("boolean", val)
    end)

    it("isDown returns false for unpressed button", function()
        expect_false(luna.mouse.isDown(1))
        expect_false(luna.mouse.isDown(2))
        expect_false(luna.mouse.isDown(3))
    end)
end)

describe("luna.gamepad module exists", function()
    it("luna.gamepad is a table", function()
        expect_type("table", luna.gamepad)
    end)
end)

describe("luna.gamepad functions", function()
    it("core query functions exist", function()
        expect_type("function", luna.gamepad.getCount)
        expect_type("function", luna.gamepad.getJoystickCount)
        expect_type("function", luna.gamepad.getJoysticks)
        expect_type("function", luna.gamepad.isConnected)
        expect_type("function", luna.gamepad.getName)
        expect_type("function", luna.gamepad.isGamepad)
        expect_type("function", luna.gamepad.getButtonCount)
        expect_type("function", luna.gamepad.getAxisCount)
        expect_type("function", luna.gamepad.isDown)
        expect_type("function", luna.gamepad.getAxis)
        expect_type("function", luna.gamepad.isVibrationSupported)
    end)

    it("empty inventory returns stable defaults", function()
        expect_equal(0, luna.gamepad.getCount())
        expect_equal(0, luna.gamepad.getJoystickCount())
        local ids = luna.gamepad.getJoysticks()
        expect_type("table", ids)
        expect_equal(0, #ids)
        expect_false(luna.gamepad.isConnected(0))
        expect_false(luna.gamepad.isGamepad(0))
    end)

    it("phase 03 advanced gamepad hooks exist", function()
        expect_type("function", luna.gamepad.getGUID)
        expect_type("function", luna.gamepad.getHat)
        expect_type("function", luna.gamepad.setVibration)
    end)
end)

describe("luna.touch module exists", function()
    it("luna.touch is a table", function()
        expect_type("table", luna.touch)
    end)
end)

describe("luna.touch functions", function()
    it("phase 03 touch query functions exist", function()
        expect_type("function", luna.touch.getTouches)
        expect_type("function", luna.touch.getPosition)
        expect_type("function", luna.touch.getPressure)
        expect_type("function", luna.touch.getTouchCount)
    end)

    it("getTouches returns an empty table by default", function()
        local touches = luna.touch.getTouches()
        expect_type("table", touches)
        expect_equal(0, #touches)
    end)
end)

describe("keyboard.isModifierActive", function()
    it("returns a boolean for valid modifiers", function()
        expect_type("boolean", luna.keyboard.isModifierActive("shift"))
        expect_type("boolean", luna.keyboard.isModifierActive("ctrl"))
        expect_type("boolean", luna.keyboard.isModifierActive("alt"))
        expect_type("boolean", luna.keyboard.isModifierActive("meta"))
        expect_type("boolean", luna.keyboard.isModifierActive("super"))
    end)
    it("returns false for unknown modifier", function()
        expect_equal(false, luna.keyboard.isModifierActive("capslock"))
    end)
    it("no modifiers held at start", function()
        expect_equal(false, luna.keyboard.isModifierActive("shift"))
        expect_equal(false, luna.keyboard.isModifierActive("ctrl"))
    end)
end)

describe("mouse cursor userdata", function()
    it("getSystemCursor returns a userdata", function()
        local c = luna.mouse.getSystemCursor("arrow")
        expect_type("userdata", c)
    end)
    it("isCursorSupported returns a bool", function()
        expect_type("boolean", luna.mouse.isCursorSupported())
        expect_equal(true, luna.mouse.isCursorSupported())
    end)
    it("getSystemCursor hand cursor returns non-nil", function()
        local c = luna.mouse.getSystemCursor("hand")
        expect_type("userdata", c)
    end)
    it("getSystemCursor crosshair cursor returns userdata", function()
        local c = luna.mouse.getSystemCursor("crosshair")
        expect_type("userdata", c)
    end)
    it("setCursor accepts userdata and updates cursor", function()
        local c = luna.mouse.getSystemCursor("hand")
        luna.mouse.setCursor(c)
        expect_equal("hand", luna.mouse.getCursor())
        luna.mouse.setCursor("arrow")
    end)
    it("setCursor still accepts string for backward compat", function()
        luna.mouse.setCursor("crosshair")
        expect_equal("crosshair", luna.mouse.getCursor())
        luna.mouse.setCursor("arrow")
    end)
end)

test_summary()
