-- Tests for Real-Time Audio DSP & Buses API
-- Implementing tests for the new flat handles and parameter sweeping logic per audio DSP design

describe("luna.audio.create_bus", function()
    it("creates a bus without returning an object", function()
        local result = luna.audio.create_bus("sfx")
        expect_equal(nil, result)
    end)
    
    it("errors if empty string is provided", function()
        expect_error(function()
            luna.audio.create_bus("")
        end, "invalid bus name")
    end)
end)

describe("luna.audio.set_bus_volume", function()
    it("sets the volume of an existing bus", function()
        luna.audio.create_bus("music")
        -- Should not error
        luna.audio.set_bus_volume("music", 0.75)
    end)

    it("errors if bus does not exist", function()
        expect_error(function()
            luna.audio.set_bus_volume("nonexistent_bus", 0.5)
        end, "bus not found")
    end)
end)

describe("luna.audio.play with bus", function()
    it("accepts a bus parameter in options", function()
        luna.audio.create_bus("ambient")
        local src = luna.audio.newSource("tests/fixtures/sine_mono_44100.wav", "static")
        local id = luna.audio.play(src, { bus = "ambient" })
        expect_type("number", id)
    end)

    it("defaults to master bus if none provided", function()
        local src = luna.audio.newSource("tests/fixtures/sine_mono_44100.wav", "static")
        local id = luna.audio.play(src, {})
        expect_type("number", id)
    end)

    it("errors if bus does not exist", function()
        local src = luna.audio.newSource("tests/fixtures/sine_mono_44100.wav", "static")
        expect_error(function()
            luna.audio.play(src, { bus = "fake_bus" })
        end, "bus not found")
    end)
end)

describe("luna.audio.add_effect", function()
    it("adds an effect and returns an integer ID", function()
        luna.audio.create_bus("sfx2")
        local effect_id = luna.audio.add_effect("sfx2", "lowpass")
        expect_type("number", effect_id)
    end)

    it("accepts initial parameters", function()
        luna.audio.create_bus("sfx3")
        local effect_id = luna.audio.add_effect("sfx3", "reverb", { room_size = 0.8, mix = 0.4 })
        expect_type("number", effect_id)
    end)

    it("errors on invalid effect type", function()
        luna.audio.create_bus("sfx4")
        expect_error(function()
            luna.audio.add_effect("sfx4", "magic_wand")
        end, "invalid effect")
    end)

    it("errors if bus does not exist for effect", function()
        expect_error(function()
            luna.audio.add_effect("nope_bus", "lowpass")
        end, "bus not found")
    end)
end)

describe("luna.audio.set_effect_param", function()
    it("mutates an effect parameter without errors", function()
        luna.audio.create_bus("music2")
        local efx = luna.audio.add_effect("music2", "lowpass")
        -- set cutoff
        luna.audio.set_effect_param("music2", efx, "cutoff", 500.0)
    end)

    it("errors if effect ID does not exist", function()
        luna.audio.create_bus("music3")
        expect_error(function()
            luna.audio.set_effect_param("music3", 9999, "cutoff", 500.0)
        end, "effect not found")
    end)

    it("errors if parameter name is invalid for effect type", function()
        luna.audio.create_bus("music4")
        local efx = luna.audio.add_effect("music4", "lowpass")
        expect_error(function()
            luna.audio.set_effect_param("music4", efx, "room_size", 0.5)
        end, "invalid parameter")
    end)
end)

describe("luna.audio.remove_effect", function()
    it("removes an existing effect", function()
        luna.audio.create_bus("sfx5")
        local efx = luna.audio.add_effect("sfx5", "bandpass")
        luna.audio.remove_effect("sfx5", efx)
        
        -- Further operations on it should error
        expect_error(function()
            luna.audio.set_effect_param("sfx5", efx, "center", 1000.0)
        end, "effect not found")
    end)

    it("errors if effect not found", function()
        luna.audio.create_bus("sfx6")
        expect_error(function()
            luna.audio.remove_effect("sfx6", 1234)
        end, "effect not found")
    end)
end)

test_summary()
