-- Luna2D Audio API Tests

describe("luna.audio module exists", function()
    it("luna.audio is a table", function()
        expect_type("table", luna.audio)
    end)
end)

describe("luna.audio functions exist", function()
    it("setMasterVolume is a function", function()
        expect_type("function", luna.audio.setMasterVolume)
    end)

    it("getMasterVolume is a function", function()
        expect_type("function", luna.audio.getMasterVolume)
    end)

    it("newSource is a function", function()
        expect_type("function", luna.audio.newSource)
    end)
end)

describe("luna.audio volume", function()
    it("setMasterVolume accepts 0..1 range", function()
        expect_no_error(function()
            luna.audio.setMasterVolume(0.5)
        end)
    end)

    it("getMasterVolume returns a number", function()
        local vol = luna.audio.getMasterVolume()
        expect_type("number", vol)
    end)

    it("setMasterVolume/getMasterVolume roundtrip", function()
        luna.audio.setMasterVolume(0.75)
        expect_near(0.75, luna.audio.getMasterVolume(), 0.01)
        luna.audio.setMasterVolume(1.0) -- reset
    end)

    it("setMasterVolume clamps to valid range", function()
        luna.audio.setMasterVolume(0.0)
        expect_near(0.0, luna.audio.getMasterVolume(), 0.01)
        luna.audio.setMasterVolume(1.0)
        expect_near(1.0, luna.audio.getMasterVolume(), 0.01)
    end)
end)

describe("audio spatial", function()
    it("getDopplerScale returns 1 by default", function()
        expect_near(1.0, luna.audio.getDopplerScale(), 0.0001)
    end)
    it("setDopplerScale round-trips", function()
        luna.audio.setDopplerScale(2.0)
        expect_near(2.0, luna.audio.getDopplerScale(), 0.0001)
        luna.audio.setDopplerScale(1.0)  -- reset
    end)
    it("getDistanceModel returns a string", function()
        expect_type("string", luna.audio.getDistanceModel())
    end)
    it("setDistanceModel round-trips", function()
        luna.audio.setDistanceModel("linear")
        expect_equal("linear", luna.audio.getDistanceModel())
        luna.audio.setDistanceModel("inverse_clamped")  -- reset
    end)
    it("setListener / getListener round-trips", function()
        luna.audio.setListener(100, 50, 0)
        local x, y, z = luna.audio.getListener()
        expect_near(100, x, 0.001)
        expect_near(50, y, 0.001)
        expect_near(0, z, 0.001)
        luna.audio.setListener(0, 0, 0)  -- reset
    end)
    it("setListener2D / getListener2D backward compat", function()
        luna.audio.setListener2D(30, 40)
        local x, y = luna.audio.getListener2D()
        expect_near(30, x, 0.001)
        expect_near(40, y, 0.001)
        luna.audio.setListener2D(0, 0)  -- reset
    end)
end)

describe("audio.newDecoder", function()
  it("is a function", function()
    expect_type("function", luna.audio.newDecoder)
  end)
  it("errors on missing file", function()
    expect_error(function()
      luna.audio.newDecoder("nonexistent_file.wav")
    end, "nonexistent_file")
  end)
end)

test_summary()
