-- Luna2D AI API Tests

-- =========================================================================
-- 1. luna.ai module exists
-- =========================================================================
describe("luna.ai module exists", function()
    it("luna.ai is a table", function()
        expect_type("table", luna.ai)
    end)

    it("has newWorld factory", function()
        expect_type("function", luna.ai.newWorld)
    end)

    it("has newBlackboard factory", function()
        expect_type("function", luna.ai.newBlackboard)
    end)

    it("has newStateMachine factory", function()
        expect_type("function", luna.ai.newStateMachine)
    end)

    it("has newBehaviorTree factory", function()
        expect_type("function", luna.ai.newBehaviorTree)
    end)

    it("has newSteeringManager factory", function()
        expect_type("function", luna.ai.newSteeringManager)
    end)

    it("has no newPathGrid factory (moved to pathfinding)", function()
        expect_type("function", luna.pathfinding.newPathGrid)
    end)

    it("has no newFlowField factory (moved to pathfinding)", function()
        expect_type("function", luna.pathfinding.newPathFlowField)
    end)

    it("has newQLearner factory", function()
        expect_type("function", luna.ai.newQLearner)
    end)

    it("has newUtilityAI factory", function()
        expect_type("function", luna.ai.newUtilityAI)
    end)

    it("has newGOAPPlanner factory", function()
        expect_type("function", luna.ai.newGOAPPlanner)
    end)

    it("has newInfluenceMap factory", function()
        expect_type("function", luna.ai.newInfluenceMap)
    end)

    it("has newSquad factory", function()
        expect_type("function", luna.ai.newSquad)
    end)

    it("has newCommandQueue factory", function()
        expect_type("function", luna.ai.newCommandQueue)
    end)

    it("has BT node factories", function()
        expect_type("function", luna.ai.newSelector)
        expect_type("function", luna.ai.newSequence)
        expect_type("function", luna.ai.newParallel)
        expect_type("function", luna.ai.newInverter)
        expect_type("function", luna.ai.newRepeater)
        expect_type("function", luna.ai.newSucceeder)
        expect_type("function", luna.ai.newAction)
        expect_type("function", luna.ai.newCondition)
    end)
end)

-- =========================================================================
-- 2. AIWorld
-- =========================================================================
describe("luna.ai AIWorld", function()
    it("creates a new world", function()
        local w = luna.ai.newWorld()
        expect_not_nil(w, "world exists")
        expect_equal("AIWorld", w:type(), "type check")
    end)

    it("adds agents by name", function()
        local w = luna.ai.newWorld()
        local a = w:addAgent("hero")
        expect_not_nil(a, "agent returned")
        expect_equal(1, w:getAgentCount(), "agent count")
    end)

    it("gets agent by name", function()
        local w = luna.ai.newWorld()
        w:addAgent("hero")
        local a = w:getAgent("hero")
        expect_not_nil(a, "found agent")
        expect_equal("hero", a:getName())
    end)

    it("returns nil for unknown agent", function()
        local w = luna.ai.newWorld()
        expect_nil(w:getAgent("nonexistent"))
    end)

    it("removes agents", function()
        local w = luna.ai.newWorld()
        local a = w:addAgent("hero")
        w:removeAgent(a)
        expect_equal(0, w:getAgentCount())
    end)

    it("updates positions based on velocity", function()
        local w = luna.ai.newWorld()
        local a = w:addAgent("mover")
        a:setPosition(0, 0)
        a:setVelocity(10, 20)
        w:update(0.5)
        local x, y = a:getPosition()
        expect_near(5.0, x, 0.01, "x after update")
        expect_near(10.0, y, 0.01, "y after update")
    end)

    it("errors on duplicate agent name", function()
        local w = luna.ai.newWorld()
        w:addAgent("hero")
        expect_error(function() w:addAgent("hero") end, "duplicate agent")
    end)

    it("provides global blackboard", function()
        local w = luna.ai.newWorld()
        local bb = w:getGlobalBlackboard()
        expect_not_nil(bb, "global bb exists")
        expect_equal("Blackboard", bb:type())
    end)

    it("supports multiple agents", function()
        local w = luna.ai.newWorld()
        w:addAgent("alpha")
        w:addAgent("beta")
        w:addAgent("gamma")
        expect_equal(3, w:getAgentCount())
    end)

    it("agent count decreases after removal", function()
        local w = luna.ai.newWorld()
        local a1 = w:addAgent("a1")
        w:addAgent("a2")
        expect_equal(2, w:getAgentCount())
        w:removeAgent(a1)
        expect_equal(1, w:getAgentCount())
    end)
end)

-- =========================================================================
-- 3. Agent
-- =========================================================================
describe("luna.ai Agent", function()
    it("type returns Agent", function()
        local w = luna.ai.newWorld()
        local a = w:addAgent("hero")
        expect_equal("Agent", a:type())
    end)

    it("getName returns name", function()
        local w = luna.ai.newWorld()
        local a = w:addAgent("warrior")
        expect_equal("warrior", a:getName())
    end)

    it("setPosition / getPosition roundtrip", function()
        local w = luna.ai.newWorld()
        local a = w:addAgent("a")
        a:setPosition(100, 200)
        local x, y = a:getPosition()
        expect_near(100, x, 0.01)
        expect_near(200, y, 0.01)
    end)

    it("setVelocity / getVelocity roundtrip", function()
        local w = luna.ai.newWorld()
        local a = w:addAgent("a")
        a:setVelocity(5, -3)
        local vx, vy = a:getVelocity()
        expect_near(5, vx, 0.01)
        expect_near(-3, vy, 0.01)
    end)

    it("setMaxSpeed / getMaxSpeed", function()
        local w = luna.ai.newWorld()
        local a = w:addAgent("a")
        a:setMaxSpeed(250)
        expect_near(250, a:getMaxSpeed(), 0.01)
    end)

    it("setMaxForce / getMaxForce", function()
        local w = luna.ai.newWorld()
        local a = w:addAgent("a")
        a:setMaxForce(500)
        expect_near(500, a:getMaxForce(), 0.01)
    end)

    it("setPriority / getPriority", function()
        local w = luna.ai.newWorld()
        local a = w:addAgent("a")
        a:setPriority(7)
        expect_equal(7, a:getPriority())
    end)

    it("setDecisionModel / getDecisionModel for fsm", function()
        local w = luna.ai.newWorld()
        local a = w:addAgent("a")
        a:setDecisionModel("fsm")
        expect_equal("fsm", a:getDecisionModel())
    end)

    it("setDecisionModel / getDecisionModel for bt", function()
        local w = luna.ai.newWorld()
        local a = w:addAgent("a")
        a:setDecisionModel("bt")
        expect_equal("bt", a:getDecisionModel())
    end)

    it("setDecisionModel / getDecisionModel for steering", function()
        local w = luna.ai.newWorld()
        local a = w:addAgent("a")
        a:setDecisionModel("steering")
        expect_equal("steering", a:getDecisionModel())
    end)

    it("addTag / hasTag / removeTag", function()
        local w = luna.ai.newWorld()
        local a = w:addAgent("a")
        expect_false(a:hasTag("enemy"), "no tag initially")
        a:addTag("enemy")
        expect_true(a:hasTag("enemy"), "tag added")
        a:removeTag("enemy")
        expect_false(a:hasTag("enemy"), "tag removed")
    end)

    it("multiple tags", function()
        local w = luna.ai.newWorld()
        local a = w:addAgent("a")
        a:addTag("fast")
        a:addTag("flying")
        expect_true(a:hasTag("fast"))
        expect_true(a:hasTag("flying"))
        expect_false(a:hasTag("slow"))
    end)

    it("getBlackboard returns Blackboard", function()
        local w = luna.ai.newWorld()
        local a = w:addAgent("a")
        local bb = a:getBlackboard()
        expect_not_nil(bb)
        expect_equal("Blackboard", bb:type())
    end)

    it("default position is zero", function()
        local w = luna.ai.newWorld()
        local a = w:addAgent("a")
        local x, y = a:getPosition()
        expect_near(0, x, 0.01)
        expect_near(0, y, 0.01)
    end)
end)

-- =========================================================================
-- 4. Blackboard
-- =========================================================================
describe("luna.ai Blackboard", function()
    it("type returns Blackboard", function()
        local bb = luna.ai.newBlackboard()
        expect_equal("Blackboard", bb:type())
    end)

    it("setNumber / getNumber roundtrip", function()
        local bb = luna.ai.newBlackboard()
        bb:setNumber("health", 42.5)
        expect_near(42.5, bb:getNumber("health"), 0.001)
    end)

    it("getNumber returns default when key missing", function()
        local bb = luna.ai.newBlackboard()
        expect_near(99, bb:getNumber("missing", 99), 0.001)
    end)

    it("getNumber returns 0 without explicit default", function()
        local bb = luna.ai.newBlackboard()
        expect_near(0, bb:getNumber("missing"), 0.001)
    end)

    it("setBool / getBool roundtrip", function()
        local bb = luna.ai.newBlackboard()
        bb:setBool("alive", true)
        expect_true(bb:getBool("alive"))
    end)

    it("getBool returns default when key missing", function()
        local bb = luna.ai.newBlackboard()
        expect_true(bb:getBool("missing", true))
    end)

    it("getBool returns false without explicit default", function()
        local bb = luna.ai.newBlackboard()
        expect_false(bb:getBool("missing"))
    end)

    it("setString / getString roundtrip", function()
        local bb = luna.ai.newBlackboard()
        bb:setString("name", "hero")
        expect_equal("hero", bb:getString("name"))
    end)

    it("getString returns default when key missing", function()
        local bb = luna.ai.newBlackboard()
        expect_equal("none", bb:getString("missing", "none"))
    end)

    it("getString returns empty without explicit default", function()
        local bb = luna.ai.newBlackboard()
        expect_equal("", bb:getString("missing"))
    end)

    it("has returns true when key exists", function()
        local bb = luna.ai.newBlackboard()
        bb:setNumber("hp", 10)
        expect_true(bb:has("hp"))
    end)

    it("has returns false when key absent", function()
        local bb = luna.ai.newBlackboard()
        expect_false(bb:has("missing"))
    end)

    it("remove deletes a key", function()
        local bb = luna.ai.newBlackboard()
        bb:setNumber("hp", 10)
        bb:remove("hp")
        expect_false(bb:has("hp"))
    end)

    it("clear removes all keys", function()
        local bb = luna.ai.newBlackboard()
        bb:setNumber("a", 1)
        bb:setBool("b", true)
        bb:setString("c", "x")
        bb:clear()
        expect_equal(0, bb:getSize())
    end)

    it("getSize returns count", function()
        local bb = luna.ai.newBlackboard()
        expect_equal(0, bb:getSize())
        bb:setNumber("a", 1)
        expect_equal(1, bb:getSize())
        bb:setBool("b", true)
        expect_equal(2, bb:getSize())
    end)

    it("getKeys returns all key names", function()
        local bb = luna.ai.newBlackboard()
        bb:setNumber("hp", 10)
        bb:setString("name", "x")
        local keys = bb:getKeys()
        expect_type("table", keys)
        expect_equal(2, #keys)
    end)
end)

-- =========================================================================
-- 5. StateMachine
-- =========================================================================
describe("luna.ai StateMachine", function()
    it("type returns StateMachine", function()
        local fsm = luna.ai.newStateMachine()
        expect_equal("StateMachine", fsm:type())
    end)

    it("addState does not error", function()
        local fsm = luna.ai.newStateMachine()
        expect_no_error(function()
            fsm:addState("idle", { onEnter = function() end })
        end)
    end)

    it("addState with all callbacks", function()
        local fsm = luna.ai.newStateMachine()
        expect_no_error(function()
            fsm:addState("patrol", {
                onEnter = function() end,
                onUpdate = function() end,
                onExit = function() end,
            })
        end)
    end)

    it("setInitialState sets current state", function()
        local fsm = luna.ai.newStateMachine()
        fsm:addState("idle", {})
        fsm:setInitialState("idle")
        expect_equal("idle", fsm:getCurrentState())
    end)

    it("getCurrentState returns nil before setting", function()
        local fsm = luna.ai.newStateMachine()
        expect_nil(fsm:getCurrentState())
    end)

    it("forceState changes state", function()
        local fsm = luna.ai.newStateMachine()
        fsm:addState("idle", {})
        fsm:addState("attack", {})
        fsm:setInitialState("idle")
        fsm:forceState("attack")
        expect_equal("attack", fsm:getCurrentState())
    end)

    it("getTimeInState starts at zero after forceState", function()
        local fsm = luna.ai.newStateMachine()
        fsm:addState("idle", {})
        fsm:setInitialState("idle")
        fsm:forceState("idle")
        expect_near(0, fsm:getTimeInState(), 0.01)
    end)

    it("addTransition does not error", function()
        local fsm = luna.ai.newStateMachine()
        fsm:addState("idle", {})
        fsm:addState("walk", {})
        expect_no_error(function()
            fsm:addTransition("idle", "walk", nil, 0)
        end)
    end)

    it("addTransition with guard function", function()
        local fsm = luna.ai.newStateMachine()
        fsm:addState("idle", {})
        fsm:addState("run", {})
        expect_no_error(function()
            fsm:addTransition("idle", "run", function() return true end, 1)
        end)
    end)
end)

-- =========================================================================
-- 6. BehaviorTree
-- =========================================================================
describe("luna.ai BehaviorTree", function()
    it("type returns BehaviorTree", function()
        local bt = luna.ai.newBehaviorTree()
        expect_equal("BehaviorTree", bt:type())
    end)

    it("getLastStatus returns success initially", function()
        local bt = luna.ai.newBehaviorTree()
        expect_equal("success", bt:getLastStatus())
    end)

    it("setRoot accepts a BTNode", function()
        local bt = luna.ai.newBehaviorTree()
        local seq = luna.ai.newSequence()
        expect_no_error(function()
            bt:setRoot(seq)
        end)
    end)
end)

-- =========================================================================
-- 7. BTNode
-- =========================================================================
describe("luna.ai BTNode", function()
    it("newSelector returns BTNode type", function()
        local n = luna.ai.newSelector()
        expect_equal("BTNode", n:type())
    end)

    it("newSequence returns BTNode type", function()
        local n = luna.ai.newSequence()
        expect_equal("BTNode", n:type())
    end)

    it("newParallel returns BTNode type", function()
        local n = luna.ai.newParallel()
        expect_equal("BTNode", n:type())
    end)

    it("newInverter returns BTNode type", function()
        local n = luna.ai.newInverter()
        expect_equal("BTNode", n:type())
    end)

    it("newRepeater returns BTNode type", function()
        local n = luna.ai.newRepeater()
        expect_equal("BTNode", n:type())
    end)

    it("newSucceeder returns BTNode type", function()
        local n = luna.ai.newSucceeder()
        expect_equal("BTNode", n:type())
    end)

    it("newAction returns BTNode type", function()
        local n = luna.ai.newAction(function() return "success" end)
        expect_equal("BTNode", n:type())
    end)

    it("newCondition returns BTNode type", function()
        local n = luna.ai.newCondition(function() return true end)
        expect_equal("BTNode", n:type())
    end)

    it("getNodeType returns selector", function()
        expect_equal("selector", luna.ai.newSelector():getNodeType())
    end)

    it("getNodeType returns sequence", function()
        expect_equal("sequence", luna.ai.newSequence():getNodeType())
    end)

    it("getNodeType returns parallel", function()
        expect_equal("parallel", luna.ai.newParallel():getNodeType())
    end)

    it("getNodeType returns inverter", function()
        expect_equal("inverter", luna.ai.newInverter():getNodeType())
    end)

    it("getNodeType returns repeater", function()
        expect_equal("repeater", luna.ai.newRepeater():getNodeType())
    end)

    it("getNodeType returns succeeder", function()
        expect_equal("succeeder", luna.ai.newSucceeder():getNodeType())
    end)

    it("getNodeType returns action", function()
        expect_equal("action", luna.ai.newAction(function() end):getNodeType())
    end)

    it("getNodeType returns condition", function()
        expect_equal("condition", luna.ai.newCondition(function() end):getNodeType())
    end)

    it("addChild on Selector increases child count", function()
        local sel = luna.ai.newSelector()
        expect_equal(0, sel:getChildCount())
        local act = luna.ai.newAction(function() end)
        sel:addChild(act)
        expect_equal(1, sel:getChildCount())
    end)

    it("addChild on Sequence increases child count", function()
        local seq = luna.ai.newSequence()
        local a1 = luna.ai.newAction(function() end)
        local a2 = luna.ai.newAction(function() end)
        seq:addChild(a1)
        seq:addChild(a2)
        expect_equal(2, seq:getChildCount())
    end)

    it("addChild on Parallel increases child count", function()
        local par = luna.ai.newParallel()
        par:addChild(luna.ai.newAction(function() end))
        expect_equal(1, par:getChildCount())
    end)

    it("addChild on Action errors", function()
        local act = luna.ai.newAction(function() end)
        local child = luna.ai.newAction(function() end)
        expect_error(function()
            act:addChild(child)
        end, "addChild on Action should error")
    end)

    it("addChild on Condition errors", function()
        local cond = luna.ai.newCondition(function() return true end)
        local child = luna.ai.newAction(function() end)
        expect_error(function()
            cond:addChild(child)
        end, "addChild on Condition should error")
    end)

    it("setChild on Inverter", function()
        local inv = luna.ai.newInverter()
        local act = luna.ai.newAction(function() end)
        expect_no_error(function()
            inv:setChild(act)
        end)
    end)

    it("setChild on Repeater", function()
        local rep = luna.ai.newRepeater(3)
        local act = luna.ai.newAction(function() end)
        expect_no_error(function()
            rep:setChild(act)
        end)
    end)

    it("setChild on Succeeder", function()
        local suc = luna.ai.newSucceeder()
        local act = luna.ai.newAction(function() end)
        expect_no_error(function()
            suc:setChild(act)
        end)
    end)

    it("setCount / getCount on Repeater", function()
        local rep = luna.ai.newRepeater(5)
        expect_equal(5, rep:getCount())
        rep:setCount(10)
        expect_equal(10, rep:getCount())
    end)

    it("getCount on non-Repeater returns 0", function()
        local sel = luna.ai.newSelector()
        expect_equal(0, sel:getCount())
    end)

    it("setSuccessPolicy on Parallel does not error", function()
        local par = luna.ai.newParallel()
        expect_no_error(function()
            par:setSuccessPolicy("require_all")
        end)
    end)

    it("setFailurePolicy on Parallel does not error", function()
        local par = luna.ai.newParallel()
        expect_no_error(function()
            par:setFailurePolicy("require_all")
        end)
    end)

    it("getChildCount returns 0 for leaf nodes", function()
        expect_equal(0, luna.ai.newAction(function() end):getChildCount())
        expect_equal(0, luna.ai.newCondition(function() end):getChildCount())
    end)
end)

-- =========================================================================
-- 8. SteeringManager
-- =========================================================================
describe("luna.ai SteeringManager", function()
    it("type returns SteeringManager", function()
        local sm = luna.ai.newSteeringManager()
        expect_equal("SteeringManager", sm:type())
    end)

    it("addSeek increases behavior count", function()
        local sm = luna.ai.newSteeringManager()
        expect_equal(0, sm:getBehaviorCount())
        sm:addSeek(100, 200)
        expect_equal(1, sm:getBehaviorCount())
    end)

    it("addFlee increases behavior count", function()
        local sm = luna.ai.newSteeringManager()
        sm:addFlee(0, 0)
        expect_equal(1, sm:getBehaviorCount())
    end)

    it("addArrive increases behavior count", function()
        local sm = luna.ai.newSteeringManager()
        sm:addArrive(50, 50)
        expect_equal(1, sm:getBehaviorCount())
    end)

    it("addWander increases behavior count", function()
        local sm = luna.ai.newSteeringManager()
        sm:addWander()
        expect_equal(1, sm:getBehaviorCount())
    end)

    it("addPursue increases behavior count", function()
        local sm = luna.ai.newSteeringManager()
        sm:addPursue("target")
        expect_equal(1, sm:getBehaviorCount())
    end)

    it("addEvade increases behavior count", function()
        local sm = luna.ai.newSteeringManager()
        sm:addEvade("threat")
        expect_equal(1, sm:getBehaviorCount())
    end)

    it("addFlock increases behavior count", function()
        local sm = luna.ai.newSteeringManager()
        sm:addFlock()
        expect_equal(1, sm:getBehaviorCount())
    end)

    it("multiple behaviors accumulate", function()
        local sm = luna.ai.newSteeringManager()
        sm:addSeek(100, 100)
        sm:addFlee(0, 0)
        sm:addWander()
        expect_equal(3, sm:getBehaviorCount())
    end)

    it("setCombineMode / getCombineMode", function()
        local sm = luna.ai.newSteeringManager()
        sm:setCombineMode("priority")
        expect_equal("priority", sm:getCombineMode())
        sm:setCombineMode("weighted")
        expect_equal("weighted", sm:getCombineMode())
    end)

    it("calculate returns two numbers", function()
        local sm = luna.ai.newSteeringManager()
        sm:addSeek(100, 100)
        local fx, fy = sm:calculate(0, 0, 0, 0, 100, 200, 1/60)
        expect_type("number", fx)
        expect_type("number", fy)
    end)

    it("getLastSteering returns two numbers", function()
        local sm = luna.ai.newSteeringManager()
        sm:addSeek(100, 100)
        sm:calculate(0, 0, 0, 0, 100, 200, 1/60)
        local fx, fy = sm:getLastSteering()
        expect_type("number", fx)
        expect_type("number", fy)
    end)

    it("addSeek with custom weight", function()
        local sm = luna.ai.newSteeringManager()
        expect_no_error(function()
            sm:addSeek(100, 100, 2.0)
        end)
        expect_equal(1, sm:getBehaviorCount())
    end)
end)

-- =========================================================================
-- 9. PathGrid
-- =========================================================================
describe("luna.ai PathGrid", function()
    it("type returns PathGrid", function()
        local g = luna.pathfinding.newPathGrid(10, 10, 32)
        expect_equal("PathGrid", g:type())
    end)

    it("getWidth / getHeight / getCellSize", function()
        local g = luna.pathfinding.newPathGrid(8, 6, 16)
        expect_equal(8, g:getWidth())
        expect_equal(6, g:getHeight())
        expect_near(16, g:getCellSize(), 0.01)
    end)

    it("all cells walkable by default", function()
        local g = luna.pathfinding.newPathGrid(5, 5, 10)
        expect_true(g:isWalkable(1, 1))
        expect_true(g:isWalkable(5, 5))
    end)

    it("setWalkable / isWalkable (1-based)", function()
        local g = luna.pathfinding.newPathGrid(5, 5, 10)
        g:setWalkable(3, 3, false)
        expect_false(g:isWalkable(3, 3))
        g:setWalkable(3, 3, true)
        expect_true(g:isWalkable(3, 3))
    end)

    it("setCost / getCost (1-based)", function()
        local g = luna.pathfinding.newPathGrid(5, 5, 10)
        g:setCost(2, 2, 3.5)
        expect_near(3.5, g:getCost(2, 2), 0.01)
    end)

    it("findPath returns a table for open grid", function()
        local g = luna.pathfinding.newPathGrid(5, 5, 10)
        local path = g:findPath(1, 1, 5, 5)
        expect_not_nil(path, "path should exist")
        expect_type("table", path)
        expect_true(#path > 0, "path should have waypoints")
    end)

    it("findPath entries have x and y fields", function()
        local g = luna.pathfinding.newPathGrid(5, 5, 10)
        local path = g:findPath(1, 1, 3, 3)
        expect_not_nil(path)
        local first = path[1]
        expect_not_nil(first.x, "x field")
        expect_not_nil(first.y, "y field")
    end)

    it("findPath returns nil for blocked path", function()
        local g = luna.pathfinding.newPathGrid(3, 1, 10)
        g:setWalkable(2, 1, false)
        local path = g:findPath(1, 1, 3, 1)
        expect_nil(path, "blocked path should be nil")
    end)

    it("findPathSmoothed returns a table", function()
        local g = luna.pathfinding.newPathGrid(5, 5, 10)
        local path = g:findPathSmoothed(1, 1, 5, 5)
        expect_not_nil(path)
        expect_type("table", path)
    end)

    it("findPath same start and goal", function()
        local g = luna.pathfinding.newPathGrid(5, 5, 10)
        local path = g:findPath(3, 3, 3, 3)
        expect_not_nil(path)
    end)
end)

-- =========================================================================
-- 10. FlowField
-- =========================================================================
describe("luna.ai FlowField", function()
    it("type returns FlowField", function()
        local g = luna.pathfinding.newPathGrid(5, 5, 10)
        local ff = luna.pathfinding.newPathFlowField(g)
        expect_equal("FlowField", ff:type())
    end)

    it("getWidth / getHeight", function()
        local g = luna.pathfinding.newPathGrid(8, 6, 10)
        local ff = luna.pathfinding.newPathFlowField(g)
        expect_equal(8, ff:getWidth())
        expect_equal(6, ff:getHeight())
    end)

    it("hasGoal returns false initially", function()
        local g = luna.pathfinding.newPathGrid(5, 5, 10)
        local ff = luna.pathfinding.newPathFlowField(g)
        expect_false(ff:hasGoal())
    end)

    it("setGoal / hasGoal / getGoal (1-based)", function()
        local g = luna.pathfinding.newPathGrid(5, 5, 10)
        local ff = luna.pathfinding.newPathFlowField(g)
        ff:setGoal(3, 4)
        expect_true(ff:hasGoal())
        local gx, gy = ff:getGoal()
        expect_equal(3, gx)
        expect_equal(4, gy)
    end)

    it("getDirection returns two numbers", function()
        local g = luna.pathfinding.newPathGrid(5, 5, 10)
        local ff = luna.pathfinding.newPathFlowField(g)
        ff:setGoal(3, 3)
        local dx, dy = ff:getDirection(1, 1)
        expect_type("number", dx)
        expect_type("number", dy)
    end)

    it("getDistance returns a number", function()
        local g = luna.pathfinding.newPathGrid(5, 5, 10)
        local ff = luna.pathfinding.newPathFlowField(g)
        ff:setGoal(3, 3)
        local d = ff:getDistance(1, 1)
        expect_type("number", d)
    end)

    it("getGoal returns nil before setGoal", function()
        local g = luna.pathfinding.newPathGrid(5, 5, 10)
        local ff = luna.pathfinding.newPathFlowField(g)
        local gx, gy = ff:getGoal()
        expect_nil(gx)
        expect_nil(gy)
    end)

    it("distance at goal is zero", function()
        local g = luna.pathfinding.newPathGrid(5, 5, 10)
        local ff = luna.pathfinding.newPathFlowField(g)
        ff:setGoal(3, 3)
        local d = ff:getDistance(3, 3)
        expect_near(0, d, 0.01)
    end)
end)

-- =========================================================================
-- 11. QLearner
-- =========================================================================
describe("luna.ai QLearner", function()
    it("type returns QLearner", function()
        local q = luna.ai.newQLearner(4, 3)
        expect_equal("QLearner", q:type())
    end)

    it("getStateCount / getActionCount", function()
        local q = luna.ai.newQLearner(4, 3)
        expect_equal(4, q:getStateCount())
        expect_equal(3, q:getActionCount())
    end)

    it("chooseAction returns 1-based action", function()
        local q = luna.ai.newQLearner(2, 3)
        local a = q:chooseAction(1)
        expect_true(a >= 1 and a <= 3, "action in range")
    end)

    it("bestAction returns 1-based action", function()
        local q = luna.ai.newQLearner(2, 3)
        local a = q:bestAction(1)
        expect_true(a >= 1 and a <= 3, "best action in range")
    end)

    it("setQValue / getQValue (1-based)", function()
        local q = luna.ai.newQLearner(3, 2)
        q:setQValue(1, 2, 5.0)
        expect_near(5.0, q:getQValue(1, 2), 0.001)
    end)

    it("learn updates Q values", function()
        local q = luna.ai.newQLearner(3, 2)
        q:setExplorationRate(0)
        q:setQValue(1, 1, 0)
        q:learn(1, 1, 10.0, 2)
        local after = q:getQValue(1, 1)
        expect_true(after > 0, "Q value should increase after positive reward")
    end)

    it("setLearningRate / getLearningRate", function()
        local q = luna.ai.newQLearner(2, 2)
        q:setLearningRate(0.5)
        expect_near(0.5, q:getLearningRate(), 0.001)
    end)

    it("setDiscountFactor / getDiscountFactor", function()
        local q = luna.ai.newQLearner(2, 2)
        q:setDiscountFactor(0.8)
        expect_near(0.8, q:getDiscountFactor(), 0.001)
    end)

    it("setExplorationRate / getExplorationRate", function()
        local q = luna.ai.newQLearner(2, 2)
        q:setExplorationRate(0.1)
        expect_near(0.1, q:getExplorationRate(), 0.001)
    end)

    it("setExplorationDecay / getExplorationDecay", function()
        local q = luna.ai.newQLearner(2, 2)
        q:setExplorationDecay(0.99)
        expect_near(0.99, q:getExplorationDecay(), 0.001)
    end)

    it("endEpisode / getEpisodeCount", function()
        local q = luna.ai.newQLearner(2, 2)
        expect_equal(0, q:getEpisodeCount())
        q:endEpisode()
        expect_equal(1, q:getEpisodeCount())
        q:endEpisode()
        expect_equal(2, q:getEpisodeCount())
    end)

    it("serialize / deserialize roundtrip", function()
        local q = luna.ai.newQLearner(2, 2)
        q:setQValue(1, 1, 3.14)
        q:setQValue(2, 2, 2.71)
        local json = q:serialize()
        expect_type("string", json)

        local q2 = luna.ai.newQLearner(2, 2)
        q2:deserialize(json)
        expect_near(3.14, q2:getQValue(1, 1), 0.001)
        expect_near(2.71, q2:getQValue(2, 2), 0.001)
    end)

    it("bestAction returns consistent results for same Q table", function()
        local q = luna.ai.newQLearner(2, 3)
        q:setQValue(1, 1, 1.0)
        q:setQValue(1, 2, 5.0)
        q:setQValue(1, 3, 2.0)
        local best = q:bestAction(1)
        expect_equal(2, best, "action 2 has highest Q")
    end)

    it("Q values start at zero", function()
        local q = luna.ai.newQLearner(3, 3)
        expect_near(0, q:getQValue(1, 1), 0.001)
        expect_near(0, q:getQValue(3, 3), 0.001)
    end)
end)

-- =========================================================================
-- 12. UtilityAI
-- =========================================================================
describe("luna.ai UtilityAI", function()
    it("type returns UtilityAI", function()
        local u = luna.ai.newUtilityAI()
        expect_equal("UtilityAI", u:type())
    end)

    it("addAction increases action count", function()
        local u = luna.ai.newUtilityAI()
        expect_equal(0, u:getActionCount())
        u:addAction("eat", function() return 0.5 end)
        expect_equal(1, u:getActionCount())
    end)

    it("evaluate returns best action name", function()
        local u = luna.ai.newUtilityAI()
        u:addAction("eat", function() return 0.3 end)
        u:addAction("sleep", function() return 0.9 end)
        u:addAction("fight", function() return 0.1 end)
        local best = u:evaluate()
        expect_equal("sleep", best)
    end)

    it("evaluate returns nil with no actions", function()
        local u = luna.ai.newUtilityAI()
        local result = u:evaluate()
        expect_nil(result)
    end)

    it("getLastAction returns last evaluated action", function()
        local u = luna.ai.newUtilityAI()
        u:addAction("patrol", function() return 1.0 end)
        u:evaluate()
        expect_equal("patrol", u:getLastAction())
    end)

    it("getLastAction returns nil before evaluate", function()
        local u = luna.ai.newUtilityAI()
        u:addAction("idle", function() return 1.0 end)
        expect_nil(u:getLastAction())
    end)

    it("addAction with weight parameter", function()
        local u = luna.ai.newUtilityAI()
        expect_no_error(function()
            u:addAction("run", function() return 0.5 end, 2.0)
        end)
        expect_equal(1, u:getActionCount())
    end)
end)

-- =========================================================================
-- 13. GOAPPlanner
-- =========================================================================
describe("luna.ai GOAPPlanner", function()
    it("type returns GOAPPlanner", function()
        local g = luna.ai.newGOAPPlanner()
        expect_equal("GOAPPlanner", g:type())
    end)

    it("addAction increases action count", function()
        local g = luna.ai.newGOAPPlanner()
        expect_equal(0, g:getActionCount())
        g:addAction("gather_wood", 1.0)
        expect_equal(1, g:getActionCount())
    end)

    it("setPrecondition does not error", function()
        local g = luna.ai.newGOAPPlanner()
        g:addAction("chop", 1.0)
        expect_no_error(function()
            g:setPrecondition("chop", "has_axe", true)
        end)
    end)

    it("setEffect does not error", function()
        local g = luna.ai.newGOAPPlanner()
        g:addAction("chop", 1.0)
        expect_no_error(function()
            g:setEffect("chop", "has_wood", true)
        end)
    end)

    it("addGoal increases goal count", function()
        local g = luna.ai.newGOAPPlanner()
        expect_equal(0, g:getGoalCount())
        g:addGoal("build_house", 1.0)
        expect_equal(1, g:getGoalCount())
    end)

    it("setGoalState does not error", function()
        local g = luna.ai.newGOAPPlanner()
        g:addGoal("build_house", 1.0)
        expect_no_error(function()
            g:setGoalState("build_house", "has_house", true)
        end)
    end)

    it("plan returns action sequence", function()
        local g = luna.ai.newGOAPPlanner()
        g:addAction("get_axe", 1.0)
        g:setEffect("get_axe", "has_axe", true)

        g:addAction("chop_tree", 2.0)
        g:setPrecondition("chop_tree", "has_axe", true)
        g:setEffect("chop_tree", "has_wood", true)

        g:addGoal("gather", 1.0)
        g:setGoalState("gather", "has_wood", true)

        local plan = g:plan({ has_axe = false, has_wood = false })
        expect_type("table", plan)
        expect_true(#plan > 0, "plan should have steps")
    end)

    it("plan returns empty table when goal already satisfied", function()
        local g = luna.ai.newGOAPPlanner()
        g:addAction("eat", 1.0)
        g:setEffect("eat", "fed", true)

        g:addGoal("stay_fed", 1.0)
        g:setGoalState("stay_fed", "fed", true)

        local plan = g:plan({ fed = true })
        expect_type("table", plan)
        expect_equal(0, #plan)
    end)

    it("addAction with callback", function()
        local g = luna.ai.newGOAPPlanner()
        expect_no_error(function()
            g:addAction("move", 1.0, function() end)
        end)
    end)
end)

-- =========================================================================
-- 14. InfluenceMap
-- =========================================================================
describe("luna.ai InfluenceMap", function()
    it("type returns InfluenceMap", function()
        local im = luna.ai.newInfluenceMap(10, 10, 32)
        expect_equal("InfluenceMap", im:type())
    end)

    it("getWidth / getHeight / getCellSize", function()
        local im = luna.ai.newInfluenceMap(8, 6, 16)
        expect_equal(8, im:getWidth())
        expect_equal(6, im:getHeight())
        expect_near(16, im:getCellSize(), 0.01)
    end)

    it("addLayer / hasLayer", function()
        local im = luna.ai.newInfluenceMap(5, 5, 10)
        expect_false(im:hasLayer("threat"))
        im:addLayer("threat")
        expect_true(im:hasLayer("threat"))
    end)

    it("setInfluence / getInfluence (1-based)", function()
        local im = luna.ai.newInfluenceMap(5, 5, 10)
        im:addLayer("danger")
        im:setInfluence("danger", 2, 3, 0.75)
        expect_near(0.75, im:getInfluence("danger", 2, 3), 0.01)
    end)

    it("propagate does not error", function()
        local im = luna.ai.newInfluenceMap(5, 5, 10)
        im:addLayer("heat")
        im:setInfluence("heat", 3, 3, 1.0)
        expect_no_error(function()
            im:propagate("heat", 0.5)
        end)
    end)

    it("decay reduces values", function()
        local im = luna.ai.newInfluenceMap(5, 5, 10)
        im:addLayer("scent")
        im:setInfluence("scent", 1, 1, 1.0)
        im:decay("scent", 0.5)
        local val = im:getInfluence("scent", 1, 1)
        expect_near(0.5, val, 0.01)
    end)

    it("clearLayer resets all values", function()
        local im = luna.ai.newInfluenceMap(3, 3, 10)
        im:addLayer("fog")
        im:setInfluence("fog", 1, 1, 1.0)
        im:setInfluence("fog", 2, 2, 0.5)
        im:clearLayer("fog")
        expect_near(0, im:getInfluence("fog", 1, 1), 0.01)
        expect_near(0, im:getInfluence("fog", 2, 2), 0.01)
    end)

    it("clearAll resets all layers", function()
        local im = luna.ai.newInfluenceMap(3, 3, 10)
        im:addLayer("a")
        im:addLayer("b")
        im:setInfluence("a", 1, 1, 1.0)
        im:setInfluence("b", 1, 1, 1.0)
        im:clearAll()
        expect_near(0, im:getInfluence("a", 1, 1), 0.01)
        expect_near(0, im:getInfluence("b", 1, 1), 0.01)
    end)

    it("getMaxPosition returns two numbers", function()
        local im = luna.ai.newInfluenceMap(5, 5, 10)
        im:addLayer("test")
        im:setInfluence("test", 3, 4, 1.0)
        local mx, my = im:getMaxPosition("test")
        expect_type("number", mx)
        expect_type("number", my)
    end)

    it("getMinPosition returns two numbers", function()
        local im = luna.ai.newInfluenceMap(5, 5, 10)
        im:addLayer("test")
        im:setInfluence("test", 2, 2, -1.0)
        local mx, my = im:getMinPosition("test")
        expect_type("number", mx)
        expect_type("number", my)
    end)

    it("queryRect returns a number", function()
        local im = luna.ai.newInfluenceMap(5, 5, 10)
        im:addLayer("zone")
        im:setInfluence("zone", 1, 1, 1.0)
        local sum = im:queryRect("zone", 0, 0, 50, 50)
        expect_type("number", sum)
    end)

    it("blend combines two layers into destination", function()
        local im = luna.ai.newInfluenceMap(3, 3, 10)
        im:addLayer("a")
        im:addLayer("b")
        im:addLayer("result")
        im:setInfluence("a", 1, 1, 1.0)
        im:setInfluence("b", 1, 1, 0.5)
        expect_no_error(function()
            im:blend("a", 1.0, "b", 1.0, "result")
        end)
        -- result should be the weighted blend
        local val = im:getInfluence("result", 1, 1)
        expect_true(val > 0, "blended value should be positive")
    end)
end)

-- =========================================================================
-- 15. Squad
-- =========================================================================
describe("luna.ai Squad", function()
    it("type returns Squad", function()
        local sq = luna.ai.newSquad("alpha")
        expect_equal("Squad", sq:type())
    end)

    it("getName returns squad name", function()
        local sq = luna.ai.newSquad("bravo")
        expect_equal("bravo", sq:getName())
    end)

    it("addMember / getMemberCount", function()
        local sq = luna.ai.newSquad("team")
        expect_equal(0, sq:getMemberCount())
        sq:addMember("soldier1")
        expect_equal(1, sq:getMemberCount())
        sq:addMember("soldier2")
        expect_equal(2, sq:getMemberCount())
    end)

    it("removeMember decreases count", function()
        local sq = luna.ai.newSquad("team")
        sq:addMember("a")
        sq:addMember("b")
        sq:removeMember("a")
        expect_equal(1, sq:getMemberCount())
    end)

    it("getMembers returns table of names", function()
        local sq = luna.ai.newSquad("team")
        sq:addMember("x")
        sq:addMember("y")
        local members = sq:getMembers()
        expect_type("table", members)
        expect_equal(2, #members)
    end)

    it("setLeader / getLeader", function()
        local sq = luna.ai.newSquad("team")
        sq:addMember("leader1")
        sq:setLeader("leader1")
        expect_equal("leader1", sq:getLeader())
    end)

    it("getLeader returns nil by default", function()
        local sq = luna.ai.newSquad("team")
        expect_nil(sq:getLeader())
    end)

    it("setFormation / getFormation / getFormationSpacing", function()
        local sq = luna.ai.newSquad("team")
        sq:setFormation("wedge", 50)
        expect_equal("wedge", sq:getFormation())
        expect_near(50, sq:getFormationSpacing(), 0.01)
    end)

    it("getFormationPosition returns two numbers (1-based index)", function()
        local sq = luna.ai.newSquad("team")
        sq:addMember("a")
        sq:addMember("b")
        local x, y = sq:getFormationPosition(1, 100, 200)
        expect_type("number", x)
        expect_type("number", y)
    end)

    it("getBlackboard returns Blackboard", function()
        local sq = luna.ai.newSquad("team")
        local bb = sq:getBlackboard()
        expect_not_nil(bb)
        expect_equal("Blackboard", bb:type())
    end)
end)

-- =========================================================================
-- 16. CommandQueue
-- =========================================================================
describe("luna.ai CommandQueue", function()
    it("type returns CommandQueue", function()
        local cq = luna.ai.newCommandQueue()
        expect_equal("CommandQueue", cq:type())
    end)

    it("isEmpty returns true initially", function()
        local cq = luna.ai.newCommandQueue()
        expect_true(cq:isEmpty())
    end)

    it("getCount returns 0 initially", function()
        local cq = luna.ai.newCommandQueue()
        expect_equal(0, cq:getCount())
    end)

    it("enqueue increases count", function()
        local cq = luna.ai.newCommandQueue()
        cq:enqueue("move", function() end)
        expect_equal(1, cq:getCount())
        expect_false(cq:isEmpty())
    end)

    it("getCurrentType returns first command type", function()
        local cq = luna.ai.newCommandQueue()
        cq:enqueue("attack", function() end)
        expect_equal("attack", cq:getCurrentType())
    end)

    it("getCurrentType returns nil when empty", function()
        local cq = luna.ai.newCommandQueue()
        expect_nil(cq:getCurrentType())
    end)

    it("cancelCurrent removes head", function()
        local cq = luna.ai.newCommandQueue()
        cq:enqueue("move", function() end)
        cq:enqueue("attack", function() end)
        cq:cancelCurrent()
        expect_equal(1, cq:getCount())
    end)

    it("clear removes all commands", function()
        local cq = luna.ai.newCommandQueue()
        cq:enqueue("a", function() end)
        cq:enqueue("b", function() end)
        cq:enqueue("c", function() end)
        cq:clear()
        expect_equal(0, cq:getCount())
        expect_true(cq:isEmpty())
    end)

    it("pushFront inserts at front", function()
        local cq = luna.ai.newCommandQueue()
        cq:enqueue("second", function() end)
        cq:pushFront("first", function() end)
        expect_equal("first", cq:getCurrentType())
    end)

    it("replace replaces all with single command", function()
        local cq = luna.ai.newCommandQueue()
        cq:enqueue("a", function() end)
        cq:enqueue("b", function() end)
        cq:replace("only", function() end)
        expect_equal(1, cq:getCount())
        expect_equal("only", cq:getCurrentType())
    end)

    it("enqueue with options table", function()
        local cq = luna.ai.newCommandQueue()
        expect_no_error(function()
            cq:enqueue("move", function() end, {
                targetX = 100,
                targetY = 200,
                priority = 5,
                interruptible = false,
            })
        end)
        expect_equal(1, cq:getCount())
    end)
end)

-- =========================================================================
-- 17. Type system
-- =========================================================================
describe("luna.ai type system", function()
    it("AIWorld:type() returns AIWorld", function()
        expect_equal("AIWorld", luna.ai.newWorld():type())
    end)

    it("Blackboard:type() returns Blackboard", function()
        expect_equal("Blackboard", luna.ai.newBlackboard():type())
    end)

    it("StateMachine:type() returns StateMachine", function()
        expect_equal("StateMachine", luna.ai.newStateMachine():type())
    end)

    it("BehaviorTree:type() returns BehaviorTree", function()
        expect_equal("BehaviorTree", luna.ai.newBehaviorTree():type())
    end)

    it("BTNode:type() returns BTNode", function()
        expect_equal("BTNode", luna.ai.newSelector():type())
    end)

    it("SteeringManager:type() returns SteeringManager", function()
        expect_equal("SteeringManager", luna.ai.newSteeringManager():type())
    end)

    it("PathGrid:type() returns PathGrid", function()
        expect_equal("PathGrid", luna.pathfinding.newPathGrid(5, 5, 10):type())
    end)

    it("FlowField:type() returns FlowField", function()
        local g = luna.pathfinding.newPathGrid(5, 5, 10)
        expect_equal("FlowField", luna.pathfinding.newPathFlowField(g):type())
    end)

    it("QLearner:type() returns QLearner", function()
        expect_equal("QLearner", luna.ai.newQLearner(2, 2):type())
    end)

    it("UtilityAI:type() returns UtilityAI", function()
        expect_equal("UtilityAI", luna.ai.newUtilityAI():type())
    end)

    it("GOAPPlanner:type() returns GOAPPlanner", function()
        expect_equal("GOAPPlanner", luna.ai.newGOAPPlanner():type())
    end)

    it("InfluenceMap:type() returns InfluenceMap", function()
        expect_equal("InfluenceMap", luna.ai.newInfluenceMap(5, 5, 10):type())
    end)

    it("Squad:type() returns Squad", function()
        expect_equal("Squad", luna.ai.newSquad("s"):type())
    end)

    it("CommandQueue:type() returns CommandQueue", function()
        expect_equal("CommandQueue", luna.ai.newCommandQueue():type())
    end)

    it("AIWorld:typeOf Object returns true", function()
        expect_true(luna.ai.newWorld():typeOf("Object"))
    end)

    it("Agent:typeOf Object returns true", function()
        local w = luna.ai.newWorld()
        local a = w:addAgent("x")
        expect_true(a:typeOf("Object"))
    end)

    it("Blackboard:typeOf Object returns true", function()
        expect_true(luna.ai.newBlackboard():typeOf("Object"))
    end)

    it("BTNode:typeOf Object returns true", function()
        expect_true(luna.ai.newSelector():typeOf("Object"))
    end)
end)

-- Print summary
test_summary()
