-- lurek.modding API unit tests
-- Headless-safe (no window / GPU / audio required).
-- Tests Mod and ModManager factory functions and metadata API.

describe("lurek.modding module exists", function()
    it("lurek.modding is a table", function()
        expect_type("table", lurek.modding)
    end)
end)

describe("Factory functions", function()
    it("newMod is a function", function()
        expect_type("function", lurek.modding.newMod)
    end)

    it("newModManager is a function", function()
        expect_type("function", lurek.modding.newModManager)
    end)
end)

describe("Mod object creation and metadata", function()
    it("newMod returns a non-nil object", function()
        local m = lurek.modding.newMod({ id = "test_mod" })
        expect_true(m ~= nil, "mod is not nil")
    end)

    it("newMod without id field raises an error", function()
        expect_error(function()
            lurek.modding.newMod({})
        end)
    end)

    it("getId returns the id passed to newMod", function()
        local m = lurek.modding.newMod({ id = "my_mod" })
        expect_equal("my_mod", m:getId())
    end)

    it("getName returns the name when provided", function()
        local m = lurek.modding.newMod({ id = "x", name = "My Mod" })
        expect_equal("My Mod", m:getName())
    end)

    it("getName returns a string even when not provided", function()
        local m = lurek.modding.newMod({ id = "x" })
        expect_type("string", m:getName())
    end)

    it("getVersion returns the version when provided", function()
        local m = lurek.modding.newMod({ id = "x", version = "1.2.3" })
        expect_equal("1.2.3", m:getVersion())
    end)

    it("getAuthor returns the author when provided", function()
        local m = lurek.modding.newMod({ id = "x", author = "Dev" })
        expect_equal("Dev", m:getAuthor())
    end)

    it("getPriority returns the priority when provided", function()
        local m = lurek.modding.newMod({ id = "x", priority = 5 })
        expect_equal(5, m:getPriority())
    end)

    it("isEnabled returns true by default", function()
        local m = lurek.modding.newMod({ id = "x" })
        expect_true(m:isEnabled(), "mods are enabled by default")
    end)

    it("setEnabled can disable a mod", function()
        local m = lurek.modding.newMod({ id = "x" })
        m:setEnabled(false)
        expect_false(m:isEnabled())
    end)

    it("setEnabled can re-enable a mod", function()
        local m = lurek.modding.newMod({ id = "x" })
        m:setEnabled(false)
        m:setEnabled(true)
        expect_true(m:isEnabled())
    end)

    it("isLoaded returns false by default", function()
        local m = lurek.modding.newMod({ id = "x" })
        expect_false(m:isLoaded())
    end)
end)

describe("ModManager object", function()
    it("newModManager returns a non-nil object", function()
        local mm = lurek.modding.newModManager()
        expect_true(mm ~= nil, "mod manager is not nil")
    end)

    it("getLoadOrder returns a table on empty manager", function()
        local mm = lurek.modding.newModManager()
        local order = mm:getLoadOrder()
        expect_type("table", order)
    end)

    it("getLoadOrder is empty on new manager", function()
        local mm = lurek.modding.newModManager()
        local order = mm:getLoadOrder()
        expect_equal(0, #order)
    end)

    it("registerMod adds a mod and getAllMods includes it", function()
        local mm = lurek.modding.newModManager()
        local m = lurek.modding.newMod({ id = "pack_a" })
        mm:registerMod(m)
        local all = mm:getAllMods()
        expect_type("table", all)
        expect_true(#all >= 1, "at least one mod registered")
    end)

    it("hasMod returns false for unknown id", function()
        local mm = lurek.modding.newModManager()
        expect_false(mm:hasMod("nonexistent_mod"))
    end)

    it("hasMod returns true after registerMod", function()
        local mm = lurek.modding.newModManager()
        local m = lurek.modding.newMod({ id = "unique_mod" })
        mm:registerMod(m)
        expect_true(mm:hasMod("unique_mod"), "found registered mod by id")
    end)

    it("unregisterMod removes the mod", function()
        local mm = lurek.modding.newModManager()
        local m = lurek.modding.newMod({ id = "temp_mod" })
        mm:registerMod(m)
        expect_true(mm:hasMod("temp_mod"))
        mm:unregisterMod("temp_mod")
        expect_false(mm:hasMod("temp_mod"))
    end)

    it("getModCount returns 0 on empty manager", function()
        local mm = lurek.modding.newModManager()
        expect_equal(0, mm:getModCount())
    end)

    it("getModCount increments after registerMod", function()
        local mm = lurek.modding.newModManager()
        local m1 = lurek.modding.newMod({ id = "m1" })
        local m2 = lurek.modding.newMod({ id = "m2" })
        mm:registerMod(m1)
        mm:registerMod(m2)
        expect_equal(2, mm:getModCount())
    end)
end)

test_summary()
