-- Lurek2D Graphics API Tests (headless - tests API existence and parameters only)

describe("lurek.gfx module exists", function()
    it("lurek.gfx is a table", function()
        expect_type("table", lurek.gfx)
    end)
end)

describe("lurek.gfx color functions", function()
    it("setColor is a function", function()
        expect_type("function", lurek.gfx.setColor)
    end)

    it("setColor accepts 3 args", function()
        expect_no_error(function()
            lurek.gfx.setColor(1, 0, 0)
        end)
    end)

    it("setColor accepts 4 args", function()
        expect_no_error(function()
            lurek.gfx.setColor(1, 0, 0, 0.5)
        end)
    end)

    it("setBackgroundColor is a function", function()
        expect_type("function", lurek.gfx.setBackgroundColor)
    end)

    it("setBackgroundColor accepts 3 args", function()
        expect_no_error(function()
            lurek.gfx.setBackgroundColor(0.1, 0.1, 0.1)
        end)
    end)
end)

describe("lurek.gfx shape functions", function()
    it("rectangle is a function", function()
        expect_type("function", lurek.gfx.rectangle)
    end)

    it("rectangle fill mode", function()
        expect_no_error(function()
            lurek.gfx.rectangle("fill", 10, 10, 100, 50)
        end)
    end)

    it("rectangle line mode", function()
        expect_no_error(function()
            lurek.gfx.rectangle("line", 10, 10, 100, 50)
        end)
    end)

    it("circle is a function", function()
        expect_type("function", lurek.gfx.circle)
    end)

    it("circle fill mode", function()
        expect_no_error(function()
            lurek.gfx.circle("fill", 50, 50, 25)
        end)
    end)

    it("line is a function", function()
        expect_type("function", lurek.gfx.line)
    end)

    it("line accepts 4 args", function()
        expect_no_error(function()
            lurek.gfx.line(0, 0, 100, 100)
        end)
    end)
end)

describe("lurek.gfx text functions", function()
    it("print is a function", function()
        expect_type("function", lurek.gfx.print)
    end)

    it("print accepts text and position", function()
        expect_no_error(function()
            lurek.gfx.print("Hello", 10, 10)
        end)
    end)
end)

describe("lurek.gfx image functions", function()
    it("newImage is a function", function()
        expect_type("function", lurek.gfx.newImage)
    end)

    it("draw is a function", function()
        expect_type("function", lurek.gfx.draw)
    end)
end)

describe("lurek.gfx advanced shapes", function()
    it("ellipse is a function", function()
        expect_type("function", lurek.gfx.ellipse)
    end)

    it("ellipse fill mode", function()
        expect_no_error(function()
            lurek.gfx.ellipse("fill", 100, 100, 50, 30)
        end)
    end)

    it("polygon is a function", function()
        expect_type("function", lurek.gfx.polygon)
    end)

    it("polygon fill mode with vertices", function()
        expect_no_error(function()
            lurek.gfx.polygon("fill", 0, 0, 100, 0, 50, 100)
        end)
    end)

    it("triangle is a function", function()
        expect_type("function", lurek.gfx.triangle)
    end)

    it("triangle fill mode", function()
        expect_no_error(function()
            lurek.gfx.triangle("fill", 0, 0, 100, 0, 50, 80)
        end)
    end)

    it("setLineWidth is a function", function()
        expect_type("function", lurek.gfx.setLineWidth)
    end)

    it("getLineWidth is a function", function()
        expect_type("function", lurek.gfx.getLineWidth)
    end)

    it("setLineWidth and getLineWidth roundtrip", function()
        lurek.gfx.setLineWidth(3.0)
        expect_near(3.0, lurek.gfx.getLineWidth())
        lurek.gfx.setLineWidth(1.0) -- reset
    end)

    it("getDimensions returns two numbers", function()
        local w, h = lurek.gfx.getDimensions()
        expect_type("number", w)
        expect_type("number", h)
        expect_true(w > 0, "width > 0")
        expect_true(h > 0, "height > 0")
    end)
end)

-- =========================================================================
-- Font metrics
-- =========================================================================
describe("font metrics", function()
    it("getFontLineHeight is a function", function()
        expect_type("function", lurek.gfx.getFontLineHeight)
    end)

    it("setFontLineHeight is a function", function()
        expect_type("function", lurek.gfx.setFontLineHeight)
    end)

    it("getFontAscent is a function", function()
        expect_type("function", lurek.gfx.getFontAscent)
    end)

    it("getFontDescent is a function", function()
        expect_type("function", lurek.gfx.getFontDescent)
    end)
end)

-- ── Nine-Slice Tests ────────────────────────────────────────────────────

describe("lurek.gfx nine-slice", function()
    it("newNineSlice is a function", function()
        expect_type("function", lurek.gfx.newNineSlice)
    end)

    it("drawNineSlice is a function", function()
        expect_type("function", lurek.gfx.drawNineSlice)
    end)

    it("creates a NineSlice from an image", function()
        local img = lurek.gfx.newImage("assets/icon.png")
        local ns = lurek.gfx.newNineSlice(img, 10, 10, 10, 10)
        expect_type("userdata", ns)
    end)

    it("NineSlice:getInsets returns correct values", function()
        local img = lurek.gfx.newImage("assets/icon.png")
        local ns = lurek.gfx.newNineSlice(img, 12, 8, 15, 6)
        local t, r, b, l = ns:getInsets()
        expect_near(12, t)
        expect_near(8, r)
        expect_near(15, b)
        expect_near(6, l)
    end)

    it("NineSlice:getTextureSize returns image dimensions", function()
        local img = lurek.gfx.newImage("assets/icon.png")
        local ns = lurek.gfx.newNineSlice(img, 5, 5, 5, 5)
        local w, h = ns:getTextureSize()
        assert(w > 0, "texture width should be positive")
        assert(h > 0, "texture height should be positive")
    end)

    it("drawNineSlice accepts NineSlice and rect", function()
        local img = lurek.gfx.newImage("assets/icon.png")
        local ns = lurek.gfx.newNineSlice(img, 10, 10, 10, 10)
        expect_no_error(function()
            lurek.gfx.drawNineSlice(ns, 50, 50, 300, 200)
        end)
    end)

    it("NineSlice:draw method works", function()
        local img = lurek.gfx.newImage("assets/icon.png")
        local ns = lurek.gfx.newNineSlice(img, 5, 5, 5, 5)
        expect_no_error(function()
            ns:draw(10, 20, 400, 300)
        end)
    end)

    it("NineSlice:typeOf returns NineSlice", function()
        local img = lurek.gfx.newImage("assets/icon.png")
        local ns = lurek.gfx.newNineSlice(img, 5, 5, 5, 5)
        assert(ns:typeOf("NineSlice"), "should be NineSlice type")
        assert(ns:typeOf("Object"), "should be Object type")
    end)

    it("rejects negative border insets", function()
        local img = lurek.gfx.newImage("assets/icon.png")
        local ok = pcall(function()
            lurek.gfx.newNineSlice(img, -5, 10, 10, 10)
        end)
        assert(not ok, "negative insets should error")
    end)
end)

-- ── Polymorphic draw() dispatch ─────────────────────────────────────────

describe("lurek.gfx.draw polymorphic dispatch", function()
    it("draw() rejects nil with an error", function()
        expect_error(function()
            lurek.gfx.draw(nil, 0, 0)
        end, "nil")
    end)

    it("draw() rejects a non-drawable string with an error", function()
        expect_error(function()
            lurek.gfx.draw("not_a_drawable", 0, 0)
        end, "drawable")
    end)

    it("draw() is a function", function()
        expect_type("function", lurek.gfx.draw)
    end)
end)

describe("lurek.gfx.captureScreenshot", function()
  it("accepts a callback without error", function()
    local ok, err = pcall(lurek.gfx.captureScreenshot, function(img)
      -- callback fires synchronously in stub mode; img is ImageData userdata
    end)
    expect_equal(ok, true)
  end)

  it("callback receives an ImageData userdata", function()
    local received_type = nil
    lurek.gfx.captureScreenshot(function(img)
      received_type = type(img)
    end)
    expect_equal(received_type, "userdata")
  end)
end)

describe("lurek.gfx.saveScreenshot", function()
    it("accepts a save-relative path without error", function()
        local ok = pcall(lurek.gfx.saveScreenshot, "save/test_graphics.png")
        expect_equal(ok, true)
    end)

    it("rejects paths outside save", function()
        expect_error(function()
            lurek.gfx.saveScreenshot("test_graphics.png")
        end, "save/")
    end)
end)

describe("lurek.gfx stencil mode", function()
  it("setStencilMode and getStencilMode round-trip correctly", function()
    lurek.gfx.setStencilMode("replace", "always", 1)
    local action, compare, value = lurek.gfx.getStencilMode()
    expect_equal(action, "replace")
    expect_equal(compare, "always")
    expect_equal(value, 1)
  end)

  it("clearStencil resets to keep/always/0", function()
    lurek.gfx.setStencilMode("invert", "equal", 5)
    lurek.gfx.clearStencil()
    local action, compare, value = lurek.gfx.getStencilMode()
    expect_equal(action, "keep")
    expect_equal(compare, "always")
    expect_equal(value, 0)
  end)

  it("setStencilMode defaults compare to always when omitted", function()
    lurek.gfx.setStencilMode("zero")
    local action, compare, value = lurek.gfx.getStencilMode()
    expect_equal(action, "zero")
    expect_equal(compare, "always")
    expect_equal(value, 0)
  end)

  it("setStencilMode errors on unknown action", function()
    expect_error(function()
      lurek.gfx.setStencilMode("explode")
    end)
  end)

  it("setStencilMode is a function", function()
    expect_type("function", lurek.gfx.setStencilMode)
  end)

  it("getStencilMode is a function", function()
    expect_type("function", lurek.gfx.getStencilMode)
  end)

  it("clearStencil is a function", function()
    expect_type("function", lurek.gfx.clearStencil)
  end)
end)

describe("lurek.gfx depth mode", function()
  it("setDepthMode and getDepthMode round-trip correctly", function()
    lurek.gfx.setDepthMode("less", true)
    local mode, write = lurek.gfx.getDepthMode()
    expect_equal(mode, "less")
    expect_equal(write, true)
  end)

  it("setDepthMode write defaults to false", function()
    lurek.gfx.setDepthMode("always")
    local mode, write = lurek.gfx.getDepthMode()
    expect_equal(mode, "always")
    expect_equal(write, false)
  end)

  it("setDepthMode errors on unknown mode", function()
    expect_error(function()
      lurek.gfx.setDepthMode("turbo")
    end)
  end)

  it("setDepthMode is a function", function()
    expect_type("function", lurek.gfx.setDepthMode)
  end)

  it("getDepthMode is a function", function()
    expect_type("function", lurek.gfx.getDepthMode)
  end)
end)

test_summary()
