-- Lurek2D UI widget API tests.
-- Covers widget construction, focus and input routing, theme access, toast helpers, and headless-safe UI tree management through lurek.ui.

-- Lurek2D GUI API Tests

-- =========================================================================
-- 1. lurek.ui module exists
-- =========================================================================
describe("lurek.ui module exists", function()
    it("lurek.ui is a table", function()
        expect_type("table", lurek.ui)
    end)

    it("has newButton factory", function()
        expect_type("function", lurek.ui.newButton)
    end)

    it("has newLabel factory", function()
        expect_type("function", lurek.ui.newLabel)
    end)

    it("has newTextInput factory", function()
        expect_type("function", lurek.ui.newTextInput)
    end)

    it("has newCheckbox factory", function()
        expect_type("function", lurek.ui.newCheckbox)
    end)

    it("has newSlider factory", function()
        expect_type("function", lurek.ui.newSlider)
    end)

    it("has newProgressBar factory", function()
        expect_type("function", lurek.ui.newProgressBar)
    end)

    it("has newComboBox factory", function()
        expect_type("function", lurek.ui.newComboBox)
    end)

    it("has newList factory", function()
        expect_type("function", lurek.ui.newList)
    end)

    it("has newPanel factory", function()
        expect_type("function", lurek.ui.newPanel)
    end)

    it("has newLayout factory", function()
        expect_type("function", lurek.ui.newLayout)
    end)

    it("has newScrollPanel factory", function()
        expect_type("function", lurek.ui.newScrollPanel)
    end)

    it("has newNinePatch factory", function()
        expect_type("function", lurek.ui.newNinePatch)
    end)

    it("has newTabBar factory", function()
        expect_type("function", lurek.ui.newTabBar)
    end)

    it("has newSeparator factory", function()
        expect_type("function", lurek.ui.newSeparator)
    end)

    it("has newSpacer factory", function()
        expect_type("function", lurek.ui.newSpacer)
    end)

    it("has newToast factory", function()
        expect_type("function", lurek.ui.newToast)
    end)

    it("has newTreeView factory", function()
        expect_type("function", lurek.ui.newTreeView)
    end)

    it("has newTheme factory", function()
        expect_type("function", lurek.ui.newTheme)
    end)

    it("has setTheme function", function()
        expect_type("function", lurek.ui.setTheme)
    end)

    it("has getTheme function", function()
        expect_type("function", lurek.ui.getTheme)
    end)

    it("has setFocus function", function()
        expect_type("function", lurek.ui.setFocus)
    end)

    it("has getFocus function", function()
        expect_type("function", lurek.ui.getFocus)
    end)

    it("has focusNext function", function()
        expect_type("function", lurek.ui.focusNext)
    end)

    it("has focusPrev function", function()
        expect_type("function", lurek.ui.focusPrev)
    end)

    it("has clearFocus function", function()
        expect_type("function", lurek.ui.clearFocus)
    end)

    it("has getRoot function", function()
        expect_type("function", lurek.ui.getRoot)
    end)

    it("has update function", function()
        expect_type("function", lurek.ui.update)
    end)

    it("has draw function", function()
        expect_type("function", lurek.ui.draw)
    end)

    it("has getWidgetCount function", function()
        expect_type("function", lurek.ui.getWidgetCount)
    end)

    it("has input routing functions", function()
        expect_type("function", lurek.ui.mousepressed)
        expect_type("function", lurek.ui.mousereleased)
        expect_type("function", lurek.ui.mousemoved)
        expect_type("function", lurek.ui.keypressed)
        expect_type("function", lurek.ui.textinput)
        expect_type("function", lurek.ui.wheelmoved)
    end)

    it("has toast functions", function()
        expect_type("function", lurek.ui.addToast)
        expect_type("function", lurek.ui.getToastCount)
    end)
end)

-- =========================================================================
-- 2. Button
-- =========================================================================
describe("lurek.ui Button", function()
    it("creates a button with text", function()
        local btn = lurek.ui.newButton("OK")
        expect_type("table", btn)
        expect_equal("OK", btn.getText())
    end)

    it("creates a button with default empty text", function()
        local btn = lurek.ui.newButton()
        expect_equal("", btn.getText())
    end)

    it("can set and get text", function()
        local btn = lurek.ui.newButton("A")
        btn.setText("B")
        expect_equal("B", btn.getText())
    end)
end)

-- =========================================================================
-- 3. Label
-- =========================================================================
describe("lurek.ui Label", function()
    it("creates a label with text", function()
        local lbl = lurek.ui.newLabel("Hello")
        expect_equal("Hello", lbl.getText())
    end)

    it("can update text", function()
        local lbl = lurek.ui.newLabel("old")
        lbl.setText("new")
        expect_equal("new", lbl.getText())
    end)
end)

-- =========================================================================
-- 4. TextInput
-- =========================================================================
describe("lurek.ui TextInput", function()
    it("creates with empty text", function()
        local ti = lurek.ui.newTextInput()
        expect_equal("", ti.getText())
    end)

    it("can set and get text", function()
        local ti = lurek.ui.newTextInput()
        ti.setText("hello")
        expect_equal("hello", ti.getText())
    end)

    it("can set input hint text", function()
        local ti = lurek.ui.newTextInput()
        ti.setPlaceholder("Enter name...")
        expect_equal("Enter name...", ti.getPlaceholder())
    end)

    it("can set max length", function()
        local ti = lurek.ui.newTextInput()
        ti.setMaxLength(10)
        -- No getter exposed; just verify no error
    end)
end)

-- =========================================================================
-- 5. CheckBox
-- =========================================================================
describe("lurek.ui CheckBox", function()
    it("creates unchecked by default", function()
        local cb = lurek.ui.newCheckbox("Option")
        expect_equal(false, cb.isChecked())
    end)

    it("can toggle checked state", function()
        local cb = lurek.ui.newCheckbox("Toggle")
        cb.setChecked(true)
        expect_equal(true, cb.isChecked())
        cb.setChecked(false)
        expect_equal(false, cb.isChecked())
    end)

    it("can set and get text", function()
        local cb = lurek.ui.newCheckbox("old")
        cb.setText("new")
        expect_equal("new", cb.getText())
    end)
end)

-- =========================================================================
-- 6. Slider
-- =========================================================================
describe("lurek.ui Slider", function()
    it("creates with min/max defaults", function()
        local sl = lurek.ui.newSlider()
        expect_equal(0, sl.getMin())
        expect_equal(100, sl.getMax())
    end)

    it("creates with custom min/max", function()
        local sl = lurek.ui.newSlider(10, 50)
        expect_equal(10, sl.getMin())
        expect_equal(50, sl.getMax())
    end)

    it("clamps value to range", function()
        local sl = lurek.ui.newSlider(0, 100)
        sl.setValue(150)
        expect_equal(100, sl.getValue())
        sl.setValue(-10)
        expect_equal(0, sl.getValue())
    end)

    it("can set step", function()
        local sl = lurek.ui.newSlider(0, 100)
        sl.setStep(10)
        sl.setValue(23)
        expect_equal(20, sl.getValue())
    end)
end)

-- =========================================================================
-- 7. ProgressBar
-- =========================================================================
describe("lurek.ui ProgressBar", function()
    it("creates with defaults", function()
        local pb = lurek.ui.newProgressBar()
        expect_equal(0, pb.getMin())
        expect_equal(100, pb.getMax())
    end)

    it("creates with custom range", function()
        local pb = lurek.ui.newProgressBar(0, 100)
        expect_equal(0, pb.getMin())
        expect_equal(100, pb.getMax())
    end)

    it("can set and get value", function()
        local pb = lurek.ui.newProgressBar(0, 100)
        pb.setValue(42)
        expect_equal(42, pb.getValue())
    end)
end)

-- =========================================================================
-- 8. ComboBox
-- =========================================================================
describe("lurek.ui ComboBox", function()
    it("creates empty", function()
        local cb = lurek.ui.newComboBox()
        expect_equal(0, cb.getItemCount())
    end)

    it("can add items", function()
        local cb = lurek.ui.newComboBox()
        cb.addItem("Apple")
        cb.addItem("Banana")
        cb.addItem("Cherry")
        expect_equal(3, cb.getItemCount())
    end)

    it("can get item by index (1-based)", function()
        local cb = lurek.ui.newComboBox()
        cb.addItem("First")
        cb.addItem("Second")
        expect_equal("First", cb.getItem(1))
        expect_equal("Second", cb.getItem(2))
    end)

    it("returns nil for out-of-bounds index", function()
        local cb = lurek.ui.newComboBox()
        cb.addItem("Only")
        expect_equal(nil, cb.getItem(5))
    end)

    it("can select and get selected index", function()
        local cb = lurek.ui.newComboBox()
        cb.addItem("A")
        cb.addItem("B")
        cb.setSelectedIndex(2)
        expect_equal(2, cb.getSelectedIndex())
    end)

    it("can remove item", function()
        local cb = lurek.ui.newComboBox()
        cb.addItem("A")
        cb.addItem("B")
        local ok = cb.removeItem(1)
        expect_equal(true, ok)
        expect_equal(1, cb.getItemCount())
    end)

    it("can clear all items", function()
        local cb = lurek.ui.newComboBox()
        cb.addItem("A")
        cb.addItem("B")
        cb.clearItems()
        expect_equal(0, cb.getItemCount())
    end)
end)

-- =========================================================================
-- 9. ListBox
-- =========================================================================
describe("lurek.ui ListBox", function()
    it("creates empty", function()
        local lb = lurek.ui.newList()
        expect_equal(0, lb.getItemCount())
    end)

    it("can add and get items", function()
        local lb = lurek.ui.newList()
        lb.addItem("X")
        lb.addItem("Y")
        expect_equal(2, lb.getItemCount())
        expect_equal("X", lb.getItem(1))
        expect_equal("Y", lb.getItem(2))
    end)
end)

-- =========================================================================
-- 10. TabBar
-- =========================================================================
describe("lurek.ui TabBar", function()
    it("creates empty", function()
        local tb = lurek.ui.newTabBar()
        expect_equal(0, tb.getTabCount())
    end)

    it("can add tabs", function()
        local tb = lurek.ui.newTabBar()
        tb.addTab("General")
        tb.addTab("Settings")
        tb.addTab("About")
        expect_equal(3, tb.getTabCount())
    end)

    it("can get tab label (1-based)", function()
        local tb = lurek.ui.newTabBar()
        tb.addTab("First")
        tb.addTab("Second")
        expect_equal("First", tb.getTab(1))
        expect_equal("Second", tb.getTab(2))
    end)

    it("can set active tab (1-based)", function()
        local tb = lurek.ui.newTabBar()
        tb.addTab("A")
        tb.addTab("B")
        tb.setActiveTab(2)
        expect_equal(2, tb.getActiveTab())
    end)

    it("can remove tab", function()
        local tb = lurek.ui.newTabBar()
        tb.addTab("A")
        tb.addTab("B")
        local ok = tb.removeTab(1)
        expect_equal(true, ok)
        expect_equal(1, tb.getTabCount())
    end)
end)

-- =========================================================================
-- 11. Base widget methods (position, size, visibility, etc.)
-- =========================================================================
describe("lurek.ui widget base methods", function()
    it("can set and get position", function()
        local btn = lurek.ui.newButton("Pos")
        btn.setPosition(100, 200)
        local x, y = btn.getPosition()
        expect_equal(100, x)
        expect_equal(200, y)
    end)

    it("can set and get size", function()
        local btn = lurek.ui.newButton("Size")
        btn.setSize(300, 150)
        local w, h = btn.getSize()
        expect_equal(300, w)
        expect_equal(150, h)
    end)

    it("can set and get visibility", function()
        local btn = lurek.ui.newButton("Vis")
        expect_equal(true, btn.isVisible())
        btn.setVisible(false)
        expect_equal(false, btn.isVisible())
    end)

    it("can set and get enabled state", function()
        local btn = lurek.ui.newButton("En")
        expect_equal(true, btn.isEnabled())
        btn.setEnabled(false)
        expect_equal(false, btn.isEnabled())
    end)

    it("can set and get id", function()
        local btn = lurek.ui.newButton("Id")
        btn.setId("my_button")
        expect_equal("my_button", btn.getId())
    end)

    it("can set and get tooltip", function()
        local btn = lurek.ui.newButton("Tip")
        btn.setTooltip("Click me!")
        expect_equal("Click me!", btn.getTooltip())
    end)

    it("can set and get z-order", function()
        local btn = lurek.ui.newButton("Z")
        btn.setZOrder(10)
        expect_equal(10, btn.getZOrder())
    end)

    it("can set and get padding (4 values)", function()
        local btn = lurek.ui.newButton("Pad")
        btn.setPadding(1, 2, 3, 4)
        local t, r, b, l = btn.getPadding()
        expect_equal(1, t)
        expect_equal(2, r)
        expect_equal(3, b)
        expect_equal(4, l)
    end)

    it("can set padding (1 value = uniform)", function()
        local btn = lurek.ui.newButton("Pad1")
        btn.setPadding(5)
        local t, r, b, l = btn.getPadding()
        expect_equal(5, t)
        expect_equal(5, r)
        expect_equal(5, b)
        expect_equal(5, l)
    end)

    it("can set and get margin", function()
        local btn = lurek.ui.newButton("Mar")
        btn.setMargin(10, 20, 10, 20)
        local t, r, b, l = btn.getMargin()
        expect_equal(10, t)
        expect_equal(20, r)
        expect_equal(10, b)
        expect_equal(20, l)
    end)

    it("contains point hit test", function()
        local btn = lurek.ui.newButton("Hit")
        btn.setPosition(10, 20)
        btn.setSize(100, 50)
        expect_equal(true, btn.containsPoint(50, 40))
        expect_equal(false, btn.containsPoint(200, 200))
    end)

    it("can set and get min size", function()
        local btn = lurek.ui.newButton("Min")
        btn.setMinSize(50, 25)
        local w, h = btn.getMinSize()
        expect_equal(50, w)
        expect_equal(25, h)
    end)

    it("can set and get max size", function()
        local btn = lurek.ui.newButton("Max")
        btn.setMaxSize(500, 300)
        local w, h = btn.getMaxSize()
        expect_equal(500, w)
        expect_equal(300, h)
    end)

    it("can set flex grow and shrink", function()
        local btn = lurek.ui.newButton("Flex")
        btn.setFlexGrow(2.0)
        expect_equal(2.0, btn.getFlexGrow())
        btn.setFlexShrink(0.5)
        expect_equal(0.5, btn.getFlexShrink())
    end)

    it("getState returns a string", function()
        local btn = lurek.ui.newButton("State")
        local s = btn.getState()
        expect_type("string", s)
        expect_equal("normal", s)
    end)
end)

-- =========================================================================
-- 12. Panel (container)
-- =========================================================================
describe("lurek.ui Panel", function()
    it("creates a panel", function()
        local p = lurek.ui.newPanel()
        expect_type("table", p)
    end)

    it("can add and count children", function()
        local p = lurek.ui.newPanel()
        local b1 = lurek.ui.newButton("A")
        local b2 = lurek.ui.newButton("B")
        p.addChild(b1)
        p.addChild(b2)
        expect_equal(2, p.getChildCount())
    end)

    it("can remove children", function()
        local p = lurek.ui.newPanel()
        local b = lurek.ui.newButton("X")
        p.addChild(b)
        expect_equal(1, p.getChildCount())
        p.removeChild(b)
        expect_equal(0, p.getChildCount())
    end)
end)

-- =========================================================================
-- 13. Layout
-- =========================================================================
describe("lurek.ui Layout", function()
    it("creates with default vertical direction", function()
        local ly = lurek.ui.newLayout()
        expect_equal("vertical", ly.getDirection())
    end)

    it("creates with specified direction", function()
        local ly = lurek.ui.newLayout("horizontal")
        expect_equal("horizontal", ly.getDirection())
    end)

    it("can change direction", function()
        local ly = lurek.ui.newLayout()
        ly.setDirection("grid")
        expect_equal("grid", ly.getDirection())
    end)

    it("can set spacing", function()
        local ly = lurek.ui.newLayout()
        ly.setSpacing(10)
        expect_equal(10, ly.getSpacing())
    end)

    it("can set alignment", function()
        local ly = lurek.ui.newLayout()
        ly.setAlign("center")
        expect_equal("center", ly.getAlign())
    end)

    it("can set justification", function()
        local ly = lurek.ui.newLayout()
        ly.setJustify("space-between")
        expect_equal("space-between", ly.getJustify())
    end)
end)

-- =========================================================================
-- 14. ScrollPanel
-- =========================================================================
describe("lurek.ui ScrollPanel", function()
    it("creates a scroll panel", function()
        local sp = lurek.ui.newScrollPanel()
        expect_type("table", sp)
    end)

    it("can set and get content size", function()
        local sp = lurek.ui.newScrollPanel()
        sp.setContentSize(800, 600)
        local w, h = sp.getContentSize()
        expect_equal(800, w)
        expect_equal(600, h)
    end)

    it("can set and get scroll position", function()
        local sp = lurek.ui.newScrollPanel()
        sp.setContentSize(500, 500)
        sp.setScrollPosition(50, 100)
        local sx, sy = sp.getScrollPosition()
        expect_equal(50, sx)
        expect_equal(100, sy)
    end)

    it("can set scroll speed", function()
        local sp = lurek.ui.newScrollPanel()
        sp.setScrollSpeed(2.0)
        -- No getter, just verify no error
    end)
end)

-- =========================================================================
-- 15. NinePatch
-- =========================================================================
describe("lurek.ui NinePatch", function()
    it("creates a nine-patch widget", function()
        local np = lurek.ui.newNinePatch()
        expect_type("table", np)
    end)
end)

-- =========================================================================
-- 16. Separator
-- =========================================================================
describe("lurek.ui Separator", function()
    it("creates horizontal separator by default", function()
        local sep = lurek.ui.newSeparator()
        expect_type("table", sep)
    end)

    it("creates vertical separator", function()
        local sep = lurek.ui.newSeparator(true)
        expect_type("table", sep)
    end)
end)

-- =========================================================================
-- 17. Spacer
-- =========================================================================
describe("lurek.ui Spacer", function()
    it("creates a spacer with default size", function()
        local sp = lurek.ui.newSpacer()
        expect_type("table", sp)
    end)

    it("creates a spacer with custom size", function()
        local sp = lurek.ui.newSpacer(50, 25)
        local w, h = nil, nil
        local ok, get_size = pcall(function() return sp["getSize"] end)
        if ok and type(get_size) == "function" then
            w, h = get_size()
        end
        expect_equal(50, w)
        expect_equal(25, h)
    end)
end)

-- =========================================================================
-- 18. Toast
-- =========================================================================
describe("lurek.ui Toast", function()
    it("creates a toast", function()
        local t = lurek.ui.newToast("Hello!", 3.0)
        expect_type("table", t)
    end)

    it("can add toast to context", function()
        local t = lurek.ui.newToast("Msg", 2.0)
        lurek.ui.addToast(t)
        local count = lurek.ui.getToastCount()
        -- count should be >= 1 (may accumulate from other tests)
        expect_equal(true, count >= 1)
    end)
end)

-- =========================================================================
-- 19. TreeView
-- =========================================================================
describe("lurek.ui TreeView", function()
    it("creates empty tree", function()
        local tv = lurek.ui.newTreeView()
        expect_equal(0, tv.getNodeCount())
    end)

    it("can add root nodes", function()
        local tv = lurek.ui.newTreeView()
        local idx1 = tv.addNode("Root 1")
        local idx2 = tv.addNode("Root 2")
        expect_equal(2, tv.getNodeCount())
        expect_type("number", idx1)
        expect_type("number", idx2)
    end)

    it("can add child nodes", function()
        local tv = lurek.ui.newTreeView()
        local root = tv.addNode("Parent")
        local child = tv.addNode("Child", root)
        expect_equal(2, tv.getNodeCount())
        expect_type("number", child)
    end)

    it("can toggle node expansion", function()
        local tv = lurek.ui.newTreeView()
        local root = tv.addNode("Root")
        -- toggle returns boolean
        local expanded = tv.toggleNode(root)
        expect_type("boolean", expanded)
    end)

    it("can remove a node", function()
        local tv = lurek.ui.newTreeView()
        tv.addNode("A")
        tv.addNode("B")
        expect_equal(2, tv.getNodeCount())
        local ok = tv.removeNode(1)
        expect_equal(true, ok)
        expect_equal(1, tv.getNodeCount())
    end)

    it("removeNode returns false for invalid index", function()
        local tv = lurek.ui.newTreeView()
        expect_equal(false, tv.removeNode(5))
    end)

    it("can clear all nodes", function()
        local tv = lurek.ui.newTreeView()
        tv.addNode("A")
        tv.addNode("B")
        tv.clearNodes()
        expect_equal(0, tv.getNodeCount())
    end)

    it("can get and set node text", function()
        local tv = lurek.ui.newTreeView()
        local idx = tv.addNode("Original")
        expect_equal("Original", tv.getNodeText(idx))
        local ok = tv.setNodeText(idx, "Changed")
        expect_equal(true, ok)
        expect_equal("Changed", tv.getNodeText(idx))
    end)

    it("can set node icon", function()
        local tv = lurek.ui.newTreeView()
        local idx = tv.addNode("Folder")
        local ok = tv.setNodeIcon(idx, "folder.png")
        expect_equal(true, ok)
    end)

    it("can expand and collapse a node", function()
        local tv = lurek.ui.newTreeView()
        local root = tv.addNode("Root")
        tv.addNode("Child", root)
        expect_equal(true, tv.expandNode(root))
        expect_equal(true, tv.isNodeExpanded(root))
        expect_equal(true, tv.collapseNode(root))
        expect_equal(false, tv.isNodeExpanded(root))
    end)

    it("isNodeExpanded returns nil for invalid index", function()
        local tv = lurek.ui.newTreeView()
        expect_equal(nil, tv.isNodeExpanded(99))
    end)

    it("can expand and collapse all", function()
        local tv = lurek.ui.newTreeView()
        local r1 = tv.addNode("R1")
        tv.addNode("C1", r1)
        tv.expandAll()
        expect_equal(true, tv.isNodeExpanded(r1))
        tv.collapseAll()
        expect_equal(false, tv.isNodeExpanded(r1))
    end)

    it("can set and get selected node", function()
        local tv = lurek.ui.newTreeView()
        local idx = tv.addNode("Node")
        expect_equal(true, tv.setSelectedNode(idx))
        expect_equal(idx, tv.getSelectedNode())
    end)

    it("getSelectedNode returns nil when none selected", function()
        local tv = lurek.ui.newTreeView()
        expect_equal(nil, tv.getSelectedNode())
    end)

    it("can get child nodes (1-based)", function()
        local tv = lurek.ui.newTreeView()
        local root = tv.addNode("Root")
        local c1 = tv.addNode("Child1", root)
        local c2 = tv.addNode("Child2", root)
        local children = tv.getChildNodes(root)
        expect_type("table", children)
        expect_equal(2, #children)
        expect_equal(c1, children[1])
        expect_equal(c2, children[2])
    end)

    it("can get parent node", function()
        local tv = lurek.ui.newTreeView()
        local root = tv.addNode("Root")
        local child = tv.addNode("Child", root)
        expect_equal(root, tv.getParentNode(child))
    end)

    it("root node has nil parent", function()
        local tv = lurek.ui.newTreeView()
        local root = tv.addNode("Root")
        expect_equal(nil, tv.getParentNode(root))
    end)

    it("can get node depth", function()
        local tv = lurek.ui.newTreeView()
        local root = tv.addNode("Root")
        local child = tv.addNode("Child", root)
        local grand = tv.addNode("Grand", child)
        expect_equal(0, tv.getNodeDepth(root))
        expect_equal(1, tv.getNodeDepth(child))
        expect_equal(2, tv.getNodeDepth(grand))
    end)
end)

-- =========================================================================
-- 20. Widget count & root
-- =========================================================================
describe("lurek.ui widget count", function()
    it("getWidgetCount returns a number", function()
        local count = lurek.ui.getWidgetCount()
        expect_type("number", count)
        expect_equal(true, count >= 0)
    end)

    it("getRoot returns a table", function()
        local root = lurek.ui.getRoot()
        expect_type("table", root)
    end)
end)

-- =========================================================================
-- 21. Focus management
-- =========================================================================
describe("lurek.ui focus", function()
    it("clearFocus works without error", function()
        lurek.ui.clearFocus()
    end)

    it("getFocus returns nil when no focus", function()
        lurek.ui.clearFocus()
        local f = lurek.ui.getFocus()
        expect_equal(nil, f)
    end)

    it("setFocus and getFocus work", function()
        local btn = lurek.ui.newButton("Focus Test")
        lurek.ui.setFocus(btn)
        local f = lurek.ui.getFocus()
        expect_type("number", f)
    end)

    it("focusNext moves focus", function()
        local b1 = lurek.ui.newButton("N1")
        local b2 = lurek.ui.newButton("N2")
        lurek.ui.setFocus(b1)
        lurek.ui.focusNext()
        -- focus should have moved
        local f = lurek.ui.getFocus()
        expect_type("number", f)
    end)
end)

-- =========================================================================
-- 22. Input routing
-- =========================================================================
describe("lurek.ui input routing", function()
    it("mousepressed returns boolean", function()
        local consumed = lurek.ui.mousepressed(100, 100, 1)
        expect_type("boolean", consumed)
    end)

    it("mousereleased returns boolean", function()
        local consumed = lurek.ui.mousereleased(100, 100, 1)
        expect_type("boolean", consumed)
    end)

    it("mousemoved returns boolean", function()
        local consumed = lurek.ui.mousemoved(100, 100)
        expect_type("boolean", consumed)
    end)

    it("keypressed returns boolean", function()
        local consumed = lurek.ui.keypressed("tab")
        expect_type("boolean", consumed)
    end)

    it("textinput returns boolean", function()
        local consumed = lurek.ui.textinput("a")
        expect_type("boolean", consumed)
    end)

    it("wheelmoved returns boolean", function()
        local consumed = lurek.ui.wheelmoved(0, -1)
        expect_type("boolean", consumed)
    end)
end)

-- =========================================================================
-- 23. Update & draw (headless: no-op but should not error)
-- =========================================================================
describe("lurek.ui update and draw", function()
    it("update runs without error", function()
        lurek.ui.update(0.016)
    end)

    it("draw runs without error", function()
        lurek.ui.draw()
    end)
end)

-- =========================================================================
-- 24. Theme
-- =========================================================================
describe("lurek.ui Theme", function()
    it("creates a theme", function()
        local theme = lurek.ui.newTheme()
        expect_type("userdata", theme)
    end)

    it("can set and get theme", function()
        local theme = lurek.ui.newTheme()
        lurek.ui.setTheme(theme)
        local t = lurek.ui.getTheme()
        expect_type("boolean", t)
    end)
end)

-- =========================================================================
-- 25. findById
-- =========================================================================
describe("lurek.ui findById", function()
    it("finds a widget by id", function()
        local btn = lurek.ui.newButton("Find Me")
        btn.setId("unique_btn")
        local found = btn.findById("unique_btn")
        -- findById searches from root; returned widget is a table or nil
        -- Since btn is the one with the id, it should find itself
        -- Note: depends on context-wide search
    end)
end)

-- =========================================================================
-- 26. Callbacks (onClick, onChange, onDraw)
-- =========================================================================
describe("lurek.ui callbacks", function()
    it("setOnClick accepts a function", function()
        local btn = lurek.ui.newButton("Clickable")
        local clicked = false
        btn.setOnClick(function()
            clicked = true
        end)
        -- Callback is stored but not invoked here
    end)

    it("setOnChange accepts a function", function()
        local sl = lurek.ui.newSlider(0, 100)
        sl.setOnChange(function(val) end)
    end)

    it("setOnDraw accepts a function", function()
        local p = lurek.ui.newPanel()
        ---@diagnostic disable-next-line: param-type-mismatch
        p.setOnDraw(p, function() end)
    end)
end)

-- =========================================================================
-- 22. RadioButton
-- =========================================================================
describe("lurek.ui.newRadioButton", function()
    it("creates a radio button", function()
        local rb = lurek.ui.newRadioButton("Option A", "group1")
        expect_type("table", rb)
    end)
    it("has correct text", function()
        local rb = lurek.ui.newRadioButton("Opt", "g")
        expect_equal("Opt", rb.getText())
    end)
    it("defaults to not selected", function()
        local rb = lurek.ui.newRadioButton("X", "g")
        expect_equal(false, rb.isSelected())
    end)
    it("can set selected", function()
        local rb = lurek.ui.newRadioButton("X", "g")
        rb.setSelected(true)
        expect_equal(true, rb.isSelected())
    end)
    it("has group", function()
        local rb = lurek.ui.newRadioButton("X", "mygroup")
        expect_equal("mygroup", rb.getGroup())
    end)
    it("has base widget methods", function()
        local rb = lurek.ui.newRadioButton("A", "g")
        expect_type("function", rb.setPosition)
        expect_type("function", rb.setSize)
        expect_type("function", rb.setVisible)
    end)
end)

-- =========================================================================
-- 23. ScrollBar
-- =========================================================================
describe("lurek.ui.newScrollBar", function()
    it("creates a scroll bar", function()
        local sb = lurek.ui.newScrollBar(true)
        expect_type("table", sb)
    end)
    it("defaults position to 0", function()
        local sb = lurek.ui.newScrollBar(true)
        expect_near(0, sb.getScrollPosition(), 0.001)
    end)
    it("can set position", function()
        local sb = lurek.ui.newScrollBar(false)
        sb.setScrollPosition(42)
        expect_near(42, sb.getScrollPosition(), 0.001)
    end)
    it("default content size is 100", function()
        local sb = lurek.ui.newScrollBar(true)
        expect_near(100, sb.getContentSize(), 0.001)
    end)
    it("default view size is 50", function()
        local sb = lurek.ui.newScrollBar(true)
        expect_near(50, sb.getViewSize(), 0.001)
    end)
    it("can set content and view sizes", function()
        local sb = lurek.ui.newScrollBar(true)
        sb.setContentSize(200)
        sb.setViewSize(80)
        expect_near(200, sb.getContentSize(), 0.001)
        expect_near(80, sb.getViewSize(), 0.001)
    end)
    it("vertical flag persists", function()
        local v = lurek.ui.newScrollBar(true)
        local h = lurek.ui.newScrollBar(false)
        expect_equal(true, v.isVertical())
        expect_equal(false, h.isVertical())
    end)
end)

-- =========================================================================
-- 24. GUIWindow
-- =========================================================================
describe("lurek.ui.newWindow", function()
    it("creates a window", function()
        local w = lurek.ui.newWindow("Title")
        expect_type("table", w)
    end)
    it("has correct title", function()
        local w = lurek.ui.newWindow("My Win")
        expect_equal("My Win", w.getTitle())
    end)
    it("defaults closeable true", function()
        local w = lurek.ui.newWindow("W")
        expect_equal(true, w.isCloseable())
    end)
    it("defaults draggable true", function()
        local w = lurek.ui.newWindow("W")
        expect_equal(true, w.isDraggable())
    end)
    it("defaults resizable false", function()
        local w = lurek.ui.newWindow("W")
        expect_equal(false, w.isResizable())
    end)
    it("can toggle closeable", function()
        local w = lurek.ui.newWindow("W")
        w.setCloseable(false)
        expect_equal(false, w.isCloseable())
    end)
    it("can add child", function()
        local w = lurek.ui.newWindow("W")
        local btn = lurek.ui.newButton("B")
        w.addChild(btn["_idx"])
        expect_equal(1, #w.getChildren())
    end)
end)

-- =========================================================================
-- 25. SplitPanel
-- =========================================================================
describe("lurek.ui.newSplitPanel", function()
    it("creates a split panel", function()
        local sp = lurek.ui.newSplitPanel("horizontal")
        expect_type("table", sp)
    end)
    it("has correct orientation", function()
        local sp = lurek.ui.newSplitPanel("vertical")
        expect_equal("vertical", sp.getOrientation())
    end)
    it("default split position is 0.5", function()
        local sp = lurek.ui.newSplitPanel("horizontal")
        expect_near(0.5, sp.getSplitPosition(), 0.001)
    end)
    it("can set split position", function()
        local sp = lurek.ui.newSplitPanel("horizontal")
        sp.setSplitPosition(0.3)
        expect_near(0.3, sp.getSplitPosition(), 0.001)
    end)
    it("can set min panel size", function()
        local sp = lurek.ui.newSplitPanel("horizontal")
        sp.setMinPanelSize(100)
        expect_near(100, sp.getMinPanelSize(), 0.001)
    end)
end)

-- =========================================================================
-- 26. DockPanel
-- =========================================================================
describe("lurek.ui.newDockPanel", function()
    it("creates a dock panel", function()
        local dp = lurek.ui.newDockPanel()
        expect_type("table", dp)
    end)
    it("starts with 0 docked", function()
        local dp = lurek.ui.newDockPanel()
        expect_equal(0, dp.getDockedCount())
    end)
    it("can dock a child", function()
        local dp = lurek.ui.newDockPanel()
        local btn = lurek.ui.newButton("B")
        dp.dock(btn["_idx"], "left")
        expect_equal(1, dp.getDockedCount())
    end)
    it("can set split size", function()
        local dp = lurek.ui.newDockPanel()
        dp.setSplitSize("left", 200)
        expect_near(200, dp.getSplitSize("left"), 0.001)
    end)
end)

-- =========================================================================
-- 27. Toolbar
-- =========================================================================
describe("lurek.ui.newToolbar", function()
    it("creates a toolbar", function()
        local tb = lurek.ui.newToolbar("horizontal")
        expect_type("table", tb)
    end)
    it("has orientation", function()
        local tb = lurek.ui.newToolbar("vertical")
        expect_equal("vertical", tb.getOrientation())
    end)
    it("can add child", function()
        local tb = lurek.ui.newToolbar("horizontal")
        local btn = lurek.ui.newButton("B")
        tb.addChild(btn["_idx"])
        expect_equal(1, tb.getChildCount())
    end)

    it("addButton returns 1-based index", function()
        local tb = lurek.ui.newToolbar("horizontal")
        local idx = tb.addButton("save", "Save File")
        expect_equal(1, idx)
        local idx2 = tb.addButton("open", "Open File")
        expect_equal(2, idx2)
    end)

    it("addButton is idempotent (no duplicate ids)", function()
        local tb = lurek.ui.newToolbar("horizontal")
        tb.addButton("dup", "First")
        local idx2 = tb.addButton("dup", "Second")
        expect_equal(1, idx2)
    end)

    it("addSeparator and addSpacer do not error", function()
        local tb = lurek.ui.newToolbar("horizontal")
        tb.addSeparator()
        tb.addSpacer(10)
        tb.addSpacer()
    end)

    it("getButton returns table with correct fields", function()
        local tb = lurek.ui.newToolbar("horizontal")
        tb.addButton("save", "Save")
        local btn = tb.getButton("save")
        expect_type("table", btn)
        expect_equal("save", btn.id)
        expect_equal("Save", btn.tooltip)
        expect_equal(true, btn.enabled)
        expect_equal(false, btn.toggled)
    end)

    it("getButton returns nil for missing id", function()
        local tb = lurek.ui.newToolbar("horizontal")
        expect_equal(nil, tb.getButton("nope"))
    end)

    it("setButtonEnabled can disable a button", function()
        local tb = lurek.ui.newToolbar("horizontal")
        tb.addButton("x", "X")
        expect_equal(true, tb.setButtonEnabled("x", false))
        local btn = tb.getButton("x")
        expect_equal(false, btn.enabled)
    end)

    it("setButtonToggled and isButtonToggled work", function()
        local tb = lurek.ui.newToolbar("horizontal")
        tb.addButton("t", "Toggle")
        expect_equal(true, tb.setButtonToggled("t", true))
        expect_equal(true, tb.isButtonToggled("t"))
    end)

    it("isButtonToggled returns nil for missing id", function()
        local tb = lurek.ui.newToolbar("horizontal")
        expect_equal(nil, tb.isButtonToggled("none"))
    end)
end)

-- =========================================================================
-- 28. MenuBar
-- =========================================================================
describe("lurek.ui.newMenuBar", function()
    it("creates a menu bar", function()
        local mb = lurek.ui.newMenuBar()
        expect_type("table", mb)
    end)
    it("starts with 0 menus", function()
        local mb = lurek.ui.newMenuBar()
        expect_equal(0, mb.getMenuCount())
    end)
    it("can add menu", function()
        local mb = lurek.ui.newMenuBar()
        local mi = lurek.ui.newMenuItem("File")
        mb.addMenu(mi["_idx"])
        expect_equal(1, mb.getMenuCount())
    end)
end)

-- =========================================================================
-- 29. MenuItem
-- =========================================================================
describe("lurek.ui.newMenuItem", function()
    it("creates a menu item", function()
        local mi = lurek.ui.newMenuItem("Edit")
        expect_type("table", mi)
    end)
    it("has correct text", function()
        local mi = lurek.ui.newMenuItem("File")
        expect_equal("File", mi.getText())
    end)
    it("defaults unchecked", function()
        local mi = lurek.ui.newMenuItem("X")
        expect_equal(false, mi.isChecked())
    end)
    it("can set shortcut", function()
        local mi = lurek.ui.newMenuItem("Save")
        mi.setShortcut("Ctrl+S")
        expect_equal("Ctrl+S", mi.getShortcut())
    end)
    it("can add sub-item", function()
        local mi = lurek.ui.newMenuItem("File")
        local sub = lurek.ui.newMenuItem("Open")
        mi.addSubItem(sub["_idx"])
        expect_equal(1, #mi.getSubItems())
    end)
end)

-- =========================================================================
-- 30. Dialog
-- =========================================================================
describe("lurek.ui.newDialog", function()
    it("creates a dialog", function()
        local d = lurek.ui.newDialog("Confirm")
        expect_type("table", d)
    end)
    it("has title", function()
        local d = lurek.ui.newDialog("Save?")
        expect_equal("Save?", d.getTitle())
    end)
    it("defaults modal true", function()
        local d = lurek.ui.newDialog("D")
        expect_equal(true, d.isModal())
    end)
    it("defaults not open", function()
        local d = lurek.ui.newDialog("D")
        expect_equal(false, d.isOpen())
    end)
    it("can open and close", function()
        local d = lurek.ui.newDialog("D")
        d.open()
        expect_equal(true, d.isOpen())
        d.close()
        expect_equal(false, d.isOpen())
    end)

    it("setContent and getContent work", function()
        local d = lurek.ui.newDialog("Edit")
        local btn = lurek.ui.newButton("B")
        expect_equal(nil, d.getContent())
        d.setContent(btn["_idx"])
        expect_equal(btn["_idx"], d.getContent())
    end)

    it("setContent nil clears content", function()
        local d = lurek.ui.newDialog("Clear")
        local btn = lurek.ui.newButton("B")
        d.setContent(btn["_idx"])
        d.setContent(nil)
        expect_equal(nil, d.getContent())
    end)

    it("addButton appends footer button and returns count", function()
        local d = lurek.ui.newDialog("Prompt")
        local count1 = d.addButton("OK")
        expect_equal(1, count1)
        local count2 = d.addButton("Cancel")
        expect_equal(2, count2)
    end)
end)

-- =========================================================================
-- 31. StatusBar
-- =========================================================================
describe("lurek.ui.newStatusBar", function()
    it("creates a status bar", function()
        local sb = lurek.ui.newStatusBar()
        expect_type("table", sb)
    end)
    it("starts with 0 sections", function()
        local sb = lurek.ui.newStatusBar()
        expect_equal(0, sb.getSectionCount())
    end)
    it("can add section", function()
        local sb = lurek.ui.newStatusBar()
        sb.addSection("Ready", 100)
        expect_equal(1, sb.getSectionCount())
    end)
    it("can set section text", function()
        local sb = lurek.ui.newStatusBar()
        sb.addSection("Info", 120)
        sb.setSectionText(1, "Updated")
        expect_equal("Updated", sb.getSectionText(1))
    end)

    it("setSectionCount resizes sections up and down", function()
        local sb = lurek.ui.newStatusBar()
        sb.addSection("A", 100)
        sb.addSection("B", 100)
        expect_equal(2, sb.getSectionCount())
        sb.setSectionCount(1)
        expect_equal(1, sb.getSectionCount())
        sb.setSectionCount(3)
        expect_equal(3, sb.getSectionCount())
    end)

    it("setSectionWidget does not error", function()
        local sb = lurek.ui.newStatusBar()
        sb.addSection("A", 100)
        local btn = lurek.ui.newButton("X")
        sb.setSectionWidget(1, btn["_idx"])
    end)
end)

-- =========================================================================
-- 32. Accordion
-- =========================================================================
describe("lurek.ui.newAccordion", function()
    it("creates an accordion", function()
        local a = lurek.ui.newAccordion()
        expect_type("table", a)
    end)
    it("starts with 0 sections", function()
        local a = lurek.ui.newAccordion()
        expect_equal(0, a.getSectionCount())
    end)
    it("defaults non-exclusive", function()
        local a = lurek.ui.newAccordion()
        expect_equal(false, a.isExclusive())
    end)
    it("can set exclusive", function()
        local a = lurek.ui.newAccordion()
        a.setExclusive(true)
        expect_equal(true, a.isExclusive())
    end)
    it("can add section", function()
        local a = lurek.ui.newAccordion()
        a.addSection("Section 1")
        expect_equal(1, a.getSectionCount())
    end)
    it("can expand section", function()
        local a = lurek.ui.newAccordion()
        a.addSection("S1")
        a.toggleSection(1)
        expect_equal(true, a.isSectionExpanded(1))
    end)
    it("can collapse section", function()
        local a = lurek.ui.newAccordion()
        a.addSection("S1")
        a.toggleSection(1)
        a.toggleSection(1)
        expect_equal(false, a.isSectionExpanded(1))
    end)
end)

-- =========================================================================
-- 33. TooltipPanel
-- =========================================================================
describe("lurek.ui.newTooltipPanel", function()
    it("creates a tooltip panel", function()
        local tp = lurek.ui.newTooltipPanel("Help text")
        expect_type("table", tp)
    end)
    it("has correct text", function()
        local tp = lurek.ui.newTooltipPanel("Tip")
        expect_equal("Tip", tp.getText())
    end)
    it("can set text", function()
        local tp = lurek.ui.newTooltipPanel("Old")
        tp.setText("New")
        expect_equal("New", tp.getText())
    end)
    it("default delay is 0.5", function()
        local tp = lurek.ui.newTooltipPanel("T")
        expect_near(0.5, tp.getDelay(), 0.001)
    end)
    it("can set delay", function()
        local tp = lurek.ui.newTooltipPanel("T")
        tp.setDelay(1.0)
        expect_near(1.0, tp.getDelay(), 0.001)
    end)
end)

-- =========================================================================
-- 34. ColorPicker
-- =========================================================================
describe("lurek.ui.newColorPicker", function()
    it("creates a color picker", function()
        local cp = lurek.ui.newColorPicker()
        expect_type("table", cp)
    end)
    it("default color is white", function()
        local cp = lurek.ui.newColorPicker()
        local r, g, b, a = cp.getColor()
        expect_near(1.0, r, 0.001)
        expect_near(1.0, g, 0.001)
        expect_near(1.0, b, 0.001)
        expect_near(1.0, a, 0.001)
    end)
    it("can set color", function()
        local cp = lurek.ui.newColorPicker()
        cp.setColor(0.5, 0.3, 0.1, 0.9)
        local r, g, b, a = cp.getColor()
        expect_near(0.5, r, 0.001)
        expect_near(0.3, g, 0.001)
        expect_near(0.1, b, 0.001)
        expect_near(0.9, a, 0.001)
    end)
    it("default shows alpha", function()
        local cp = lurek.ui.newColorPicker()
        expect_equal(true, cp.getShowAlpha())
    end)
    it("default color mode is rgb", function()
        local cp = lurek.ui.newColorPicker()
        expect_equal("rgb", cp.getColorMode())
    end)
    it("can set color mode", function()
        local cp = lurek.ui.newColorPicker()
        cp.setColorMode("hsv")
        expect_equal("hsv", cp.getColorMode())
    end)
end)

-- =========================================================================
-- 35. GUITable
-- =========================================================================
describe("lurek.ui.newTable", function()
    it("creates a table", function()
        local t = lurek.ui.newTable()
        expect_type("table", t)
    end)
    it("starts with 0 columns", function()
        local t = lurek.ui.newTable()
        expect_equal(0, t.getColumnCount())
    end)
    it("starts with 0 rows", function()
        local t = lurek.ui.newTable()
        expect_equal(0, t.getRowCount())
    end)
    it("can add column", function()
        local t = lurek.ui.newTable()
        t.addColumn("Name", 100)
        expect_equal(1, t.getColumnCount())
    end)
    it("can add row", function()
        local t = lurek.ui.newTable()
        t.addColumn("Name", 100)
        t.addRow({"Alice"})
        expect_equal(1, t.getRowCount())
    end)
    it("no selected row by default", function()
        local t = lurek.ui.newTable()
        expect_equal(nil, t.getSelectedRow())
    end)
    it("can select row after adding", function()
        local t = lurek.ui.newTable()
        t.addColumn("Name", 100)
        t.addRow({"Alice"})
        t.setSelectedRow(1)
        expect_equal(1, t.getSelectedRow())
    end)
    it("can set sortable", function()
        local t = lurek.ui.newTable()
        t.setSortable(true)
        expect_equal(true, t.isSortable())
    end)
end)

-- =========================================================================
-- 36. ImageWidget
-- =========================================================================
describe("lurek.ui.newImageWidget", function()
    it("creates an image widget", function()
        local iw = lurek.ui.newImageWidget()
        expect_type("table", iw)
    end)
    it("default scale mode is fit", function()
        local iw = lurek.ui.newImageWidget()
        expect_equal("fit", iw.getScaleMode())
    end)
    it("can set scale mode", function()
        local iw = lurek.ui.newImageWidget()
        iw.setScaleMode("fill")
        expect_equal("fill", iw.getScaleMode())
    end)
    it("default tint is white", function()
        local iw = lurek.ui.newImageWidget()
        local r, g, b, a = iw.getTint()
        expect_near(1.0, r, 0.001)
        expect_near(1.0, g, 0.001)
        expect_near(1.0, b, 0.001)
        expect_near(1.0, a, 0.001)
    end)
    it("can set tint", function()
        local iw = lurek.ui.newImageWidget()
        iw.setTint(0.5, 0.2, 0.8, 1.0)
        local r, g, b, a = iw.getTint()
        expect_near(0.5, r, 0.001)
        expect_near(0.2, g, 0.001)
        expect_near(0.8, b, 0.001)
        expect_near(1.0, a, 0.001)
    end)
end)

describe("lurek.ui.parseWidgetState", function()
    it("is a function", function()
        expect_type("function", lurek.ui.parseWidgetState)
    end)

    it("returns 'normal' for valid input", function()
        expect_equal(lurek.ui.parseWidgetState("normal"), "normal")
    end)

    it("returns 'hovered' for valid input", function()
        expect_equal(lurek.ui.parseWidgetState("hovered"), "hovered")
    end)

    it("returns 'pressed' for valid input", function()
        expect_equal(lurek.ui.parseWidgetState("pressed"), "pressed")
    end)

    it("returns 'focused' for valid input", function()
        expect_equal(lurek.ui.parseWidgetState("focused"), "focused")
    end)

    it("returns 'disabled' for valid input", function()
        expect_equal(lurek.ui.parseWidgetState("disabled"), "disabled")
    end)

    it("returns nil for an invalid state string", function()
        expect_equal(lurek.ui.parseWidgetState("invalid"), nil)
    end)

    it("returns nil for an empty string", function()
        expect_equal(lurek.ui.parseWidgetState(""), nil)
    end)

    it("is case-sensitive  - 'Normal' returns nil", function()
        expect_equal(lurek.ui.parseWidgetState("Normal"), nil)
    end)
end)

-- =========================================================================
-- New factories: SpinBox, Switch, Badge
-- =========================================================================

describe("lurek.ui.newSpinBox factory", function()
    it("is callable", function()
        expect_equal(type(lurek.ui.newSpinBox), "function")
    end)

    it("returns a table", function()
        local sb = lurek.ui.newSpinBox(0, 100)
        expect_equal(type(sb), "table")
    end)

    it("getValue returns min after creation", function()
        local sb = lurek.ui.newSpinBox(10, 50)
        expect_equal(sb.getValue(), 10)
    end)

    it("increment changes value", function()
        local sb = lurek.ui.newSpinBox(0, 100)
        sb.increment()
        expect_equal(sb.getValue() > 0, true)
    end)

    it("decrement at min stays at min", function()
        local sb = lurek.ui.newSpinBox(5, 20)
        sb.decrement()
        expect_equal(sb.getValue(), 5)
    end)

    it("setRange is callable without error", function()
        local sb = lurek.ui.newSpinBox(0, 10)
        sb.setRange(1, 99)
        expect_equal(true, true)
    end)

    -- Migrated from Rust spin_box_increment_respects_step.
    it("increment advances value by custom step", function()
        local sb = lurek.ui.newSpinBox(0, 100)
        sb.setStep(2.0)
        sb.increment()
        expect_near(2.0, sb.getValue(), 0.001)
    end)

    -- Migrated from Rust spin_box_increment_clamps_at_max.
    it("increment clamps at max when step overshoots", function()
        local sb = lurek.ui.newSpinBox(0, 10)
        sb.setStep(1000.0)
        sb.increment()
        expect_near(10.0, sb.getValue(), 0.001)
    end)

    -- Migrated from Rust spin_box_set_value_clamps_to_range.
    it("setValue clamps to max when value exceeds range", function()
        local sb = lurek.ui.newSpinBox(0, 100)
        sb.setValue(999)
        expect_near(100.0, sb.getValue(), 0.001)
    end)

    -- Migrated from Rust spin_box_set_value_clamps_to_range.
    it("setValue clamps to min when value is below range", function()
        local sb = lurek.ui.newSpinBox(5, 50)
        sb.setValue(-1)
        expect_near(5.0, sb.getValue(), 0.001)
    end)
end)

describe("lurek.ui.newSwitch factory", function()
    it("is callable", function()
        expect_equal(type(lurek.ui.newSwitch), "function")
    end)

    it("returns a table", function()
        local sw = lurek.ui.newSwitch(false)
        expect_equal(type(sw), "table")
    end)

    it("isOn returns false when created off", function()
        local sw = lurek.ui.newSwitch(false)
        expect_equal(sw.isOn(), false)
    end)

    it("setOn(true) flips state", function()
        local sw = lurek.ui.newSwitch(false)
        sw.setOn(true)
        expect_equal(sw.isOn(), true)
    end)

    it("toggle flips state back and forth", function()
        local sw = lurek.ui.newSwitch(true)
        sw.toggle()
        expect_equal(sw.isOn(), false)
        sw.toggle()
        expect_equal(sw.isOn(), true)
    end)
end)

describe("lurek.ui.newBadge factory", function()
    it("is callable", function()
        expect_equal(type(lurek.ui.newBadge), "function")
    end)

    it("returns a table", function()
        local b = lurek.ui.newBadge(3)
        expect_equal(type(b), "table")
    end)

    it("getCount returns initial count", function()
        local b = lurek.ui.newBadge(7)
        expect_equal(b.getCount(), 7)
    end)

    it("getDisplayText returns count string below cap", function()
        local b = lurek.ui.newBadge(5)
        expect_equal(b.getDisplayText(), "5")
    end)

    it("getDisplayText shows plus notation when over cap", function()
        local b = lurek.ui.newBadge(200)
        expect_equal(b.getDisplayText(), "99+")
    end)

    it("setCount updates count", function()
        local b = lurek.ui.newBadge(0)
        b.setCount(42)
        expect_equal(b.getCount(), 42)
    end)

    -- Migrated from Rust badge_display_text_at_max_shows_count.
    it("getDisplayText shows exact count at cap boundary", function()
        local b = lurek.ui.newBadge(99)
        expect_equal(b.getDisplayText(), "99")
    end)
end)

-- =========================================================================
-- Module helpers: setDefaultTheme, setViewport, flushCache
-- =========================================================================

describe("lurek.ui default theme and viewport helpers", function()
    it("setDefaultTheme is callable", function()
        expect_equal(type(lurek.ui.setDefaultTheme), "function")
        lurek.ui.setDefaultTheme()
        expect_equal(true, true)
    end)

    it("setViewport is callable", function()
        expect_equal(type(lurek.ui.setViewport), "function")
        lurek.ui.setViewport(1280, 720)
        expect_equal(true, true)
    end)

    it("flushCache returns boolean", function()
        expect_equal(type(lurek.ui.flushCache), "function")
        local result = lurek.ui.flushCache()
        expect_equal(type(result), "boolean")
    end)

    it("flushCache returns false on second consecutive call", function()
        lurek.ui.flushCache()
        local clean = lurek.ui.flushCache()
        expect_equal(clean, false)
    end)
end)
test_summary()
