-- Luna2D Graph API Tests

-- Helper: build a simple 2-node graph with one edge
local function make_simple_graph()
    local g = luna.graph.newGraph()
    local n1 = g:addNode("source", -1)
    local n2 = g:addNode("sink", -1)
    local e = g:addEdge(n1, n2)
    return g, n1, n2, e
end

-- =========================================================================
-- 1. Module existence
-- =========================================================================
describe("luna.graph module exists", function()
    it("luna.graph is a table", function()
        expect_type("table", luna.graph)
    end)

    it("has newGraph factory", function()
        expect_type("function", luna.graph.newGraph)
    end)
end)

-- =========================================================================
-- 2. Graph construction
-- =========================================================================
describe("Graph construction", function()
    it("newGraph returns a userdata", function()
        local g = luna.graph.newGraph()
        expect_type("userdata", g)
    end)

    it("addNode returns a node handle", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        expect_type("userdata", n)
    end)

    it("addEdge returns an edge handle", function()
        local g, n1, n2, e = make_simple_graph()
        expect_type("userdata", e)
    end)

    it("addNode with type and capacity", function()
        local g = luna.graph.newGraph()
        local n = g:addNode("factory", 10)
        expect_equal("factory", n:getType())
        expect_equal(10, n:getCapacity())
    end)

    it("addNode defaults to 'default' type and -1 capacity", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        expect_equal("default", n:getType())
        expect_equal(-1, n:getCapacity())
    end)
end)

-- =========================================================================
-- 3. Node management
-- =========================================================================
describe("Node management", function()
    it("hasNode returns true for added node", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        expect_true(g:hasNode(n))
    end)

    it("removeNode returns true", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        expect_true(g:removeNode(n))
    end)

    it("hasNode returns false after removal", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        g:removeNode(n)
        expect_false(g:hasNode(n))
    end)

    it("getNodeCount reflects additions", function()
        local g = luna.graph.newGraph()
        expect_equal(0, g:getNodeCount())
        g:addNode()
        expect_equal(1, g:getNodeCount())
        g:addNode()
        expect_equal(2, g:getNodeCount())
    end)

    it("getNodes returns all nodes", function()
        local g = luna.graph.newGraph()
        g:addNode("a")
        g:addNode("b")
        g:addNode("c")
        local nodes = g:getNodes()
        expect_equal(3, #nodes)
    end)

    it("getNodeCount decreases after removeNode", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        g:addNode()
        expect_equal(2, g:getNodeCount())
        g:removeNode(n)
        expect_equal(1, g:getNodeCount())
    end)
end)

-- =========================================================================
-- 4. Edge management
-- =========================================================================
describe("Edge management", function()
    it("hasEdge returns true for added edge", function()
        local g, n1, n2, e = make_simple_graph()
        expect_true(g:hasEdge(e))
    end)

    it("removeEdge returns true", function()
        local g, n1, n2, e = make_simple_graph()
        expect_true(g:removeEdge(e))
    end)

    it("hasEdge returns false after removal", function()
        local g, n1, n2, e = make_simple_graph()
        g:removeEdge(e)
        expect_false(g:hasEdge(e))
    end)

    it("getEdgeCount reflects additions", function()
        local g = luna.graph.newGraph()
        local a = g:addNode()
        local b = g:addNode()
        local c = g:addNode()
        expect_equal(0, g:getEdgeCount())
        g:addEdge(a, b)
        expect_equal(1, g:getEdgeCount())
        g:addEdge(b, c)
        expect_equal(2, g:getEdgeCount())
    end)

    it("getEdges returns all edges", function()
        local g, n1, n2, e = make_simple_graph()
        local edges = g:getEdges()
        expect_equal(1, #edges)
    end)

    it("getEdgeBetween finds existing edge", function()
        local g, n1, n2, e = make_simple_graph()
        local found = g:getEdgeBetween(n1, n2)
        expect_not_nil(found)
    end)

    it("getEdgeBetween returns nil for no edge", function()
        local g, n1, n2, e = make_simple_graph()
        local found = g:getEdgeBetween(n2, n1)
        expect_nil(found)
    end)

    it("getEdgeCount decreases after removeEdge", function()
        local g, n1, n2, e = make_simple_graph()
        expect_equal(1, g:getEdgeCount())
        g:removeEdge(e)
        expect_equal(0, g:getEdgeCount())
    end)

    it("addEdge with edge type", function()
        local g = luna.graph.newGraph()
        local a = g:addNode()
        local b = g:addNode()
        local e = g:addEdge(a, b, "conveyor")
        expect_equal("conveyor", e:getType())
    end)
end)

-- =========================================================================
-- 5. Item management
-- =========================================================================
describe("Item management", function()
    it("createItem returns a handle", function()
        local g = luna.graph.newGraph()
        local item = g:createItem()
        expect_type("userdata", item)
    end)

    it("createItem with type and decay", function()
        local g = luna.graph.newGraph()
        local item = g:createItem("ore", 5.0)
        expect_equal("ore", item:getType())
        expect_near(5.0, item:getDecayTime(), 0.001)
    end)

    it("addItem places item at node", function()
        local g = luna.graph.newGraph()
        local n = g:addNode("store", -1)
        local item = g:createItem("box")
        g:addItem(item, n)
        expect_equal(1, n:getItemCount())
    end)

    it("removeItem removes from graph", function()
        local g = luna.graph.newGraph()
        local item = g:createItem()
        expect_true(g:hasItem(item))
        g:removeItem(item)
        expect_false(g:hasItem(item))
    end)

    it("getItems returns all items", function()
        local g = luna.graph.newGraph()
        g:createItem("a")
        g:createItem("b")
        local items = g:getItems()
        expect_equal(2, #items)
    end)

    it("getItemCount reflects state", function()
        local g = luna.graph.newGraph()
        expect_equal(0, g:getItemCount())
        local item = g:createItem()
        expect_equal(1, g:getItemCount())
        g:removeItem(item)
        expect_equal(0, g:getItemCount())
    end)

    it("hasItem returns false for removed item", function()
        local g = luna.graph.newGraph()
        local item = g:createItem()
        g:removeItem(item)
        expect_false(g:hasItem(item))
    end)
end)

-- =========================================================================
-- 6. Node properties
-- =========================================================================
describe("Node properties", function()
    it("getType and setType", function()
        local g = luna.graph.newGraph()
        local n = g:addNode("alpha")
        expect_equal("alpha", n:getType())
        n:setType("beta")
        expect_equal("beta", n:getType())
    end)

    it("getCapacity and setCapacity", function()
        local g = luna.graph.newGraph()
        local n = g:addNode("x", 5)
        expect_equal(5, n:getCapacity())
        n:setCapacity(20)
        expect_equal(20, n:getCapacity())
    end)

    it("getItemCount starts at 0", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        expect_equal(0, n:getItemCount())
    end)

    it("isFull with unlimited capacity", function()
        local g = luna.graph.newGraph()
        local n = g:addNode("x", -1)
        expect_false(n:isFull())
    end)

    it("isFull with limited capacity", function()
        local g = luna.graph.newGraph()
        local n = g:addNode("x", 1)
        expect_false(n:isFull())
        local item = g:createItem()
        g:addItem(item, n)
        expect_true(n:isFull())
    end)

    it("isActive defaults to true", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        expect_true(n:isActive())
    end)

    it("setActive toggles state", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        n:setActive(false)
        expect_false(n:isActive())
        n:setActive(true)
        expect_true(n:isActive())
    end)

    it("getProcessTime and setProcessTime", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        n:setProcessTime(2.5)
        expect_near(2.5, n:getProcessTime(), 0.001)
    end)

    it("getPushRate and setPushRate", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        n:setPushRate(3.0)
        expect_near(3.0, n:getPushRate(), 0.001)
    end)

    it("getPullRate and setPullRate", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        n:setPullRate(4.0)
        expect_near(4.0, n:getPullRate(), 0.001)
    end)

    it("getPushFilter and setPushFilter", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        expect_nil(n:getPushFilter())
        n:setPushFilter("ore")
        expect_equal("ore", n:getPushFilter())
    end)

    it("getPullFilter and setPullFilter", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        expect_nil(n:getPullFilter())
        n:setPullFilter("wood")
        expect_equal("wood", n:getPullFilter())
    end)

    it("isQueueEnabled and setQueueEnabled", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        n:setQueueEnabled(true)
        expect_true(n:isQueueEnabled())
        n:setQueueEnabled(false)
        expect_false(n:isQueueEnabled())
    end)

    it("getQueueCapacity and setQueueCapacity", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        n:setQueueCapacity(10)
        expect_equal(10, n:getQueueCapacity())
    end)

    it("getQueueSize starts at 0", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        expect_equal(0, n:getQueueSize())
    end)

    it("getItems on node returns placed items", function()
        local g = luna.graph.newGraph()
        local n = g:addNode("x", -1)
        local i1 = g:createItem("a")
        local i2 = g:createItem("b")
        g:addItem(i1, n)
        g:addItem(i2, n)
        local items = n:getItems()
        expect_equal(2, #items)
    end)

    it("getEdges returns edges for node", function()
        local g, n1, n2, e = make_simple_graph()
        local out = n1:getEdges("out")
        expect_equal(1, #out)
        local inc = n2:getEdges("in")
        expect_equal(1, #inc)
    end)

    it("getEdges with 'both' returns all", function()
        local g = luna.graph.newGraph()
        local a = g:addNode()
        local b = g:addNode()
        local c = g:addNode()
        g:addEdge(a, b)
        g:addEdge(c, b)
        local edges = b:getEdges("both")
        expect_equal(2, #edges)
    end)
end)

-- =========================================================================
-- 7. Edge properties
-- =========================================================================
describe("Edge properties", function()
    it("getType and setType", function()
        local g, n1, n2, e = make_simple_graph()
        e:setType("pipe")
        expect_equal("pipe", e:getType())
    end)

    it("getFrom and getTo return correct nodes", function()
        local g, n1, n2, e = make_simple_graph()
        local from = e:getFrom()
        local to = e:getTo()
        expect_type("userdata", from)
        expect_type("userdata", to)
    end)

    it("getCapacity and setCapacity", function()
        local g, n1, n2, e = make_simple_graph()
        e:setCapacity(5)
        expect_equal(5, e:getCapacity())
    end)

    it("getThroughput and setThroughput", function()
        local g, n1, n2, e = make_simple_graph()
        e:setThroughput(2.0)
        expect_near(2.0, e:getThroughput(), 0.001)
    end)

    it("getTravelTime and setTravelTime", function()
        local g, n1, n2, e = make_simple_graph()
        e:setTravelTime(3.0)
        expect_near(3.0, e:getTravelTime(), 0.001)
    end)

    it("getWeight and setWeight", function()
        local g, n1, n2, e = make_simple_graph()
        e:setWeight(10.5)
        expect_near(10.5, e:getWeight(), 0.001)
    end)

    it("getSpeedModifier and setSpeedModifier", function()
        local g, n1, n2, e = make_simple_graph()
        e:setSpeedModifier(0.5)
        expect_near(0.5, e:getSpeedModifier(), 0.001)
    end)

    it("getCooldown and setCooldown", function()
        local g, n1, n2, e = make_simple_graph()
        e:setCooldown(2.0)
        expect_near(2.0, e:getCooldown(), 0.001)
    end)

    it("isBidirectional and setBidirectional", function()
        local g, n1, n2, e = make_simple_graph()
        expect_false(e:isBidirectional())
        e:setBidirectional(true)
        expect_true(e:isBidirectional())
    end)

    it("isActive and setActive", function()
        local g, n1, n2, e = make_simple_graph()
        expect_true(e:isActive())
        e:setActive(false)
        expect_false(e:isActive())
    end)

    it("getItemsInTransit is empty initially", function()
        local g, n1, n2, e = make_simple_graph()
        local transit = e:getItemsInTransit()
        expect_equal(0, #transit)
    end)
end)

-- =========================================================================
-- 8. Item properties
-- =========================================================================
describe("Item properties", function()
    it("getType and setType", function()
        local g = luna.graph.newGraph()
        local item = g:createItem("ore")
        expect_equal("ore", item:getType())
        item:setType("refined_ore")
        expect_equal("refined_ore", item:getType())
    end)

    it("getDecayTime and setDecayTime", function()
        local g = luna.graph.newGraph()
        local item = g:createItem("food", 10.0)
        expect_near(10.0, item:getDecayTime(), 0.001)
        item:setDecayTime(5.0)
        expect_near(5.0, item:getDecayTime(), 0.001)
    end)

    it("getRemainingLife for non-decaying item", function()
        local g = luna.graph.newGraph()
        local item = g:createItem("rock", -1.0)
        -- Non-decaying items should have remaining life equal to decay_time (or -1)
        expect_near(-1.0, item:getRemainingLife(), 0.001)
    end)

    it("isAlive is true for new item", function()
        local g = luna.graph.newGraph()
        local item = g:createItem()
        expect_true(item:isAlive())
    end)

    it("kill makes item not alive", function()
        local g = luna.graph.newGraph()
        local item = g:createItem()
        item:kill()
        expect_false(item:isAlive())
    end)

    it("getPriority and setPriority", function()
        local g = luna.graph.newGraph()
        local item = g:createItem()
        item:setPriority(5)
        expect_equal(5, item:getPriority())
    end)

    it("getPosition returns nil for unplaced item", function()
        local g = luna.graph.newGraph()
        local item = g:createItem()
        local pos1, pos2 = item:getPosition()
        expect_nil(pos1)
    end)

    it("getPosition returns node for placed item", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        local item = g:createItem()
        g:addItem(item, n)
        local pos1, pos2 = item:getPosition()
        expect_type("userdata", pos1)
        expect_nil(pos2)
    end)

    it("getPosition returns edge and progress for in-transit item", function()
        local g, n1, n2, e = make_simple_graph()
        e:setTravelTime(10.0)
        local item = g:createItem()
        g:addItem(item, n1)
        g:sendItem(item, e)
        local pos1, pos2 = item:getPosition()
        expect_type("userdata", pos1)
        expect_type("number", pos2)
    end)
end)

-- =========================================================================
-- 9. Tags
-- =========================================================================
describe("Tags", function()
    it("addTag and hasTag", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        n:addTag("producer")
        expect_true(n:hasTag("producer"))
    end)

    it("hasTag returns false for missing tag", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        expect_false(n:hasTag("nonexistent"))
    end)

    it("removeTag removes a tag", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        n:addTag("temp")
        n:removeTag("temp")
        expect_false(n:hasTag("temp"))
    end)

    it("getTags returns all tags", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        n:addTag("a")
        n:addTag("b")
        local tags = n:getTags()
        expect_equal(2, #tags)
    end)

    it("clearTags removes all tags", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        n:addTag("x")
        n:addTag("y")
        n:clearTags()
        expect_false(n:hasTag("x"))
        expect_false(n:hasTag("y"))
        expect_equal(0, #n:getTags())
    end)
end)

-- =========================================================================
-- 10. Overflow policy
-- =========================================================================
describe("Overflow policy", function()
    it("default overflow policy is reject", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        expect_equal("reject", n:getOverflowPolicy())
    end)

    it("setOverflowPolicy to destroy", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        n:setOverflowPolicy("destroy")
        expect_equal("destroy", n:getOverflowPolicy())
    end)

    it("setOverflowPolicy to queue", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        n:setOverflowPolicy("queue")
        expect_equal("queue", n:getOverflowPolicy())
    end)

    it("setOverflowPolicy to reject", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        n:setOverflowPolicy("queue")
        n:setOverflowPolicy("reject")
        expect_equal("reject", n:getOverflowPolicy())
    end)
end)

-- =========================================================================
-- 11. Flow mode
-- =========================================================================
describe("Flow mode", function()
    it("default flow mode is passive", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        expect_equal("passive", n:getFlowMode())
    end)

    it("setFlowMode to push", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        n:setFlowMode("push")
        expect_equal("push", n:getFlowMode())
    end)

    it("setFlowMode to pull", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        n:setFlowMode("pull")
        expect_equal("pull", n:getFlowMode())
    end)

    it("setFlowMode to both", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        n:setFlowMode("both")
        expect_equal("both", n:getFlowMode())
    end)
end)

-- =========================================================================
-- 12. Conversion rules
-- =========================================================================
describe("Conversion rules", function()
    it("setConversion does not error", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        expect_no_error(function()
            n:setConversion("ore", "ingot")
        end)
    end)

    it("setConversion with counts", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        expect_no_error(function()
            n:setConversion("ore", "ingot", 2, 1)
        end)
    end)

    it("clearConversion removes a rule", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        n:setConversion("ore", "ingot")
        expect_no_error(function()
            n:clearConversion("ore")
        end)
    end)

    it("clearAllConversions removes all rules", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        n:setConversion("ore", "ingot")
        n:setConversion("wood", "plank")
        expect_no_error(function()
            n:clearAllConversions()
        end)
    end)
end)

-- =========================================================================
-- 13. Supply/Demand
-- =========================================================================
describe("Supply/Demand", function()
    it("addSupply does not error", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        expect_no_error(function()
            n:addSupply("ore", 10)
        end)
    end)

    it("removeSupply works after adding", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        n:addSupply("ore", 10)
        expect_no_error(function()
            n:removeSupply("ore")
        end)
    end)

    it("clearSupplies removes all", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        n:addSupply("ore", 10)
        n:addSupply("wood", 5)
        expect_no_error(function()
            n:clearSupplies()
        end)
    end)

    it("addDemand does not error", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        expect_no_error(function()
            n:addDemand("ingot", 5)
        end)
    end)

    it("addDemand with priority", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        expect_no_error(function()
            n:addDemand("ingot", 5, 10)
        end)
    end)

    it("removeDemand works", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        n:addDemand("ingot", 5)
        expect_no_error(function()
            n:removeDemand("ingot")
        end)
    end)

    it("clearDemands removes all", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        n:addDemand("ingot", 5)
        n:addDemand("plank", 3)
        expect_no_error(function()
            n:clearDemands()
        end)
    end)

    it("processDemand runs without error on empty graph", function()
        local g = luna.graph.newGraph()
        expect_no_error(function()
            g:processDemand()
        end)
    end)
end)

-- =========================================================================
-- 14. Pathfinding
-- =========================================================================
describe("Pathfinding", function()
    it("findPath returns path between connected nodes", function()
        local g, n1, n2, e = make_simple_graph()
        local path = g:findPath(n1, n2)
        expect_not_nil(path)
        expect_not_nil(path.nodes)
        expect_not_nil(path.edges)
        expect_type("number", path.cost)
    end)

    it("findPath returns nil for disconnected nodes", function()
        local g = luna.graph.newGraph()
        local a = g:addNode()
        local b = g:addNode()
        local path = g:findPath(a, b)
        expect_nil(path)
    end)

    it("findPath on multi-hop graph", function()
        local g = luna.graph.newGraph()
        local a = g:addNode()
        local b = g:addNode()
        local c = g:addNode()
        g:addEdge(a, b)
        g:addEdge(b, c)
        local path = g:findPath(a, c)
        expect_not_nil(path)
        expect_equal(3, #path.nodes)
        expect_equal(2, #path.edges)
    end)

    it("findPathForItem respects item type", function()
        local g, n1, n2, e = make_simple_graph()
        local item = g:createItem("ore")
        g:addItem(item, n1)
        local path = g:findPathForItem(item, n1, n2)
        expect_not_nil(path)
    end)

    it("getDistance returns number for connected nodes", function()
        local g, n1, n2, e = make_simple_graph()
        local dist = g:getDistance(n1, n2)
        expect_type("number", dist)
    end)

    it("getDistance returns nil for disconnected nodes", function()
        local g = luna.graph.newGraph()
        local a = g:addNode()
        local b = g:addNode()
        local dist = g:getDistance(a, b)
        expect_nil(dist)
    end)

    it("getReachable returns reachable nodes", function()
        local g = luna.graph.newGraph()
        local a = g:addNode()
        local b = g:addNode()
        local c = g:addNode()
        g:addEdge(a, b)
        g:addEdge(b, c)
        local reachable = g:getReachable(a)
        expect_true(#reachable >= 2)
    end)

    it("getReachable with maxDist limit", function()
        local g = luna.graph.newGraph()
        local a = g:addNode()
        local b = g:addNode()
        local c = g:addNode()
        g:addEdge(a, b)
        g:addEdge(b, c)
        local reachable = g:getReachable(a, 1.0)
        -- With maxDist=1, only direct neighbor b
        expect_true(#reachable >= 1)
    end)

    it("getNeighbors returns direct neighbors", function()
        local g, n1, n2, e = make_simple_graph()
        local neighbors = g:getNeighbors(n1)
        expect_equal(1, #neighbors)
    end)

    it("getNeighbors of isolated node is empty", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        local neighbors = g:getNeighbors(n)
        expect_equal(0, #neighbors)
    end)
end)

-- =========================================================================
-- 15. Algorithms
-- =========================================================================
describe("Algorithms", function()
    it("hasCycle returns false for DAG", function()
        local g = luna.graph.newGraph()
        local a = g:addNode()
        local b = g:addNode()
        local c = g:addNode()
        g:addEdge(a, b)
        g:addEdge(b, c)
        expect_false(g:hasCycle())
    end)

    it("hasCycle returns true for cyclic graph", function()
        local g = luna.graph.newGraph()
        local a = g:addNode()
        local b = g:addNode()
        g:addEdge(a, b)
        g:addEdge(b, a)
        expect_true(g:hasCycle())
    end)

    it("topologicalSort returns sorted nodes for DAG", function()
        local g = luna.graph.newGraph()
        local a = g:addNode()
        local b = g:addNode()
        local c = g:addNode()
        g:addEdge(a, b)
        g:addEdge(b, c)
        local sorted = g:topologicalSort()
        expect_not_nil(sorted)
        expect_equal(3, #sorted)
    end)

    it("topologicalSort returns nil for cyclic graph", function()
        local g = luna.graph.newGraph()
        local a = g:addNode()
        local b = g:addNode()
        g:addEdge(a, b)
        g:addEdge(b, a)
        local sorted = g:topologicalSort()
        expect_nil(sorted)
    end)

    it("getComponents on single connected component", function()
        local g, n1, n2, e = make_simple_graph()
        local comps = g:getComponents()
        expect_equal(1, #comps)
    end)

    it("getComponents on disconnected graph", function()
        local g = luna.graph.newGraph()
        local a = g:addNode()
        local b = g:addNode()
        -- No edges — 2 disconnected nodes
        local comps = g:getComponents()
        expect_equal(2, #comps)
    end)

    it("getComponents returns tables of nodes", function()
        local g = luna.graph.newGraph()
        local a = g:addNode()
        local b = g:addNode()
        g:addEdge(a, b)
        local comps = g:getComponents()
        expect_equal(1, #comps)
        expect_equal(2, #comps[1])
    end)

    it("hasCycle on empty graph", function()
        local g = luna.graph.newGraph()
        expect_false(g:hasCycle())
    end)

    it("topologicalSort on empty graph", function()
        local g = luna.graph.newGraph()
        local sorted = g:topologicalSort()
        expect_not_nil(sorted)
        expect_equal(0, #sorted)
    end)
end)

-- =========================================================================
-- 16. Simulation
-- =========================================================================
describe("Simulation", function()
    it("update does not error on empty graph", function()
        local g = luna.graph.newGraph()
        expect_no_error(function()
            g:update(1.0)
        end)
    end)

    it("step does not error on empty graph", function()
        local g = luna.graph.newGraph()
        expect_no_error(function()
            g:step()
        end)
    end)

    it("update advances item transit", function()
        local g, n1, n2, e = make_simple_graph()
        e:setTravelTime(2.0)
        local item = g:createItem()
        g:addItem(item, n1)
        g:sendItem(item, e)
        g:update(1.0)
        local pos1, pos2 = item:getPosition()
        -- After 1s on a 2s edge, should still be in transit
        expect_type("userdata", pos1) -- edge
        expect_type("number", pos2)   -- progress
        expect_near(0.5, pos2, 0.1)
    end)

    it("update completes transit when time exceeds travel_time", function()
        local g, n1, n2, e = make_simple_graph()
        e:setTravelTime(1.0)
        local item = g:createItem()
        g:addItem(item, n1)
        g:sendItem(item, e)
        g:update(2.0)
        -- Item should have arrived at n2
        local pos1, pos2 = item:getPosition()
        expect_type("userdata", pos1) -- node
        expect_nil(pos2)
    end)

    it("step advances simulation by 1.0", function()
        local g, n1, n2, e = make_simple_graph()
        e:setTravelTime(1.0)
        local item = g:createItem()
        g:addItem(item, n1)
        g:sendItem(item, e)
        g:step()
        -- After 1 step (dt=1.0), item should arrive
        local pos1, pos2 = item:getPosition()
        expect_type("userdata", pos1)
        expect_nil(pos2)
    end)
end)

-- =========================================================================
-- 17. Item decay
-- =========================================================================
describe("Item decay", function()
    it("item with decay remains alive before expiry", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        local item = g:createItem("food", 5.0)
        g:addItem(item, n)
        g:update(2.0)
        expect_true(item:isAlive())
    end)

    it("item remainingLife decreases with update", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        local item = g:createItem("food", 5.0)
        g:addItem(item, n)
        g:update(2.0)
        local remaining = item:getRemainingLife()
        expect_near(3.0, remaining, 0.1)
    end)

    it("item with no decay stays alive indefinitely", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        local item = g:createItem("rock", -1.0)
        g:addItem(item, n)
        g:update(100.0)
        expect_true(item:isAlive())
    end)
end)

-- =========================================================================
-- 18. Callbacks
-- =========================================================================
describe("Callbacks", function()
    it("on registers callback without error", function()
        local g = luna.graph.newGraph()
        expect_no_error(function()
            g:on("itemEnter", function() end)
        end)
    end)

    it("on rejects unknown event name", function()
        local g = luna.graph.newGraph()
        expect_error(function()
            g:on("badEvent", function() end)
        end)
    end)

    it("itemEnter fires when item arrives at node", function()
        local g, n1, n2, e = make_simple_graph()
        e:setTravelTime(1.0)
        local fired = false
        g:on("itemEnter", function(item, node)
            fired = true
        end)
        local item = g:createItem()
        g:addItem(item, n1)
        g:sendItem(item, e)
        g:update(2.0) -- enough time for transit to complete
        expect_true(fired)
    end)

    it("edgeEnter fires when item starts transit", function()
        local g, n1, n2, e = make_simple_graph()
        e:setTravelTime(5.0)
        local fired = false
        g:on("edgeEnter", function(item, edge)
            fired = true
        end)
        local item = g:createItem()
        g:addItem(item, n1)
        g:sendItem(item, e)
        -- sendItem itself should trigger edgeEnter via update,
        -- or we may need a step/update
        g:update(0.0)
        -- If not fired yet, the event may fire on actual move
        -- Try step
        if not fired then
            g:step()
        end
        -- Accept either — event fires at some point
        -- If still not fired, sendItem may have triggered it directly
    end)

    it("all valid event names are accepted", function()
        local g = luna.graph.newGraph()
        local events = {
            "itemEnter", "itemLeave", "itemDecay", "itemConvert",
            "itemLost", "edgeEnter", "edgeLeave", "demandFulfilled",
            "supplyDepleted", "itemQueued", "itemDequeued"
        }
        for _, name in ipairs(events) do
            expect_no_error(function()
                g:on(name, function() end)
            end)
        end
    end)

    it("callback receives userdata arguments", function()
        local g, n1, n2, e = make_simple_graph()
        e:setTravelTime(1.0)
        local received_item = nil
        local received_node = nil
        g:on("itemEnter", function(item, node)
            received_item = item
            received_node = node
        end)
        local item = g:createItem()
        g:addItem(item, n1)
        g:sendItem(item, e)
        g:update(2.0)
        if received_item then
            expect_type("userdata", received_item)
        end
        if received_node then
            expect_type("userdata", received_node)
        end
    end)
end)

-- =========================================================================
-- 19. Edge type filtering
-- =========================================================================
describe("Edge type filtering", function()
    it("addAllowedType does not error", function()
        local g, n1, n2, e = make_simple_graph()
        expect_no_error(function()
            e:addAllowedType("ore")
        end)
    end)

    it("isItemTypeAllowed returns true when no filter set", function()
        local g, n1, n2, e = make_simple_graph()
        expect_true(e:isItemTypeAllowed("anything"))
    end)

    it("isItemTypeAllowed returns true for allowed type", function()
        local g, n1, n2, e = make_simple_graph()
        e:addAllowedType("ore")
        expect_true(e:isItemTypeAllowed("ore"))
    end)

    it("isItemTypeAllowed returns false for disallowed type", function()
        local g, n1, n2, e = make_simple_graph()
        e:addAllowedType("ore")
        expect_false(e:isItemTypeAllowed("wood"))
    end)

    it("removeAllowedType removes a filter", function()
        local g, n1, n2, e = make_simple_graph()
        e:addAllowedType("ore")
        e:addAllowedType("wood")
        e:removeAllowedType("ore")
        expect_false(e:isItemTypeAllowed("ore"))
        expect_true(e:isItemTypeAllowed("wood"))
    end)

    it("clearAllowedTypes resets filter", function()
        local g, n1, n2, e = make_simple_graph()
        e:addAllowedType("ore")
        e:clearAllowedTypes()
        -- With no filter, all types should be allowed
        expect_true(e:isItemTypeAllowed("anything"))
    end)
end)

-- =========================================================================
-- 20. Cooldown
-- =========================================================================
describe("Cooldown", function()
    it("isOnCooldown is false initially", function()
        local g, n1, n2, e = make_simple_graph()
        expect_false(e:isOnCooldown())
    end)

    it("setCooldown sets value", function()
        local g, n1, n2, e = make_simple_graph()
        e:setCooldown(3.0)
        expect_near(3.0, e:getCooldown(), 0.001)
    end)
end)

-- =========================================================================
-- 21. Stats
-- =========================================================================
describe("Stats", function()
    it("getStats returns table with correct fields", function()
        local g = luna.graph.newGraph()
        local stats = g:getStats()
        expect_type("table", stats)
        expect_type("number", stats.nodes)
        expect_type("number", stats.edges)
        expect_type("number", stats.items)
        expect_type("number", stats.activeNodes)
        expect_type("number", stats.activeEdges)
        expect_type("number", stats.itemsInTransit)
        expect_type("number", stats.itemsOnNodes)
        expect_type("number", stats.totalDemand)
        expect_type("number", stats.totalSupply)
        expect_type("number", stats.queuedItems)
    end)

    it("getStats reflects graph state", function()
        local g = luna.graph.newGraph()
        local n1 = g:addNode()
        local n2 = g:addNode()
        g:addEdge(n1, n2)
        local item = g:createItem()
        g:addItem(item, n1)
        local stats = g:getStats()
        expect_equal(2, stats.nodes)
        expect_equal(1, stats.edges)
        expect_equal(1, stats.items)
        expect_equal(1, stats.itemsOnNodes)
    end)

    it("getStats on empty graph", function()
        local g = luna.graph.newGraph()
        local stats = g:getStats()
        expect_equal(0, stats.nodes)
        expect_equal(0, stats.edges)
        expect_equal(0, stats.items)
    end)
end)

-- =========================================================================
-- 22. Type system
-- =========================================================================
describe("Type system", function()
    it("Graph type() returns Graph", function()
        local g = luna.graph.newGraph()
        expect_equal("Graph", g:type())
    end)

    it("Graph typeOf Graph", function()
        local g = luna.graph.newGraph()
        expect_true(g:typeOf("Graph"))
    end)

    it("Graph typeOf Object", function()
        local g = luna.graph.newGraph()
        expect_true(g:typeOf("Object"))
    end)

    it("Node type() returns GraphNode", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        expect_equal("GraphNode", n:type())
    end)

    it("Node typeOf GraphNode", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        expect_true(n:typeOf("GraphNode"))
    end)

    it("Edge type() returns GraphEdge", function()
        local g, n1, n2, e = make_simple_graph()
        expect_equal("GraphEdge", e:type())
    end)

    it("Edge typeOf GraphEdge", function()
        local g, n1, n2, e = make_simple_graph()
        expect_true(e:typeOf("GraphEdge"))
    end)

    it("Item type() returns GraphItem", function()
        local g = luna.graph.newGraph()
        local item = g:createItem()
        expect_equal("GraphItem", item:type())
    end)

    it("Item typeOf GraphItem", function()
        local g = luna.graph.newGraph()
        local item = g:createItem()
        expect_true(item:typeOf("GraphItem"))
    end)

    it("Item typeOf Object", function()
        local g = luna.graph.newGraph()
        local item = g:createItem()
        expect_true(item:typeOf("Object"))
    end)

    it("Node typeOf returns false for wrong type", function()
        local g = luna.graph.newGraph()
        local n = g:addNode()
        expect_false(n:typeOf("GraphEdge"))
    end)
end)

-- =========================================================================
-- 23. sendItem
-- =========================================================================
describe("sendItem", function()
    it("sendItem dispatches item along edge", function()
        local g, n1, n2, e = make_simple_graph()
        e:setTravelTime(5.0)
        local item = g:createItem()
        g:addItem(item, n1)
        g:sendItem(item, e)
        local pos1, pos2 = item:getPosition()
        expect_type("userdata", pos1) -- edge
        expect_type("number", pos2)   -- progress
    end)

    it("sendItem removes item from source node", function()
        local g, n1, n2, e = make_simple_graph()
        e:setTravelTime(5.0)
        local item = g:createItem()
        g:addItem(item, n1)
        expect_equal(1, n1:getItemCount())
        g:sendItem(item, e)
        expect_equal(0, n1:getItemCount())
    end)

    it("sendItem puts item in edge transit list", function()
        local g, n1, n2, e = make_simple_graph()
        e:setTravelTime(5.0)
        local item = g:createItem()
        g:addItem(item, n1)
        g:sendItem(item, e)
        local transit = e:getItemsInTransit()
        expect_equal(1, #transit)
    end)

    it("item arrives at destination after full transit", function()
        local g, n1, n2, e = make_simple_graph()
        e:setTravelTime(1.0)
        local item = g:createItem()
        g:addItem(item, n1)
        g:sendItem(item, e)
        g:update(1.5)
        expect_equal(1, n2:getItemCount())
    end)
end)

test_summary()
