import * as vscode from "vscode";
import * as path from "path";
import * as fs from "fs";

// ─── Lua API call detection ───────────────────────────────

interface DetectedCall {
  module: string;
  func: string;
  line: number;
  text: string;
}

function detectLurekCalls(text: string): DetectedCall[] {
  const calls: DetectedCall[] = [];
  const seen = new Set<string>();
  const regex = /lurek\.(\w+)\.(\w+)\s*\(/g;

  for (const [lineIdx, line] of text.split("\n").entries()) {
    let match: RegExpExecArray | null;
    regex.lastIndex = 0;
    while ((match = regex.exec(line)) !== null) {
      const module = match[1];
      const func = match[2];
      const key = `${module}.${func}`;
      if (!seen.has(key)) {
        seen.add(key);
        calls.push({ module, func, line: lineIdx + 1, text: line.trim() });
      }
    }
  }
  return calls;
}

function detectFunctions(text: string): Array<{ name: string; line: number; endLine: number; body: string }> {
  const fns: Array<{ name: string; line: number; endLine: number; body: string }> = [];
  const lines = text.split("\n");
  const funcPattern = /^(?:local\s+)?function\s+([\w.:]+)\s*\(/;

  for (let i = 0; i < lines.length; i++) {
    const match = funcPattern.exec(lines[i]);
    if (match) {
      const name = match[1];
      const startLine = i;
      // Find matching `end`
      let depth = 1;
      let j = i + 1;
      for (; j < lines.length && depth > 0; j++) {
        const trimmed = lines[j].trim();
        if (/^(?:function|if|for|while|repeat)\b/.test(trimmed) && !trimmed.endsWith("end")) {
          depth++;
        }
        if (/^end\b/.test(trimmed)) {
          depth--;
        }
      }
      fns.push({
        name,
        line: startLine + 1,
        endLine: j,
        body: lines.slice(startLine, j).join("\n"),
      });
    }
  }
  return fns;
}

// ─── Test file generation ─────────────────────────────────

function generateTestContent(sourceFileName: string, calls: DetectedCall[]): string {
  const lines: string[] = [
    `-- Auto-generated tests for ${sourceFileName}`,
    `-- Generated by Lurek2D Toolkit`,
    "",
    `local passed = 0`,
    `local failed = 0`,
    `local total = 0`,
    "",
    `local function test(name, fn)`,
    `  total = total + 1`,
    `  local ok, err = pcall(fn)`,
    `  if ok then`,
    `    passed = passed + 1`,
    `    print("[PASS] " .. name)`,
    `  else`,
    `    failed = failed + 1`,
    `    print("[FAIL] " .. name .. ": " .. tostring(err))`,
    `  end`,
    `end`,
    "",
  ];

  // Group calls by module
  const modules = new Map<string, DetectedCall[]>();
  for (const call of calls) {
    const list = modules.get(call.module) ?? [];
    list.push(call);
    modules.set(call.module, list);
  }

  for (const [mod, modCalls] of modules) {
    lines.push(`-- Tests for lurek.${mod}`, "");
    for (const call of modCalls) {
      lines.push(
        `test("lurek.${mod}.${call.func} works", function()`,
        `  -- Source line ${call.line}: ${call.text}`,
        `  -- TODO: Add proper test assertion`,
        `  local result = lurek.${mod}.${call.func}()`,
        `  assert(result ~= nil, "lurek.${mod}.${call.func} should return a value")`,
        `end)`,
        "",
      );
    }
  }

  lines.push(
    `-- Summary`,
    `print(string.format("\\n%d/%d tests passed (%d failed)", passed, total, failed))`,
    `if failed > 0 then`,
    `  error(string.format("%d tests failed", failed))`,
    `end`,
    "",
  );

  return lines.join("\n");
}

function generateFunctionTestContent(
  sourceFileName: string,
  funcName: string,
  funcBody: string,
): string {
  const calls = detectLurekCalls(funcBody);

  const lines: string[] = [
    `-- Tests for function: ${funcName}`,
    `-- Source: ${sourceFileName}`,
    `-- Generated by Lurek2D Toolkit`,
    "",
    `local passed = 0`,
    `local failed = 0`,
    `local total = 0`,
    "",
    `local function test(name, fn)`,
    `  total = total + 1`,
    `  local ok, err = pcall(fn)`,
    `  if ok then`,
    `    passed = passed + 1`,
    `    print("[PASS] " .. name)`,
    `  else`,
    `    failed = failed + 1`,
    `    print("[FAIL] " .. name .. ": " .. tostring(err))`,
    `  end`,
    `end`,
    "",
    `-- Basic existence test`,
    `test("${funcName} is defined", function()`,
    `  assert(type(${funcName}) == "function", "${funcName} should be a function")`,
    `end)`,
    "",
    `-- Call test`,
    `test("${funcName} can be called", function()`,
    `  -- TODO: Provide appropriate arguments`,
    `  local ok, err = pcall(${funcName})`,
    `  -- Adjust based on expected behavior`,
    `end)`,
    "",
  ];

  if (calls.length > 0) {
    lines.push(`-- API dependency tests`);
    for (const call of calls) {
      lines.push(
        `test("${funcName} uses lurek.${call.module}.${call.func}", function()`,
        `  -- Verify lurek.${call.module}.${call.func} is available`,
        `  assert(type(lurek.${call.module}.${call.func}) == "function",`,
        `    "lurek.${call.module}.${call.func} should be available")`,
        `end)`,
        "",
      );
    }
  }

  lines.push(
    `-- Summary`,
    `print(string.format("\\n%d/%d tests passed (%d failed)", passed, total, failed))`,
    `if failed > 0 then`,
    `  error(string.format("%d tests failed", failed))`,
    `end`,
    "",
  );

  return lines.join("\n");
}

// ─── Commands ─────────────────────────────────────────────

function getGameRoot(filePath: string): string | undefined {
  let dir = path.dirname(filePath);
  for (let i = 0; i < 10; i++) {
    if (fs.existsSync(path.join(dir, "main.lua")) || fs.existsSync(path.join(dir, "conf.lua"))) {
      return dir;
    }
    const parent = path.dirname(dir);
    if (parent === dir) {
      break;
    }
    dir = parent;
  }
  // Fallback: workspace root
  return vscode.workspace.workspaceFolders?.[0]?.uri.fsPath;
}

export function registerTestCommands(context: vscode.ExtensionContext): void {
  // ── lurek.test.generateForFile ────────────────────────────
  context.subscriptions.push(
    vscode.commands.registerCommand("lurek.test.generateForFile", async () => {
      const editor = vscode.window.activeTextEditor;
      if (!editor || editor.document.languageId !== "lua") {
        vscode.window.showWarningMessage("Open a Lua file first.");
        return;
      }

      const doc = editor.document;
      const text = doc.getText();
      const calls = detectLurekCalls(text);

      if (calls.length === 0) {
        vscode.window.showInformationMessage("No lurek.* API calls detected in this file.");
        return;
      }

      const sourceFileName = path.basename(doc.fileName);
      const gameRoot = getGameRoot(doc.fileName);
      if (!gameRoot) {
        vscode.window.showErrorMessage("Could not determine game root directory.");
        return;
      }

      const testsDir = path.join(gameRoot, "tests");
      if (!fs.existsSync(testsDir)) {
        fs.mkdirSync(testsDir, { recursive: true });
      }

      const testFileName = `test_${sourceFileName}`;
      const testFilePath = path.join(testsDir, testFileName);
      const content = generateTestContent(sourceFileName, calls);
      fs.writeFileSync(testFilePath, content, "utf-8");

      const testDoc = await vscode.workspace.openTextDocument(testFilePath);
      await vscode.window.showTextDocument(testDoc);
      vscode.window.showInformationMessage(
        `Generated test file: tests/${testFileName} (${calls.length} API calls detected)`
      );
    })
  );

  // ── lurek.test.generateForFunction ────────────────────────
  context.subscriptions.push(
    vscode.commands.registerCommand("lurek.test.generateForFunction", async () => {
      const editor = vscode.window.activeTextEditor;
      if (!editor || editor.document.languageId !== "lua") {
        vscode.window.showWarningMessage("Open a Lua file first.");
        return;
      }

      const doc = editor.document;
      const text = doc.getText();
      const cursorLine = editor.selection.active.line + 1;
      const fns = detectFunctions(text);

      // Find the function that contains the cursor
      const target = fns.find((f) => cursorLine >= f.line && cursorLine <= f.endLine);
      if (!target) {
        vscode.window.showWarningMessage("No function found at cursor position.");
        return;
      }

      const sourceFileName = path.basename(doc.fileName);
      const gameRoot = getGameRoot(doc.fileName);
      if (!gameRoot) {
        vscode.window.showErrorMessage("Could not determine game root directory.");
        return;
      }

      const testsDir = path.join(gameRoot, "tests");
      if (!fs.existsSync(testsDir)) {
        fs.mkdirSync(testsDir, { recursive: true });
      }

      const safeName = target.name.replace(/[.:]/g, "_");
      const testFileName = `test_${safeName}.lua`;
      const testFilePath = path.join(testsDir, testFileName);
      const content = generateFunctionTestContent(sourceFileName, target.name, target.body);
      fs.writeFileSync(testFilePath, content, "utf-8");

      const testDoc = await vscode.workspace.openTextDocument(testFilePath);
      await vscode.window.showTextDocument(testDoc);
      vscode.window.showInformationMessage(
        `Generated test file: tests/${testFileName} for ${target.name}()`
      );
    })
  );

  // ── lurek.test.runCurrent ─────────────────────────────────
  context.subscriptions.push(
    vscode.commands.registerCommand("lurek.test.runCurrent", async () => {
      const editor = vscode.window.activeTextEditor;
      if (!editor || editor.document.languageId !== "lua") {
        vscode.window.showWarningMessage("Open a Lua test file first.");
        return;
      }

      const filePath = editor.document.fileName;
      const gameRoot = getGameRoot(filePath);
      if (!gameRoot) {
        vscode.window.showErrorMessage("Could not determine game root directory.");
        return;
      }

      const lurekPath = vscode.workspace.getConfiguration("lurek").get<string>("enginePath", "lurek2d");
      const terminal = getOrCreateTerminal("Lurek2D Tests");
      terminal.show();
      const relPath = path.relative(gameRoot, filePath).replace(/\\/g, "/");
      terminal.sendText(`cd "${gameRoot}" && "${lurekPath}" --test "${relPath}"`);
    })
  );

  // ── lurek.test.runAll ─────────────────────────────────────
  context.subscriptions.push(
    vscode.commands.registerCommand("lurek.test.runAll", async () => {
      const editor = vscode.window.activeTextEditor;
      const gameRoot = editor
        ? getGameRoot(editor.document.fileName)
        : vscode.workspace.workspaceFolders?.[0]?.uri.fsPath;

      if (!gameRoot) {
        vscode.window.showErrorMessage("No game project found.");
        return;
      }

      const testsDir = path.join(gameRoot, "tests");
      if (!fs.existsSync(testsDir)) {
        vscode.window.showWarningMessage("No tests/ directory found in the game project.");
        return;
      }

      const testFiles = fs.readdirSync(testsDir).filter((f) => f.endsWith(".lua"));
      if (testFiles.length === 0) {
        vscode.window.showWarningMessage("No Lua test files found in tests/.");
        return;
      }

      const outputChannel = vscode.window.createOutputChannel("Lurek2D Test Results");
      outputChannel.show();
      outputChannel.appendLine(`Running ${testFiles.length} test file(s)...`);
      outputChannel.appendLine("─".repeat(50));

      const lurekPath = vscode.workspace.getConfiguration("lurek").get<string>("enginePath", "lurek2d");
      const terminal = getOrCreateTerminal("Lurek2D Tests");
      terminal.show();

      for (const testFile of testFiles) {
        outputChannel.appendLine(`\nRunning: ${testFile}`);
        terminal.sendText(`cd "${gameRoot}" && "${lurekPath}" --test "tests/${testFile}"`);
      }

      outputChannel.appendLine("\n" + "─".repeat(50));
      outputChannel.appendLine(`Queued ${testFiles.length} test files.`);
    })
  );

  // ── lurek.test.coverage ───────────────────────────────────
  context.subscriptions.push(
    vscode.commands.registerCommand("lurek.test.coverage", async () => {
      const editor = vscode.window.activeTextEditor;
      const gameRoot = editor
        ? getGameRoot(editor.document.fileName)
        : vscode.workspace.workspaceFolders?.[0]?.uri.fsPath;

      if (!gameRoot) {
        vscode.window.showErrorMessage("No game project found.");
        return;
      }

      // Scan all .lua files in the project for lurek.* API usage
      const luaFiles = findLuaFiles(gameRoot);
      const allCalls = new Set<string>();
      const testedCalls = new Set<string>();

      for (const file of luaFiles) {
        const content = fs.readFileSync(file, "utf-8");
        const calls = detectLurekCalls(content);
        const isTest = file.includes(`${path.sep}tests${path.sep}`) || path.basename(file).startsWith("test_");

        for (const call of calls) {
          const key = `lurek.${call.module}.${call.func}`;
          allCalls.add(key);
          if (isTest) {
            testedCalls.add(key);
          }
        }
      }

      const outputChannel = vscode.window.createOutputChannel("Lurek2D API Coverage");
      outputChannel.show();
      outputChannel.appendLine("Lurek2D API Coverage Report");
      outputChannel.appendLine("═".repeat(50));
      outputChannel.appendLine(`Total API calls used: ${allCalls.size}`);
      outputChannel.appendLine(`Covered by tests:     ${testedCalls.size}`);
      const pct = allCalls.size > 0 ? Math.round((testedCalls.size / allCalls.size) * 100) : 0;
      outputChannel.appendLine(`Coverage:             ${pct}%`);
      outputChannel.appendLine("");

      if (allCalls.size > testedCalls.size) {
        outputChannel.appendLine("Untested API calls:");
        for (const call of [...allCalls].sort()) {
          if (!testedCalls.has(call)) {
            outputChannel.appendLine(`  ⚠ ${call}`);
          }
        }
      }

      outputChannel.appendLine("");
      outputChannel.appendLine("Tested API calls:");
      for (const call of [...testedCalls].sort()) {
        outputChannel.appendLine(`  ✓ ${call}`);
      }
    })
  );
}

function findLuaFiles(dir: string, results: string[] = []): string[] {
  if (!fs.existsSync(dir)) {
    return results;
  }
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory() && entry.name !== "node_modules" && entry.name !== ".git") {
      findLuaFiles(fullPath, results);
    } else if (entry.isFile() && entry.name.endsWith(".lua")) {
      results.push(fullPath);
    }
  }
  return results;
}

function getOrCreateTerminal(name: string): vscode.Terminal {
  const existing = vscode.window.terminals.find((t) => t.name === name);
  if (existing) {
    return existing;
  }
  return vscode.window.createTerminal(name);
}
