describe("<a> + <b> integration", function()
    it("uses <a> output as <b> input", function()
        local world_id = lurek.physics.newWorld(0, 100)
        local body_id = lurek.physics.newBody(world_id, 50, 50, "dynamic")
        local x, y = body_id:getPosition()
        expect_near(50, x, 0.1)
        lurek.physics.destroyWorld(world_id)
    end)
end)
test_summary()
