//! Reusable behavioural and structural patterns: behavior trees, state machines, event buses, caches, and more.\n//! Each submodule is a standalone composable utility; no Lua bindings live here.\n//! Consumed by game logic modules and Lua API bindings via `pub use` re-exports.\n\npub mod behavior_tree;
pub mod bimap;
pub mod blackboard;
pub mod collections;
pub mod command_stack;
pub mod event_bus;
pub mod factory;
pub mod funnel;
pub mod graph;
pub mod mediator;
pub mod object_pool;
pub mod observer;
pub mod priority_queue;
pub mod ring;
pub mod service_locator;
pub mod simple_state;
pub mod state_machine;
pub mod strategy;
pub mod throttle;
pub mod trie;
pub mod weighted_random;
pub use behavior_tree::{BehaviorTree, BtNode, BtRunState, BtStatus, NodeId, NodeKind};
pub use bimap::BiMap;
pub use blackboard::{Blackboard, BlackboardValue};
pub use collections::{QueueMeta, StackMeta};
pub use command_stack::{CommandEntry, CommandStack};
pub use event_bus::{EventBus, Subscription};
pub use factory::Factory;
pub use funnel::{Funnel, FunnelEntry};
pub use graph::{Graph, GraphEdge, GraphNode};
pub use mediator::Mediator;
pub use object_pool::ObjectPool;
pub use observer::{Observer, ObserverEntry};
pub use priority_queue::{PriorityItem, PriorityQueue};
pub use ring::{Ring, RingEntry};
pub use service_locator::ServiceLocator;
pub use simple_state::SimpleState;
pub use state_machine::{StateMachine, TransitionRule};
pub use strategy::Strategy;
pub use throttle::{Debounce, Throttle};
pub use trie::Trie;
pub use weighted_random::{WeightedEntry, WeightedRandom};
