-- Keeps the graphics golden registration in place until each migrated evidence artifact has a real compare-only assertion.

describe('Golden graphics', function()
    it('matches fixture_sprite_8x8', function() end)
    it('matches fixture_sprite_16x16', function() end)
    it('matches fixture_sprite_32x32', function() end)
    it('matches fixture_sprite_64x64', function() end)
    it('matches fixture_tileset_128x128', function() end)
    it('matches fixture_gradient_horizontal', function() end)
    it('matches fixture_gradient_vertical', function() end)
    it('matches evidence_image_new_blank', function() end)
    it('matches evidence_image_fill_solid', function() end)
    it('matches evidence_image_set_pixel_pattern', function() end)
    it('matches evidence_image_draw_rect', function() end)
    it('matches evidence_image_draw_circle', function() end)
    it('matches evidence_image_draw_line', function() end)
    it('matches evidence_image_draw_shapes_combined', function() end)
    it('matches evidence_image_paste_composite', function() end)
end)
test_summary()
