#!/usr/bin/env python3
"""
gen_docs_rust.py — Generate compact Rust API reference from docs/API/api_data.json.

Reads the master data file and writes a Markdown reference of public Rust
items (structs, enums, fns, traits) for Luna2D engine contributors.

Usage:
    python tools/gen_docs_rust.py                   # -> docs/API/rust-api.md
    python tools/gen_docs_rust.py --output FILE     # custom output path
    python tools/gen_docs_rust.py --input FILE      # custom input path

Exit codes:
    0 — success
    1 — fatal error
"""

import argparse
import json
import sys
from pathlib import Path

WORKSPACE_ROOT = Path(__file__).resolve().parent.parent
INPUT_FILE = WORKSPACE_ROOT / "docs" / "API" / "api_data.json"
OUTPUT_FILE = WORKSPACE_ROOT / "docs" / "API" / "rust-api.md"

# Kind display labels
_KIND_LABEL = {
    "struct": "struct",
    "enum": "enum",
    "fn": "fn",
    "trait": "trait",
    "type": "type",
    "const": "const",
    "static": "static",
    "mod": "mod",
}

# Modules to skip (test utilities, build scripts, etc.)
_SKIP_MODS = {"main", "root", "lib"}

# How to group modules for display (top-level src/ folder name)
def _top_group(mod_path: str) -> str:
    if "::" in mod_path:
        return mod_path.split("::")[0]
    return mod_path


def generate_rust_docs(data: dict) -> str:
    rust_api = data["rust_api"]
    modules = rust_api["modules"]
    s = rust_api["summary"]
    generated = data["meta"]["generated"][:10]
    version = data["meta"]["version"]

    out = []
    out.append("# Luna2D Rust API Reference")
    out.append("")
    out.append("> Auto-generated by `tools/gen_docs_rust.py` from `docs/API/api_data.json`.")
    out.append(f"> Version: `{version}` | Generated: {generated}")
    out.append(
        f"> **Coverage:** {s['documented']}/{s['total_items']} public items documented"
    )
    out.append("")
    out.append("> For Lua scripting API see `docs/API/lua-api.md`.")
    out.append("> For engine contributors and extension authors only.")
    out.append("")

    # Group by top-level module
    groups: dict = {}
    for mod_path, mod_data in sorted(modules.items()):
        if mod_path in _SKIP_MODS:
            continue
        items = mod_data.get("items", [])
        if not items:
            continue
        group = _top_group(mod_path)
        groups.setdefault(group, []).append((mod_path, mod_data))

    # TOC
    out.append("## Contents")
    out.append("")
    for group in sorted(groups.keys()):
        anchor = group.replace("_", "-")
        total_items = sum(len(md.get("items", [])) for _, md in groups[group])
        out.append(f"- [`{group}`](#{anchor}) — {total_items} items")
    out.append("")

    # Per-group sections
    for group in sorted(groups.keys()):
        anchor = group.replace("_", "-")
        out.append(f"## `{group}` {{#{anchor}}}")
        out.append("")

        for mod_path, mod_data in sorted(groups[group]):
            items = mod_data.get("items", [])
            if not items:
                continue

            module_doc = mod_data.get("module_doc", "")
            src = mod_data.get("source_file", "")

            # Sub-section per file
            out.append(f"### `{mod_path}`")
            out.append("")
            if module_doc:
                out.append(f"> {module_doc.split(chr(10))[0]}")
                out.append("")
            if src:
                out.append(f"*Source: [{src}]({src})*")
                out.append("")

            # Table of items
            out.append("| Kind | Name | Description |")
            out.append("|------|------|-------------|")
            for item in sorted(items, key=lambda x: (x["kind"], x["name"])):
                kind = _KIND_LABEL.get(item["kind"], item["kind"])
                name = item["name"]
                desc = item.get("description", "") or "*(undocumented)*"
                if len(desc) > 80:
                    desc = desc[:77] + "..."
                src_link = f"[`{name}`]({item['file']}#L{item['line']})" if item.get("line") else f"`{name}`"
                out.append(f"| `{kind}` | {src_link} | {desc} |")
            out.append("")

    out.append("---")
    out.append("*Generated by `tools/gen_docs_rust.py`. Do not edit by hand.*")

    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate Luna2D compact Rust API docs.")
    parser.add_argument("--input", default=str(INPUT_FILE))
    parser.add_argument("--output", default=str(OUTPUT_FILE))
    args = parser.parse_args()

    input_path = Path(args.input)
    if not input_path.exists():
        print(f"[ERROR] Input not found: {input_path}", file=sys.stderr)
        print("Run 'python tools/gen_api_data.py' first.", file=sys.stderr)
        return 1

    data = json.loads(input_path.read_text(encoding="utf-8"))
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    content = generate_rust_docs(data)
    output_path.write_text(content, encoding="utf-8")

    print(f"[OK] Generated {output_path} ({content.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
