#!/usr/bin/env python3
"""
gen_docs_tests.py — Generate test catalog from docs/api_data.json.

Produces a compact Markdown reference of all test functions in tests/*.rs
and integration Lua scripts in tests/lua/, with their descriptions and
module grouping.

Usage:
    python tools/gen_docs_tests.py                # -> docs/test-docs.md
    python tools/gen_docs_tests.py --output FILE  # custom output path
    python tools/gen_docs_tests.py --input FILE   # custom input path

Exit codes:
    0 — success
    1 — fatal error
"""

import argparse
import json
import sys
from pathlib import Path

WORKSPACE_ROOT = Path(__file__).resolve().parent.parent
INPUT_FILE = WORKSPACE_ROOT / "docs" / "api_data.json"
OUTPUT_FILE = WORKSPACE_ROOT / "docs" / "test-docs.md"


def generate_test_docs(data: dict) -> str:
    tests_data = data["tests"]
    rs_tests = tests_data.get("rust", [])
    lua_tests = tests_data.get("lua", [])
    generated = data["meta"]["generated"][:10]
    version = data["meta"]["version"]

    out = []
    out.append("# Luna2D Test Catalog")
    out.append("")
    out.append("> Auto-generated by `tools/gen_docs_tests.py` from `docs/api_data.json`.")
    out.append(f"> Version: `{version}` | Generated: {generated}")
    out.append(
        f"> **{len(rs_tests)}** Rust tests | **{len(lua_tests)}** Lua integration tests"
    )
    out.append("")

    # Group Rust tests by module
    by_module: dict = {}
    for t in rs_tests:
        mod = t.get("module", "unknown")
        by_module.setdefault(mod, []).append(t)

    # TOC
    out.append("## Contents")
    out.append("")
    out.append("### Rust tests by module")
    out.append("")
    for mod in sorted(by_module.keys()):
        count = len(by_module[mod])
        anchor = f"rust-{mod.replace('_', '-')}"
        out.append(f"- [`{mod}`](#{anchor}) — {count} tests")
    out.append("")

    if lua_tests:
        out.append("### Lua integration tests")
        out.append("")
        out.append(f"- [{len(lua_tests)} scripts in tests/lua/](#lua-integration-tests)")
        out.append("")

    # Rust test sections
    out.append("---")
    out.append("")
    out.append("## Rust Tests")
    out.append("")

    for mod in sorted(by_module.keys()):
        tests = by_module[mod]
        anchor = f"rust-{mod.replace('_', '-')}"
        out.append(f"### `{mod}` tests {{#{anchor}}}")
        out.append("")
        out.append(f"File: `tests/{mod}_tests.rs` — {len(tests)} tests")
        out.append("")
        out.append("| Test function | Description |")
        out.append("|---------------|-------------|")
        for t in sorted(tests, key=lambda x: x["name"]):
            name = t["name"]
            desc = t.get("description", "") or "*(no description)*"
            if len(desc) > 100:
                desc = desc[:97] + "..."
            file_link = f"[{t['file']}]({t['file']}#L{t['line']})" if t.get("line") else t["file"]
            out.append(f"| `{name}` | {desc} |")
        out.append("")

    # Lua integration tests
    if lua_tests:
        out.append("---")
        out.append("")
        out.append("## Lua Integration Tests")
        out.append("")
        out.append("> Located in `tests/lua/`. Run with `cargo run -- tests/lua/` on a debug build.")
        out.append("> These exercise the full `luna.*` API surface end-to-end.")
        out.append("")
        out.append("| Script | Description |")
        out.append("|--------|-------------|")
        for t in sorted(lua_tests, key=lambda x: x["file"]):
            file_path = t["file"]
            desc = t.get("description", "") or "*(no description)*"
            if len(desc) > 100:
                desc = desc[:97] + "..."
            out.append(f"| [`{file_path}`]({file_path}) | {desc} |")
        out.append("")

    out.append("---")
    out.append("*Generated by `tools/gen_docs_tests.py`. Do not edit by hand.*")

    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate Luna2D test catalog.")
    parser.add_argument("--input", default=str(INPUT_FILE))
    parser.add_argument("--output", default=str(OUTPUT_FILE))
    args = parser.parse_args()

    input_path = Path(args.input)
    if not input_path.exists():
        print(f"[ERROR] Input not found: {input_path}", file=sys.stderr)
        print("Run 'python tools/gen_api_data.py' first.", file=sys.stderr)
        return 1

    data = json.loads(input_path.read_text(encoding="utf-8"))
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    content = generate_test_docs(data)
    output_path.write_text(content, encoding="utf-8")

    print(f"[OK] Generated {output_path} ({content.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
