pub mod combo;
pub mod gamepad;
pub mod keyboard;
pub mod mouse;
pub mod recorder;
pub mod touch;
pub use combo::{ComboDetector, ComboProgress, ComboStep};
pub use gamepad::gilrs_axis_to_string;
pub use gamepad::gilrs_button_to_string;
pub use gamepad::virtual_dpad;
pub use gamepad::GamepadMappings;
pub use gamepad::GamepadState;
pub use gamepad::GamepadVibrationRequest;
pub use keyboard::winit_scancode_to_string;
pub use keyboard::KeyboardState;
pub use mouse::MouseState;
pub use mouse::SystemCursor;
pub use mouse::{is_cursor_supported, CursorHandle, CursorKind};
pub use touch::{TouchPoint, TouchState};
pub const EVENT_KEY_PRESSED: &str = "keypressed";
pub const EVENT_KEY_RELEASED: &str = "keyreleased";
pub const EVENT_MOUSE_MOVED: &str = "mousemoved";
pub const EVENT_MOUSE_PRESSED: &str = "mousepressed";
pub const EVENT_MOUSE_RELEASED: &str = "mousereleased";
pub const EVENT_WHEEL_MOVED: &str = "wheelmoved";
pub const EVENT_TEXT_INPUT: &str = "textinput";
